// ===== EN — Secret Base =====
export const L_en_base = {
"title":"Secret Base",
"export_done":"Base exported as JSON!",
"win":{
"moved":"Base moved: {name}. Your furniture was returned to the stock.",
"title":"Secret Base",
"mode_label":"Render mode",
"layout_label":"Base layout",
"layout_group":{"cave":"Caves","cave_red":"Red caves","cave_blue":"Blue caves","cave_yellow":"Yellow caves","tree":"Trees","bush":"Bushes"},
"refresh":"Refresh",
"mode3d":"3D (ORAS models)",
"mode2d":"Emerald 2D",
"empty":"Load a save file to see your secret base.",
"not_established":"No Secret Base established yet. Visit an alcove from a Hoenn route's Location window, then settle in!",
"no_gl":"WebGL2 unavailable — falling back to 2D.",
"layout":{
"cave_1":"Cave · Room 1","cave_2":"Cave · Room 2","cave_3":"Cave · Room 3","cave_4":"Cave · Room 4",
"tree_1":"Tree · Room 1","tree_2":"Tree · Corridor 2","tree_3":"Tree · Room 3","tree_4":"Tree · Two wings 4",
"bush_1":"Bush · Room 1","bush_2":"Bush · Room 2","bush_3":"Bush · Cross 3","bush_4":"Bush · Room 4",
"cave_red_1":"Red Cave · Room 1","cave_red_2":"Red Cave · Hall 2","cave_red_3":"Red Cave · Room 3","cave_red_4":"Red Cave · Room 4",
"cave_blue_1":"Blue Cave · Room 1","cave_blue_2":"Blue Cave · Hall 2","cave_blue_3":"Blue Cave · Well 3","cave_blue_4":"Blue Cave · Room 4",
"cave_yellow_1":"Yellow Cave · Room 1","cave_yellow_2":"Yellow Cave · Hall 2","cave_yellow_3":"Yellow Cave · Room 3","cave_yellow_4":"Yellow Cave · Room 4",
"cave_5":"Cave · Mezzanine 5","cave_6":"Cave · Balcony 6",
"tree_5":"Tree · Hanging 5","tree_6":"Tree · Mezzanine 6",
"bush_5":"Bush · Terrace 5","bush_6":"Bush · Grand Terrace 6",
"cave_red_5":"Red Cave · Mezzanine 5","cave_red_6":"Red Cave · Balconies 6",
"cave_blue_5":"Blue Cave · Mezzanine 5","cave_blue_6":"Blue Cave · Balcony 6",
"cave_yellow_5":"Yellow Cave · Mezzanine 5","cave_yellow_6":"Yellow Cave · Balconies 6"
}
},
"debug":{"granted":"Decoration catalog: {n} items added to stock (debug).","npc_name":"NPC","npc_added":"NPC created from your current party: {name}.","npcs_added":"{n} NPCs settled into the base!"},
"edit":{
"move_hint":"Holding {name}: click a tile to set it down there, right-click to cancel (or « Pick up » to stash it).",
"need2d":"Editing happens in Emerald 2D mode — switch the renderer in the top-right corner.",
"moved_item":"{name} moved.",
"move_cancel":"Move cancelled, the item went back to its place.",
"pc_own":"Your PC: manage your base from this window (switch back to edit mode).",
"pc_record":"{name}\u2019s PC — visits: {v}, NPCs won: {w}, NPCs beaten: {l}.",
"pc_record_none":"No record to show.",
"stock":"Stock",
"stock_empty":"Empty stock — use the decoration catalog (debug) to furnish.",
"pals":"NPCs",
"rotate":"Rotate",
"pickup":"Pick up",
"place_hint":"Click a tile to place · right-click or “Rotate” to turn.",
"select_hint":"Click a placed decoration to pick it up and set it back elsewhere, or pick an item from the stock.",
"placed":"{name} placed!",
"picked_up":"{name} put back in stock.",
"rotated":"{name} rotated.",
"npc_move_hint":"Holding {name}: click a tile to place them there.",
"npc_no_team":"{name} has no team yet \u2014 click them in edit mode, then \u201cEdit\u201d.",
"npc_placed":"{name} settles in!",
"npc_picked_up":"{name} removed from the room.",
"visit":"Visit",
"visit_stop":"End visit",
"visit_hint":"Click a tile to walk there · click a decoration or NPC to interact.",
"visit_only2d":"Interactive visits run in 2D view (3D comes later).",
"visit_start":"Welcome to {name}'s base!",
"visit_start_own":"Welcome to your very own base!",
"battle_done":"{name} has already been challenged during this visit.",
"visit_end":"Visit over — {w} win(s), {l} loss(es).",
"export":"Export",
"import":"Visit a file…",
"battle_challenge":"{name} challenges you!",
"battle_won":"Victory against {name}!",
"battle_lost":"Defeat against {name}…",
"heal":"Your party is fully healed!",
"sit":"You rest for a moment…",
"light_on":"The lamp turns on.",
"light_off":"The lamp turns off.",
"punch":"Hiya! What a punch!",
"rules":"This base's battle rules are displayed.",
"message":"There's a message written here…",
"reveal":"Something invisible appears!",
"blocked":"Can't go there."
},
"notes":["C","D","E","F","G","A","B","C+"],
"visit":{
"burst":"Pop! The balloon bursts!",
"glitter":"The mat sparkles under your steps…",
"jump":"Boing!",
"slide":"You slide all the way down!",
"spin":"The mat whirls and pushes you back!",
"spinforce":"The panel launches you!",
"pitfall":"Ouch! You fell into a pit!",
"squareone":"Back to the entrance!",
"warp":"Warp!",
"door_break":"You smash through the fake door!",
"invisible":"There's something invisible here…",
"makiwara":"A post used by sword masters for Cut practice.",
"note":"The note “{note}” rings."
},
"err":{
"unknown":"Unknown item.",
"no_base":"No secret base yet.",
"stairs_anchor":"Stairs must be placed on the dedicated ramp spot.",
"board_hole":"The board (2 tiles tall) is placed with its top on a hole.",
"pc_unreachable":"The PC must stay reachable on foot from the entrance.",
"already_placed":"Already in the base (unique automatic item).",
"occupied":"Tile already occupied.",
"out_of_bounds":"Outside the base bounds.",
"wall_only":"This decoration hangs on walls.",
"surface_only":"This decoration goes indoors.",
"needs_surface":"Place it on the floor, a desk, a mat or a tire.",
"floor_only":"Place it on the floor.",
"uneven":"Place it on level ground (not straddling the cliff).",
"entrance":"The entrance must stay clear.",
"wall_hidden":"This wall can't be seen from any walkable tile.",
"surface_taken":"That spot is already taken.",
"max_placed":"Maximum 26 decorations placed, Hoenn style!",
"blocks_spawn":"That would block the entrance path.",
"blocks_npc":"That would make an NPC unreachable.",
"not_in_stock":"This item is no longer in stock.",
"not_rotatable":"This item can't be rotated.",
"npc_max":"Up to 8 friends per base.",
"npc_team":"An NPC needs at least one Pokémon.",
"import_empty":"No file selected.",
"import_too_big":"File too large.",
"import_json":"This file is not valid JSON.",
"import_kind":"This file is not a PokéWorld secret base.",
"import_version":"Unsupported base version.",
"import_layout":"Unknown room layout.",
"import_items":"Invalid item list.",
"import_npcs":"Invalid NPC list.",
"export":"Export failed."
},
// NPC names + quotes (before/victory/defeat)

"dlg":{
"npc_sub":"Encounter",
"npc_default":"\u2026",
"fight":"Battle",
"decline":"Walk away",
"close":"Close",
"rematch":"Rematch",
"res_won":"You defeated {name}!",
"res_lost":"{name} defeated you\u2026",
"res_quote_won":"\u2026",
"res_quote_lost":"\u2026",
"pc_title":"Base PC",
"pc_own":"Your own terminal",
"pc_guest":"Owner\u2019s terminal",
"pc_visits":"Visits:",
"pc_wins":"NPC wins:",
"pc_losses":"NPCs beaten:",
"pc_empty":"This terminal has no features yet \u2014 they are coming in a future update."
},
"npced":{
"title":"NPC editor",
"edit_selected":"Edit NPC",
"place_npc":"NPC",
"place_hint":"Pick up the NPC, then click a tile to place them.",
"hint":"Set up this NPC: name, look, lines and team. Visitors to your base will be able to battle them.",
"name":"Name",
"sprite":"NPC look",
"team":"Team ({n}/6)",
"team_empty":"Empty team",
"add_mon":"Add a Pok\u00e9mon",
"remove_mon":"Remove this Pok\u00e9mon",
"level_auto":"Level, moves and held item come from the chosen Pok\u00e9mon.",
"pick_title":"Pick a Pok\u00e9mon",
"pick_search":"Search a Pok\u00e9mon\u2026",
"pick_hint":"Click the sprite to change Pok\u00e9mon",
"pick_item_title":"Held item \u2014 {name}",
"no_item":"No held item",
"remove_item":"Remove item",
"item_set":"{name} is holding {item}.",
"from_preset":"Import a team\u2026",
"from_preset_active":"Active team",
"quotes":"Lines",
"quote_pre":"Before the battle",
"quote_win":"If they win",
"quote_lose":"If they lose",
"save":"Save",
"back":"Back",
"edit_sprite_hint":"Click sprite to change appearance",
"sprite_picker_title":"Choose appearance",
"sprite_picker_hint":"Click to change, closes automatically",
"preset_picker_title":"Choose a team",
"preset_picker_hint":"Click a team to import",
"delete":"Delete this NPC",
"delete_confirm":"Delete {name}? This cannot be undone.",
"updated":"{name} updated.",
"deleted":"{name} deleted.",
"imported":"Team imported: {n} Pok\u00e9mon."
},
"pc":{
"msg_saved":"PC message saved!",
"msg_title":"PC Message",
"msg_hint":"Message for visitors who take your flag",
"msg_placeholder":"Welcome to my base! Have fun!",
"msg_label":"Custom message",
"edit_selected":"Edit PC"
},

"npc":{
"gamin_tristan":{"name":"Youngster Tristan","pre":"I trained my Pokémon just for this base!","win":"Hey! You're really strong!","lose":"I knew my Rattata was the best!"},
"gamin_hugo":{"name":"Youngster Hugo","pre":"No one beats my fist duo!","win":"Ouch… my arms are jelly.","lose":"Did you see that?! What a fight!"},
"fillette_lea":{"name":"Lass Léa","pre":"Look how cute they are… and tough too!","win":"Even defeated, my team is the cutest!","lose":"So neat! Thanks for the battle!"},
"fillette_manon":{"name":"Lass Manon","pre":"My plants will poison everything!","win":"My plants need sun after that…","lose":"Nature always wins in the end!"},
"marin_gwenole":{"name":"Sailor Gwénolé","pre":"All hands on deck, landlubber!","win":"Blimey… beaten on dry land…","lose":"The sea always sides with the sailor!"},
"marin_erwan":{"name":"Sailor Erwan","pre":"Ride your Pokémon and hold fast!","win":"I took the waves, not you!","lose":"Right on target! Set sail for victory!"},
"ecolier_mathis":{"name":"Schoolkid Mathis","pre":"I studied types all night!","win":"But my math was exact…","lose":"Theory becomes practice. Lesson learned!"},
"ecoliere_jade":{"name":"Schoolgirl Jade","pre":"Fancy a psychic duel?","win":"I foresaw it… and yet…","lose":"My mind saw your defeat before you did!"}
},
"cat":{"desks":"Desks","chairs":"Chairs","mats":"Mats","plants":"Plants","objects":"Objects","wall":"Wall Art","dolls":"Dolls","cushions":"Cushions","appliances":"Appliances","tricks":"Tricks"},
"i":{
"a_note_mat":"A Note Mat",
"attract_mat":"Attract Mat",
"azurill_doll":"Azurill Doll",
"b_note_mat":"B Note Mat",
"ball_cushion":"Ball Cushion",
"ball_poster":"Ball Poster",
"baltoy_doll":"Baltoy Doll",
"big_plant":"Big Plant",
"blastoise_doll":"Blastoise Doll",
"blue_balloon":"Blue Balloon",
"blue_brick":"Blue Brick",
"blue_poster":"Blue Poster",
"blue_tent":"Blue Tent",
"breakable_door":"Breakable Door",
"brick_chair":"Brick Chair",
"brick_desk":"Brick Desk",
"c_high_note_mat":"High C Note Mat",
"c_low_note_mat":"Low C Note Mat",
"camp_chair":"Camp Chair",
"camp_desk":"Camp Desk",
"charizard_doll":"Charizard Doll",
"chikorita_doll":"Chikorita Doll",
"clefairy_doll":"Clefairy Doll",
"colorful_plant":"Colorful Plant",
"comfort_chair":"Comfort Chair",
"comfort_desk":"Comfort Desk",
"cute_poster":"Cute Poster",
"cute_tv":"Cute TV",
"cyndaquil_doll":"Cyndaquil Doll",
"d_note_mat":"D Note Mat",
"diamond_cushion":"Diamond Cushion",
"ditto_doll":"Ditto Doll",
"duskull_doll":"Duskull Doll",
"e_note_mat":"E Note Mat",
"f_note_mat":"F Note Mat",
"fence_length":"Fence Length",
"fence_width":"Fence Width",
"fire_blast_mat":"Fire Blast Mat",
"fire_cushion":"Fire Cushion",
"fissure_mat":"Fissure Mat",
"g_note_mat":"G Note Mat",
"glass_ornament":"Glass Ornament",
"glitter_mat":"Glitter Mat",
"gold_shield":"Gold Shield",
"gorgeous_plant":"Gorgeous Plant",
"grass_cushion":"Grass Cushion",
"green_poster":"Green Poster",
"gulpin_doll":"Gulpin Doll",
"hard_chair":"Hard Chair",
"hard_desk":"Hard Desk",
"heavy_chair":"Heavy Chair",
"heavy_desk":"Heavy Desk",
"jigglypuff_doll":"Jigglypuff Doll",
"jump_mat":"Jump Mat",
"kecleon_doll":"Kecleon Doll",
"kiss_cushion":"Kiss Cushion",
"kiss_poster":"Kiss Poster",
"lapras_doll":"Lapras Doll",
"long_poster":"Long Poster",
"lotad_doll":"Lotad Doll",
"marill_doll":"Marill Doll",
"meowth_doll":"Meowth Doll",
"mud_ball":"Mud Ball",
"mudkip_doll":"Mudkip Doll",
"pc":"PC",
"pichu_doll":"Pichu Doll",
"pika_cushion":"Pika Cushion",
"pika_poster":"Pika Poster",
"pikachu_doll":"Pikachu Doll",
"pokemon_chair":"Pokémon Chair",
"pokemon_desk":"Pokémon Desk",
"powder_snow_mat":"Powder Snow Mat",
"pretty_chair":"Pretty Chair",
"pretty_desk":"Pretty Desk",
"pretty_flowers":"Pretty Flowers",
"ragged_chair":"Ragged Chair",
"ragged_desk":"Ragged Desk",
"red_balloon":"Red Balloon",
"red_brick":"Red Brick",
"red_plant":"Red Plant",
"red_poster":"Red Poster",
"red_tent":"Red Tent",
"regice_doll":"Regice Doll",
"regirock_doll":"Regirock Doll",
"registeel_doll":"Registeel Doll",
"rhydon_doll":"Rhydon Doll",
"round_cushion":"Round Cushion",
"round_tv":"Round TV",
"sand_ornament":"Sand Ornament",
"sea_poster":"Sea Poster",
"seedot_doll":"Seedot Doll",
"silver_shield":"Silver Shield",
"skitty_doll":"Skitty Doll",
"sky_poster":"Sky Poster",
"slide":"Slide",
"small_chair":"Small Chair",
"small_desk":"Small Desk",
"smoochum_doll":"Smoochum Doll",
"snorlax_doll":"Snorlax Doll",
"solid_board":"Solid Board",
"spikes_mat":"Spikes Mat",
"spin_cushion":"Spinarak Cushion",
"spin_mat":"Spin Mat",
"stairs":"Stairs",
"stand":"Stand",
"surf_mat":"Surf Mat",
"swablu_doll":"Swablu Doll",
"thunder_mat":"Thunder Mat",
"tire":"Tire",
"togepi_doll":"Togepi Doll",
"torchic_doll":"Torchic Doll",
"totodile_doll":"Totodile Doll",
"treecko_doll":"Treecko Doll",
"tropical_plant":"Tropical Plant",
"tv":"TV",
"venusaur_doll":"Venusaur Doll",
"wailmer_doll":"Wailmer Doll",
"water_cushion":"Water Cushion",
"wynaut_doll":"Wynaut Doll",
"yellow_balloon":"Yellow Balloon",
"yellow_brick":"Yellow Brick",
"zigzag_cushion":"Zigzag Cushion"
}
};

// T2 (vague 38) : module ESM — export natif ; la surface classique est
// gardée sur l'objet global pour les registres (data.js) et les harnais VM.
if (typeof globalThis !== 'undefined') globalThis.L_en_base = L_en_base;
