// ===== EN — Gym Leader / Champion names & titles =====
export const L_en_champions = {
"brock": {"name":"Brock","title":"Pewter Gym Leader","badgeName":"Boulder Badge"},
"misty": {"name":"Misty","title":"Cerulean Gym Leader","badgeName":"Cascade Badge"},
"surge": {"name":"Lt. Surge","title":"Vermilion Gym Leader","badgeName":"Thunder Badge"},
"erika": {"name":"Erika","title":"Celadon Gym Leader","badgeName":"Rainbow Badge"},
"koga": {"name":"Koga","title":"Fuchsia Gym Leader","badgeName":"Soul Badge"},
"sabrina": {"name":"Sabrina","title":"Saffron Gym Leader","badgeName":"Marsh Badge"},
"blaine": {"name":"Blaine","title":"Cinnabar Gym Leader","badgeName":"Volcano Badge"},
"giovanni": {"name":"Giovanni","title":"Viridian Gym Leader","badgeName":"Earth Badge"},
"elite4": {"name":"Kanto League","title":"Kanto League","badgeName":"Kanto Champion Title"},
"johto_elite4": {"name":"Johto League","title":"Johto League","badgeName":"Johto Champion Title"},
"falkner": {"name":"Falkner","title":"Violet Gym Leader","badgeName":"Zephyr Badge"},
"bugsy": {"name":"Bugsy","title":"Azalea Gym Leader","badgeName":"Hive Badge"},
"whitney": {"name":"Whitney","title":"Goldenrod Gym Leader","badgeName":"Plain Badge"},
"morty": {"name":"Morty","title":"Ecruteak Gym Leader","badgeName":"Fog Badge"},
"chuck": {"name":"Chuck","title":"Cianwood Gym Leader","badgeName":"Storm Badge"},
"jasmine": {"name":"Jasmine","title":"Olivine Gym Leader","badgeName":"Mineral Badge"},
"pryce": {"name":"Pryce","title":"Mahogany Gym Leader","badgeName":"Glacier Badge"},
"clair": {"name":"Clair","title":"Blackthorn Gym Leader","badgeName":"Rising Badge"},
// League gauntlet stages (pass 19) — names/titles shown during the League
"lorelei": {"name":"Lorelei","title":"Elite Four — Ice & Water"},
"bruno": {"name":"Bruno","title":"Elite Four — Fighting & Rock"},
"agatha": {"name":"Agatha","title":"Elite Four — Ghost & Poison"},
"lance": {"name":"Lance","title":"Elite Four — Dragon"},
"blue": {"name":"Blue","title":"Kanto League Champion"},
"will": {"name":"Will","title":"Elite Four — Psychic"},
"koga_e4": {"name":"Koga","title":"Elite Four — Poison"},
"bruno_johto": {"name":"Bruno","title":"Elite Four — Fighting"},
"karen": {"name":"Karen","title":"Elite Four — Dark"},
"lance_johto": {"name":"Lance","title":"Johto League Champion"},
  "roxanne": {"name":"Roxanne","title":"Rustboro Gym Leader","badgeName":"Stone Badge"},
  "brawly": {"name":"Brawly","title":"Dewford Gym Leader","badgeName":"Knuckle Badge"},
  "wattson": {"name":"Wattson","title":"Mauville Gym Leader","badgeName":"Dynamo Badge"},
  "flannery": {"name":"Flannery","title":"Lavaridge Gym Leader","badgeName":"Heat Badge"},
  "norman": {"name":"Norman","title":"Petalburg Gym Leader","badgeName":"Balance Badge"},
  "winona": {"name":"Winona","title":"Fortree Gym Leader","badgeName":"Feather Badge"},
  "tate_liza": {"name":"Tate & Liza","title":"Mossdeep Gym Leaders (Duo)","badgeName":"Mind Badge"},
  "juan": {"name":"Juan","title":"Sootopolis Gym Leader","badgeName":"Rain Badge"},
  "sidney": {"name":"Sidney","title":"Elite Four Dark","badgeName":""},
  "phoebe": {"name":"Phoebe","title":"Elite Four Ghost","badgeName":""},
  "glacia": {"name":"Glacia","title":"Elite Four Ice","badgeName":""},
  "drake": {"name":"Drake","title":"Elite Four Dragon","badgeName":""},
  "steven": {"name":"Steven Stone","title":"Hoenn Champion","badgeName":"Hoenn Champion Title"},
  "hoenn_elite4": {"name":"Hoenn League","title":"Hoenn League","badgeName":"Hoenn Champion Title"},
};

// T2 (vague 38) : module ESM — export natif ; la surface classique est
// gardée sur l'objet global pour les registres (data.js) et les harnais VM.
if (typeof globalThis !== 'undefined') globalThis.L_en_champions = L_en_champions;
