// ===== EN — COMBAT strings =====
// Auto-extracted & grouped by domain. Edit text here, never hardcode in logic.

window.L_en_combat = {
"battle_lock_box":"<b>Battle in progress:</b> Adding or swapping is disabled.",
"battle_lock_team":"<b>Battle in progress:</b> Party is locked.",
"champ_no_loot":"Gym Leader battles do not award wild Pokémon captures.",
"dupe_tag":"duplicate",
"leave_combat":"Leave Combat",
"live_loot":"Live Loot:",
"no_loot_yet":"No loot collected yet.",
"talent_intimidate_player":"🧬 [Intimidate] {name}'s Attack fell!",
"talent_regenerator_player":"🧬 [Regenerator] {name} restored HP!",
"talent_intimidate_enemy":"🧬 [Intimidate] {name}'s Attack fell!",
"combat_attack_auto_1":"🧬 [Levitate] {p0} floats above Ground attacks!",
"combat_attack_auto_2":"🧬 [Lightning Rod] {p0} absorbed Electric attack!",
"combat_attack_auto_3":"{p0}'s attack missed!",
"combat_attack_auto_4":"It doesn't affect {p0}...",
"combat_attack_auto_5":"{p0} already has a status condition!",
"combat_attack_auto_6":"It doesn't affect {p0}...",
"combat_attack_auto_7":"{p0} is paralyzed!",
"combat_attack_auto_8":"{p0}'s attack missed!",
"combat_attack_auto_9":"It doesn't affect {p0}...",
"combat_attack_auto_10":"{p0} was poisoned!",
"combat_attack_auto_11":"{p0}'s attack missed!",
"combat_attack_auto_12":"It doesn't affect {p0}...",
"combat_attack_auto_13":"{p0} was badly poisoned!",
"combat_attack_auto_14":"{p0}'s attack missed!",
"combat_attack_auto_15":"It doesn't affect {p0}...",
"combat_attack_auto_16":"{p0} was burned!",
"combat_attack_auto_17":"{p0}'s attack missed!",
"combat_attack_auto_18":"{p0} fell asleep!",
"combat_attack_auto_19":"{p0}'s attack missed!",
"combat_attack_auto_20":"It doesn't affect {p0}...",
"combat_attack_auto_21":"{p0} was frozen!",
"combat_attack_auto_22":"{p0}'s attack missed!",
"combat_attack_auto_23":"{p0}'s Speed won't go any lower!",
"combat_attack_auto_24":"{p0}'s Speed fell!",
"combat_attack_auto_25":"🧬 [Huge Power] Physical Attack boosted by +60%!",
"combat_attack_auto_26":"🧬 [Guts] Attack boosted by +50% due to status!",
"combat_attack_auto_27":"🧬 [Overgrow] Grass power boosted!",
"combat_attack_auto_28":"🧬 [Blaze] Fire power boosted!",
"combat_attack_auto_29":"🧬 [Torrent] Water power boosted!",
"combat_attack_auto_30":"🧬 [Thick Fat] Fire/Ice damage halved!",
"combat_attack_auto_31":"🧬 [Multiscale] Full HP defense halved incoming damage!",
"combat_attack_auto_32":"{p0}'s King's Rock made {p1} flinch!",
"combat_attack_auto_33":"🧬 [Sturdy] {p0} endured the fatal hit!",
"combat_attack_auto_34":"🧬 [Rough Skin] {p0} took {p1} recoil damage!",
"combat_attack_auto_35":"🧬 [Static] {p0} paralyzed attacker on contact!",
"combat_attack_auto_36":"🧬 [Poison Point] {p0} poisoned attacker on contact!",
"combat_attack_auto_37":"{p0} is damaged by recoil! (-{p1} HP)",
"combat_attack_auto_38":"{p0} is hurt by Life Orb! (-{p1} HP)",
"combat_attack_auto_39":"{p0} flinched!",
"combat_attack_auto_40":"{p0} was burned!",
"combat_attack_auto_41":"{p0} was paralyzed!",
"combat_attack_auto_42":"{p0} was poisoned!",
"combat_attack_auto_43":"{p0} was frozen!",
"combat_attack_auto_44":"{p0} fell asleep!",
"combat_damage_lost":"{name} lost {damage} HP!{effect}",
"critical_hit":"Critical hit!",
"status_burn_faded":"{name}'s burn faded!",
"status_poison_faded":"{name} is no longer poisoned!",
"status_para_faded":"{name} is no longer paralyzed!",
"status_freeze_faded":"{name} thawed out!",
"status_sleep_faded":"{name} woke up!",
"burn_damage":"{name} is hurt by the burn (-{damage} HP)",
"poison_damage":"{name} is hurt by poison (-{damage} HP)",
"bad_poison_damage":"{name} is hurt by toxic poison (-{damage} HP)",
"leftovers_heal":"{name} restored {heal} HP with Leftovers!",
"pokemon_fainted":"{name} fainted!",
"training_round_ev":"🟢 Round defeated! EV {stat} increased to {value}/6!",
"new_talent_unlocked":"🎉 New ability unlocked: {talent} ({rarity})!",
"talent_reconfirmed":"✨ Ability {talent} ({rarity}) re-confirmed!",
"no_new_talent":"No new ability this time...",
"training_room_round":" TRAINING ROOM - Round {round}/6: {pokemon}!",
"champion_sends":"{champion} sends out {pokemon}!",
"league_stage_victory":" Victory against {trainer}! Your team was fully healed (100% HP)!",
"league_stage_success":" Stage {stage}/5 cleared! Team healed! Next battle: {trainer}...",
"league_next_battle":" KANTO LEAGUE - Battle {stage}/5: {trainer} sends out {pokemon}!",
"team_gains_xp":"Your team gains {xp} XP each!",
"empty_enemy_team_error":" Error: enemy team is empty.",
"enemy_not_found_error":" Error: enemy Pokémon not found.",
"wild_shiny_appears":" A wild {name} appeared... it sparkles strangely!",
"pokemon_appears":"{name} appeared!",
"trainer_sends":"{trainer} sends out {pokemon}!",
"give_up":"🏳 Give up",
"leave_battle_button":"🚪 Leave",
"need_badges_challenge":" You need {need} badge(s) to challenge {champion}.",
"league_battle_challenge":" KANTO LEAGUE - Battle 1/5: {trainer} challenges you!",
"league_intro_quote":"{trainer}: “Prepare to face the power of the Elite Four!”",
"champion_team_error":" Team error for champion {champion}.",
"champion_battle_start":"🎮 Battle against {champion}!",
"champion_intro_quote":"{champion}: “I am this Gym Leader!”",
"wild_pokemon_shiny_appears":" A wild {name} appeared... it sparkles strangely!",
"wild_pokemon_appears":"A wild {name} appeared!",
"player_pokemon_ko":"{name} is KO!",
"training_failed_ko_log":" Your training Pokémon is KO! Training failed...",
"training_failed_ko_notify":"Training failed! Your Pokémon was knocked out.",
"all_pokemon_ko_lost":"All your Pokémon are KO! You lost...",
"money_lost":"You lose {money}₽!",
"battle_lost_recover":" You lost! Start a new battle whenever you want: your team is healed at the beginning of each battle.",
"go_pokemon":"Go, {name}!",
"switch_pending":"⏳ {name} will enter battle as soon as possible...",
"solo_training_no_switch":"Switch impossible: your Pokémon is training solo at the Dojo!",
"shiny_captured":" SHINY POKÉMON CAUGHT! ",
"hidden_talent_unlocked_reward":" (Hidden Talent unlocked!)",
"league_master_victory_log":" You defeated the Kanto Champion and triumphed over all 5 League battles!",
"league_master_title_reward":" Congratulations! You obtain the Pokémon Master Title! (+{money}₽)",
"rematch_won_reward":" Rematch won against {champion}! (+{money}₽)",
"league_victory_message":" Congratulations! You triumphed over all 5 Kanto League battles and obtained the Pokémon Master Title!",
"add_pokemon":"Add a Pokémon",
"team_count":"{count}/6 in team",
"item_removed_team":"{item} removed from the team.",
"evolution_duplicate_bonus":" {name} would have evolved into {target}, already owned! (+{money}₽)",
"evolution_duplicate_bonus_html":" {name} would have evolved into <b>{target}</b>, already owned! (+{money}₽)",
"evolution_triggered_box":" {name} triggered an evolution: {target} appears in the PC Box!",
"evolution_created_box":" An evolution of {name} was born: <b>{target}</b> (Lv.1, → box)!",
"captured_pokemon_title":"Captured Pokémon:",
"found_items_title":"Items found:",
"woke_up_log":"{name} woke up!",
"sleeping_turns_log":"{name} is asleep... ({turns} turn{plural})",
"thawed_log":"{name} thawed out!",
"frozen_skip_log":"{name} is frozen...",
"paralyzed_skip_log":"{name} is paralyzed and cannot move!",
"uses_move_log":"{name} uses <b>{move}</b>!",
"forfeit_champion":"You give up the battle against {champion}. You can challenge them again anytime.",
"leave_battle_notify":"🚪 You leave the battle.",
"leaving_button":"⏳ Leaving...",
"map_legend_title":"Map legend",
"current_location":"Current location",
"reachable_location":"Reachable location",
"locked_location":"Locked location",
"eff_immune":"⛔ Immune!",
"eff_very_weak":"😴 Barely effective...",
"battle_in_progress":"Battle in progress",
};
