// ===== EN — ECONOMY strings =====
// Auto-extracted & grouped by domain. Edit text here, never hardcode in logic.

window.L_en_economy = {
  "already_eq": "Already equipped",
  "already_held": "Already held by",
  "already_owned_sp": "Species owned",
  "back_bag": "🎒 Back to Bag",
  "box_empty": "Your PC box is empty.<br><br>Pokémon caught when party is full (6/6) and evolutions appear here.",
  "evolves_into": "Evolves into:",
  "in_stock": "In stock",
  "inv_empty": "Your bag is empty.<br><br>Buy berries in the shop or dig underground for stones and treasures.",
  "market_cat_leg": "👑 Legendaries",
  "market_cat_other": "🔹 Other Pokémon",
  "market_cat_rare": "💎 Rare Pokémon",
  "market_cat_starter": "🌟 Starters",
  "market_empty": "All Pokémon are already obtainable in game!",
  "market_owned": "✅ Already Owned",
  "mine_chisel": "⛏️ Chisel (1x1 deep, -5 Energy)",
  "mine_energy": "⚡ Drilling Energy",
  "mine_energy_hint": "+2 / sec · +15 per wild battle victory",
  "mine_hammer": "🔨 Hammer (3x3 wide, -15 Energy)",
  "mine_new_layer": "🔄 New Layer Survey",
  "mine_treasures": "Excavated Treasures:",
  "no_evo_stone": "No evolution stones available.",
  "remove_q": "Remove",
  "sell_all": "Sell All",
  "sell_one": "Sell x1",
  "shop_empty": "No shop here.",
  "stone_inv_lbl": "Evolution Stone",
  "stone_lbl": "🪨 Evolution Stone: Click to evolve a compatible Pokémon",
  "treasure_inv_lbl": "Treasure (Resell)",
  "treasure_lbl": "💰 Underground Treasure: Click to sell",
  "use_stone": "Use",
  "will_replace": "(will replace current item)",
};

