// ===== EN — Location names (all regions) =====

window.L_location_names_en = {
  "abandoned_ship": "Abandoned Ship",
  "ancient_tomb": "Ancient Tomb (Registeel)",
  "aqua_hideout": "Aqua Hideout",
  "azalea": "Azalea Town",
  "battle_frontier": "Battle Frontier",
  "blackthorn": "Blackthorn City",
  "burnedtower": "Burned Tower",
  "cave_of_origin": "Cave of Origin",
  "celadon": "Celadon City",
  "cerulean": "Cerulean City",
  "ceruleancave": "Cerulean Cave",
  "cherrygrove": "Cherrygrove City",
  "cianwood": "Cianwood City",
  "cinnabar": "Cinnabar Island",
  "darkcave": "Dark Cave",
  "desert_ruins": "Desert Ruins (Regirock)",
  "dewford": "Dewford Town",
  "diglettscave": "Diglett's Cave",
  "ecruteak": "Ecruteak City",
  "evergrande": "Ever Grande City",
  "fallarbor": "Fallarbor Town",
  "fiery_path": "Fiery Path",
  "fortree": "Fortree City",
  "fuchsia": "Fuchsia City",
  "goldenrod": "Goldenrod City",
  "granite_cave": "Granite Cave",
  "hoenn_league": "Hoenn Pokémon League",
  "icepath": "Ice Path",
  "ilexforest": "Ilex Forest",
  "indigo": "Indigo Plateau",
  "indigo_jo": "Indigo Plateau",
  "island_cave": "Island Cave (Regice)",
  "jroute26": "Route 26",
  "jroute27": "Route 27",
  "jroute28": "Route 28",
  "jroute29": "Route 29",
  "jroute30": "Route 30",
  "jroute31": "Route 31",
  "jroute32": "Route 32",
  "jroute32_mid": "Route 32",
  "jroute32_south": "Route 32",
  "jroute33": "Route 33",
  "jroute34": "Route 34",
  "jroute35": "Route 35",
  "jroute36": "Route 36",
  "jroute37": "Route 37",
  "jroute38": "Road 38/39",
  "jroute39": "Route 39",
  "jroute40": "Route 40",
  "jroute41": "Route 41",
  "jroute42": "Route 42",
  "jroute43": "Route 43",
  "jroute44": "Route 44",
  "jroute45": "Road 45/46",
  "jroute46": "Route 46",
  "jroute47": "Route 47",
  "jroute48": "Route 48",
  "lakerage": "Lake of Rage",
  "lavaridge": "Lavaridge Town",
  "lavender": "Lavender Town",
  "lilycove": "Lilycove City",
  "littleroot": "Littleroot Town",
  "mahogany": "Mahogany Town",
  "mauville": "Mauville City",
  "meteor_falls": "Meteor Falls",
  "mirage_island": "Mirage Island",
  "mossdeep": "Mossdeep City",
  "mossdeep_space_center": "Mossdeep Space Center",
  "mt_chimney": "Mt. Chimney",
  "mt_pyre": "Mt. Pyre",
  "mtmoon": "Mt. Moon",
  "mtmortar": "Mt. Mortar",
  "mtsilver": "Mt. Silver",
  "nationalpark": "National Park",
  "newbark": "New Bark Town",
  "oldale": "Oldale Town",
  "olivine": "Olivine City",
  "pacifidlog": "Pacifidlog Town",
  "pallet": "Pallet Town",
  "petalburg": "Petalburg City",
  "petalburg_woods": "Petalburg Woods",
  "pewter": "Pewter City",
  "pokemonmansion": "Pokémon Mansion",
  "pokemontower": "Pokémon Tower",
  "powerplant": "Power Plant",
  "rocktunnel": "Rock Tunnel",
  "route1": "Route 1",
  "route10": "Route 10",
  "route101": "Route 101",
  "route102": "Route 102",
  "route103": "Route 103",
  "route104": "Route 104",
  "route105": "Route 105",
  "route106": "Route 106",
  "route107": "Route 107",
  "route108": "Route 108",
  "route109": "Route 109",
  "route11": "Route 11",
  "route110": "Route 110",
  "route111": "Route 111",
  "route112": "Route 112",
  "route113": "Route 113",
  "route114": "Route 114",
  "route115": "Route 115",
  "route116": "Route 116",
  "route117": "Route 117",
  "route118": "Route 118",
  "route119": "Route 119",
  "route12": "Route 12",
  "route120": "Route 120",
  "route121": "Route 121",
  "route122": "Route 122",
  "route123": "Route 123",
  "route124": "Route 124",
  "route125": "Route 125",
  "route126": "Route 126",
  "route127": "Route 127",
  "route128": "Route 128",
  "route129": "Route 129",
  "route13": "Route 13",
  "route130": "Route 130",
  "route131": "Route 131",
  "route132": "Route 132",
  "route133": "Route 133",
  "route134": "Route 134",
  "route14": "Route 14",
  "route15": "Route 15",
  "route16": "Route 16",
  "route17": "Cycling Road (17)",
  "route18": "Route 18",
  "route19": "Sea Route 19",
  "route2": "Route 2",
  "route20": "Sea Route 20",
  "route21": "Sea Route 21",
  "route22": "Route 22",
  "route23": "Victory Road (23)",
  "route24": "Nugget Bridge (24)",
  "route25": "Route 25",
  "route2_south": "Route 2 (South)",
  "route3": "Route 3",
  "route4": "Route 4",
  "route5": "Route 5",
  "route6": "Route 6",
  "route7": "Route 7",
  "route8": "Route 8",
  "route9": "Route 9",
  "ruinsofalph": "Ruins of Alph",
  "rustboro": "Rustboro City",
  "rusturf_tunnel": "Rusturf Tunnel",
  "safari_zone_ho": "Hoenn Safari Zone",
  "safarizone": "Safari Zone",
  "saffron": "Saffron City",
  "seafloor_cavern": "Seafloor Cavern",
  "seafoamislands": "Seafoam Islands",
  "sealed_chamber": "Sealed Chamber",
  "shoal_cave": "Shoal Cave",
  "sky_pillar": "Sky Pillar",
  "slateport": "Slateport City",
  "slowpokewell": "Slowpoke Well",
  "sootopolis": "Sootopolis City",
  "southern_island": "Southern Island",
  "sprouttower": "Sprout Tower",
  "tintower": "Bell Tower",
  "tohjofalls": "Tohjo Falls",
  "unioncave": "Union Cave",
  "verdanturf": "Verdanturf Town",
  "vermilion": "Vermilion City",
  "victoryroad": "Victory Road (Cave)",
  "victoryroad_ho": "Hoenn Victory Road",
  "victoryroad_jo": "Victory Road (Johto)",
  "violet": "Violet City",
  "viridian": "Viridian City",
  "viridianforest": "Viridian Forest",
  "weather_institute": "Weather Institute",
  "whirlislands": "Whirl Islands"
};
