// ===== EN — Location names (Kanto + Johto) =====

window.L_location_names_en = {
  "azalea": "Azalea Town",
  "blackthorn": "Blackthorn City",
  "celadon": "Celadon City",
  "cerulean": "Cerulean City",
  "ceruleancave": "Cerulean Cave",
  "cherrygrove": "Cherrygrove City",
  "cianwood": "Cianwood City",
  "cinnabar": "Cinnabar Island",
  "diglettscave": "Diglett's Cave",
  "ecruteak": "Ecruteak City",
  "fuchsia": "Fuchsia City",
  "goldenrod": "Goldenrod City",
  "ilexforest": "Ilex Forest",
  "indigo": "Indigo Plateau",
  "jroute29": "Road 29",
  "jroute30": "Road 30",
  "jroute31": "Road 31",
  "jroute32": "Road 32",
  "jroute32_mid": "Road 32",
  "jroute32_south": "Road 32",
  "jroute33": "Road 33",
  "jroute34": "Road 34",
  "jroute35": "Road 35",
  "jroute36": "Road 36",
  "jroute38": "Road 38/39",
  "jroute40": "Sea Road 40/41",
  "jroute42": "Road 42",
  "jroute44": "Ice Path (44)",
  "jroute45": "Road 45/46",
  "lakerage": "Lake of Rage",
  "lavender": "Lavender Town",
  "mahogany": "Mahogany Town",
  "mtmoon": "Mt. Moon",
  "newbark": "New Bark Town",
  "olivine": "Olivine City (Harbor 🚢)",
  "pallet": "Pallet Town",
  "pewter": "Pewter City",
  "pokemonmansion": "Pokémon Mansion",
  "pokemontower": "Pokémon Tower",
  "powerplant": "Power Plant",
  "rocktunnel": "Rock Tunnel",
  "route1": "Road 1",
  "route10": "Road 10",
  "route11": "Road 11",
  "route12": "Road 12",
  "route13": "Road 13",
  "route14": "Road 14",
  "route15": "Road 15",
  "route16": "Road 16",
  "route17": "Cycling Road (17)",
  "route18": "Road 18",
  "route19": "Sea Road 19",
  "route2": "Road 2",
  "route20": "Sea Road 20",
  "route21": "Sea Road 21",
  "route22": "Road 22",
  "route23": "Victory Road (23)",
  "route24": "Nugget Bridge (24)",
  "route25": "Road 25",
  "route3": "Road 3",
  "route4": "Road 4",
  "route5": "Road 5",
  "route6": "Road 6",
  "route7": "Road 7",
  "route8": "Road 8",
  "route9": "Road 9",
  "safarizone": "Safari Zone",
  "saffron": "Saffron City",
  "seafoamislands": "Seafoam Islands",
  "unioncave": "Union Cave",
  "vermilion": "Vermilion City",
  "victoryroad": "Victory Road (Cave)",
  "violet": "Violet City",
  "viridian": "Viridian City",
  "viridianforest": "Viridian Forest",
};

