// ===== EN — Location names (Kanto + Johto) =====

window.L_location_names_en = {
"azalea":"Azalea Town",
"blackthorn":"Blackthorn City",
"celadon":"Celadon City",
"cerulean":"Cerulean City",
"ceruleancave":"Cerulean Cave",
"cherrygrove":"Cherrygrove City",
"cianwood":"Cianwood City",
"cinnabar":"Cinnabar Island",
"diglettscave":"Diglett's Cave",
"ecruteak":"Ecruteak City",
"fuchsia":"Fuchsia City",
"goldenrod":"Goldenrod City",
"ilexforest":"Ilex Forest",
"indigo":"Indigo Plateau",
"jroute29":"Route 29",
"jroute30":"Route 30",
"jroute31":"Route 31",
"jroute32":"Route 32",
"jroute32_mid":"Route 32",
"jroute32_south":"Route 32",
"jroute33":"Route 33",
"jroute34":"Route 34",
"jroute35":"Route 35",
"jroute36":"Route 36",
"jroute38":"Road 38/39",
"jroute40":"Route 40",
"jroute42":"Route 42",
"jroute44":"Route 44",
"jroute45":"Road 45/46",
"lakerage":"Lake of Rage",
"lavender":"Lavender Town",
"mahogany":"Mahogany Town",
"mtmoon":"Mt. Moon",
"newbark":"New Bark Town",
"olivine":"Olivine City",
"pallet":"Pallet Town",
"pewter":"Pewter City",
"pokemonmansion":"Pokémon Mansion",
"pokemontower":"Pokémon Tower",
"powerplant":"Power Plant",
"rocktunnel":"Rock Tunnel",
"route1":"Route 1",
"route10":"Route 10",
"route11":"Route 11",
"route12":"Route 12",
"route13":"Route 13",
"route14":"Route 14",
"route15":"Route 15",
"route16":"Route 16",
"route17":"Cycling Road (17)",
"route18":"Route 18",
"route19":"Sea Route 19",
"route2":"Route 2",
"route20":"Sea Route 20",
"route21":"Sea Route 21",
"route22":"Route 22",
"route23":"Victory Road (23)",
"route24":"Nugget Bridge (24)",
"route25":"Route 25",
"route3":"Route 3",
"route4":"Route 4",
"route5":"Route 5",
"route6":"Route 6",
"route7":"Route 7",
"route8":"Route 8",
"route9":"Route 9",
"safarizone":"Safari Zone",
"saffron":"Saffron City",
"seafoamislands":"Seafoam Islands",
"unioncave":"Union Cave",
"vermilion":"Vermilion City",
"victoryroad":"Victory Road (Cave)",
"violet":"Violet City",
"viridian":"Viridian City",
"viridianforest":"Viridian Forest",
"jroute26":"Route 26",
"jroute27":"Route 27",
"jroute28":"Route 28",
"jroute37":"Route 37",
"jroute39":"Route 39",
"jroute41":"Route 41",
"jroute46":"Route 46",
"jroute47":"Route 47",
"jroute48":"Route 48",
"nationalpark":"National Park",
"indigo_jo":"Indigo Plateau",
"sprouttower":"Sprout Tower",
"ruinsofalph":"Ruins of Alph",
"burnedtower":"Burned Tower",
"tintower":"Bell Tower",
"mtmortar":"Mt. Mortar",
"icepath":"Ice Path",
"darkcave":"Dark Cave",
"slowpokewell":"Slowpoke Well",
"whirlislands":"Whirl Islands",
"victoryroad_jo":"Victory Road (Johto)",
"mtsilver":"Mt. Silver",
"tohjofalls":"Tohjo Falls"
};

