// ===== EN — Move names (French id -> English name) =====

window.L_move_names_en = {
"absorb":"Absorb",
"bite":"Bite",
"blizzard":"Blizzard",
"bodyslam":"Body Slam",
"bubble":"Bubble",
"bugbite":"Bug Bite",
"confusion":"Confusion",
"crunch":"Crunch",
"dazzlinggleam":"Dazzling Gleam",
"dig":"Dig",
"doubleedge":"Double-Edge",
"dragonbreath":"Dragon Breath",
"dragonrage":"Dragon Rage",
"earthquake":"Earthquake",
"ember":"Ember",
"fieryspin":"Fire Spin",
"fireblast":"Fire Blast",
"flamethrower":"Flamethrower",
"gust":"Gust",
"hydropump":"Hydro Pump",
"hyperbeam":"Hyper Beam",
"icebeam":"Ice Beam",
"irontail":"Iron Tail",
"jumpkick":"Jump Kick",
"karatechop":"Karate Chop",
"lick":"Lick",
"megapunch":"Mega Punch",
"metalclaw":"Metal Claw",
"moonblast":"Moonblast",
"mudshot":"Mud Shot",
"nightshade":"Night Shade",
"outrage":"Outrage",
"poisonsting":"Poison Sting",
"powdersnow":"Powder Snow",
"psybeam":"Psybeam",
"psychic":"Psychic",
"quickattack":"Quick Attack",
"razorleaf":"Razor Leaf",
"return":"Return",
"rockslide":"Rock Slide",
"rockthrow":"Rock Throw",
"scratch":"Scratch",
"shadowball":"Shadow Ball",
"skyattack":"Sky Attack",
"slash":"Slash",
"sludgebomb":"Sludge Bomb",
"solarbeam":"Solar Beam",
"stoneedge":"Stone Edge",
"stringshot":"String Shot",
"surf":"Surf",
"tackle":"Tackle",
"thunder":"Thunder",
"thunderbolt":"Thunderbolt",
"thundershock":"Thunder Shock",
"thunderwave":"Thunder Wave",
"toxic":"Toxic",
"vinewhip":"Vine Whip",
"watergun":"Water Gun",
"wingattack":"Wing Attack",
};



window.L_en_move_descs = {
  "absorb": "A legitimate strategic combat move.",
  "acid": "10% chance to decrease enemy Special Defense by 50%",
  "acidarmor": "Increases Defense by 100%",
  "acidspray": "50% chance to decrease enemy Special Defense by 50%",
  "acrobatics": "Power doubles if the user is not holding any item",
  "acupressure": "Raises by 100% two random stats",
  "aerialace": "A legitimate strategic combat move.",
  "aeroblast": "A legitimate strategic combat move.",
  "afteryou": "A legitimate strategic combat move.",
  "agility": "Increases Speed by 75%",
  "aircutter": "A legitimate strategic combat move.",
  "airslash": "A legitimate strategic combat move.",
  "alluringvoice": "A legitimate strategic combat move.",
  "allyswitch": "A legitimate strategic combat move.",
  "amnesia": "Increases Special Defense by 100%",
  "ancientpower": "10% chance to increase all Stats by 50%",
  "aquajet": "Attacks x1.2 faster than usual",
  "aquaring": "A legitimate strategic combat move.",
  "aquatail": "A legitimate strategic combat move.",
  "armthrust": "Hits 2-5 times",
  "aromatherapy": "A legitimate strategic combat move.",
  "assist": "A legitimate strategic combat move.",
  "assurance": "A legitimate strategic combat move.",
  "astonish": "A legitimate strategic combat move.",
  "attract": "A legitimate strategic combat move.",
  "aurasphere": "A legitimate strategic combat move.",
  "aurorabeam": "50% chance to decrease enemy Attack by 50%",
  "auroraveil": "A legitimate strategic combat move.",
  "autotomize": "A legitimate strategic combat move.",
  "avalanche": "Decreases enemy Speed by 50%",
  "axekick": "A legitimate strategic combat move.",
  "babydolleyes": "Decreases enemy Attack by 50%",
  "barbbarrage": "Hits 2-5 times",
  "barrage": "Hits 2-5 times",
  "barrier": "Increases Defense by 100%",
  "batonpass": "User transfers all of its stat changes and status to a the entire team and faints. This move can only be present once per team",
  "beatup": "A legitimate strategic combat move.",
  "belch": "A legitimate strategic combat move.",
  "bellydrum": "Increases Attack by 150% but decreases Defense and Special Defense by 50%",
  "bestow": "A legitimate strategic combat move.",
  "bide": "A legitimate strategic combat move.",
  "bind": "A legitimate strategic combat move.",
  "bite": "A legitimate strategic combat move.",
  "blastburn": "A legitimate strategic combat move.",
  "blazekick": "10% chance to inflict",
  "blizzard": "A legitimate strategic combat move.",
  "block": "A legitimate strategic combat move.",
  "bodypress": "Power increases by x1.2-1.5 if Defense/Special Defense is risen",
  "bodyslam": "A legitimate strategic combat move.",
  "boneclub": "A legitimate strategic combat move.",
  "bonemerang": "A legitimate strategic combat move.",
  "bonerush": "Hits 2-5 times",
  "bounce": "Power increases by x1.2-1.5 if Defense/Special Defense is risen",
  "bravebird": "Attacks x1.2 slower than usual",
  "breakingswipe": "A legitimate strategic combat move.",
  "brickbreak": "30% chance to decrease enemy Defense by 50%",
  "brine": "A legitimate strategic combat move.",
  "brutalswing": "Decreases Attack by 50%",
  "bubble": "A legitimate strategic combat move.",
  "bubblebeam": "30% chance to decrease enemy Speed by 50%",
  "bugbite": "A legitimate strategic combat move.",
  "bugbuzz": "10% chance to decrease enemy Special Defense by 50%",
  "bulkup": "Increases Attack and Defense by 50%",
  "bulldoze": "Decreases enemy Speed by 50%",
  "bulletpunch": "Attacks x1.2 faster than usual",
  "bulletseed": "Hits 2-5 times",
  "burningjealousy": "A legitimate strategic combat move.",
  "burnup": "Inflicts",
  "calmmind": "Increases Special Defense and Special Attack by 50%",
  "camouflage": "Temporarily changes the type of the user corresponding to the weather, and increases Speed by 75%",
  "captivate": "A legitimate strategic combat move.",
  "charge": "Increases Special Attack by 100%, Defense by 50% and Special Defense by 50%",
  "chargebeam": "50% chance to increase Special Attack by 50%",
  "charm": "Decreases enemy Attack by 100%",
  "chillingwater": "Decreases enemy Attack by 50%",
  "chillyreception": "Changes the weather to  and switches to the next party member",
  "chipaway": "A legitimate strategic combat move.",
  "circlethrow": "A legitimate strategic combat move.",
  "clamp": "Hits 2-5 times",
  "clearsmog": "A legitimate strategic combat move.",
  "closecombat": "Decreases Defense and Special Defense by 50%",
  "coaching": "A legitimate strategic combat move.",
  "coil": "Increases Attack and Defense by 50%",
  "cometpunch": "Hits 2-5 times",
  "comeuppance": "A legitimate strategic combat move.",
  "confide": "A legitimate strategic combat move.",
  "confuseray": "Inflicts",
  "confusion": "Attacks x1.2 faster than usual",
  "constrict": "A legitimate strategic combat move.",
  "conversion": "Temporarily changes the type of the user to the type of the first move slot, and increases Speed by 75%",
  "conversion2": "A legitimate strategic combat move.",
  "copycat": "A legitimate strategic combat move.",
  "corrosivegas": "A legitimate strategic combat move.",
  "cosmicpower": "A legitimate strategic combat move.",
  "cottonguard": "Increases Defense by 100% and Special Defense by 50%",
  "cottonspore": "Decreases enemy Speed by 75%",
  "counter": "A legitimate strategic combat move.",
  "covet": "A legitimate strategic combat move.",
  "crabhammer": "Attacks x1.2 slower than usual",
  "crosschop": "A legitimate strategic combat move.",
  "crosspoison": "10% chance to inflict",
  "crunch": "10% chance to decrease enemy Defense by 50%",
  "crushclaw": "A legitimate strategic combat move.",
  "curse": "A legitimate strategic combat move.",
  "cut": "A legitimate strategic combat move.",
  "darkestlariat": "A legitimate strategic combat move.",
  "darkpulse": "A legitimate strategic combat move.",
  "dazzlinggleam": "A legitimate strategic combat move.",
  "defensecurl": "A legitimate strategic combat move.",
  "defog": "A legitimate strategic combat move.",
  "destinybond": "A legitimate strategic combat move.",
  "detect": "A legitimate strategic combat move.",
  "dig": "Power increases by x1.2-1.5 if Defense/Special Defense is risen",
  "disable": "A legitimate strategic combat move.",
  "disarmingvoice": "Attacks x1.2 faster than usual",
  "discharge": "30% chance to inflict",
  "dive": "A legitimate strategic combat move.",
  "dizzypunch": "10% chance to inflict",
  "doubleedge": "A legitimate strategic combat move.",
  "doublehit": "Hits 2 times",
  "doublekick": "A legitimate strategic combat move.",
  "doubleslap": "Hits 2-5 times",
  "doubleteam": "A legitimate strategic combat move.",
  "dracometeor": "Decreases Special Attack by 50%",
  "dragonbreath": "10% chance to inflict",
  "dragoncheer": "A legitimate strategic combat move.",
  "dragonclaw": "A legitimate strategic combat move.",
  "dragondance": "Increases Attack and Speed by 50%. Attacks x1.4 slower than usual",
  "dragonpulse": "A legitimate strategic combat move.",
  "dragonrage": "A legitimate strategic combat move.",
  "dragonrush": "Attacks x1.2 slower than usual. Power increases by x1.2-1.5 if Defense/Special Defense is risen",
  "dragontail": "30% chance to increase Attack by 50%",
  "drainingkiss": "50% chance to decrease enemy Defense by 50%",
  "drainpunch": "A legitimate strategic combat move.",
  "dreameater": "A legitimate strategic combat move.",
  "drillpeck": "A legitimate strategic combat move.",
  "drillrun": "A legitimate strategic combat move.",
  "dualchop": "Hits 2 times",
  "dualwingbeat": "Hits 2 times",
  "dynamicpunch": "Inflicts",
  "earthpower": "10% chance to decrease enemy Special Defense by 50%",
  "earthquake": "A legitimate strategic combat move.",
  "echoedvoice": "Multiplies base power by 1.2x everytime its used, up to 5 times. Depletes all stacks upon switching Pokemon",
  "eerieimpulse": "A legitimate strategic combat move.",
  "eggbomb": "A legitimate strategic combat move.",
  "electricterrain": "Changes the weather to",
  "electroball": "Attacks x2 faster than usual",
  "electroweb": "Decreases enemy Speed by 50%",
  "embargo": "Prevents the enemy to use the move in the slot embargo was used. This is treated as a status effect",
  "ember": "10% chance to inflict",
  "encore": "A legitimate strategic combat move.",
  "endeavor": "A legitimate strategic combat move.",
  "endure": "A legitimate strategic combat move.",
  "energyball": "10% chance to decrease enemy Special Defense by 50%",
  "entrainment": "A legitimate strategic combat move.",
  "eruption": "A legitimate strategic combat move.",
  "expandingforce": "A legitimate strategic combat move.",
  "explosion": "A legitimate strategic combat move.",
  "extrasensory": "A legitimate strategic combat move.",
  "extremespeed": "Attacks x1.2 faster than usual",
  "facade": "Power doubles if the user is Paralyzed, Burned or Poisoned",
  "fairywind": "30% chance to decrease enemy Speed by 50%",
  "fakeout": "A legitimate strategic combat move.",
  "faketears": "Decreases enemy Special Defense by 100%",
  "falseswipe": "A legitimate strategic combat move.",
  "featherdance": "Decreases enemy Attack by 100%",
  "feint": "A legitimate strategic combat move.",
  "feintattack": "Attacks x1.2 faster than usual",
  "fellstinger": "A legitimate strategic combat move.",
  "finalgambit": "A legitimate strategic combat move.",
  "fireblast": "Attacks x1.2 slower than usual",
  "firefang": "10% chance to inflict",
  "firepledge": "A legitimate strategic combat move.",
  "firepunch": "10% chance to inflict",
  "firespin": "Hits 2-5 times",
  "firstimpression": "Attacks x1.2 slower than usual",
  "fissure": "A legitimate strategic combat move.",
  "flail": "A legitimate strategic combat move.",
  "flameburst": "Inflicts  to the entire team",
  "flamecharge": "50% chance to increase Speed by 50%",
  "flamethrower": "10% chance to inflict",
  "flamewheel": "A legitimate strategic combat move.",
  "flareblitz": "Attacks x1.2 slower than usual",
  "flash": "A legitimate strategic combat move.",
  "flashcannon": "10% chance to decrease enemy Special Defense by 50%",
  "flatter": "A legitimate strategic combat move.",
  "fling": "A legitimate strategic combat move.",
  "flipturn": "A legitimate strategic combat move.",
  "flowershield": "A legitimate strategic combat move.",
  "fly": "A legitimate strategic combat move.",
  "focusblast": "Attacks x1.2 slower than usual",
  "focusenergy": "A legitimate strategic combat move.",
  "focuspunch": "A legitimate strategic combat move.",
  "followme": "A legitimate strategic combat move.",
  "foresight": "A legitimate strategic combat move.",
  "foulplay": "A legitimate strategic combat move.",
  "freezedry": "Super-effective against Water-types",
  "frenzyplant": "Attacks x1.5 slower than usual",
  "frostbreath": "30% chance to decrease enemy Special Attack by 50%",
  "frustration": "A legitimate strategic combat move.",
  "furyattack": "A legitimate strategic combat move.",
  "furycutter": "Multiplies base power by 1.2x everytime its used, up to 5 times. Depletes all stacks upon switching Pokemon",
  "furyswipes": "A legitimate strategic combat move.",
  "futuresight": "Attacks x2 slower than usual",
  "gastroacid": "A legitimate strategic combat move.",
  "gigadrain": "A legitimate strategic combat move.",
  "gigaimpact": "Attacks x1.5 slower than usual",
  "glare": "A legitimate strategic combat move.",
  "grassknot": "A legitimate strategic combat move.",
  "grasspledge": "A legitimate strategic combat move.",
  "grasswhistle": "A legitimate strategic combat move.",
  "grassyglide": "A legitimate strategic combat move.",
  "grassyterrain": "Changes the weather to",
  "gravity": "A legitimate strategic combat move.",
  "growl": "Decreases enemy Attack by 50%",
  "growth": "A legitimate strategic combat move.",
  "grudge": "A legitimate strategic combat move.",
  "guardsplit": "A legitimate strategic combat move.",
  "guardswap": "A legitimate strategic combat move.",
  "guillotine": "A legitimate strategic combat move.",
  "gunkshot": "A legitimate strategic combat move.",
  "gust": "A legitimate strategic combat move.",
  "gyroball": "A legitimate strategic combat move.",
  "hail": "Changes the weather to",
  "hammerarm": "Decreases Speed by 50%",
  "harden": "A legitimate strategic combat move.",
  "hardpress": "A legitimate strategic combat move.",
  "haze": "A legitimate strategic combat move.",
  "headbutt": "A legitimate strategic combat move.",
  "headsmash": "A legitimate strategic combat move.",
  "healbell": "A legitimate strategic combat move.",
  "healblock": "A legitimate strategic combat move.",
  "healingwish": "A legitimate strategic combat move.",
  "healpulse": "A legitimate strategic combat move.",
  "heartstamp": "A legitimate strategic combat move.",
  "heatcrash": "Decreases Attack by 50%",
  "heatwave": "50% chance to inflict",
  "heavyslam": "A legitimate strategic combat move.",
  "helpinghand": "A legitimate strategic combat move.",
  "hex": "Power doubles if the target has a status effect",
  "hiddenpower": "A legitimate strategic combat move.",
  "highhorsepower": "A legitimate strategic combat move.",
  "highjumpkick": "A legitimate strategic combat move.",
  "honeclaws": "Increases Attack and Speed by 50%. Attacks x1.4 slower than usual",
  "hornattack": "A legitimate strategic combat move.",
  "horndrill": "A legitimate strategic combat move.",
  "howl": "Increases Attack by 100% to the entire team",
  "hurricane": "10% chance to inflict",
  "hydrocannon": "Attacks x1.5 slower than usual",
  "hydropump": "Attacks x1.2 slower than usual",
  "hyperbeam": "Attacks x1.5 slower than usual",
  "hyperdrill": "A legitimate strategic combat move.",
  "hyperfang": "A legitimate strategic combat move.",
  "hypervoice": "A legitimate strategic combat move.",
  "hypnosis": "A legitimate strategic combat move.",
  "iceball": "Multiplies base power by 1.2x everytime its used, up to 5 times. Depletes all stacks upon switching Pokemon",
  "icebeam": "10% chance to inflict",
  "icefang": "10% chance to inflict",
  "icepunch": "10% chance to inflict",
  "iceshard": "Attacks x1.2 faster than usual",
  "icespinner": "A legitimate strategic combat move.",
  "iciclecrash": "A legitimate strategic combat move.",
  "iciclespear": "Hits 2-5 times",
  "icywind": "Decreases enemy Speed by 50%",
  "imprison": "A legitimate strategic combat move.",
  "incinerate": "A legitimate strategic combat move.",
  "inferno": "Decreases Defense and Special Defense by 100%",
  "infestation": "Hits 2-5 times",
  "ingrain": "A legitimate strategic combat move.",
  "iondeluge": "A legitimate strategic combat move.",
  "irondefense": "Increases Defense by 100%",
  "ironhead": "A legitimate strategic combat move.",
  "irontail": "Attacks x1.2 slower than usual. Power increases by x1.2-1.5 if Defense/Special Defense is risen",
  "jumpkick": "A legitimate strategic combat move.",
  "karatechop": "A legitimate strategic combat move.",
  "kinesis": "Increases Special Attack by 100% and Special Defense by 50%",
  "knockoff": "30% chance to decrease enemy Defense by 50%",
  "laserfocus": "A legitimate strategic combat move.",
  "lashout": "A legitimate strategic combat move.",
  "lastresort": "A legitimate strategic combat move.",
  "lavaplume": "A legitimate strategic combat move.",
  "leafblade": "A legitimate strategic combat move.",
  "leafstorm": "Decreases Special Attack by 50%",
  "leaftornado": "A legitimate strategic combat move.",
  "leechlife": "A legitimate strategic combat move.",
  "leechseed": "A legitimate strategic combat move.",
  "leer": "Decreases enemy Defense by 50%",
  "lick": "10% chance to inflict",
  "lifedew": "A legitimate strategic combat move.",
  "lightscreen": "Changes the weather to",
  "liquidation": "30% chance to increase Defense by 50%",
  "lockon": "A legitimate strategic combat move.",
  "lovelykiss": "10% chance to inflict",
  "lowkick": "A legitimate strategic combat move.",
  "lowsweep": "Decreases enemy Speed by 50%",
  "luckychant": "A legitimate strategic combat move.",
  "lunge": "A legitimate strategic combat move.",
  "machpunch": "A legitimate strategic combat move.",
  "magicalleaf": "50% chance to decrease enemy Special Attack by 50%",
  "magiccoat": "A legitimate strategic combat move.",
  "magicroom": "A legitimate strategic combat move.",
  "magnetbomb": "A legitimate strategic combat move.",
  "magneticflux": "Increases Special Defense by 50%",
  "magnetrise": "A legitimate strategic combat move.",
  "magnitude": "Power randomly varies from x1 to x8",
  "meanlook": "A legitimate strategic combat move.",
  "meditate": "A legitimate strategic combat move.",
  "mefirst": "Perform the first move of the oponent. Attacks x3 faster than usual",
  "megadrain": "A legitimate strategic combat move.",
  "megahorn": "A legitimate strategic combat move.",
  "megakick": "A legitimate strategic combat move.",
  "megapunch": "A legitimate strategic combat move.",
  "memento": "Faints the user and decreases enemy Attack and Special Attack by 100%",
  "metalburst": "A legitimate strategic combat move.",
  "metalclaw": "30% chance to increase Attack by 50%",
  "metalsound": "Decreases enemy Special Defense by 100%",
  "meteorbeam": "Attacks x1.2 slower than usual",
  "meteormash": "A legitimate strategic combat move.",
  "metronome": "User performs any move at random",
  "milkdrink": "A legitimate strategic combat move.",
  "mimic": "Perform the first move of the oponent, at double the damage",
  "mindreader": "A legitimate strategic combat move.",
  "minimize": "A legitimate strategic combat move.",
  "miracleeye": "A legitimate strategic combat move.",
  "mirrorcoat": "A legitimate strategic combat move.",
  "mirrormove": "A legitimate strategic combat move.",
  "mirrorshot": "A legitimate strategic combat move.",
  "mist": "A legitimate strategic combat move.",
  "mistyexplosion": "A legitimate strategic combat move.",
  "mistyterrain": "Changes the weather to",
  "moonblast": "10% chance to decrease enemy Special Attack by 50%",
  "moonlight": "A legitimate strategic combat move.",
  "morningsun": "Changes the weather to  and increases Special Attack by 50%",
  "mudbomb": "A legitimate strategic combat move.",
  "muddywater": "30% chance to decrease enemy Speed by 50%",
  "mudshot": "Decreases enemy Speed by 50%",
  "mudslap": "A legitimate strategic combat move.",
  "mudsport": "Temporarily adds Ground to the type of the enemy. Super-effective damage bonus dealt from temporal types is halved, and applying a second temporary type replaces the first one",
  "mysticalfire": "Decreases Special Attack by 100%",
  "nastyplot": "Increases Special Attack by 100%",
  "naturalgift": "A legitimate strategic combat move.",
  "naturepower": "A legitimate strategic combat move.",
  "nightmare": "A legitimate strategic combat move.",
  "nightshade": "A legitimate strategic combat move.",
  "nightslash": "A legitimate strategic combat move.",
  "nuzzle": "30% chance to inflict",
  "octazooka": "A legitimate strategic combat move.",
  "odorsleuth": "A legitimate strategic combat move.",
  "ominouswind": "10% chance to increase all Stats by 50%",
  "outrage": "Inflicts  on the user",
  "overheat": "Decreases Special Attack by 50%",
  "painsplit": "A legitimate strategic combat move.",
  "payback": "A legitimate strategic combat move.",
  "payday": "Once used,increases the weight of rare item drops by 1% for the current battle. Multiple uses wont stack. Works always for everyone regardless of the user",
  "peck": "A legitimate strategic combat move.",
  "perishsong": "A legitimate strategic combat move.",
  "petalblizzard": "A legitimate strategic combat move.",
  "petaldance": "A legitimate strategic combat move.",
  "phantomforce": "Attacks x1.2 slower than usual",
  "pinmissile": "Hits 2-5 times",
  "playnice": "Decreases enemy Attack by 50%",
  "playrough": "A legitimate strategic combat move.",
  "pluck": "A legitimate strategic combat move.",
  "poisonfang": "10% chance to inflict",
  "poisongas": "A legitimate strategic combat move.",
  "poisonjab": "10% chance to inflict",
  "poisonpowder": "Inflicts",
  "poisonsting": "30% chance to inflict",
  "poisontail": "20% chance to inflict",
  "pollenpuff": "A legitimate strategic combat move.",
  "poltergeist": "A legitimate strategic combat move.",
  "pounce": "Decreases enemy Speed by 50%",
  "pound": "A legitimate strategic combat move.",
  "powdersnow": "10% chance to inflict",
  "powergem": "A legitimate strategic combat move.",
  "powersplit": "A legitimate strategic combat move.",
  "powerswap": "A legitimate strategic combat move.",
  "powertrick": "A legitimate strategic combat move.",
  "powertrip": "A legitimate strategic combat move.",
  "poweruppunch": "50% chance to increase Attack by 50%",
  "powerwhip": "A legitimate strategic combat move.",
  "present": "A legitimate strategic combat move.",
  "protect": "A legitimate strategic combat move.",
  "psybeam": "30% chance to inflict",
  "psychic": "10% chance to decrease enemy Special Defense by 50%",
  "psychicfangs": "A legitimate strategic combat move.",
  "psychicnoise": "A legitimate strategic combat move.",
  "psychicterrain": "A legitimate strategic combat move.",
  "psychocut": "A legitimate strategic combat move.",
  "psychoshift": "A legitimate strategic combat move.",
  "psychup": "A legitimate strategic combat move.",
  "psyshieldbash": "Increases Defense by 50%",
  "psyshock": "A legitimate strategic combat move.",
  "psystrike": "A legitimate strategic combat move.",
  "psywave": "A legitimate strategic combat move.",
  "punishment": "A legitimate strategic combat move.",
  "pursuit": "A legitimate strategic combat move.",
  "quash": "A legitimate strategic combat move.",
  "quickattack": "Attacks x1.2 faster than usual",
  "quickguard": "A legitimate strategic combat move.",
  "quiverdance": "Increases Special Attack and Speed by 50%. Attacks x1.4 slower than usual",
  "rage": "A legitimate strategic combat move.",
  "ragefist": "Multiplies base power by 1.2x everytime its used, up to 5 times. Depletes all stacks upon switching Pokemon",
  "ragepowder": "Inflicts , but increases enemy Special Attack by 100%",
  "ragingbull": "A legitimate strategic combat move.",
  "ragingfury": "A legitimate strategic combat move.",
  "raindance": "Changes the weather to",
  "rapidspin": "A legitimate strategic combat move.",
  "razorleaf": "30% chance to decrease enemy Defense by 50%",
  "razorshell": "50% chance to decrease enemy Defense by 50%",
  "razorwind": "A legitimate strategic combat move.",
  "recover": "A legitimate strategic combat move.",
  "recycle": "A legitimate strategic combat move.",
  "reflect": "Changes the weather to",
  "reflecttype": "A legitimate strategic combat move.",
  "refresh": "A legitimate strategic combat move.",
  "rest": "A legitimate strategic combat move.",
  "retaliate": "A legitimate strategic combat move.",
  "return": "A legitimate strategic combat move.",
  "revenge": "A legitimate strategic combat move.",
  "reversal": "A legitimate strategic combat move.",
  "risingvoltage": "A legitimate strategic combat move.",
  "roar": "A legitimate strategic combat move.",
  "rockblast": "Hits 2-5 times",
  "rockclimb": "A legitimate strategic combat move.",
  "rockpolish": "Increases Speed by 75%",
  "rockslide": "Power increases by x1.2-1.5 if Defense/Special Defense is risen",
  "rocksmash": "A legitimate strategic combat move.",
  "rockthrow": "A legitimate strategic combat move.",
  "rocktomb": "Decreases enemy Speed by 50%",
  "roleplay": "A legitimate strategic combat move.",
  "rollingkick": "A legitimate strategic combat move.",
  "rollout": "Multiplies base power by 1.2x everytime its used, up to 5 times. Depletes all stacks upon switching Pokemon",
  "roost": "A legitimate strategic combat move.",
  "rototiller": "Increases Attack and Special Attack by 100%",
  "round": "A legitimate strategic combat move.",
  "sacredfire": "10% chance to inflict",
  "safeguard": "Changes the weather to",
  "sandattack": "A legitimate strategic combat move.",
  "sandstorm": "Changes the weather to",
  "sandtomb": "A legitimate strategic combat move.",
  "scald": "30% chance to inflict",
  "scaleshot": "Hits 2-5 times",
  "scaryface": "A legitimate strategic combat move.",
  "scorchingsands": "30% chance to inflict",
  "scratch": "A legitimate strategic combat move.",
  "screech": "Decreases enemy Defense by 100%",
  "secretpower": "A legitimate strategic combat move.",
  "seedbomb": "10% chance to decrease enemy Attack by 50%",
  "seismictoss": "A legitimate strategic combat move.",
  "selfdestruct": "A legitimate strategic combat move.",
  "shadowball": "10% chance to decrease enemy Special Defense by 50%",
  "shadowclaw": "A legitimate strategic combat move.",
  "shadowpunch": "A legitimate strategic combat move.",
  "shadowsneak": "Attacks x1.2 faster than usual",
  "sharpen": "A legitimate strategic combat move.",
  "sheercold": "A legitimate strategic combat move.",
  "shellsmash": "A legitimate strategic combat move.",
  "shockwave": "A legitimate strategic combat move.",
  "signalbeam": "30% chance to inflict",
  "silverwind": "50% chance to decrease enemy Special Defense by 50%",
  "simplebeam": "A legitimate strategic combat move.",
  "sing": "A legitimate strategic combat move.",
  "sketch": "Executes the first move slot",
  "skillswap": "A legitimate strategic combat move.",
  "skittersmack": "A legitimate strategic combat move.",
  "skullbash": "A legitimate strategic combat move.",
  "skyattack": "A legitimate strategic combat move.",
  "skydrop": "Decreases enemy Speed by 50%",
  "skyuppercut": "Power doubles if the target is Flying-Type",
  "slackoff": "A legitimate strategic combat move.",
  "slam": "A legitimate strategic combat move.",
  "slash": "A legitimate strategic combat move.",
  "sleeppowder": "A legitimate strategic combat move.",
  "sleeptalk": "A legitimate strategic combat move.",
  "sludge": "30% chance to inflict",
  "sludgebomb": "30% chance to inflict",
  "sludgewave": "10% chance to inflict",
  "smackdown": "Power doubles if the target is Flying-Type",
  "smartstrike": "A legitimate strategic combat move.",
  "smellingsalts": "Power doubles if the target is Paralyzed",
  "smog": "30% chance to inflict",
  "smokescreen": "A legitimate strategic combat move.",
  "snarl": "Decreases enemy Special Attack by 50%",
  "snatch": "A legitimate strategic combat move.",
  "snore": "A legitimate strategic combat move.",
  "snowscape": "Changes the weather to  and increases Special Attack by 50%",
  "soak": "Temporarily adds Water to the type of the enemy. Super-effective damage bonus dealt from temporal types is halved, and applying a second temporary type replaces the first one",
  "softboiled": "A legitimate strategic combat move.",
  "solarbeam": "Attacks x1.2 slower than usual",
  "solarblade": "Attacks x1.2 slower than usual",
  "sonicboom": "A legitimate strategic combat move.",
  "spark": "A legitimate strategic combat move.",
  "sparklingaria": "Removes  for the entire party",
  "speedswap": "A legitimate strategic combat move.",
  "spiderweb": "A legitimate strategic combat move.",
  "spikecannon": "A legitimate strategic combat move.",
  "spikes": "A legitimate strategic combat move.",
  "spite": "A legitimate strategic combat move.",
  "spitup": "A legitimate strategic combat move.",
  "splash": "...",
  "spore": "50% chance to inflict",
  "spotlight": "A legitimate strategic combat move.",
  "stealthrock": "A legitimate strategic combat move.",
  "steamroller": "A legitimate strategic combat move.",
  "steelbeam": "A legitimate strategic combat move.",
  "steelroller": "A legitimate strategic combat move.",
  "steelwing": "50% chance to increase Defense by 50%",
  "stickyweb": "Decreases enemy Speed by 50%",
  "stockpile": "A legitimate strategic combat move.",
  "stomp": "A legitimate strategic combat move.",
  "stompingtantrum": "Decreases Attack by 50%",
  "stoneedge": "A legitimate strategic combat move.",
  "storedpower": "Increases base power by 30 for every unique stat up of the user",
  "stormthrow": "Power increases by x1.2-1.5 if Defense/Special Defense is risen",
  "strength": "A legitimate strategic combat move.",
  "strengthsap": "A legitimate strategic combat move.",
  "stringshot": "Decreases enemy Speed by 75%",
  "strugglebug": "Decreases enemy Special Attack by 50%. Power increases by x1.2-1.5 if Defense/Special Defense is risen",
  "stunspore": "Inflicts",
  "submission": "A legitimate strategic combat move.",
  "substitute": "A legitimate strategic combat move.",
  "suckerpunch": "A legitimate strategic combat move.",
  "sunnyday": "Changes the weather to",
  "supercellslam": "Decreases Attack by 50%",
  "superfang": "A legitimate strategic combat move.",
  "superpower": "Decreases Defense and Attack by 50%",
  "supersonic": "A legitimate strategic combat move.",
  "surf": "A legitimate strategic combat move.",
  "swagger": "Inflicts , but increases enemy Attack by 100%",
  "swallow": "A legitimate strategic combat move.",
  "sweetkiss": "Inflicts",
  "sweetscent": "A legitimate strategic combat move.",
  "swift": "Attacks x1.2 faster than usual",
  "switcheroo": "A legitimate strategic combat move.",
  "swordsdance": "Increases Attack by 100%",
  "synchronoise": "A legitimate strategic combat move.",
  "synthesis": "A legitimate strategic combat move.",
  "tackle": "A legitimate strategic combat move.",
  "tailslap": "A legitimate strategic combat move.",
  "tailwhip": "A legitimate strategic combat move.",
  "tailwind": "Increases Speed by 50% to the entire team. Attacks x1.5 slower than usual",
  "takedown": "A legitimate strategic combat move.",
  "taunt": "A legitimate strategic combat move.",
  "tearfullook": "A legitimate strategic combat move.",
  "teeterdance": "A legitimate strategic combat move.",
  "telekinesis": "A legitimate strategic combat move.",
  "teleport": "A legitimate strategic combat move.",
  "temperflare": "A legitimate strategic combat move.",
  "terablast": "A legitimate strategic combat move.",
  "terrainpulse": "A legitimate strategic combat move.",
  "thief": "A legitimate strategic combat move.",
  "thrash": "A legitimate strategic combat move.",
  "throatchop": "A legitimate strategic combat move.",
  "thunder": "Attacks x1.2 slower than usual",
  "thunderbolt": "10% chance to inflict",
  "thunderfang": "10% chance to inflict",
  "thunderpunch": "10% chance to inflict",
  "thundershock": "10% chance to inflict",
  "thunderwave": "Inflicts",
  "tickle": "A legitimate strategic combat move.",
  "tidyup": "A legitimate strategic combat move.",
  "torment": "A legitimate strategic combat move.",
  "toxic": "Inflicts",
  "toxicspikes": "A legitimate strategic combat move.",
  "toxicthread": "Inflicts  and decreases enemy Speed by 50%",
  "trailblaze": "Increases Speed by 50%",
  "transform": "A legitimate strategic combat move.",
  "triattack": "10% chance to inflict , or",
  "trick": "A legitimate strategic combat move.",
  "trickroom": "Changes the weather to",
  "tripleaxel": "Multiplies base power by 1.3x everytime its used, up to 3 times. Depletes all stacks upon switching Pokemon",
  "triplekick": "A legitimate strategic combat move.",
  "trumpcard": "A legitimate strategic combat move.",
  "twinbeam": "Hits 2 times",
  "twineedle": "Hits 2 times",
  "twister": "A legitimate strategic combat move.",
  "upperhand": "A legitimate strategic combat move.",
  "uproar": "A legitimate strategic combat move.",
  "uturn": "Switches to the next party member",
  "vacuumwave": "Attacks x1.2 faster than usual",
  "venomdrench": "A legitimate strategic combat move.",
  "venoshock": "Power doubles if the target is",
  "vicegrip": "A legitimate strategic combat move.",
  "vinewhip": "A legitimate strategic combat move.",
  "vitalthrow": "A legitimate strategic combat move.",
  "voltswitch": "Switches to the next party member",
  "volttackle": "10% chance to inflict",
  "wakeupslap": "A legitimate strategic combat move.",
  "waterfall": "A legitimate strategic combat move.",
  "watergun": "A legitimate strategic combat move.",
  "waterpledge": "A legitimate strategic combat move.",
  "waterpulse": "30% chance to inflict",
  "watersport": "A legitimate strategic combat move.",
  "waterspout": "A legitimate strategic combat move.",
  "wavecrash": "Decreases Attack by 50%",
  "weatherball": "Power doubles under a weather condition, and type changes depending on it ( is Fire,  is Water,  is Ground,  is Ice,  is Ghost,  is Electric,  is Grass,  is Psychic )",
  "whirlpool": "Hits 2-5 times",
  "whirlwind": "A legitimate strategic combat move.",
  "wideguard": "A legitimate strategic combat move.",
  "wildcharge": "Attacks x1.2 slower than usual",
  "willowisp": "Inflicts",
  "wingattack": "A legitimate strategic combat move.",
  "wish": "A legitimate strategic combat move.",
  "withdraw": "A legitimate strategic combat move.",
  "wonderroom": "A legitimate strategic combat move.",
  "woodhammer": "A legitimate strategic combat move.",
  "workup": "A legitimate strategic combat move.",
  "worryseed": "A legitimate strategic combat move.",
  "wrap": "A legitimate strategic combat move.",
  "wringout": "A legitimate strategic combat move.",
  "xscissor": "A legitimate strategic combat move.",
  "yawn": "A legitimate strategic combat move.",
  "zapcannon": "Inflicts",
  "zenheadbutt": "A legitimate strategic combat move."
};
