// ===== EN — Move names (French id -> English name) =====

window.L_move_names_en = {
"absorb":"Absorb",
"bite":"Bite",
"blizzard":"Blizzard",
"bodyslam":"Body Slam",
"bubble":"Bubble",
"bugbite":"Bug Bite",
"confusion":"Confusion",
"crunch":"Crunch",
"dazzlinggleam":"Dazzling Gleam",
"dig":"Dig",
"doubleedge":"Double-Edge",
"dragonbreath":"Dragon Breath",
"dragonrage":"Dragon Rage",
"earthquake":"Earthquake",
"ember":"Ember",
"fieryspin":"Fire Spin",
"fireblast":"Fire Blast",
"flamethrower":"Flamethrower",
"gust":"Gust",
"hydropump":"Hydro Pump",
"hyperbeam":"Hyper Beam",
"icebeam":"Ice Beam",
"irontail":"Iron Tail",
"jumpkick":"Jump Kick",
"karatechop":"Karate Chop",
"lick":"Lick",
"megapunch":"Mega Punch",
"metalclaw":"Metal Claw",
"moonblast":"Moonblast",
"mudshot":"Mud Shot",
"nightshade":"Night Shade",
"outrage":"Outrage",
"poisonsting":"Poison Sting",
"powdersnow":"Powder Snow",
"psybeam":"Psybeam",
"psychic":"Psychic",
"quickattack":"Quick Attack",
"razorleaf":"Razor Leaf",
"return":"Return",
"rockslide":"Rock Slide",
"rockthrow":"Rock Throw",
"scratch":"Scratch",
"shadowball":"Shadow Ball",
"skyattack":"Sky Attack",
"slash":"Slash",
"sludgebomb":"Sludge Bomb",
"solarbeam":"Solar Beam",
"stoneedge":"Stone Edge",
"stringshot":"String Shot",
"surf":"Surf",
"tackle":"Tackle",
"thunder":"Thunder",
"thunderbolt":"Thunderbolt",
"thundershock":"Thunder Shock",
"thunderwave":"Thunder Wave",
"toxic":"Toxic",
"vinewhip":"Vine Whip",
"watergun":"Water Gun",
"wingattack":"Wing Attack",
};
