// ===== EN — UI strings =====
// Auto-extracted & grouped by domain. Edit text here, never hardcode in logic.

window.L_en_ui = {
"dict_abilities":"Abilities",
"dict_moves":"Moves",
"dict_items":"Items",
"dictionary_title":"Dictionary",
"add_to_team_btn":"Add to Party",
"box_header":"Pokémon in PC Box",
"box_pc_note":"This Pokémon is in your PC box. Place it in your active party to train or equip items!",
"box_swap_header":"Swap: choose a box Pokémon to replace",
"buy_btn":"Buy",
"quest_challenge_btn":"Challenge!",
"challenge_btn":"Challenge",
"choose_starter":"Choose your Starter",
"cols3":"3 Columns",
"defeated_lbl":"defeated",
"drop_items_lbl":"Findable Items:",
"eq_sub":"Equipment Management",
"equip_btn":"Equip",
"equipped_lbl":"Equipped on:",
"evo_title":"Evolution Method:",
"evolve_btn":"Evolve!",
"explore_btn":"Explore",
"explore_routes":"Explore routes",
"fiche_btn":"Sheet",
"finish_btn":"Done",
"forget_btn":"Forget",
"forget_first":"(forget one first)",
"full_btn":"Full",
"idle_desc":"Move to a route on the left map and click <b> Explore</b> or <b> Challenge</b> to launch a real-time battle in the center!",
"idle_title":"Exploration Idle",
"inv_desc_sub":"Select an item from your inventory to use or equip.",
"inv_sub":"Click an item to use, sell, or equip it onto a Pokémon.",
"lang_title":"Langue / Language",
"learn_btn":"Learn",
"learnable_moves":"Learnable Moves",
"loot_btn":"Loot",
"loot_continue_btn":"Continue on Road",
"loot_restart_btn":"Restart Battle Immediately",
"loot_summary_title":"Session Loot Summary",
"loot_title":"Session Loot Summary",
"lvl_lbl":"Lvl",
"market_sub":"Buy rare Pokémon not found in the wild!",
"market_title":"PokéMarket",
"mine_sub":"Dig through rock layers to uncover <b>Evolution Stones</b>, Nuggets and Fossils!",
"mine_title":"Grand Underground (Kanto Mines)",
"modify_btn":"Modify",
"moves_lbl":"Moves:",
"no_item":"No item",
"no_more_moves":"No other moves available.",
"owned_btn":"Owned",
"rarity_com":"● Common (~75%)",
"rarity_rare":"Rare (~4%)",
"rarity_uncom":"Uncommon (~20%)",
"rematch_btn":"Rematch",
"req_lbl":"required",
"shop_sub":"Bag capped at 25 copies per item.",
"skin_shiny_lbl":"Shiny Skin",
"skin_shiny_sub":"Cosmetic appearance only",
"starter_choose_sub":"This Pokémon will accompany you throughout your adventure.",
"starter_choose_title":"Choose your Starter!",
"stone_evo_title":"Stone Evolution",
"stone_sub":"Select a Pokémon to use this stone.",
"swap_btn":"Swap",
"swap_with_btn":"Swap with",
"tab_box":"PC Box",
"tab_dex":"Pokédex",
"tab_fossil":"Fossils",
"tab_info":"Location",
"tab_inv":"Bag",
"tab_market":"Market",
"tab_mine":"Underground",
"tab_shop":"Shop",
"team_btn":"Party",
"team_empty":"No Pokémon in active party!",
"to_box_btn":"Withdraw (→ box)",
"typ_dungeon":"Cave / Dungeon",
"typ_route":"Road / Route",
"typ_sea":"Sea Road",
"typ_town":"Town / City",
"wild_poke":"Wild Pokémon",
"win_battle":"Live Battle (PokéChill)",
"win_map":"Kanto Map",
"win_tabs":"Location",
"win_team":"Active Party",
"xp_lbl":"XP:",
"lang_switched_fr":"Language switched to French!",
"lang_switched_en":"Language switched to English!",
"save_incompatible_deleted":"Incompatible save removed automatically.",
"level_abbrev":"Lv.",
"stat_hp_short":"HP",
"click_replace_context_info":"Click to select for replacement | right-click or long-press for info",
"replacement_badge":"⬇ Replacement",
"power_abbrev":"Pow:",
"learnable_moves_title":"Learnable Moves",
"click_to_replace_selected":"← Click to replace selected",
"select_move_first":"(4/4 — select a move above first)",
"context_info_touch":"Right-click or long-press for info",
"no_other_moves":"No other moves available.",
"level_word":"Level",
"pc_box":"PC Box",
"shiny_skin":"Shiny Skin",
"cosmetic_switch_only":"Cosmetic switch only",
"moves_title":"Moves",
"cancel":"Cancel",
"stone_evolution":"Stone evolution",
"team_full_title":"Team full (6/6)",
"add_to_team":"➕ Add to team",
"remove_from_team":"Remove from team",
"swap_with":"Swap with {name}",
"the_team":"the team",
"evolution_stone_notify":" {from} evolved into {to} using {item}!",
"welcome_johto":"🚢 Welcome to the Johto region — New Bark Town!",
"arrived_kanto_harbor":"🚢 Arrived at Vermilion City harbor in Kanto!",
"map_title_prefix":"Map: ",
"roaming_legendary_appeared":" ROAMING LEGENDARY APPEARED: {name}!",
"no_pokemon_in_team":" You do not have any Pokémon!",
"no_wild_pokemon_here":"No wild Pokémon here.",
"team_healed_center":"🏥 Team healed at the Pokémon Center!",
"all_pokemon_healed":" All your Pokémon were healed!",
"pokemon_already_healthy":"Your Pokémon are already in great shape!",
"fullscreen_pc_box":"Full-Screen PC Box",
"action_blocked_in_battle":"Action impossible during battle: leave the battle first!",
"team_already_full":" Your team is already full (6/6). Remove a Pokémon first.",
"species_already_in_team":" Species already in the team.",
"species_already_in_team_present":" Species already present in the team.",
"box_conflict":" Box conflict.",
"joined_team":"{name} joined your team!",
"sent_to_box":"{name} was sent to the box.",
"must_keep_one_pokemon":" You must keep at least one Pokémon in the team.",
"species_already_in_box":" This species is already in the box.",
"presets_label":"Presets:",
"remove":"Remove",
"equipped_item_label":"Equipped item",
"none":"None",
"no_equippable_item":"No equippable item",
"holding_item":"{name} is holding {item}!",
"holding_nothing":"{name} is no longer holding anything.",
"item_removed_from":"{item} removed from {name}.",
"load_preset_title":"Load {name}",
"save_current_team_title":"Save current team",
"pokemon_talents":"Abilities / Talents",
"locked_talent_hint":"Locked: Farm/catch to unlock",
"item_power":"Power:",
"no_item_equipped_bag":"No item equipped. Choose one from the Bag tab.",
"cosmetic_switch_only_team":"Cosmetic switch only",
"sail_to_johto":"Sail to Johto",
"sail_to_kanto":"Sail to Kanto",
"locked":"Locked",
"next_zone":"the next zone",
"battles":"battles",
"to_unlock":"to unlock",
"roaming_legendary_rotation":"Roaming Legendary (12h rotation):",
"can_appear_here":"can appear here!",
"roaming_short":"Roaming (1%)",
"map_title_name":"Map: {region}",
"requires_badges":"requires {need} badge(s) (you have {have})",
"win_wild_battles_req":"win {need} wild battles in {location} (you have {have})",
"locked_by_story":"locked by story — {current}/{required}",
"choose_kanto_starter_first":"⛔ Choose your Kanto starter in Pallet Town first!",
"choose_johto_starter_first":"⛔ Choose your Johto starter in New Bark Town first!",
"need_badges_access":"⛔ You need {need} badge(s) to access {location}! (you have {have})",
"story_not_reached":"📖 The story has not reached {location} yet! (Story progress {current}/{required})",
"win_battles_to_unlock":"⛔ Win {need} wild battles in {from} to unlock {to}! (you have {have})",
"location_not_reachable":"⛔ {location} is not reachable yet.",
"teleported_to":" Teleported to {location}.",
"panel_inventory_title":"Bag",
"panel_shop_title":"Shop",
"panel_market_title":"Poké Market",
"panel_pokedex_title":"Pokédex",
"shortcut_pc_box":"PC Box",
"shortcut_bag":"Bag",
"shortcut_market":"Poké Market",
"starter_johto_chikorita_desc":"Grass - Calm & sturdy",
"starter_johto_cyndaquil_desc":"Fire - Fast & explosive",
"starter_johto_totodile_desc":"Water - Strong jaws",
"starter_kanto_bulbasaur_desc":"Grass/Poison - Solid defensive resilience",
"starter_kanto_charmander_desc":"Fire - High offensive firepower",
"starter_kanto_squirtle_desc":"Water - Great balanced durability",
"starter_welcome_johto":"Welcome to Johto! Professor Elm is waiting in New Bark Town.",
"starter_welcome_kanto":"Welcome to Kanto! Professor Oak is waiting in Pallet Town.",
"starter_title_johto":"Choose your Johto Starter!",
"starter_title_kanto":"Choose your Starter!",
"starter_subtitle":"This Pokémon will accompany you throughout your adventure in this region.",
"choose":"Choose",
"starter_required":"You must choose a starter to continue. This window cannot be closed.",
"partner_now":"{name} is now your partner!",
"shiny_form_unlocked":" Shiny form unlocked/owned!",
"level_up_moves":"Level-up Moves",
"close":"Close",
"move_cat_physical":"Physical",
"move_cat_special":"Special",
"move_cat_status":"Status",
"accuracy":"Accuracy",
"effects":"Effects",
"no_special_effects":"No special effects",
"back_to_pokemon":"Back to Pokémon",
"effect_burn_stat":"Burns ({pct}%) — 3 turns DOT",
"effect_para_stat":"Paralyzes ({pct}%) — 2 turns",
"effect_poison_stat":"Poisons ({pct}%) — 3 turns DOT",
"effect_badpoison_stat":"Badly poisons ({pct}%) — Persistent, increasing DOT",
"effect_sleep_stat":"Causes sleep ({pct}%) — 1-3 turns",
"effect_freeze_stat":"Freezes ({pct}%) — 3 turns max",
"effect_slow_stat":"Lowers Speed ({pct}%)",
"effect_burn_chance":"{pct}% chance to burn — 3 turns DOT",
"effect_para_chance":"{pct}% chance to paralyze — 2 turns",
"effect_poison_chance":"{pct}% chance to poison — 3 turns DOT",
"effect_freeze_chance":"{pct}% chance to freeze — 3 turns max",
"effect_sleep_chance":"{pct}% chance to sleep — 1-3 turns",
"effect_slow_chance":"{pct}% chance to lower Speed",
"effect_confuse_chance":"{pct}% chance to confuse",
"effect_flinch_chance":"{pct}% chance to make flinch",
"effect_crit":"High critical hit ratio (×1.5 damage)",
"effect_recoil":"Recoil: 25% of damage dealt",
"effect_recharge":"Must recharge next turn",
"effect_trap":"Traps opponent for 4-5 turns",
"effect_drain":"Drains 50% of damage as HP",
"effect_charge":"Charges first turn, attacks second",
"effect_heal":"Heals {pct}% HP",
"effect_priority":"Priority +{prio} (attacks first)",
"effect_fixed":"Fixed damage: {damage} HP",
"sort_name":"Name",
"sort_quantity":"Quantity",
"sort_category":"Category",
"filter_label":"Filter:",
"sort_label":"Sort:",
"mine_locked_badges":"Mine locked (2 Badges required)",
"pokedex_seen":"Seen",
"pokedex_caught":"Caught",
"pokedex_shiny":"Shiny",
"pokedex_moves":"Moves",
"wild_legendary_appeared":"⚔ WILD LEGENDARY: {name} (Lv.65) appeared! Defeat it to capture!",
"item_found_log":"{icon} Item found: {item}!",
"money_won_log":"You won {money}₽!",
"capture_title":"Capture!",
"training_complete":" Training Complete!{reward}",
"legendary_boss_defeated":" You defeated Legendary Boss {pokemon}!",
"boss_captured":" Boss defeated! Captured {pokemon}{shiny}!",
"continue":"Continue",
"held_effect_max":"Held Effect (at 25/25)",
"item_type_stone":" Evolution Stone",
"item_type_treasure":" Treasure",
"item_type_candy":" Candy",
"item_type_special":" Special",
"item_type_key":"🔑 Key Item",
"item_type_held":" Held Item",
"item_type_berry":"🍓 Berry",
"description":"Description",
"price":"Price",
"owned":"Owned",
"money":"Money",
"bought":"Bought",
"stock":"Stock",
"indigo_shop_locked_title":"Indigo Plateau Shop Locked",
"indigo_shop_locked_desc":"This elite shop is reserved exclusively for Kanto League Masters.",
"bag_full_for":"Bag full for {item} (max {max}).",
"item_bought":"✅ {item} bought!",
"sent_to_box_price":"{name} sent to PC Box! (-{price}₽)",
"joined_team_price":"{name} joined your team! (-{price}₽)",
"hatchery_locked_title":"Hatchery Locked",
"hatchery_locked_desc":"Defeat Misty in Cerulean City (2 Badges) to unlock the Route 5 Hatchery!",
"hatchery_place_slot":"Slot #{slot}: Place Pokémon",
"ready":"Ready!",
"incubating":"Incubating: {steps} / {required} KOs",
"hatch":"Hatch!",
"hatchery_upgrade_slot":"Upgrade Daycare: +1 Egg Slot ({cost}₽)",
"fossil_lab":"Fossil Lab",
"fossil_lab_desc":"Revive prehistoric Pokémon found in the Underground Mine, PokéClicker style!",
"no_fossils_yet":"No fossils yet",
"fossil_mine_hint":"Dig in the Underground Mine to find Helix, Dome & Old Amber!",
"go_to_mine":"Go to Mine",
"quantity_abbrev":"Qty",
"revives_into":"Revives into",
"revive":"Revive!",
"fossil_lab_tip":"<b>PokéClicker style:</b> Fossils are found while mining. Each fossil revives instantly into its prehistoric Pokémon (Lv.1). Shiny chance applies!",
"hatchery_upgraded":" Hatchery upgraded! You now have {slots} egg slots!",
"iv_money_bonus":" (+5,000 bonus)",
"no_fossil_left":"No fossil left!",
"unknown_fossil":"Unknown fossil.",
"fossil_revived_party":"🧬 {name} revived! Joined your party!",
"fossil_revived_box":"🧬 {name} revived! Sent to PC Box.",
"box_label":"Box",
"fossils":"Fossils",
"no_pokemon_found":"No Pokémon found.",
"select_or_details_hint":"Click: Select | Right-Click: Details",
"fossil_selector_hint":"Select a fossil to send it to the Hatchery.",
"incubate":"Incubate",
"ko_unit":"KOs",
"hatchery_full":"Hatchery full!",
"fossil_sent_hatchery":" {item} sent to the Hatchery!",
"dig_mine_fossils":"Dig in the Underground Mine to find fossils!",
"preset_adventure":"Adventure Team",
"preset_boss":"Boss Team",
"preset_training":"Training Team",
"preset_saved":" {name} saved ({count} Pokémon)!",
"cannot_change_team_battle":"You cannot change your battle team during a fight!",
"preset_empty":"This team preset is empty! Put Pokémon in your team and click Save.",
"preset_pokemon_not_found":"No Pokémon from this preset were found!",
"preset_loaded":" {name} loaded successfully ({count} Pokémon)!",
"no_pokemon_yet":"You do not have any Pokémon yet!",
"choose_starter_bang":"Choose your Starter!",
"explore_to_catch":"Explore routes to catch some.",
"live_battle_lock_team":"Live battle in progress:",
"team_locked_battle_long":"The active team is locked. You cannot swap, reorder, or change equipment during battle.",
"cannot_swap_team_battle":"Action impossible: you cannot swap the team during battle.",
"cannot_during_battle":"Impossible during battle!",
"cannot_remove_only_pokemon":"You cannot remove your only Pokémon!",
"removed_to_pc":"{name} removed from the team and placed in the PC Box.",
"swap_cancelled":"Swap cancelled.",
"box_pokemon_not_found":"Pokémon not found in the box!",
"team_pokemon_not_found":"Team Pokémon not found!",
"pokemon_swapped":"{a} and {b} were swapped!",
"team_full_short":"Team full! (6/6)",
"pokemon_not_found":"Pokémon not found!",
"added_to_team":"{name} added to the team!",
"selected_pokemon":"Selected: {name} (Lv.{level})",
"team_full_select_replace":"Team full! (6/6) - Select a team Pokémon to replace first.",
"already_in_team":"This Pokémon is already in the team!",
"selected_for_training":"🏋️ {name} selected for training!",
"cannot_deposit_only_pokemon":"You cannot deposit your only Pokémon!",
"deposited_hatchery":"🥚 {name} deposited at the Hatchery!",
"no_active_pokemon":"No active Pokémon.",
"team_location":" Team",
"box_location":" Box",
"easy_minus_two":"Easy: -2 Lv.",
"easy_minus_one":"Easy: -1 Lv.",
"medium_plus_two":"Medium: +2 Lv.",
"medium_plus_three":"Medium: +3 Lv.",
"talent_system_unavailable":"Talent system unavailable",
"no_talent_species":"No talent available for this species",
"no_compatible_talent":"No compatible talent found",
"all_talents_unlocked":"All talents are unlocked! Training can still reroll.",
"holo_ditto":"Holo-Ditto",
"holo_porygon":"Holo-Porygon",
"punching_bag":"Punching Bag",
"training_room_battle_start":" TRAINING ROOM ({mode}) - Round 1/3: {pokemon} Lv.{level}!",
"switch_pending":"⏳ {name} will enter battle as soon as possible...",
"solo_training_no_switch":"Switch impossible: your Pokémon is training solo at the Dojo!",
"shiny_captured":" SHINY POKÉMON CAUGHT! ",
"hidden_talent_unlocked_reward":" (Hidden Talent unlocked!)",
"league_master_victory_log":" You defeated the Kanto Champion and triumphed over all 5 League battles!",
"league_master_title_reward":" Congratulations! You obtain the Pokémon Master Title! (+{money}₽)",
"rematch_won_reward":" Rematch won against {champion}! (+{money}₽)",
"league_victory_message":" Congratulations! You triumphed over all 5 Kanto League battles and obtained the Pokémon Master Title!",
"add_pokemon":"Add a Pokémon",
"team_count":"{count}/6 in team",
"item_removed_team":"{item} removed from the team.",
"evolution_duplicate_bonus":" {name} would have evolved into {target}, already owned! (+{money}₽)",
"evolution_duplicate_bonus_html":" {name} would have evolved into <b>{target}</b>, already owned! (+{money}₽)",
"evolution_triggered_box":" {name} triggered an evolution: {target} appears in the PC Box!",
"evolution_created_box":" An evolution of {name} was born: <b>{target}</b> (Lv.1, → box)!",
"captured_pokemon_title":"Captured Pokémon:",
"found_items_title":"Items found:",
"map_help_title_attr":"Help — map color code",
"map_help_title":"Map color code",
"map_help_green":"<b>Green</b> — A quest (main or side) is available here.",
"map_help_purple":"<b>Purple</b> — A roaming legendary is present (not caught).",
"map_help_blue":"<b>Blue</b> — Pokémon still need to be caught.",
"map_help_yellow":"<b>Yellow</b> — A shiny still needs to be caught.",
"map_help_gray":"<b>Gray</b> — Locked area (missing badge or story).",
"map_help_transparent":"<b>Transparent</b> — Completed area (everything caught).",
"no_save_found":"No save found",
"game_loaded":"Game loaded!",
"no_save_to_export":"No save to export",
"save_exported":"Save exported!",
"save_imported_reload":"Save imported! Reloading...",
"save_deleted":"Save deleted",
"debug_x10_on":"⚡ x10 speed enabled",
"debug_x10_off":"x10 speed disabled",
"mine_found":"⛏ Found: {item}!",
"mine_battle_log":"⛏ Underground: You dug up {icon} <b>{item}</b>!",
"legacy_message_n_10_super_bonbons_ajout_s":"+10 Super Bonbons ajoutés !",
"legacy_message_n_50_000_ajout_s":"+50 000₽ ajoutés !",
"legacy_message_n_8_badges_d_bloqu_s":"8 Badges débloqués !",
"legacy_message_n_aucun_pok_mon_entra_ner":"No Pokémon to train!",
"legacy_message_n_capacit_s_pleines_4_oubliezen_une_dabord":"Moves full (4). Forget one first.",
"legacy_message_n_ce_pok_mon_conna_t_ou_a_d_j_d_bloqu_to":"This Pokémon knows or has unlocked all moves available for its species!",
"legacy_message_n_ce_pok_mon_est_d_j_au_niveau_100_maximu":"This Pokémon is already at max Level 100!",
"legacy_message_n_ce_pok_mon_poss_de_d_j_6_toiles_ev_sur":"This Pokémon already has 6 EV stars on all stats (36/36)!",
"legacy_message_n_erreur_lors_de_la_cr_ation_du_pok_mon":"Error creating Pokémon.",
"legacy_message_n_objectif_pas_encore_termin":"Objectif pas encore terminé !",
"legacy_message_n_partie_sauvegard_e":"Game saved!",
"legacy_message_n_qu_te_d_j_active":"Quête déjà active.",
"legacy_message_n_qu_te_d_j_termin_e":"Quête déjà terminée.",
"legacy_message_n_qu_te_r_p_table_d_j_active":"Quête répétable déjà active.",
"legacy_message_n_sauvegarde_import_e":"⬆ Save imported!",
"legacy_message_n_un_pok_mon_doit_conserver_au_moins_une_c":"A Pokémon must keep at least one move.",
"legacy_message_n_vous_poss_dez_d_j_cette_esp_ce":"You already own this species!",
"legacy_message_n_nergie_de_mine_restaur_e_100":"Énergie de mine restaurée à 100 !",
"legacy_message_n_nergie_insuffisante_combattez_des_pok_m":"Not enough energy! Fight wild Pokémon to recharge.",
"legacy_message_n2_cet_objet_na_aucun_effet_sur_ce_pok_mon":"This item has no effect on this Pokémon.",
"woke_up_log":"{name} woke up!",
"sleeping_turns_log":"{name} is asleep... ({turns} turn{plural})",
"thawed_log":"{name} thawed out!",
"frozen_skip_log":"{name} is frozen...",
"paralyzed_skip_log":"{name} is paralyzed and cannot move!",
"uses_move_log":"{name} uses <b>{move}</b>!",
"forfeit_champion":"You give up the battle against {champion}. You can challenge them again anytime.",
"leave_battle_notify":"🚪 You leave the battle.",
"leaving_button":"⏳ Leaving...",
"map_legend_title":"Map legend",
"current_location":"Current location",
"reachable_location":"Reachable location",
"locked_location":"Locked location",
"selector_title_hatchery":"Hatchery & Daycare",
"selector_title_training":"Training Room",
"selector_title_team":"Team Selection",
"selector_title_box":"PC Box",
"equip_click_title":"Click: equip",
"sprite_click_context_title":"Left click: team | Right click: info",
"team_location_clean":"Team",
"box_pc_location":"PC Box",
"change_or_info_title":"Click: change | Right-click: info",
"sprite_team_info_title":"Left click: team | Right-click: info",
"rarity_common_label":"Common",
"rarity_uncommon_label":"Uncommon",
"rarity_rare_label":"Rare",
"rarity_unknown_label":"Unknown",
"shop_default_name":"Shop",
"battle_in_progress":"Battle in progress",
"select_or_details_hint":"Click: Select | Right-Click: Details",
"context_info_touch":"Right-click or long-press for info",
};
