// ===== EN — UI strings =====
// Auto-extracted & grouped by domain. Edit text here, never hardcode in logic.

window.L_en_ui = {
"debug_toggle_btn":"🛠️ Debug",
"debug_x10_toggle":"x10 speed:",
"debug_fill_mine":"⚡ Refill Mine Energy (100)",
"debug_unlock_badges":"🏅 Unlock 8 Kanto Badges",
"debug_give_candies":"🍬 +10 Rare Candies",
"debug_give_money":"💰 +50,000₽",
"debug_menu_title":"🛠️ Debug / cheats",
"guide_pokedex_title":"Pokédex",
"guide_dictionary_text":"Search items, moves and abilities. See who knows a move, who owns an ability and where to get an item.",
"guide_dictionary_title":"Dictionary",
"guide_training_text":"Train a Pokémon for levels, EV, abilities or advanced moves.",
"guide_training_title":"Training",
"guide_hatchery_text":"Deposit Pokémon or fossils. Upgrades and automation are in the dedicated menu.",
"guide_hatchery_title":"Hatchery",
"guide_mine_text":"Dig tiles to reveal treasures and fossils. The mine refreshes after all items are found.",
"guide_mine_title":"Mine",
"guide_bag_text":"Items are sorted by category. Some are held items, some evolve Pokémon, sell for money or serve quests.",
"guide_bag_title":"Bag",
"guide_pokemon_text":"The Pokémon sheet shows Base Stats, IV, EV, abilities, held item, known and learnable moves.",
"guide_pokemon_title":"Pokémon",
"guide_combat_text":"Battles are automatic. Watch HP, charging moves and loot, and switch Pokémon if needed.",
"guide_combat_title":"Combat",
"guide_map_text":"Click an unlocked area to travel. Routes may require battles; important cities may require badges or quests.",
"guide_map_title":"Map & progression",
"tutorial_step_badge_desc":"Progress to Pewter City and defeat Brock.",
"tutorial_step_badge_title":"First badge",
"tutorial_step_dex_desc":"Open the Pokédex and click a seen Pokémon.",
"tutorial_step_dex_title":"Pokédex",
"tutorial_step_bag_desc":"Open the Bag from shortcuts to view your items.",
"tutorial_step_bag_title":"Bag",
"tutorial_step_sheet_desc":"Open a Pokémon sheet to view stats, IV, EV, abilities and moves.",
"tutorial_step_sheet_title":"Pokémon sheet",
"tutorial_step_route1_desc":"Go to Route 1 and win 3 wild battles to learn the game flow.",
"tutorial_step_route1_title":"First battles",
"guide_intro":"Quick guide to understand PokéWorld without interrupting gameplay.",
"tutorial_progress":"tutorial",
"tutorial_complete_desc":"You know the basics. The guide remains available from shortcuts.",
"tutorial_complete_title":"Tutorial complete",
"tutorial_enable":"Enable tutorials",
"tutorial_disable_all":"Disable",
"tutorial_enabled":"Tutorials enabled",
"tutorial_disabled":"Tutorials disabled",
"guide_title":"Guide",
"dict_abilities":"Abilities",
"dict_moves":"Moves",
"dict_items":"Items",
"dictionary_title":"Dictionary",
"add_to_team_btn":"Add to Party",
"box_header":"Pokémon in PC Box",
"box_pc_note":"This Pokémon is in your PC box. Place it in your active party to train or equip items!",
"box_swap_header":"Swap: choose a box Pokémon to replace",
"buy_btn":"Buy",
"quest_challenge_btn":"Challenge!",
"challenge_btn":"Challenge",
"arena_challenge_label":"Gym - Challenge {champion}",
"arena_rematch_label":"Gym - Rematch {champion}",
"arena_locked_label":"Gym - {champion} ({badges} badges required)",
"league_challenge_label":"League - Challenge {champion}",
"league_rematch_label":"League - Rematch {champion}",
"league_locked_label":"League - {champion} ({badges} badges required)",
"choose_starter":"Choose your Starter",
"cols3":"3 Columns",
"defeated_lbl":"defeated",
"drop_items_lbl":"Findable Items:",
"eq_sub":"Equipment Management",
"equip_btn":"Equip",
"equipped_lbl":"Equipped on:",
"evo_title":"Evolution Method:",
"evolve_btn":"Evolve!",
"explore_btn":"Explore",
"explore_routes":"Explore routes",
"fiche_btn":"Sheet",
"finish_btn":"Done",
"forget_btn":"Forget",
"forget_first":"(forget one first)",
"full_btn":"Full",
"idle_desc":"Move to a route on the left map and click <b> Explore</b> or <b> Challenge</b> to launch a real-time battle in the center!",
"idle_title":"Exploration Idle",
"inv_desc_sub":"Select an item from your inventory to use or equip.",
"inv_sub":"Click an item to use, sell, or equip it onto a Pokémon.",
"lang_title":"Langue / Language",
"learn_btn":"Learn",
"learnable_moves":"Learnable Moves",
"loot_btn":"Loot",
"loot_continue_btn":"Continue on Road",
"loot_restart_btn":"Restart Battle Immediately",
"loot_summary_title":"Session Loot Summary",
"loot_title":"Session Loot Summary",
"lvl_lbl":"Lvl",
"market_sub":"Buy rare Pokémon not found in the wild!",
"market_title":"PokéMarket",
"mine_sub":"Dig through rock layers to uncover <b>Evolution Stones</b>, Nuggets and Fossils!",
"mine_title":"Grand Underground (Kanto Mines)",
"modify_btn":"Modify",
"moves_lbl":"Moves:",
"no_item":"No item",
"no_more_moves":"No other moves available.",
"owned_btn":"Owned",
"rarity_com":"● Common (~75%)",
"rarity_rare":"Rare (~4%)",
"rarity_uncom":"Uncommon (~20%)",
"rematch_btn":"Rematch",
"req_lbl":"required",
"shop_sub":"Bag capped at 25 copies per item.",
"skin_shiny_lbl":"Shiny Skin",
"skin_shiny_sub":"Cosmetic appearance only",
"starter_choose_sub":"This Pokémon will accompany you throughout your adventure.",
"starter_choose_title":"Choose your Starter!",
"stone_evo_title":"Stone Evolution",
"stone_sub":"Select a Pokémon to use this stone.",
"swap_btn":"Swap",
"swap_with_btn":"Swap with",
"tab_box":"PC Box",
"tab_dex":"Pokédex",
"tab_fossil":"Fossils",
"tab_info":"Location",
"tab_inv":"Bag",
"tab_market":"Market",
"tab_mine":"Underground",
"tab_shop":"Shop",
"team_btn":"Party",
"team_empty":"No Pokémon in active party!",
"to_box_btn":"Withdraw (→ box)",
"typ_dungeon":"Cave / Dungeon",
"typ_route":"Road / Route",
"typ_sea":"Sea Road",
"typ_town":"Town / City",
"wild_poke":"Wild Pokémon",
"win_battle":"Live Battle (PokéChill)",
"win_map":"Kanto Map",
"win_tabs":"Location",
"win_team":"Active Party",
"xp_lbl":"XP:",
"lang_switched_fr":"Language switched to French!",
"lang_switched_en":"Language switched to English!",
"save_incompatible_deleted":"Incompatible save removed automatically.",
"level_abbrev":"Lv.",
"stat_hp_short":"HP",
"click_replace_context_info":"Click to select for replacement | right-click or long-press for info",
"replacement_badge":"⬇ Replacement",
"power_abbrev":"Pow:",
"learnable_moves_title":"Learnable Moves",
"click_to_replace_selected":"← Click to replace selected",
"select_move_first":"(4/4 — select a move above first)",
"context_info_touch":"Right-click or long-press for info",
"no_other_moves":"No other moves available.",
"level_word":"Level",
"pc_box":"PC Box",
"shiny_skin":"Shiny Skin",
"cosmetic_switch_only":"Cosmetic switch only",
"moves_title":"Moves",
"cancel":"Cancel",
"stone_evolution":"Stone evolution",
"team_full_title":"Team full (6/6)",
"add_to_team":"➕ Add to team",
"remove_from_team":"Remove from team",
"swap_with":"Swap with {name}",
"the_team":"the team",
"evolution_stone_notify":" {from} evolved into {to} using {item}!",
"welcome_johto":"🚢 Welcome to the Johto region — New Bark Town!",
"arrived_kanto_harbor":"🚢 Arrived at Vermilion City harbor in Kanto!",
"map_title_prefix":"Map: ",
"roaming_legendary_appeared":" ROAMING LEGENDARY APPEARED: {name}!",
"no_pokemon_in_team":" You do not have any Pokémon!",
"no_wild_pokemon_here":"No wild Pokémon here.",
"team_healed_center":"🏥 Team healed at the Pokémon Center!",
"all_pokemon_healed":" All your Pokémon were healed!",
"pokemon_already_healthy":"Your Pokémon are already in great shape!",
"fullscreen_pc_box":"Full-Screen PC Box",
"action_blocked_in_battle":"Action impossible during battle: leave the battle first!",
"team_already_full":" Your team is already full (6/6). Remove a Pokémon first.",
"species_already_in_team":" Species already in the team.",
"species_already_in_team_present":" Species already present in the team.",
"box_conflict":" Box conflict.",
"joined_team":"{name} joined your team!",
"sent_to_box":"{name} was sent to the box.",
"must_keep_one_pokemon":" You must keep at least one Pokémon in the team.",
"species_already_in_box":" This species is already in the box.",
"presets_label":"Presets:",
"remove":"Remove",
"equipped_item_label":"Equipped item",
"none":"None",
"no_equippable_item":"No equippable item",
"holding_item":"{name} is holding {item}!",
"holding_nothing":"{name} is no longer holding anything.",
"item_removed_from":"{item} removed from {name}.",
"load_preset_title":"Load {name}",
"save_current_team_title":"Save current team",
"pokemon_talents":"Abilities / Talents",
"locked_talent_hint":"Locked: Farm/catch to unlock",
"item_power":"Power:",
"no_item_equipped_bag":"No item equipped. Choose one from the Bag tab.",
"cosmetic_switch_only_team":"Cosmetic switch only",
"sail_to_johto":"Sail to Johto",
"sail_to_kanto":"Sail to Kanto",
"locked":"Locked",
"next_zone":"the next zone",
"battles":"battles",
"to_unlock":"to unlock",
"roaming_legendary_rotation":"Roaming Legendary (12h rotation):",
"can_appear_here":"can appear here!",
"roaming_short":"Roaming (1%)",
"map_title_name":"Map: {region}",
"requires_badges":"requires {need} badge(s) (you have {have})",
"win_wild_battles_req":"win {need} wild battles in {location} (you have {have})",
"locked_by_story":"locked by story — {current}/{required}",
"choose_kanto_starter_first":"⛔ Choose your Kanto starter in Pallet Town first!",
"choose_johto_starter_first":"⛔ Choose your Johto starter in New Bark Town first!",
"need_badges_access":"⛔ You need {need} badge(s) to access {location}! (you have {have})",
"story_not_reached":"📖 The story has not reached {location} yet! (Story progress {current}/{required})",
"win_battles_to_unlock":"⛔ Win {need} wild battles in {from} to unlock {to}! (you have {have})",
"location_not_reachable":"⛔ {location} is not reachable yet.",
"teleported_to":" Teleported to {location}.",
"panel_inventory_title":"Bag",
"panel_shop_title":"Shop",
"panel_market_title":"Poké Market",
"panel_pokedex_title":"Pokédex",
"shortcut_pc_box":"PC Box",
"shortcut_bag":"Bag",
"shortcut_market":"Poké Market",
"starter_johto_chikorita_desc":"Grass - Calm & sturdy",
"starter_johto_cyndaquil_desc":"Fire - Fast & explosive",
"starter_johto_totodile_desc":"Water - Strong jaws",
"starter_kanto_bulbasaur_desc":"Grass/Poison - Solid defensive resilience",
"starter_kanto_charmander_desc":"Fire - High offensive firepower",
"starter_kanto_squirtle_desc":"Water - Great balanced durability",
"starter_welcome_johto":"Welcome to Johto! Professor Elm is waiting in New Bark Town.",
"starter_welcome_kanto":"Welcome to Kanto! Professor Oak is waiting in Pallet Town.",
"starter_title_johto":"Choose your Johto Starter!",
"starter_title_kanto":"Choose your Starter!",
"starter_subtitle":"This Pokémon will accompany you throughout your adventure in this region.",
"choose":"Choose",
"starter_required":"You must choose a starter to continue. This window cannot be closed.",
"partner_now":"{name} is now your partner!",
"shiny_form_unlocked":" Shiny form unlocked/owned!",
"level_up_moves":"Level-up Moves",
"close":"Close",
"move_cat_physical":"Physical",
"move_cat_special":"Special",
"move_cat_status":"Status",
"accuracy":"Accuracy",
"effects":"Effects",
"no_special_effects":"No special effects",
"back_to_pokemon":"Back to Pokémon",
"effect_burn_stat":"Burns ({pct}%) — 3 turns DOT",
"effect_para_stat":"Paralyzes ({pct}%) — 2 turns",
"effect_poison_stat":"Poisons ({pct}%) — 3 turns DOT",
"effect_badpoison_stat":"Badly poisons ({pct}%) — Persistent, increasing DOT",
"effect_sleep_stat":"Causes sleep ({pct}%) — 1-3 turns",
"effect_freeze_stat":"Freezes ({pct}%) — 3 turns max",
"effect_slow_stat":"Lowers Speed ({pct}%)",
"effect_burn_chance":"{pct}% chance to burn — 3 turns DOT",
"effect_para_chance":"{pct}% chance to paralyze — 2 turns",
"effect_poison_chance":"{pct}% chance to poison — 3 turns DOT",
"effect_freeze_chance":"{pct}% chance to freeze — 3 turns max",
"effect_sleep_chance":"{pct}% chance to sleep — 1-3 turns",
"effect_slow_chance":"{pct}% chance to lower Speed",
"effect_confuse_chance":"{pct}% chance to confuse",
"effect_flinch_chance":"{pct}% chance to make flinch",
"effect_crit":"High critical hit ratio (×1.5 damage)",
"effect_recoil":"Recoil: 25% of damage dealt",
"effect_recharge":"Must recharge next turn",
"effect_trap":"Traps opponent for 4-5 turns",
"effect_drain":"Drains 50% of damage as HP",
"effect_charge":"Charges first turn, attacks second",
"effect_heal":"Heals {pct}% HP",
"effect_priority":"Priority +{prio} (attacks first)",
"effect_fixed":"Fixed damage: {damage} HP",
"sort_name":"Name",
"sort_quantity":"Quantity",
"sort_category":"Category",
"filter_label":"Filter:",
"sort_label":"Sort:",
"mine_locked_badges":"Mine locked (2 Badges required)",
"pokedex_seen":"Seen",
"pokedex_caught":"Caught",
"pokedex_shiny":"Shiny",
"pokedex_moves":"Moves",
"wild_legendary_appeared":"⚔ WILD LEGENDARY: {name} (Lv.65) appeared! Defeat it to capture!",
"item_found_log":"{icon} Item found: {item}!",
"money_won_log":"You won {money}₽!",
"capture_title":"Capture!",
"training_complete":" Training Complete!{reward}",
"legendary_boss_defeated":" You defeated Legendary Boss {pokemon}!",
"boss_captured":" Boss defeated! Captured {pokemon}{shiny}!",
"continue":"Continue",
"held_effect_max":"Held Effect (at 25/25)",
"item_type_stone":" Evolution Stone",
"item_type_treasure":" Treasure",
"item_type_candy":" Candy",
"item_type_special":" Special",
"item_type_key":"🔑 Key Item",
"item_type_held":" Held Item",
"item_type_berry":"🍓 Berry",
"description":"Description",
"price":"Price",
"owned":"Owned",
"money":"Money",
"bought":"Bought",
"stock":"Stock",
"indigo_shop_locked_title":"Indigo Plateau Shop Locked",
"indigo_shop_locked_desc":"This elite shop is reserved exclusively for Kanto League Masters.",
"bag_full_for":"Bag full for {item} (max {max}).",
"item_bought":"✅ {item} bought!",
"sent_to_box_price":"{name} sent to PC Box! (-{price}₽)",
"joined_team_price":"{name} joined your team! (-{price}₽)",
"hatchery_locked_title":"Hatchery Locked",
"hatchery_locked_desc":"Defeat Misty in Cerulean City (2 Badges) to unlock the Route 5 Hatchery!",
"hatchery_place_slot":"Slot #{slot}: Place Pokémon",
"ready":"Ready!",
"incubating":"Incubating: {steps} / {required} KOs",
"hatch":"Hatch!",
"hatchery_upgrade_slot":"Upgrade Daycare: +1 Egg Slot ({cost}₽)",
"fossil_lab":"Fossil Lab",
"fossil_lab_desc":"Revive prehistoric Pokémon found in the Underground Mine, PokéClicker style!",
"no_fossils_yet":"No fossils yet",
"fossil_mine_hint":"Dig in the Underground Mine to find Helix, Dome & Old Amber!",
"go_to_mine":"Go to Mine",
"quantity_abbrev":"Qty",
"revives_into":"Revives into",
"revive":"Revive!",
"fossil_lab_tip":"<b>PokéClicker style:</b> Fossils are found while mining. Each fossil revives instantly into its prehistoric Pokémon (Lv.1). Shiny chance applies!",
"hatchery_upgraded":" Hatchery upgraded! You now have {slots} egg slots!",
"iv_money_bonus":" (+5,000 bonus)",
"no_fossil_left":"No fossil left!",
"unknown_fossil":"Unknown fossil.",
"fossil_revived_party":"🧬 {name} revived! Joined your party!",
"fossil_revived_box":"🧬 {name} revived! Sent to PC Box.",
"box_label":"Box",
"fossils":"Fossils",
"no_pokemon_found":"No Pokémon found.",
"select_or_details_hint":"Click: Select | Right-Click: Details",
"fossil_selector_hint":"Select a fossil to send it to the Hatchery.",
"incubate":"Incubate",
"ko_unit":"KOs",
"hatchery_full":"Hatchery full!",
"fossil_sent_hatchery":" {item} sent to the Hatchery!",
"dig_mine_fossils":"Dig in the Underground Mine to find fossils!",
"preset_adventure":"Adventure Team",
"preset_boss":"Boss Team",
"preset_training":"Training Team",
"preset_saved":" {name} saved ({count} Pokémon)!",
"cannot_change_team_battle":"You cannot change your battle team during a fight!",
"preset_empty":"This team preset is empty! Put Pokémon in your team and click Save.",
"preset_pokemon_not_found":"No Pokémon from this preset were found!",
"preset_loaded":" {name} loaded successfully ({count} Pokémon)!",
"no_pokemon_yet":"You do not have any Pokémon yet!",
"choose_starter_bang":"Choose your Starter!",
"explore_to_catch":"Explore routes to catch some.",
"live_battle_lock_team":"Live battle in progress:",
"team_locked_battle_long":"The active team is locked. You cannot swap, reorder, or change equipment during battle.",
"cannot_swap_team_battle":"Action impossible: you cannot swap the team during battle.",
"cannot_during_battle":"Impossible during battle!",
"cannot_remove_only_pokemon":"You cannot remove your only Pokémon!",
"removed_to_pc":"{name} removed from the team and placed in the PC Box.",
"swap_cancelled":"Swap cancelled.",
"box_pokemon_not_found":"Pokémon not found in the box!",
"team_pokemon_not_found":"Team Pokémon not found!",
"pokemon_swapped":"{a} and {b} were swapped!",
"team_full_short":"Team full! (6/6)",
"pokemon_not_found":"Pokémon not found!",
"added_to_team":"{name} added to the team!",
"selected_pokemon":"Selected: {name} (Lv.{level})",
"team_full_select_replace":"Team full! (6/6) - Select a team Pokémon to replace first.",
"already_in_team":"This Pokémon is already in the team!",
"selected_for_training":"🏋️ {name} selected for training!",
"cannot_deposit_only_pokemon":"You cannot deposit your only Pokémon!",
"deposited_hatchery":"🥚 {name} deposited at the Hatchery!",
"no_active_pokemon":"No active Pokémon.",
"team_location":" Team",
"box_location":" Box",
"easy_minus_two":"Easy: -2 Lv.",
"easy_minus_one":"Easy: -1 Lv.",
"medium_plus_two":"Medium: +2 Lv.",
"medium_plus_three":"Medium: +3 Lv.",
"talent_system_unavailable":"Talent system unavailable",
"no_talent_species":"No talent available for this species",
"no_compatible_talent":"No compatible talent found",
"all_talents_unlocked":"All talents are unlocked! Training can still reroll.",
"holo_ditto":"Holo-Ditto",
"holo_porygon":"Holo-Porygon",
"punching_bag":"Punching Bag",
"training_room_battle_start":" TRAINING ROOM ({mode}) - Round 1/6: {pokemon} Lv.{level}!",
"switch_pending":"⏳ {name} will enter battle as soon as possible...",
"solo_training_no_switch":"Switch impossible: your Pokémon is training solo at the Dojo!",
"shiny_captured":" SHINY POKÉMON CAUGHT! ",
"hidden_talent_unlocked_reward":" (Hidden Talent unlocked!)",
"league_master_victory_log":" You defeated the Kanto Champion and triumphed over all 5 League battles!",
"league_master_title_reward":" Congratulations! You obtain the Pokémon Master Title! (+{money}₽)",
"rematch_won_reward":" Rematch won against {champion}! (+{money}₽)",
"league_victory_message":" Congratulations! You triumphed over all 5 Kanto League battles and obtained the Pokémon Master Title!",
"add_pokemon":"Add a Pokémon",
"team_count":"{count}/6 in team",
"item_removed_team":"{item} removed from the team.",
"evolution_duplicate_bonus":" {name} would have evolved into {target}, already owned! (+{money}₽)",
"evolution_duplicate_bonus_html":" {name} would have evolved into <b>{target}</b>, already owned! (+{money}₽)",
"evolution_triggered_box":" {name} triggered an evolution: {target} appears in the PC Box!",
"evolution_created_box":" An evolution of {name} was born: <b>{target}</b> (Lv.1, → box)!",
"captured_pokemon_title":"Captured Pokémon:",
"found_items_title":"Items found:",
"map_help_title_attr":"Help — map color code",
"map_help_title":"Map color code",
"map_help_green":"<b>Green</b> — A quest (main or side) is available here.",
"map_help_purple":"<b>Purple</b> — A roaming legendary is present (not caught).",
"map_help_blue":"<b>Blue</b> — Pokémon still need to be caught.",
"map_help_yellow":"<b>Yellow</b> — A shiny still needs to be caught.",
"map_help_gray":"<b>Gray</b> — Locked area (missing badge or story).",
"map_help_transparent":"<b>Transparent</b> — Completed area (everything caught).",
"no_save_found":"No save found",
"game_loaded":"Game loaded!",
"no_save_to_export":"No save to export",
"save_exported":"Save exported!",
"save_imported_reload":"Save imported! Reloading...",
"save_deleted":"Save deleted",
"debug_x10_on":"⚡ x10 speed enabled",
"debug_x10_off":"x10 speed disabled",
"mine_found":"⛏ Found: {item}!",
"mine_battle_log":"⛏ Underground: You dug up {icon} <b>{item}</b>!",
"legacy_message_n_10_super_bonbons_ajout_s":"+10 Super Bonbons ajoutés !",
"legacy_message_n_50_000_ajout_s":"+50 000₽ ajoutés !",
"legacy_message_n_8_badges_d_bloqu_s":"8 Badges débloqués !",
"legacy_message_n_aucun_pok_mon_entra_ner":"No Pokémon to train!",
"legacy_message_n_capacit_s_pleines_4_oubliezen_une_dabord":"Moves full (4). Forget one first.",
"legacy_message_n_ce_pok_mon_conna_t_ou_a_d_j_d_bloqu_to":"This Pokémon knows or has unlocked all moves available for its species!",
"legacy_message_n_ce_pok_mon_est_d_j_au_niveau_100_maximu":"This Pokémon is already at max Level 100!",
"legacy_message_n_ce_pok_mon_poss_de_d_j_6_toiles_ev_sur":"This Pokémon already has 6 EV stars on all stats (36/66)!",
"legacy_message_n_erreur_lors_de_la_cr_ation_du_pok_mon":"Error creating Pokémon.",
"legacy_message_n_objectif_pas_encore_termin":"Objectif pas encore terminé !",
"legacy_message_n_partie_sauvegard_e":"Game saved!",
"legacy_message_n_qu_te_d_j_active":"Quête déjà active.",
"legacy_message_n_qu_te_d_j_termin_e":"Quête déjà terminée.",
"legacy_message_n_qu_te_r_p_table_d_j_active":"Quête répétable déjà active.",
"legacy_message_n_sauvegarde_import_e":"⬆ Save imported!",
"legacy_message_n_un_pok_mon_doit_conserver_au_moins_une_c":"A Pokémon must keep at least one move.",
"legacy_message_n_vous_poss_dez_d_j_cette_esp_ce":"You already own this species!",
"legacy_message_n_nergie_de_mine_restaur_e_100":"Énergie de mine restaurée à 100 !",
"legacy_message_n_nergie_insuffisante_combattez_des_pok_m":"Not enough energy! Fight wild Pokémon to recharge.",
"legacy_message_n2_cet_objet_na_aucun_effet_sur_ce_pok_mon":"This item has no effect on this Pokémon.",
"woke_up_log":"{name} woke up!",
"sleeping_turns_log":"{name} is asleep... ({turns} turn{plural})",
"thawed_log":"{name} thawed out!",
"frozen_skip_log":"{name} is frozen...",
"paralyzed_skip_log":"{name} is paralyzed and cannot move!",
"uses_move_log":"{name} uses <b>{move}</b>!",
"forfeit_champion":"You give up the battle against {champion}. You can challenge them again anytime.",
"leave_battle_notify":"🚪 You leave the battle.",
"leaving_button":"⏳ Leaving...",
"map_legend_title":"Map legend",
"current_location":"Current location",
"reachable_location":"Reachable location",
"locked_location":"Locked location",
"selector_title_hatchery":"Hatchery & Daycare",
"selector_title_training":"Training Room",
"selector_title_team":"Team Selection",
"selector_title_box":"PC Box",
"equip_click_title":"Click: equip",
"sprite_click_context_title":"Left click: team | Right click: info",
"team_location_clean":"Team",
"box_pc_location":"PC Box",
"change_or_info_title":"Click: change | Right-click: info",
"sprite_team_info_title":"Left click: team | Right-click: info",
"rarity_common_label":"Common",
"rarity_uncommon_label":"Uncommon",
"rarity_rare_label":"Rare",
"rarity_unknown_label":"Unknown",
"shop_default_name":"Shop",
"battle_in_progress":"Battle in progress",
"battle_in_progress_no_training":"Battle in progress: you cannot start training.",
"training_in_progress_no_battle":"Training in progress: you cannot start another battle.",
"management_trainers":"Trainers",
"hatchery_trainers_soon":"Hatchery trainers are coming soon in a future hatchery update.",
"training_trainers_soon":"Training trainers are coming soon in a future training update.",
"select_or_details_hint":"Click: Select | Right-Click: Details",
"context_info_touch":"Right-click or long-press for info",
"save_menu_title":"PokéWorld",
"save_menu_subtitle":"Choose a save or create a new adventure.",
"save_menu_empty_title":"No save found",
"save_menu_empty_desc":"Create a new save or import a file to add it to the list.",
"save_menu_new":"New save",
"save_menu_import":"Import",
"save_menu_click_hint":"Click to play",
"save_menu_badges":"Badges",
"save_menu_pokedex":"Pokédex",
"save_menu_playtime":"Play time",
"save_menu_id":"ID",
"save_default_name":"Save {num}",
"save_imported_name":"Imported save",
"save_created":"New save created!",
"save_imported_library":"Save added to the list!",
"save_profile_title":"🎴 Save profile",
"save_profile_name":"Save name",
"save_profile_color":"Card color",
"save_profile_background":"Card background",
"save_profile_apply":"Apply to save menu",
"save_profile_updated":"Save profile updated!",
"save_profile_name_placeholder":"Save name",
"save_color_blue":"Blue",
"save_color_red":"Red",
"save_color_green":"Green",
"save_color_purple":"Purple",
"save_color_gold":"Gold",
"save_color_silver":"Silver",
"save_bg_classic":"Kanto — Red / Blue",
"save_bg_goldsilver":"Johto — Gold / Silver",
"save_bg_emerald":"Hoenn — Emerald",
"save_bg_diamondpearl":"Sinnoh — Diamond / Pearl",
"save_bg_blackwhite":"Unova — Black / White",
"save_bg_xy":"Kalos — X / Y",
"save_bg_forest":"Animated forest",
"save_error_too_large":"Error: save is too large",
"save_error_message":"Error while saving: {message}",
"load_error_message":"Error while loading: {message}",
"save_export_error":"Export error",
"save_import_error":"Import error: {message}",
"save_delete_error":"Delete error",
"save_profile_icon":"Save icon (PC Box Pokémon)",
"save_icon_keep_current":"Keep current icon",
"save_icon_no_box":"No Pokémon available in the PC Box",
"save_need_starter":"Choose a starter before saving.",
"save_choose_starter_first":"Choose your starter: the save will be created right after.",
"save_profile_choose_icon":"Choose from PC Box",
"save_profile_current_icon":"Current icon",
"save_context_download":"Download",
"save_context_import_overwrite":"Import (overwrite)",
"save_context_delete":"Delete",
"save_delete_confirm":"Permanently delete this save?",
"save_overwritten":"Save overwritten!",
"afk_progress_summary":"AFK {time}: {wins} battles won, {fainted} Pokémon fainted, +{money}₽.",
"afk_battle_log_summary":"⏱ AFK {time}: {wins} wild Pokémon defeated, {fainted} Pokémon fainted (+{money}₽).",
"afk_energy_summary":"AFK {time}: mine energy recovered.",
"debug_timeskip_10m":"⏱ AFK timeskip +10 min",
"debug_timeskip_unavailable":"AFK timeskip unavailable.",
"afk_progress_lost_summary":"AFK {time}: lost, your whole party fainted ({wins} battles won, +{money}₽).",
"afk_battle_log_lost_summary":"⏱ AFK {time}: lost, your whole party fainted after {wins} battles won (+{money}₽).",
"afk_no_progress_summary":"AFK {time}: no active wild area to simulate.",
"afk_party_ko_log":"⏱ AFK: your party fainted, simulation stopped.",
"afk_error_resume":"AFK simulation error: battle resumed.",
"afk_panel_title_return":"AFK return",
"afk_panel_title_debug":"Debug timeskip",
"afk_panel_status_ok":"Progress simulated successfully.",
"afk_panel_status_lost":"Lost: your whole party fainted.",
"afk_panel_status_empty":"No resources gained during this period.",
"afk_panel_status_error":"AFK simulation error.",
"afk_panel_duration":"Duration",
"afk_panel_battles":"Battles",
"afk_panel_money":"Money",
"afk_panel_captures":"Catches",
"afk_panel_energy":"Mine energy",
"afk_panel_items":"Items gained",
"afk_none":"None",
"afk_panel_team_ko":"Pokémon fainted",
"team_slot_name":"Team slot {slot}",
"afk_captures_normal":"Normal",
"afk_captures_shiny":"Shiny",
"duplicate_short":"duplicate(s)",
"region_kanto":"Kanto",
"region_johto":"Johto",
"region_hoenn":"Hoenn",
"region_sinnoh":"Sinnoh",
"region_locked_league":"Access to {target} locked: defeat the {region} League first.",
"region_locked_dex":"Access to {target} locked: complete the {region} Pokédex first ({caught}/{total}).",
"region_locked_generic":"Access to {target} locked.",
"region_team_restricted":"In {region}, before defeating the local League, only {region} Pokémon can battle. Remove: {pokemon}.",
"league_battle_challenge_region":"{region} LEAGUE - Battle 1/5: {trainer} challenges you!",
"league_master_victory_log_region":"You defeated the {region} Champion and triumphed over all 5 League battles!",
"league_master_title_reward_region":"Congratulations! You obtain the {region} Master Title! (+{money}₽)",
"league_victory_message_region":"Congratulations! You triumphed over all 5 {region} League battles!",
"league_next_battle_region":"{region} LEAGUE - Battle {stage}/5: {trainer} sends out {pokemon}!",
"pokedex_regions":"Visible regions",
"box_filter_region":"Region",
"box_filter_type":"Type",
"box_filter_shiny":"Shiny",
"box_filter_evolution":"Evolution",
"box_filter_all_regions":"All",
"box_filter_all_types":"All",
"box_filter_all_shiny":"All",
"box_filter_shiny_only":"Shiny",
"box_filter_non_shiny_only":"Non-shiny",
"box_filter_all_evo":"All",
"box_filter_evo_missing":"Possible evolution not owned",
"box_filter_reset":"Reset",
"filters_title":"Filters",
"quest_battle_btn":"Battle",
"quest_battle_started":"Quest battle: {quest}",
"quest_battle_none":"No active battle quest here.",
"quest_battle_title":"Local quest",
"quest_reward_battle_active":"A battle is already running: finish it before challenging this Pokémon.",
"quest_reward_battle_started":"Challenge started: {pokemon} is waiting in battle!",
"shiny_skin_on":"Shiny sprite enabled",
"shiny_skin_off":"Normal sprite enabled",
"duplicate_item_money_log":"Already owned item: {item} converted into +{money}₽.",
"capture_duplicate_no_money":"{name} was already owned: no Pokédollars gained.",
"rematch_no_money":"Rematch won: no Pokédollars gained.",
"fossil_not_sellable":"Fossils cannot be sold.",
"repeatable_slots":"Repeatable quest slots",
"repeatable_upgrades":"Repeatable upgrades",
"repeatable_reroll_timer":"Free reroll: {time}",
"repeatable_reroll_wait":"Reroll available in {time}",
"repeatable_slots_full":"Slots full",
"repeatable_slots_current":"Current slots: {count}/{max}",
"repeatable_slot_upgrade_buy":"Unlock slot {next} ({price}₽)",
"repeatable_slots_max":"All repeatable slots are unlocked.",
"repeatable_reroll_free_desc":"Reroll is free every 10 minutes. No paid reroll.",
"repeatable_slot_upgraded":"Repeatable quest slots: {count}.",
"hatchery_management_title":"Hatchery management",
"hatchery_management_button":"Hatchery management",
"hatchery_slots_title":"Slot upgrades",
"hatchery_slots_current":"Current slots: {count}/{max}",
"hatchery_automation_title":"Hatchery automation",
"hatchery_automation_desc":"Buy a module first, then enable or disable its behavior.",
"automation_autoHatch_desc":"Automatically hatches ready eggs.",
"automation_autoSeedHatchery_desc":"Automatically fills empty slots from the PC box.",
"automation_buy_button":"Buy ({price}₽)",
"automation_owned":"Purchased",
"automation_enabled":"Enabled",
"automation_disabled":"Disabled",
"automation_already_bought":"Automation already purchased.",
"hatchery_slots_max":"All hatchery slots are unlocked.",
"automation_autoHatch":"Auto-hatch",
"automation_autoSeedHatchery":"Auto-fill slots",
"automation_upgrade_need_money":"Upgrade too expensive: {price}₽ required.",
"automation_upgrade_bought":"Upgrade bought: {name} ({price}₽).",
"training_slots":"Training slots",
"training_slots_current":"Current slots: {count}/{max}",
"training_multi_slot_buy":"Unlock 2nd slot ({price}₽)",
"training_multi_slot_bought":"Second training slot unlocked.",
"training_multi_slot_max":"The second training slot is already unlocked.",
"training_multi_slot_note":"The second slot now unlocks a real parallel training battle: assign another Pokémon and run two training sessions at the same time.",
"training_upgrades":"Upgrades",
"training_center_title":"Training Center",
"training_parallel_hint":"Each slot runs its own training battle in parallel.",
"training_slot_title":"Slot {slot}",
"training_slot_empty":"No Pokémon assigned to this slot.",
"training_slot_choose":"Add a Pokémon",
"training_slot_change":"Change Pokémon",
"training_slot_active":"Battle running",
"training_slot_time_left":"{time} left",
"training_slot_busy":"This slot is already training.",
"training_slot_no_pokemon":"No Pokémon in this slot.",
"training_slot_started":"Training started for {name} ({mode}).",
"training_slot_failed":"Training failed for {name}. The coach was too strong.",
"training_slot_cancel":"Give up",
"training_slot_cancelled":"Training cancelled.",
"training_slot_missing":"Training Pokémon not found.",
"training_slot_locked":"2nd slot locked",
"training_slot_last_success":"Last result: {mode} succeeded{reward}",
"training_slot_last_failed":"Last result: {mode} failed",
"selector_title_training_slot":"Training Room — slot {slot}",
"selected_for_training_slot":"🏋️ {name} selected for slot {slot}!",
"training_mode_move_title":"📖 Move Discipline",
"training_mode_move_desc":"Unlocks one move locked behind training.",
"training_mode_move_done":"All training moves are already unlocked.",
"training_mode_talent_title":"🧬 Talent Workshop",
"training_mode_talent_desc":"Attempts to obtain one of this Pokémon’s talents.",
"training_mode_talent_done":"All available talents are already unlocked.",
"training_mode_ev_title":"🟢 Targeted EV Stage",
"training_mode_ev_desc":"Gain exactly 1 random EV.",
"training_mode_ev_done":"EVs are maxed.",
"training_mode_level_title":"⭐ Level Stage",
"training_mode_level_desc":"Gain between 2 and 5 levels.",
"training_mode_level_done":"Level 100 reached.",
"management_upgrades":"Upgrades",
"management_automation":"Automation",
"training_management_title":"Training management",
"training_management_button":"Training management",
"training_automation_title":"Training automation",
"training_automation_desc":"Training slot overview, ready for future automations.",
"training_live_title":"Live training battles",
"training_live_running":"Training running",
"training_live_waiting":"The battle is starting...",
"training_live_visible_hint":"Battle visible in the Live Battle panel.",
"training_live_started":"{name} starts {mode} training against {enemy}.",
"training_live_hit":"{name} uses {move} on {target}: {damage} damage.",
"training_live_miss":"{name} missed {move}.",
"training_live_no_effect":"It has no effect on {name}.",
"training_live_status_move":"{move} sets the pace of the battle.",
"training_live_next_round":"Round {round}/{total}: {enemy} enters. Your Pokémon is healed.",
"training_live_enemy_down":"{enemy} is KO!",
"training_round_label":"Round {round}/{total}",
"note":"Note",
};
