// ===== EN — UI strings =====
// Auto-extracted & grouped by domain. Edit text here, never hardcode in logic.

window.L_en_ui = {
  "add_to_team_btn": "➕ Add to Party",
  "box_header": "📦 Pokémon in PC Box",
  "box_pc_note": "📦 This Pokémon is in your PC box. Place it in your active party to train or equip items!",
  "box_swap_header": "🔁 Swap: choose a box Pokémon to replace",
  "buy_btn": "Buy",
  "challenge_btn": "⚔️ Challenge",
  "choose_starter": "Choose your Starter",
  "cols3": "3 Columns",
  "defeated_lbl": "defeated",
  "drop_items_lbl": "🎁 Findable Items:",
  "eq_sub": "Equipment Management",
  "equip_btn": "Equip",
  "equipped_lbl": "Equipped on:",
  "evo_title": "🌱 Evolution Method:",
  "evolve_btn": "Evolve!",
  "explore_btn": "🌾 Explore",
  "explore_routes": "🌾 Explore routes",
  "fiche_btn": "📋 Sheet",
  "finish_btn": "✓ Done",
  "forget_btn": "Forget",
  "forget_first": "(forget one first)",
  "full_btn": "Full",
  "idle_desc": "Move to a route on the left map and click <b>🌾 Explore</b> or <b>⚔️ Challenge</b> to launch a real-time battle in the center!",
  "idle_title": "Exploration Idle",
  "inv_desc_sub": "Select an item from your inventory to use or equip.",
  "inv_sub": "Click an item to use, sell, or equip it onto a Pokémon.",
  "lang_title": "🌐 Langue / Language",
  "learn_btn": "Learn",
  "learnable_moves": "Learnable Moves",
  "loot_btn": "📋 Loot",
  "loot_continue_btn": "Continue on Road",
  "loot_restart_btn": "🔄 Restart Battle Immediately",
  "loot_summary_title": "📋 Session Loot Summary",
  "loot_title": "📋 Session Loot Summary",
  "lvl_lbl": "Lvl",
  "market_sub": "Buy rare Pokémon not found in the wild!",
  "market_title": "🏪 PokéMarket",
  "mine_sub": "Dig through rock layers to uncover <b>Evolution Stones</b>, Nuggets and Fossils!",
  "mine_title": "⛏️ Grand Underground (Kanto Mines)",
  "modify_btn": "✏️ Modify",
  "moves_lbl": "Moves:",
  "no_item": "No item",
  "no_more_moves": "No other moves available.",
  "owned_btn": "Owned",
  "rarity_com": "● Common (~75%)",
  "rarity_rare": "⭐ Rare (~4%)",
  "rarity_uncom": "🔹 Uncommon (~20%)",
  "rematch_btn": "🔄 Rematch",
  "req_lbl": "required",
  "shop_sub": "Bag capped at 25 copies per item.",
  "skin_shiny_lbl": "✨ Shiny Skin",
  "skin_shiny_sub": "Cosmetic appearance only",
  "starter_choose_sub": "This Pokémon will accompany you throughout your adventure.",
  "starter_choose_title": "Choose your Starter!",
  "stone_evo_title": "🪨 Stone Evolution",
  "stone_sub": "Select a Pokémon to use this stone.",
  "swap_btn": "🔁 Swap",
  "swap_with_btn": "🔁 Swap with",
  "tab_box": "📦 PC Box",
  "tab_dex": "📖 Pokédex",
  "tab_fossil": "🦴 Fossils",
  "tab_info": "📍 Location",
  "tab_inv": "🎒 Bag",
  "tab_market": "🏪 Market",
  "tab_mine": "⛏️ Underground",
  "tab_shop": "🛒 Shop",
  "team_btn": "➕ Party",
  "team_empty": "No Pokémon in active party!",
  "to_box_btn": "📦 Withdraw (→ box)",
  "typ_dungeon": "⛰ Cave / Dungeon",
  "typ_route": "🌿 Road / Route",
  "typ_sea": "🌊 Sea Road",
  "typ_town": "🏙 Town / City",
  "wild_poke": "🌿 Wild Pokémon",
  "win_battle": "⚔️ Live Battle (PokéChill)",
  "win_map": "🗺️ Kanto Map",
  "win_tabs": "📍 Location",
  "win_team": "⚡ Active Party",
  "xp_lbl": "XP:",
  "lang_switched_fr": "🇫🇷 Language switched to French!",
  "lang_switched_en": "🇬🇧 Language switched to English!",
};

