var _guideSection = null;
function tutIsEn(){ const c=(typeof currentLang==='function'?currentLang():((G&&G.lang)||'fr')); return String(c).charAt(0)==='e'; }
function tt(fr,en){ return tutIsEn()?en:fr; }
function ensureTutorialState(){
 if(!G.tutorial||typeof G.tutorial!=='object') G.tutorial={};
 if(G.tutorial.enabled===undefined) G.tutorial.enabled=true;
 if(!G.tutorial.completed) G.tutorial.completed={};
 if(!G.tutorial.dismissedTips) G.tutorial.dismissedTips={};
 if(!G.tutorial.rewards) G.tutorial.rewards={};
 return G.tutorial;
}
function tutorialIsEnabled(){ return !!ensureTutorialState().enabled; }
function tutorialDisable(){ const st=ensureTutorialState(); st.enabled=false; saveGame(); try{renderStoryWindow();}catch(_){} notify(tt('Tutoriel désactivé','Tutorial disabled'),'var(--light1)'); }
function tutorialEnable(){ const st=ensureTutorialState(); st.enabled=true; saveGame(); try{renderStoryWindow();}catch(_){} notify(tt('Tutoriel activé','Tutorial enabled'),'var(--green)'); }
function tutorialDismissTip(id){ if(id) ensureTutorialState().dismissedTips[id]=true; saveGame(); }
function closeTutorialTip(){ const el=document.getElementById('tutorial-tip'); if(el) el.remove(); }
function tutorialMark(id){ const st=ensureTutorialState(); if(id&&!st.completed[id]){ st.completed[id]=true; updateTutorialProgress(); saveGame(); try{renderStoryWindow();}catch(_){} } }
function tutorialDeviceHint(kind){
 const touch=(typeof navigator!=='undefined'&&navigator.maxTouchPoints>0)||('ontouchstart' in window);
 if(kind==='sheet') return touch?tt('Mobile : appuie longtemps sur un Pokémon de ton équipe ou touche sa carte.','Mobile: long-press a team Pokémon or tap its card.'):tt('PC : clique ou clic droit sur un Pokémon dans Équipe Active.','PC: click or right-click a Pokémon in Active Team.');
 if(kind==='map') return touch?tt('Mobile : utilise la barre du bas pour revenir à Carte ou Lieu.','Mobile: use the bottom bar to return to Map or Location.'):tt('PC : clique sur la Carte puis utilise la fenêtre Lieu.','PC: click the Map, then use the Location window.');
 return touch?tt('Mobile : utilise les gros boutons.','Mobile: use the large buttons.'):tt('PC : utilise les raccourcis et le clic droit.','PC: use shortcuts and right-click.');
}
function tutorialSteps(){ return [
 {id:'route1_battles',title:()=>tt('Premiers combats','First battles'),desc:()=>tt('Gagne 3 combats sauvages sur la Route 1.','Win 3 wild battles on Route 1.'),how:()=>tt(`Carte → Route 1, puis dans Lieu clique 🌾 Explorer. ${tutorialDeviceHint('map')}`,`Map → Route 1, then in Location click 🌾 Explore. ${tutorialDeviceHint('map')}`),actionLabel:()=>tt('Aller à Route 1','Go to Route 1'),actionCall:'clickLocation',actionArgs:"'route1'",done:()=>((G.wildWinsByLoc||{}).route1||0)>=3,money:300,items:{berry_oran:3},rewardText:()=>tt('+300₽ + 3 Baies Oran','+300₽ + 3 Oran Berries')},
 {id:'open_poke_sheet',title:()=>tt('Lire une fiche Pokémon','Read a Pokémon sheet'),desc:()=>tt('Ouvre une fiche Pokémon.','Open a Pokémon sheet.'),how:()=>`${tutorialDeviceHint('sheet')} ${tt('Regarde les onglets Base Stats / IV / EV.','Check the Base Stats / IV / EV tabs.')}`,actionLabel:()=>tt('Voir mon équipe','View my team'),actionCall:'showTab',actionArgs:"'team'",done:()=>!!ensureTutorialState().completed.open_poke_sheet,money:200,rewardText:()=>'+200₽'},
 {id:'open_bag',title:()=>tt('Ouvrir le sac','Open the bag'),desc:()=>tt('Ouvre le Sac depuis les Raccourcis.','Open the Bag from Shortcuts.'),how:()=>tt('Dans Raccourcis, clique 🎒 Sac.','In Shortcuts, click 🎒 Bag.'),actionLabel:()=>tt('Ouvrir le Sac','Open Bag'),actionCall:'openFullscreenPanel',actionArgs:"'inventory'",items:{potion:2},done:()=>!!ensureTutorialState().completed.open_bag,rewardText:()=>tt('+2 Potions','+2 Potions')},
 {id:'open_pokedex',title:()=>tt('Consulter le Pokédex','Check the Pokédex'),desc:()=>tt('Ouvre le Pokédex et clique un Pokémon vu.','Open the Pokédex and click a seen Pokémon.'),how:()=>tt('Dans Raccourcis, ouvre le Pokédex puis clique un Pokémon non grisé.','From Shortcuts, open the Pokédex and click a non-grayed Pokémon.'),actionLabel:()=>tt('Ouvrir le Pokédex','Open Pokédex'),actionCall:'openFullscreenPanel',actionArgs:"'pokedex'",done:()=>!!ensureTutorialState().completed.open_pokedex,money:500,rewardText:()=>'+500₽'},
 {id:'first_badge',title:()=>tt('Premier badge','First badge'),desc:()=>tt('Progresse jusqu’à Argenta et bats Pierre.','Progress to Pewter City and defeat Brock.'),how:()=>tt('Nettoie les routes jusqu’à Argenta puis clique ⚔️ Défier Pierre dans Lieu.','Clear routes to Pewter City, then click ⚔️ Challenge Brock in Location.'),actionLabel:()=>tt('Voir le lieu','View location'),actionCall:'showTab',actionArgs:"'info'",done:()=>G.badges&&G.badges.includes('brock'),items:{rarecandy:1},rewardText:()=>tt('+1 Super Bonbon','+1 Rare Candy')}
]; }
function tutorialGiveReward(step){ const st=ensureTutorialState(); if(!step||st.rewards[step.id]) return; if(step.money){G.money=(G.money||0)+step.money; try{updateHeader();}catch(_){}} if(step.items){for(const k in step.items)addToInventory(k,step.items[k]);} st.rewards[step.id]=true; if(step.rewardText) notify(step.rewardText(),'var(--green)'); }
function updateTutorialProgress(){ const st=ensureTutorialState(); for(const step of tutorialSteps()){ if(!st.completed[step.id]&&step.done()) st.completed[step.id]=true; if(st.completed[step.id]) tutorialGiveReward(step);} if(tutorialSteps().every(s=>st.completed[s.id])&&st.enabled){st.enabled=false; try{saveGame();}catch(_){}} }
function currentTutorialStep(){ updateTutorialProgress(); const st=ensureTutorialState(); return tutorialSteps().find(s=>!st.completed[s.id])||null; }
function renderTutorialQuestBlock(){ const st=ensureTutorialState(); if(!st.enabled) return ''; const steps=tutorialSteps(); const step=currentTutorialStep(); if(!step){st.enabled=false; try{saveGame();}catch(_){} return '';} const done=steps.filter(s=>st.completed[s.id]).length; const idx=steps.findIndex(s=>s.id===step.id)+1; return `<div class="tutorial-quest-card active"><div class="tutorial-quest-head"><span>💡</span><b>${tt('Tutoriel guidé','Guided tutorial')} — ${tt('Étape','Step')} ${idx}/${steps.length}</b></div><div class="tutorial-quest-title">${step.title()}</div><p>${step.desc()}</p><div class="tutorial-how"><b>${tt('Comment faire','How to do it')} :</b><br>${step.how()}</div><div class="tutorial-progress-bar"><div data-pct="${Math.round(done/steps.length*100)}"></div></div><div class="tutorial-quest-actions">${step.actionCall?`<button class="hbtn tutorial-primary" data-action="legacy-call" data-call="${step.actionCall}" data-call-args="${step.actionArgs||''}">${step.actionLabel()}</button>`:''}<button class="hbtn" data-action="legacy-call" data-call="openFullscreenPanel" data-call-args="'guide'">${tt('Guide','Guide')}</button><button class="hbtn" data-action="legacy-call" data-call="tutorialDisable" data-call-args="">${tt('Désactiver','Disable')}</button></div></div>`; }
function showTutorialTip(id,title,body){ return; }
function guideSections(){ return {
 map:{icon:'🗺️',title:tt('Carte & progression','Map & progression'),pages:[[tt('Lire la carte','Reading the map'),tt('Les lieux colorés sont disponibles, les lieux gris sont verrouillés. Le bouton ? explique la légende.','Colored areas are available; gray areas are locked. The ? button explains the legend.')],[tt('Dans un lieu','Inside a location'),tt('La fenêtre Lieu peut afficher : Explorer, arène/boss, boutique, PNJ/quêtes, accès région/bateau et infos.','The Location window can show: Explore, gym/boss, shop, NPC/quests, region/boat access and info.')],[tt('Débloquer','Unlocking'),tt('Certaines routes demandent des combats. D’autres zones demandent badges, quêtes ou objets spéciaux.','Some routes require battles. Other areas require badges, quests or special items.')]]},
 combat:{icon:'⚔️',title:tt('Combat','Combat'),pages:[[tt('Automatique','Automatic'),tt('Les Pokémon attaquent quand leur barre est chargée. La vitesse x1/x2/x3 change le rythme.','Pokémon attack when their bar is charged. x1/x2/x3 changes the pace.')],[tt('Changer de Pokémon','Switching Pokémon'),tt('Clique un Pokémon de ton équipe en combat pour le rendre actif.','Click a team Pokémon in battle to make it active.')],[tt('Statuts','Status effects'),tt('Brûlure, poison, paralysie, sommeil et gel modifient le combat.','Burn, poison, paralysis, sleep and freeze affect combat.')]]},
 pokemon:{icon:'🧬',title:tt('Pokémon','Pokémon'),pages:[[tt('Fiche','Sheet'),`${tutorialDeviceHint('sheet')} ${tt('La fiche montre niveau, types, stats, IV, EV, talents et attaques.','The sheet shows level, types, stats, IV, EV, abilities and moves.')}`],[tt('IV et EV','IV and EV'),tt('Les IV sont rares et permanents. Les EV viennent de l’entraînement et renforcent une stat.','IVs are rare permanent bonuses. EVs come from training and boost a stat.')],[tt('Attaques','Moves'),tt('Clique une attaque connue puis une attaque apprenable pour remplacer.','Click a known move, then a learnable move to replace it.')]]},
 bag:{icon:'🎒',title:tt('Sac','Bag'),pages:[[tt('Catégories','Categories'),tt('Baies, objets tenus, pierres, trésors, fossiles et objets spéciaux sont séparés.','Berries, held items, stones, treasures, fossils and special items are separated.')]]},
 mine:{icon:'⛏️',title:tt('Mine','Mine'),pages:[[tt('Creuser','Digging'),tt('Le burin est précis, le marteau creuse large.','The chisel is precise; the hammer digs wide.')]]},
 hatchery:{icon:'🥚',title:tt('Pension','Hatchery'),pages:[[tt('Slots','Slots'),tt('Dépose des Pokémon ou fossiles. Les améliorations sont dans le menu dédié.','Deposit Pokémon or fossils. Upgrades are in the dedicated menu.')]]},
 training:{icon:'🏋️',title:tt('Entraînement','Training'),pages:[[tt('Modes','Modes'),tt('Capacité, Talent, EV et Niveau ont chacun un rôle.','Move, Ability, EV and Level each have a role.')]]},
 dictionary:{icon:'📚',title:tt('Dictionnaire','Dictionary'),pages:[[tt('Recherche','Search'),tt('Cherche objets, attaques et talents pour voir leurs effets et sources.','Search items, moves and abilities to see effects and sources.')]]}
}; }
function setGuideSection(section){ _guideSection=section||null; const el=document.getElementById('fs-panel-content'); if(el) renderGuidePanel(el); }
function renderGuidePanel(el){ const sections=guideSections(); if(_guideSection&&sections[_guideSection]){ const sec=sections[_guideSection]; el.innerHTML=`<div class="guide-header"><div><h2>${sec.icon} ${sec.title}</h2><p>${tt('Guide détaillé','Detailed guide')}</p></div><button class="hbtn" data-action="legacy-call" data-call="setGuideSection" data-call-args="null">← ${tt('Retour','Back')}</button></div><div class="guide-page-list">${sec.pages.map(([title,txt])=>`<article class="guide-info-card"><h3>${title}</h3><p>${txt}</p></article>`).join('')}</div>`; return;} el.innerHTML=`<div class="guide-header"><div><h2>${tt('Guide','Guide')}</h2><p>${tt('Choisis une rubrique pour tout savoir.','Choose a topic to learn everything.')}</p></div></div><div class="guide-actions"><button class="hbtn" data-action="legacy-call" data-call="tutorialEnable" data-call-args="">${tt('Activer les tutos','Enable tutorials')}</button><button class="hbtn" data-action="legacy-call" data-call="tutorialDisable" data-call-args="">${tt('Désactiver tutos','Disable tutorials')}</button></div><div class="guide-grid">${Object.entries(sections).map(([id,sec])=>`<button class="guide-card guide-card-button" data-action="legacy-call" data-call="setGuideSection" data-call-args="'${id}'"><h3>${sec.icon} ${sec.title}</h3><p>${sec.pages.length} ${tt('pages d’informations','information pages')}</p></button>`).join('')}</div>`; }
function installTutorialHooks(){ const wrap=(name,cb)=>{ const fn=window[name]; if(typeof fn!=='function'||fn.__tutorialWrapped) return; const nw=function(...args){ const res=fn.apply(this,args); try{cb(args,res);}catch(_){} return res;}; nw.__tutorialWrapped=true; window[name]=nw;}; wrap('pickStarter',()=>{try{renderStoryWindow();}catch(_){}}); wrap('openFullscreenPanel',([panel])=>{if(panel==='inventory')tutorialMark('open_bag'); if(panel==='pokedex')tutorialMark('open_pokedex');}); wrap('openPokeModal',()=>tutorialMark('open_poke_sheet')); wrap('openBoxPokeModal',()=>tutorialMark('open_poke_sheet')); wrap('exploreArea',()=>updateTutorialProgress()); wrap('renderMap',()=>updateTutorialProgress()); }
setTimeout(installTutorialHooks,500);
if(typeof window!=='undefined'){ window.ensureTutorialState=ensureTutorialState; window.tutorialDisable=tutorialDisable; window.tutorialEnable=tutorialEnable; window.tutorialDismissTip=tutorialDismissTip; window.closeTutorialTip=closeTutorialTip; window.tutorialMark=tutorialMark; window.renderTutorialQuestBlock=renderTutorialQuestBlock; window.renderGuidePanel=renderGuidePanel; window.setGuideSection=setGuideSection; window.showTutorialTip=showTutorialTip; window.installTutorialHooks=installTutorialHooks; }
export {};
