export default [
  {
    files: [
      'src/**/*.js',
      'tools/**/*.js',
      'tools/**/*.mjs',
      '*.js',
    ],
    ignores: [
      'src/legacy-es/**',
      'src/legacy/**',
      'dist/**',
      'node_modules/**',
      'src/ui/input/inline-handler-sanitizer.js',
      'src/data/**',
      'src/localization/**',
    ],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        globalThis: 'readonly',
        console: 'readonly',
        navigator: 'readonly',
        MutationObserver: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        HTMLElement: 'readonly',
        HTMLButtonElement: 'readonly',
        HTMLSpanElement: 'readonly',
        MouseEvent: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        getComputedStyle: 'readonly',
        performance: 'readonly',
        Audio: 'readonly',
        Image: 'readonly',
        CustomEvent: 'readonly',
        localStorage: 'readonly',
        getIcon: 'readonly',
        t: 'readonly',
      },
    },
    linterOptions: {
      reportUnusedDisableDirectives: true,
    },
    rules: {
      'no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_|^o$',
          varsIgnorePattern: '^_',
          caughtErrors: 'all',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      'no-undef': 'error',
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-var': 'warn',
      'prefer-const': 'warn',
    },
  },
  {
    files: [
      'src/engine/**/*.js',
      'src/game/**/*.js',
      // Classic window-wired modules (wave 33: ex-src/game, moved to their
      // architectural layers unchanged) — they resolve game globals through
      // the window surface like before by design.
      'src/ui/game/**/*.js',
      'src/application/combat/**/*.js',
      'src/application/world/**/*.js',
      'src/application/economy/**/*.js',
      'src/application/quests/**/*.js',
      'src/application/automation/**/*.js',
      'src/application/base/**/*.js',
      'src/application/save/**/*.js',
      'src/application/breeding/**/*.js',
      'src/application/bootstrap-timers.js',
      'src/application/game-state.js',
      'src/application/pokemon-factory.js',
      'src/core/game-utils.js',
      'src/engine/input/action-dispatcher.js',
      'src/engine/runtime/classic-bridge.js',
    ],
    rules: {
      'no-undef': 'off',
    },
  },
];


