/**
 * PokéWorld UI — Secret Base internals (rebuilt from zero on the ECS DS):
 * BaseNpcDialogView (NPC encounter + battle-end panel), BasePcDialogView
 * (flag card + PC message), BaseNpcEditorView (editor form) and the four
 * editor pickers (mon / held item / sprite looks / team preset).
 *
 * Before, base-dialog.js and base-npc-editor.js grew raw HTML strings:
 * inline styles on every panel (rgba-black surfaces, hardcoded #c9bc8a
 * text), a gradient rank progress bar inside the flag card, ONE inline
 * `background: linear-gradient(135deg, #e53935, #c62828) !important`
 * collect button fighting the flat-control paint, a GREYED-OUT DEAD
 * cooldown button (DS violation — informative line instead, same rule
 * as the quest cards / wave-21 lock line), and ~103 inline-styled sprite
 * images in the looks picker. All moved to token classes (DS2822).
 *
 * Kept contracts (router + change wiring):
 *  - dialogs: `.modal-close[data-call="closeBaseDialog"]`, fight/rematch
 *    data-call="baseDialogNpcFight", team `.preset-chip`, `.base-dlg-body`
 *    / `.base-dlg-speech` / `.base-dlg-stats` classes,
 *  - PC: `#base-pc-panel`, `#base-pc-msg-input` (maxlength 200),
 *    save data-call="saveBasePcMessage", collect
 *    data-call="collectSecretBaseFlag" data-call-args="'id'" (QUOTED),
 *  - editor: `#base-npced-team`, name input
 *    data-change-call="baseNpcEditorSetField"
 *    data-change-args="'name', this.value", quote inputs
 *    data-change-call="baseNpcEditorSetQuote"
 *    data-change-args="'pre|win|lose', this.value",
 *  - pickers: `.preset-pick-row[data-call="baseNpcEditorPickChoose"]`,
 *    item rows data-call="baseNpcEditorEquipItem" +
 *    data-context-call="openItemInfo" (quoted key), looks grid
 *    `.base-npc-look(.sel)[data-call="baseNpcEditorSetSprite"]`,
 *    filters data-action="filter-base-npc-picker" /
 *    "filter-base-npc-sprite", preset rows
 *    data-call="baseNpcEditorImportPresetFromPicker" (quoted key).
 *
 * The vdom serializer escapes text — adapters pass RAW (unescaped,
 * already localized) strings. Pokemon cards / sprite chips arrive as
 * trusted DS component HTML via h.raw (they are generated by
 * generatePokeCardHTML / spriteImg, both already unified).
 *
 * @module ui/views/BaseViews
 */
import { UIView } from './UIView.js';
import { UIRenderComponent } from '../../engine/components/UIRenderComponent.js';
import { h, toHTMLString } from '../../engine/render/vdom.js';
import { panelHeaderVNode } from '../components/panel-header.js';

/* ─── NPC dialog (encounter OR battle-end, driven by the model) ───────── */

export class BaseNpcDialogView extends UIView {
  constructor(model) {
    super({ name: 'BaseNpcDialogView', model: model || {} });
  }

  windowVNode() {
    const m = this.model;
    return [h('div', { class: 'pw-base-dialog' },
      panelHeaderVNode({
        icon: h('img', { class: 'pw-base-portrait is-28', src: m.titleIconUrl || '', alt: '' }),
        title: m.name || '',
        subtitle: m.subText || '',
        subtitleClass: `pw-${m.subKind || 'light1'}`,
        close: { call: 'closeBaseDialog' },
      }),
      h('div', { class: 'base-dlg-body' },
        h('div', { class: 'base-dlg-portrait' },
          h('img', { class: 'pw-base-portrait is-96', src: m.portraitUrl || '', alt: '' })),
        h('div', { class: 'base-dlg-speech' }, m.speech || '')),
      (m.teamChipsHtml || []).length
        ? h('div', { class: 'pw-row base-dlg-team' }, ...(m.teamChipsHtml || []).map((c) => h.raw(c)))
        : null,
      h('div', { class: 'pw-btn-group' },
        m.primary
          ? h('button', { class: 'hbtn', dataset: { action: 'legacy-call', call: m.primary.call, callArgs: m.primary.callArgs || '' } },
              m.primary.label || '')
          : null,
        h('button', { class: 'hbtn pw-btn-cancel', dataset: { action: 'legacy-call', call: 'closeBaseDialog', callArgs: '' } },
          m.secondaryLabel || '')))];
  }

  onLoad() {
    this.windowEntity = this.spawn('ui:base-npc-dialog', []);
    this.windowEntity.addComponent(new UIRenderComponent({ template: () => this.windowVNode() }));
  }

  /** DOM-free serialization for the classic adapter (base-dialog.js). */
  static toHTML(model) {
    const view = new BaseNpcDialogView(model);
    view.enter();
    return toHTMLString(view.buildView());
  }
}

/* ─── PC dialog (ORAS flag card + PC message) ─────────────────────────── */

export class BasePcDialogView extends UIView {
  constructor(model) {
    super({ name: 'BasePcDialogView', model: model || {} });
  }

  flagCardVNode(f) {
    const next = f.next || null;
    return h('div', { class: `pw-ui-panel pw-base-flag-card is-rank-${f.rankId || 'normal'}` },
      h('div', { class: 'pw-row pw-base-flag-head' },
        h('div', null,
          h('div', { class: 'pw-base-flag-rank' }, '🚩 ' + (f.rankLabel || '')),
          h('div', { class: 'pw-base-flag-count' },
            (f.countLabel || '') + ' ',
            h('b', null, String(f.count || 0)),
            ' ' + (f.flagsWord || ''),
            f.uniqueBases ? [' · ', h('b', null, String(f.uniqueBases)), ' ' + (f.basesWord || '')] : null)),
        f.ownBadge ? h('span', { class: 'pw-badge-gold pw-base-own-badge' }, f.ownBadge) : null),
      h('div', { class: 'pw-base-flag-bar' },
        h('div', {
          class: 'pw-base-flag-fill',
          dataset: { pct: String(Math.max(0, Math.min(100, Math.round(f.pct || 0)))) },
          style: { width: `${Math.max(0, Math.min(100, Math.round(f.pct || 0)))}%` },
        })),
      h('div', { class: 'pw-base-flag-next' },
        next && next.kind === 'supreme'
          ? h('b', null, next.text || '')
          : [(next && next.label) || '', ' ', h('b', null, String((next && next.req) || '')), ' ' + ((next && next.countText) || '')]),
      h('div', { class: 'pw-base-flag-bonuses' },
        h('div', { class: 'pw-base-flag-bonuses-title' }, f.bonusesTitle || ''),
        ...(f.bonusLines || []).map((l) => h('div', null, l))),
      f.collect
        ? h('button', {
            class: 'hbtn pw-btn-danger pw-base-flag-collect',
            dataset: { action: 'legacy-call', call: 'collectSecretBaseFlag', callArgs: f.collect.callArgs || '' },
          }, f.collect.label || '')
        : (f.cooldownText ? h('div', { class: 'pw-base-flag-cooldown' }, '🚩 ' + f.cooldownText) : null));
  }

  pcPanelVNode(pc) {
    if (pc.kind === 'edit') {
      return h('div', { class: 'pw-ui-panel pw-base-pc-panel is-edit' },
        h('div', { class: 'pw-base-pc-title' }, '💬 ' + (pc.title || '')),
        h('div', { class: 'pw-base-pc-hint' }, pc.hint || ''),
        h('textarea', {
          id: 'base-pc-msg-input', class: 'pw-base-pc-input',
          maxlength: '200', placeholder: pc.placeholder || '',
        }, pc.value || ''),
        h('div', { class: 'pw-base-pc-actions' },
          h('button', { class: 'hbtn', dataset: { action: 'legacy-call', call: 'saveBasePcMessage', callArgs: '' } },
            pc.saveLabel || ''),
          h('span', { class: 'pw-base-pc-count' }, `${(pc.value || '').length}/200`)));
    }
    return h('div', { class: 'pw-ui-panel pw-base-pc-panel' },
      h('div', { class: 'pw-base-pc-title' }, '💬 ' + (pc.title || '')),
      h('div', { class: 'pw-base-pc-quote' }, '“' + (pc.text || '') + '”'));
  }

  windowVNode() {
    const m = this.model;
    const stats = m.stats || null;
    return [h('div', { class: 'pw-base-dialog' },
      panelHeaderVNode({
        icon: '🖥️',
        title: m.title || '',
        subtitle: m.subText || '',
        close: { call: 'closeBaseDialog' },
      }),
      stats
        ? h('div', { class: 'pw-row base-dlg-stats' },
            h('span', null, (stats.visitsLabel || '') + ' ', h('b', null, String(stats.visits | 0))),
            h('span', null, (stats.winsLabel || '') + ' ', h('b', null, String(stats.wins | 0))),
            h('span', null, (stats.lossesLabel || '') + ' ', h('b', null, String(stats.losses | 0))))
        : null,
      h('div', { id: 'base-pc-panel', class: 'base-dlg-panel pw-base-pc-wrap' },
        this.flagCardVNode(m.flag || {}),
        m.pc ? this.pcPanelVNode(m.pc) : null))];
      // Wave 28 (user feedback): the "Fermer" button is REMOVED — it was a
      // duplicate of the title ✕ (and of the new Escape/back handling), and
      // it sat mid-sheet instead of at the bottom of the panel.
  }

  onLoad() {
    this.windowEntity = this.spawn('ui:base-pc-dialog', []);
    this.windowEntity.addComponent(new UIRenderComponent({ template: () => this.windowVNode() }));
  }

  /** DOM-free serialization for the classic adapter (base-dialog.js). */
  static toHTML(model) {
    const view = new BasePcDialogView(model);
    view.enter();
    return toHTMLString(view.buildView());
  }
}

/* ─── NPC editor form (name / sprite / team cards / quotes / actions) ─── */

export class BaseNpcEditorView extends UIView {
  constructor(model) {
    super({ name: 'BaseNpcEditorView', model: model || {} });
  }

  windowVNode() {
    const m = this.model;
    return [h('div', { class: 'pw-base-npced' },
      panelHeaderVNode({
        icon: h('img', { class: 'pw-base-portrait is-28', src: m.titleIconUrl || '', alt: '' }),
        title: m.title || '',
        close: { call: 'closeBaseNpcEditor' },
      }),
      // Wave 26 (user): everything between the header and the footer lives
      // in ONE scroller (.pw-base-npced / DS2826) — the team and the quote
      // fields no longer slide under the actions bar and off the sheet.
      h('div', { class: 'pw-base-npced-scroll' },
      h('small', { class: 'preset-manager-hint' }, m.hint || ''),
      // Wave 28 (user): dedicated identity row — sprite LEFT, name field
      // RIGHT, side by side. Before, the 64px portrait button was crammed
      // into the 22px .preset-row-idx chip and OVERLAPPED the name input
      // ("l'un par dessus l'autre").
      h('div', { class: 'pw-base-npced-id' },
        h('button', {
          type: 'button', class: 'base-npc-portrait-btn pw-base-npced-id-portrait', title: m.portraitHint || '',
          dataset: { action: 'legacy-call', call: 'baseNpcEditorOpenSpritePicker', callArgs: '' },
        },
          h('img', { class: 'pw-base-portrait is-64', src: m.portraitUrl || '', alt: '' }),
          h('span', { class: 'base-npc-portrait-edit' }, '✏️')),
        h('div', { class: 'pw-base-npced-id-name' },
          h('input', {
            class: 'preset-name-input', maxlength: '18', value: m.nameValue || '',
            placeholder: m.namePlaceholder || '',
            dataset: { changeCall: 'baseNpcEditorSetField', changeArgs: "'name', this.value" },
          }),
          h('div', { class: 'pw-text-sm pw-light1' }, m.spriteMetaLine || ''))),
      h('div', { class: 'pw-row pw-btn-group pw-base-npced-teambar' },
        h('b', null, m.teamLabel || ''),
        h('span', { class: 'pw-text-sm pw-light1' }, m.levelAutoText || ''),
        h('button', { class: 'hbtn', dataset: { action: 'legacy-call', call: 'baseNpcEditorOpenPresetPicker', callArgs: '' } },
          m.presetBtnLabel || '')),
      h('div', { id: 'base-npced-team', class: 'team-view pw-base-npced-team' }, h.raw(m.cardsHtml || '')),
      h('div', { class: 'pw-row pw-btn-group' }, h('b', null, m.quotesLabel || '')),
      h('div', { class: 'preset-list' },
        ...(m.quotes || []).map((q) => h('div', { class: 'preset-row' },
          h('span', { class: 'preset-row-count' }, q.label || ''),
          h('input', {
            class: 'preset-name-input', maxlength: '80', value: q.value || '',
            dataset: { changeCall: 'baseNpcEditorSetQuote', changeArgs: `'${q.key}', this.value` },
          }))))),
      h('div', { class: 'pw-btn-group pw-base-npced-actions' },
        h('button', { class: 'hbtn', dataset: { action: 'legacy-call', call: 'baseNpcEditorSave', callArgs: '' } }, m.saveLabel || ''),
        h('button', { class: 'hbtn pw-btn-danger', dataset: { action: 'legacy-call', call: 'baseNpcEditorDelete', callArgs: '' } }, m.deleteLabel || ''),
        h('button', { class: 'hbtn pw-btn-cancel', dataset: { action: 'legacy-call', call: 'closeBaseNpcEditor', callArgs: '' } }, m.backLabel || '')))];
  }

  onLoad() {
    this.windowEntity = this.spawn('ui:base-npc-editor', []);
    this.windowEntity.addComponent(new UIRenderComponent({ template: () => this.windowVNode() }));
  }

  /** DOM-free serialization for the classic adapter (base-npc-editor.js). */
  static toHTML(model) {
    const view = new BaseNpcEditorView(model);
    view.enter();
    return toHTMLString(view.buildView());
  }
}

/* ─── Mon picker (fallback when the unified selector is unavailable) ──── */

export class BaseNpcPickerView extends UIView {
  constructor(model) {
    super({ name: 'BaseNpcPickerView', model: model || {} });
  }

  windowVNode() {
    const m = this.model;
    return [h('div', { class: 'pw-base-picker' },
      panelHeaderVNode({
        icon: '🔍',
        title: m.title || '',
        subtitle: m.sub || '',
        close: { call: 'renderBaseNpcEditor' },
      }),
      h('input', {
        class: 'dict-search preset-pick-search', value: m.searchValue || '',
        placeholder: m.searchPlaceholder || '',
        dataset: { action: 'filter-base-npc-picker' },
      }),
      h('div', { class: 'preset-pick-list pw-base-pick-scroll' },
        (m.rows || []).length
          ? (m.rows || []).map((r) => h('div', {
              class: 'inv-item preset-pick-row',
              dataset: { action: 'legacy-call', call: 'baseNpcEditorPickChoose', callArgs: r.callArgs || '' },
            },
              h('div', { class: 'inv-icon' }, h.raw(r.spriteHtml || '')),
              h('div', { class: 'pw-flex-1' },
                h('div', { class: 'inv-name' }, (r.nameText || '') + ' ', h('small', { class: 'pw-light1' }, r.metaText || ''))),
              h('span', { class: `preset-pick-tag${r.inBox ? ' in-box' : ''}` }, r.tagText || '')))
          : h('div', { class: 'pw-empty-state-md' }, m.emptyLabel || '')),
      h('div', { class: 'pw-btn-group' },
        m.remove
          ? h('button', { class: 'hbtn pw-btn-danger', dataset: { action: 'legacy-call', call: 'baseNpcEditorRemoveMon', callArgs: m.remove.callArgs || '' } },
              m.remove.label || '')
          : null,
        h('button', { class: 'hbtn pw-btn-cancel', dataset: { action: 'legacy-call', call: 'renderBaseNpcEditor', callArgs: '' } },
          m.backLabel || '')))];
  }

  onLoad() {
    this.windowEntity = this.spawn('ui:base-npc-picker', []);
    this.windowEntity.addComponent(new UIRenderComponent({ template: () => this.windowVNode() }));
  }

  /** DOM-free serialization for the classic adapter (base-npc-editor.js). */
  static toHTML(model) {
    const view = new BaseNpcPickerView(model);
    view.enter();
    return toHTMLString(view.buildView());
  }
}

/* ─── Held-item picker (fallback when the fullscreen picker is missing) ─ */

export class BaseNpcItemPickerView extends UIView {
  constructor(model) {
    super({ name: 'BaseNpcItemPickerView', model: model || {} });
  }

  windowVNode() {
    const m = this.model;
    return [h('div', { class: 'pw-base-picker' },
      panelHeaderVNode({
        iconHtml: m.titleIconHtml || '',
        title: m.title || '',
        subtitle: m.sub || '',
        close: { call: 'renderBaseNpcEditor' },
      }),
      h('div', { class: 'preset-pick-list pw-base-pick-scroll' },
        (m.rows || []).length
          ? (m.rows || []).map((r) => h('div', {
              class: `inv-item preset-pick-row${r.isCurrent ? ' is-current' : ''}`,
              dataset: {
                action: 'legacy-call', call: 'baseNpcEditorEquipItem', callArgs: r.callArgs || '',
                contextCall: 'openItemInfo', contextArgs: r.contextArgs || '',
              },
            },
              h('div', { class: 'inv-icon' }, h.raw(r.spriteHtml || '')),
              h('div', { class: 'pw-flex-1' },
                h('div', { class: 'inv-name' }, r.nameText || ''),
                h('div', { class: 'inv-desc' }, h.raw(r.descText || '')))))
          : h('div', { class: 'pw-empty-state-md' }, m.emptyLabel || '')),
      h('div', { class: 'pw-btn-group' },
        m.remove
          ? h('button', { class: 'hbtn pw-btn-danger', dataset: { action: 'legacy-call', call: 'baseNpcEditorClearItem', callArgs: m.remove.callArgs || '' } },
              m.remove.label || '')
          : null,
        h('button', { class: 'hbtn pw-btn-cancel', dataset: { action: 'legacy-call', call: 'renderBaseNpcEditor', callArgs: '' } },
          m.backLabel || '')))];
  }

  onLoad() {
    this.windowEntity = this.spawn('ui:base-npc-item-picker', []);
    this.windowEntity.addComponent(new UIRenderComponent({ template: () => this.windowVNode() }));
  }

  /** DOM-free serialization for the classic adapter (base-npc-editor.js). */
  static toHTML(model) {
    const view = new BaseNpcItemPickerView(model);
    view.enter();
    return toHTMLString(view.buildView());
  }
}

/* ─── Sprite looks picker (used standalone AND inside the editor) ─────── */

export class BaseNpcSpritePickerView extends UIView {
  constructor(model) {
    super({ name: 'BaseNpcSpritePickerView', model: model || {} });
  }

  static lookVNode(s) {
    return h('button', {
      type: 'button', class: `base-npc-look${s.selected ? ' sel' : ''}`, title: s.id || '',
      dataset: { action: 'legacy-call', call: 'baseNpcEditorSetSprite', callArgs: `'${s.id}'` },
    }, h('img', { class: 'pw-base-portrait is-48', src: s.url || '', alt: '' }));
  }

  windowVNode() {
    const m = this.model;
    return [h('div', { class: 'pw-base-picker' },
      panelHeaderVNode({
        icon: '🎨',
        title: m.title || '',
        subtitle: m.hint || null,
        close: { call: m.closeCall || 'renderBaseNpcEditor' },
      }),
      h('input', {
        class: 'dict-search pw-base-looks-filter', value: m.filterValue || '',
        placeholder: m.filterPlaceholder || 'trainer-42...',
        dataset: { action: 'filter-base-npc-sprite' },
      }),
      h('div', { class: 'base-npc-looks pw-base-looks-scroll' },
        (m.sprites || []).length
          ? (m.sprites || []).map((s) => BaseNpcSpritePickerView.lookVNode(s))
          : (m.emptyLabel || '')),
      h('div', { class: 'pw-btn-group' },
        h('button', { class: 'hbtn pw-btn-cancel', dataset: { action: 'legacy-call', call: m.closeCall || 'renderBaseNpcEditor', callArgs: '' } },
          m.backLabel || '')))];
  }

  onLoad() {
    this.windowEntity = this.spawn('ui:base-npc-sprite-picker', []);
    this.windowEntity.addComponent(new UIRenderComponent({ template: () => this.windowVNode() }));
  }

  /** DOM-free serialization for the classic adapter (base-npc-editor.js). */
  static toHTML(model) {
    const view = new BaseNpcSpritePickerView(model);
    view.enter();
    return toHTMLString(view.buildView());
  }

  /**
   * Grid-only serialization: baseNpcEditorFilterSprite re-renders JUST the
   * `.base-npc-looks` grid to keep the search input focused — same buttons.
   */
  static looksHTML(sprites) {
    return toHTMLString((sprites || []).map((s) => BaseNpcSpritePickerView.lookVNode(s)));
  }
}

/* ─── Team preset picker ──────────────────────────────────────────────── */

export class BaseNpcPresetPickerView extends UIView {
  constructor(model) {
    super({ name: 'BaseNpcPresetPickerView', model: model || {} });
  }

  windowVNode() {
    const m = this.model;
    return [h('div', { class: 'pw-base-picker' },
      panelHeaderVNode({
        icon: '📋',
        title: m.title || '',
        subtitle: m.hint || '',
        close: { call: 'renderBaseNpcEditor' },
      }),
      h('div', { class: 'preset-pick-list pw-base-pick-scroll' },
        (m.rows || []).length
          ? (m.rows || []).map((r) => h('div', {
              class: 'inv-item preset-pick-row pw-base-preset-row',
              dataset: { action: 'legacy-call', call: 'baseNpcEditorImportPresetFromPicker', callArgs: r.callArgs || '' },
            },
              h('div', { class: 'pw-base-preset-row-inner' },
                h('div', { class: 'inv-name' }, (r.name || '') + ' ', h('small', { class: 'pw-light1' }, `(${r.count || 0})`)),
                h('div', { class: 'pw-base-preset-sprites' }, h.raw(r.spritesHtml || '')))))
          : h('div', { class: 'pw-empty-state-md' }, m.emptyLabel || '')),
      h('div', { class: 'pw-btn-group' },
        h('button', { class: 'hbtn pw-btn-cancel', dataset: { action: 'legacy-call', call: 'renderBaseNpcEditor', callArgs: '' } },
          m.backLabel || '')))];
  }

  onLoad() {
    this.windowEntity = this.spawn('ui:base-npc-preset-picker', []);
    this.windowEntity.addComponent(new UIRenderComponent({ template: () => this.windowVNode() }));
  }

  /** DOM-free serialization for the classic adapter (base-npc-editor.js). */
  static toHTML(model) {
    const view = new BaseNpcPresetPickerView(model);
    view.enter();
    return toHTMLString(view.buildView());
  }
}

