// ===== FR — Base secrète =====
window.L_fr_base = {
"title":"Base Secrète",
"export_done":"Base exportée en JSON !",
"win":{
"moved":"Base déménagée : {name}. Les meubles sont retournés au stock.",
"title":"Base Secrète",
"mode_label":"Mode de rendu",
"layout_label":"Gabarit de la base",
"layout_group":{"cave":"Grottes","cave_red":"Grottes rouges","cave_blue":"Grottes bleues","cave_yellow":"Grottes jaunes","tree":"Arbres","bush":"Buissons"},
"refresh":"Rafraîchir",
"mode3d":"3D (modèles ORAS)",
"mode2d":"2D Émeraude",
"empty":"Charge une sauvegarde pour voir ta base secrète.",
"not_established":"Aucune Base Secrète établie. Visitez une alcôve depuis la fenêtre Lieu d'une route de Hoenn, puis installez-vous !",
"no_gl":"WebGL2 indisponible — affichage 2D.",
"layout":{
"cave_1":"Grotte · Salle 1","cave_2":"Grotte · Salle 2","cave_3":"Grotte · Salle 3","cave_4":"Grotte · Salle 4",
"tree_1":"Arbre · Salle 1","tree_2":"Arbre · Couloir 2","tree_3":"Arbre · Salle 3","tree_4":"Arbre · Deux ailes 4",
"bush_1":"Buisson · Salle 1","bush_2":"Buisson · Salle 2","bush_3":"Buisson · Croix 3","bush_4":"Buisson · Salle 4",
"cave_red_1":"Grotte Rouge · Salle 1","cave_red_2":"Grotte Rouge · Couloir 2","cave_red_3":"Grotte Rouge · Salle 3","cave_red_4":"Grotte Rouge · Salle 4",
"cave_blue_1":"Grotte Bleue · Salle 1","cave_blue_2":"Grotte Bleue · Couloir 2","cave_blue_3":"Grotte Bleue · Puits 3","cave_blue_4":"Grotte Bleue · Salle 4",
"cave_yellow_1":"Grotte Jaune · Salle 1","cave_yellow_2":"Grotte Jaune · Couloir 2","cave_yellow_3":"Grotte Jaune · Salle 3","cave_yellow_4":"Grotte Jaune · Salle 4",
"cave_5":"Grotte · Mezzanine 5","cave_6":"Grotte · Balcon 6",
"tree_5":"Arbre · Suspendue 5","tree_6":"Arbre · Mezzanine 6",
"bush_5":"Buisson · Terrasse 5","bush_6":"Buisson · Grande Terrasse 6",
"cave_red_5":"Grotte Rouge · Mezzanine 5","cave_red_6":"Grotte Rouge · Balcons 6",
"cave_blue_5":"Grotte Bleue · Mezzanine 5","cave_blue_6":"Grotte Bleue · Balcon 6",
"cave_yellow_5":"Grotte Jaune · Mezzanine 5","cave_yellow_6":"Grotte Jaune · Balcons 6"
}
},
"debug":{"granted":"Catalogue déco : {n} objets ajoutés au stock (debug).","npc_name":"PNJ","npc_added":"PNJ créé depuis ton équipe actuelle : {name}.","npcs_added":"{n} PNJ installés dans la base !"},
"edit":{
"move_hint":"{name} en main : clique une case pour le poser là, clic droit pour l\u2019annuler (+ « Ramasser » pour le ranger).",
"need2d":"L\u2019édition se fait en mode 2D Émeraude — bascule le rendu en haut à droite.",
"moved_item":"{name} déplacé.",
"move_cancel":"Déplacement annulé, le meuble est revenu à sa place.",
"pc_own":"Ton PC : c\u2019est ici que tu gères ta base (retourne en mode édition).",
"pc_record":"PC de {name} — visites : {v}, PNJ vainqueurs : {w}, PNJ battus : {l}.",
"pc_record_none":"Aucun record à afficher.",
"stock":"Stock",
"stock_empty":"Stock vide — utilise le catalogue déco (debug) pour meubler.",
"pals":"PNJ",
"rotate":"Pivoter",
"pickup":"Ramasser",
"place_hint":"Clique une case pour poser · clic droit ou « Pivoter » pour tourner.",
"select_hint":"Clique un meuble posé pour le prendre en main et le redéposer ailleurs, ou choisis un objet du stock.",
"placed":"{name} posé !",
"picked_up":"{name} rangé dans le stock.",
"rotated":"{name} pivoté.",
"npc_move_hint":"{name} en main : clique une case pour l\u2019installer là.",
"npc_no_team":"{name} n\u2019a pas encore d\u2019\u00e9quipe \u2014 clique-le en mode \u00e9dition puis \u00ab Modifier \u00bb.",
"npc_placed":"{name} s'installe !",
"npc_picked_up":"{name} retiré de la salle.",
"visit":"Visiter",
"visit_stop":"Terminer la visite",
"visit_hint":"Clique une case pour t'y déplacer · clique un meuble ou un PNJ pour interagir.",
"visit_only2d":"La visite interactive se joue en vue 2D (la 3D arrive plus tard).",
"visit_start":"Bienvenue dans la base de {name} !",
"visit_start_own":"Bienvenue dans ta propre base !",
"battle_done":"{name} a déjà été défié pendant cette visite.",
"visit_end":"Fin de la visite — {w} victoire(s), {l} défaite(s).",
"export":"Exporter",
"import":"Visiter un fichier…",
"battle_challenge":"{name} te défie !",
"battle_won":"Victoire contre {name} !",
"battle_lost":"Défaite face à {name}…",
"heal":"L'équipe est toute guérie !",
"sit":"Tu te reposes un instant…",
"light_on":"La lampe s'allume.",
"light_off":"La lampe s'éteint.",
"punch":"Hiya ! Quel beau coup de poing !",
"rules":"Les règles de combat de cette base sont affichées.",
"message":"Il y a un message écrit ici…",
"reveal":"Quelque chose d'invisible apparaît !",
"blocked":"Impossible d'aller là."
},
"notes":["do","ré","mi","fa","sol","la","si","do+"],
"visit":{
"burst":"Paf ! Le ballon éclate !",
"glitter":"Le tapis scintille sous vos pas…",
"jump":"Boing !",
"slide":"Vous glissez jusqu'en bas !",
"spin":"Le tapis tourbillonne et vous repousse !",
"spinforce":"Le panneau vous propulse !",
"pitfall":"Ouch ! Vous êtes tombé dans un trou !",
"squareone":"Retour à l'entrée !",
"warp":"Téléportation !",
"door_break":"Vous enfoncez la fausse porte !",
"invisible":"Il y a quelque chose d'invisible ici…",
"makiwara":"Un poteau utilisé par les maîtres d'armes pour s'entraîner à Coupe.",
"note":"La note « {note} » résonne."
},
"err":{
"unknown":"Objet inconnu.",
"no_base":"Aucune base secrète pour l'instant.",
"stairs_anchor":"L'escalier doit être posé sur la rampe prévue.",
"board_hole":"La planche (2 cases de haut) se pose le haut sur un trou.",
"pc_unreachable":"Le PC doit rester joignable à pied depuis l\u2019ouverture.",
"already_placed":"Déjà présent dans la base (objet automatique unique).",
"occupied":"Case déjà occupée.",
"out_of_bounds":"Hors des limites de la base.",
"wall_only":"Cette décoration s'accroche au mur.",
"surface_only":"Cette décoration se pose à l'intérieur.",
"needs_surface":"À poser au sol ou sur un bureau, un tapis ou un pneu.",
"floor_only":"À poser au sol.",
"uneven":"À poser sur un sol de niveau (pas à cheval sur la falaise).",
"entrance":"L'entrée doit rester libre.",
"wall_hidden":"Ce mur n'est visible d'aucune case praticable.",
"surface_taken":"Cette place est déjà prise.",
"max_placed":"Maximum 26 objets posés, comme à Hoenn !",
"blocks_spawn":"Impossible : cela bloquerait l'accès à l'entrée.",
"blocks_npc":"Impossible : un PNJ serait injoignable.",
"not_in_stock":"Cet objet n'est plus dans le stock.",
"not_rotatable":"Cet objet ne tourne pas.",
"npc_max":"Maximum 8 PNJ dans une base.",
"npc_team":"Un PNJ doit avoir au moins un Pokémon.",
"import_empty":"Aucun fichier sélectionné.",
"import_too_big":"Fichier trop volumineux.",
"import_json":"Ce fichier n'est pas un JSON valide.",
"import_kind":"Ce fichier n'est pas une base secrète PokéWorld.",
"import_version":"Version de base non prise en charge.",
"import_layout":"Gabarit de salle inconnu.",
"import_items":"Liste d'objets invalide.",
"import_npcs":"Liste de PNJ invalide.",
"export":"Échec de l'export."
},
// Noms + répliques des PNJ (avant/victoire/défaite)

"dlg":{
"npc_sub":"Rencontre",
"npc_default":"\u2026",
"fight":"Combattre",
"decline":"Passer son chemin",
"close":"Fermer",
"rematch":"Revanche",
"res_won":"Tu as battu {name} !",
"res_lost":"{name} t\u2019a battu\u2026",
"res_quote_won":"\u2026",
"res_quote_lost":"\u2026",
"pc_title":"PC de la base",
"pc_own":"Ton terminal personnel",
"pc_guest":"Terminal du propri\u00e9taire",
"pc_visits":"Visites :",
"pc_wins":"PNJ vainqueurs :",
"pc_losses":"PNJ battus :",
"pc_empty":"Ce terminal n\u2019a pas encore de fonctions \u2014 elles arriveront dans une prochaine mise \u00e0 jour."
},
"npced":{
"title":"\u00c9diteur de PNJ",
"edit_selected":"Modifier le PNJ",
"place_npc":"PNJ",
"place_hint":"Prends le PNJ puis clique une case pour l\u2019installer.",
"hint":"Configure ce PNJ : son nom, son allure, ses r\u00e9pliques et son \u00e9quipe. Les visiteurs de ta base pourront l\u2019affronter.",
"name":"Nom",
"sprite":"Allure du PNJ",
"team":"\u00c9quipe ({n}/6)",
"team_empty":"\u00c9quipe vide",
"add_mon":"Ajouter un Pok\u00e9mon",
"remove_mon":"Retirer ce Pok\u00e9mon",
"level_auto":"Niveau, attaques et objet sont repris du Pok\u00e9mon choisi.",
"pick_title":"Choisir un Pok\u00e9mon",
"pick_search":"Rechercher un Pok\u00e9mon\u2026",
"pick_hint":"Clique le sprite pour changer de Pok\u00e9mon",
"pick_item_title":"Objet tenu \u2014 {name}",
"no_item":"Aucun objet tenu",
"remove_item":"Retirer l\u2019objet",
"item_set":"{name} tient {item}.",
"from_preset":"Importer une \u00e9quipe\u2026",
"from_preset_active":"\u00c9quipe active",
"quotes":"R\u00e9pliques",
"quote_pre":"Avant le combat",
"quote_win":"S\u2019il gagne",
"quote_lose":"S\u2019il perd",
"save":"Enregistrer",
"back":"Retour",
"delete":"Supprimer ce PNJ",
"delete_confirm":"Supprimer {name} ? Cette action est d\u00e9finitive.",
"updated":"{name} mis \u00e0 jour.",
"deleted":"{name} supprim\u00e9.",
"imported":"\u00c9quipe import\u00e9e : {n} Pok\u00e9mon."
},

"npc":{
"gamin_tristan":{"name":"Gamin Tristan","pre":"J'ai dressé mes Pokémon juste pour cette base !","win":"Hé ! Tu es super fort, toi !","lose":"Je savais que mon Rattata était le meilleur !"},
"gamin_hugo":{"name":"Gamin Hugo","pre":"Personne ne bat mon duo de poings !","win":"Aïe… mes bras sont en compote.","lose":"Vous avez vu ça ?! Quel combat !"},
"fillette_lea":{"name":"Fillette Léa","pre":"Regarde comme ils sont mignons… et costauds !","win":"Même défaite, ma team reste la plus mignonne !","lose":"Trop chouette ! Merci pour le combat !"},
"fillette_manon":{"name":"Fillette Manon","pre":"Mes plantes vont tout empoisonner !","win":"Mes plantes ont besoin de soleil après ça…","lose":"La nature reprend toujours ses droits !"},
"marin_gwenole":{"name":"Marin Gwénolé","pre":"À l'abordage, moussaillon !","win":"Tonnerre de Brest… battu à sec…","lose":"La mer est toujours du côté du marin !"},
"marin_erwan":{"name":"Marin Erwan","pre":"Vogue sur tes Pokémon et tiens bon !","win":"J'ai pris le bouillon, pas toi !","lose":"En plein dans le mille ! Cap sur la victoire !"},
"ecolier_mathis":{"name":"Écolier Mathis","pre":"J'ai révisé les types cette nuit !","win":"Mes calculs étaient pourtant exacts…","lose":"La théorie devient pratique. Leçon retenue !"},
"ecoliere_jade":{"name":"Écolière Jade","pre":"Un duel psychique, ça te tente ?","win":"Je l'avais prédit… et pourtant…","lose":"Mon esprit a vu ta défaite avant toi !"}
},
"cat":{"desks":"Bureaux","chairs":"Chaises","mats":"Tapis","plants":"Plantes","objects":"Objets","wall":"Mural","dolls":"Poupées","cushions":"Coussins","appliances":"Appareils","tricks":"Farces"},
"i":{
"a_note_mat":"Tapis La",
"attract_mat":"Tapis Attraction",
"azurill_doll":"Poupée Azurill",
"b_note_mat":"Tapis Si",
"ball_cushion":"Coussin Ball",
"ball_poster":"Poster Ball",
"baltoy_doll":"Poupée Balbuto",
"big_plant":"Grosse Plante",
"blastoise_doll":"Poupée Tortank",
"blue_balloon":"Ballon Bleu",
"blue_brick":"Brique Bleue",
"blue_poster":"Poster Bleu",
"blue_tent":"Tente Bleue",
"breakable_door":"Porte Fragile",
"brick_chair":"Chaise Brique",
"brick_desk":"Bureau Brique",
"c_high_note_mat":"Tapis Do Aigu",
"c_low_note_mat":"Tapis Do Grave",
"camp_chair":"Chaise Rondin",
"camp_desk":"Bureau Rondin",
"charizard_doll":"Poupée Dracaufeu",
"chikorita_doll":"Poupée Germignon",
"clefairy_doll":"Poupée Mélofée",
"colorful_plant":"Plante Colore",
"comfort_chair":"Chaise Confort",
"comfort_desk":"Bureau Confort",
"cute_poster":"Poster Mignon",
"cute_tv":"Télé Mignonne",
"cyndaquil_doll":"Poupée Héricendre",
"d_note_mat":"Tapis Ré",
"diamond_cushion":"Coussin Diamant",
"ditto_doll":"Poupée Métamorph",
"duskull_doll":"Poupée Skelénox",
"e_note_mat":"Tapis Mi",
"f_note_mat":"Tapis Fa",
"fence_length":"Barrière Long.",
"fence_width":"Barrière Larg.",
"fire_blast_mat":"Tapis Déflagra",
"fire_cushion":"Coussin Feu",
"fissure_mat":"Tapis Fissure",
"g_note_mat":"Tapis Sol",
"glass_ornament":"Objet Verre",
"glitter_mat":"Tapis Paillete",
"gold_shield":"Bouclier Or",
"gorgeous_plant":"Plante Superbe",
"grass_cushion":"Coussin Plante",
"green_poster":"Poster Vert",
"gulpin_doll":"Poupée Gloupti",
"hard_chair":"Chaise Massive",
"hard_desk":"Bureau Massif",
"heavy_chair":"Grande Chaise",
"heavy_desk":"Grand Bureau",
"jigglypuff_doll":"Poupée Rondoudou",
"jump_mat":"Tapis Saut",
"kecleon_doll":"Poupée Kecleon",
"kiss_cushion":"Coussin Baiser",
"kiss_poster":"Poster Baiser",
"lapras_doll":"Poupée Lokhlass",
"long_poster":"Poster Long",
"lotad_doll":"Poupée Nénupiot",
"marill_doll":"Poupée Marill",
"meowth_doll":"Poupée Miaouss",
"mud_ball":"Boule de Boue",
"mudkip_doll":"Poupée Gobou",
"pc":"PC",
"pichu_doll":"Poupée Pichu",
"pika_cushion":"Coussin Pika",
"pika_poster":"Poster Pika",
"pikachu_doll":"Poupée Pikachu",
"pokemon_chair":"Chaise Pokémon",
"pokemon_desk":"Bureau Pokémon",
"powder_snow_mat":"Tapis Neige",
"pretty_chair":"Jolie Chaise",
"pretty_desk":"Joli Bureau",
"pretty_flowers":"Jolies Fleurs",
"ragged_chair":"Chaise Abîmée",
"ragged_desk":"Bureau Abîmé",
"red_balloon":"Ballon Rouge",
"red_brick":"Brique Rouge",
"red_plant":"Plante Rouge",
"red_poster":"Poster Rouge",
"red_tent":"Tente Rouge",
"regice_doll":"Poupée Regice",
"regirock_doll":"Poupée Regirock",
"registeel_doll":"Poupée Registeel",
"rhydon_doll":"Poupée Rhinoféros",
"round_cushion":"Coussin Rond",
"round_tv":"Télé Ronde",
"sand_ornament":"Statue Sable",
"sea_poster":"Poster Mer",
"seedot_doll":"Poupée Grainipiot",
"silver_shield":"Bouclier Arg.",
"skitty_doll":"Poupée Skitty",
"sky_poster":"Poster Ciel",
"slide":"Toboggan",
"small_chair":"Petite Chaise",
"small_desk":"Petit Bureau",
"smoochum_doll":"Poupée Lippouti",
"snorlax_doll":"Poupée Ronflex",
"solid_board":"Planche Solide",
"spikes_mat":"Tapis Pics",
"spin_cushion":"Coussin Mimigal",
"spin_mat":"Tapis Tournant",
"stairs":"Escalier",
"stand":"Présentoir",
"surf_mat":"Tapis Surf",
"swablu_doll":"Poupée Tylton",
"thunder_mat":"Tapis Éclair",
"tire":"Pneu",
"togepi_doll":"Poupée Togepi",
"torchic_doll":"Poupée Poussifeu",
"totodile_doll":"Poupée Kaiminus",
"treecko_doll":"Poupée Arcko",
"tropical_plant":"Plante Tropicale",
"tv":"Télé",
"venusaur_doll":"Poupée Florizarre",
"wailmer_doll":"Poupée Wailmer",
"water_cushion":"Coussin Eau",
"wynaut_doll":"Poupée Okéoké",
"yellow_balloon":"Ballon Jaune",
"yellow_brick":"Brique Jaune",
"zigzag_cushion":"Coussin Zigzag"
}
};

