// ===== FR — Gym Leader / Champion names & titles =====
window.L_fr_champions = {
"brock": {"name":"Pierre","title":"Champion Arène Argenta","badgeName":"Badge Roche"},
"misty": {"name":"Ondine","title":"Championne Arène Azuria","badgeName":"Badge Cascade"},
"surge": {"name":"Major Bob","title":"Champion Arène Carmin sur Mer","badgeName":"Badge Foudre"},
"erika": {"name":"Erika","title":"Championne Arène Céladopole","badgeName":"Badge Prisme"},
"koga": {"name":"Koga","title":"Champion Arène Parmanie","badgeName":"Badge Âme"},
"sabrina": {"name":"Morgane","title":"Championne Arène Safrania","badgeName":"Badge Marais"},
"blaine": {"name":"Auguste","title":"Champion Arène Cramois'île","badgeName":"Badge Volcan"},
"giovanni": {"name":"Giovanni","title":"Champion Arène Jadielle","badgeName":"Badge Terre"},
"elite4": {"name":"Ligue Kanto","title":"Ligue Kanto","badgeName":"Titre de Maître Kanto"},
"johto_elite4": {"name":"Ligue Johto","title":"Ligue Johto","badgeName":"Titre de Maître Johto"},
"falkner": {"name":"Albert","title":"Champion Arène Mauville","badgeName":"Badge Zéphyr"},
"bugsy": {"name":"Hector","title":"Champion Arène Écorcia","badgeName":"Badge Essaim"},
"whitney": {"name":"Blanche","title":"Championne Arène Doublonville","badgeName":"Badge Plaine"},
"morty": {"name":"Mortimer","title":"Champion Arène Rosalia","badgeName":"Badge Brume"},
"chuck": {"name":"Chuck","title":"Champion Arène Irisia","badgeName":"Badge Choc"},
"jasmine": {"name":"Jasmine","title":"Championne Arène Oliville","badgeName":"Badge Minéral"},
"pryce": {"name":"Frédo","title":"Champion Arène Acajou","badgeName":"Badge Glacier"},
"clair": {"name":"Sandra","title":"Championne Arène Ébénelle","badgeName":"Badge Lever"},
// Étapes des ligues (passe 19) — noms/titres affichés pendant le gauntlet
"lorelei": {"name":"Olga","title":"Conseil 4 — Glace & Eau"},
"bruno": {"name":"Aldo","title":"Conseil 4 — Combat & Roche"},
"agatha": {"name":"Agatha","title":"Conseil 4 — Spectre & Poison"},
"lance": {"name":"Peter","title":"Conseil 4 — Dragon"},
"blue": {"name":"Bleu","title":"Maître de la Ligue Kanto"},
"will": {"name":"Clément","title":"Conseil 4 — Psy"},
"koga_e4": {"name":"Koga","title":"Conseil 4 — Poison"},
"bruno_johto": {"name":"Aldo","title":"Conseil 4 — Combat"},
"karen": {"name":"Marion","title":"Conseil 4 — Ténèbres"},
"lance_johto": {"name":"Peter","title":"Maître de la Ligue Johto"},
  "roxanne": {"name":"Roxanne","title":"Championne Arène Mérouville","badgeName":"Badge Roche"},
  "brawly": {"name":"Bastien","title":"Champion Arène Myokara","badgeName":"Badge Poing"},
  "wattson": {"name":"Voltère","title":"Champion Arène Lavandia","badgeName":"Badge Dynamo"},
  "flannery": {"name":"Adrianna","title":"Championne Arène Vermilava","badgeName":"Badge Chaleur"},
  "norman": {"name":"Norman","title":"Champion Arène Clémenti-Ville","badgeName":"Badge Équilibre"},
  "winona": {"name":"Alizée","title":"Championne Arène Cimmery","badgeName":"Badge Plume"},
  "tate_liza": {"name":"Lévy & Tatia","title":"Champions Arène Algatia (Duo)","badgeName":"Badge Esprit"},
  "juan": {"name":"Juan","title":"Champion Arène Atalanopolis","badgeName":"Badge Pluie"},
  "sidney": {"name":"Damien","title":"Conseil 4 Ténèbres","badgeName":""},
  "phoebe": {"name":"Spectra","title":"Conseil 4 Spectre","badgeName":""},
  "glacia": {"name":"Glacia","title":"Conseil 4 Glace","badgeName":""},
  "drake": {"name":"Aragon","title":"Conseil 4 Dragon","badgeName":""},
  "steven": {"name":"Pierre Rochard","title":"Maître de Hoenn","badgeName":"Titre de Maître Hoenn"},
  "hoenn_elite4": {"name":"Ligue Hoenn","title":"Ligue Hoenn","badgeName":"Titre de Maître Hoenn"},
};



