// ===== FR — COMBAT strings =====
// Auto-extracted & grouped by domain. Edit text here, never hardcode in logic.

window.L_fr_combat = {
"battle_lock_box":"<b>Combat en cours :</b> L'ajout ou l'échange est désactivé.",
"battle_lock_team":"<b>Combat en cours :</b> L'équipe est verrouillée.",
"champ_no_loot":"Les combats d'arène n'accordent pas de capture de Pokémon sauvage.",
"dupe_tag":"doublon",
"leave_combat":"Quitter le combat",
"live_loot":"Butin en direct :",
"no_loot_yet":"Aucun butin récolté pour le moment.",
"battle_summary_no_damage":"Aucun dégât enregistré pour cette session.",
"battle_summary_no_captures":"Aucune capture pendant cette session.",
"battle_summary_no_items":"Aucun objet trouvé pendant cette session.",
"battle_summary_duplicates":"Doublons",
"battle_summary_shiny":"Chromatique",
"battle_summary_standard":"Standard",
"battle_transform_log":"Transformation : {source} prend l'apparence de {target} !",
"battle_talent_discovered_log":"Talent découvert : {talent} !",
"talent_intimidate_player":"[Intimidation] L'Attaque de {name} baisse !",
"talent_regenerator_player":"[Régé-Force] {name} régénère ses PV !",
"talent_intimidate_enemy":"[Intimidation] L'Attaque de {name} baisse !",
"combat_attack_auto_1":"[Lévitation] {p0} flotte au-dessus de l'attaque Sol !",
"combat_attack_auto_2":"[Paratonnerre] {p0} absorbe l'attaque Électrik !",
"combat_attack_auto_3":"{p0} rate son coup !",
"combat_attack_auto_4":"Ça n'affecte pas {p0}...",
"combat_attack_auto_5":"{p0} souffre déjà d'une altération d'état !",
"combat_attack_auto_6":"Ça n'affecte pas {p0}...",
"combat_attack_auto_7":"{p0} est paralysé !",
"combat_attack_auto_8":"{p0} rate son coup !",
"combat_attack_auto_9":"Ça n'affecte pas {p0}...",
"combat_attack_auto_10":"{p0} est empoisonné !",
"combat_attack_auto_11":"{p0} rate son coup !",
"combat_attack_auto_12":"Ça n'affecte pas {p0}...",
"combat_attack_auto_13":"{p0} est gravement empoisonné !",
"combat_attack_auto_14":"{p0} rate son coup !",
"combat_attack_auto_15":"Ça n'affecte pas {p0}...",
"combat_attack_auto_16":"{p0} est brûlé !",
"combat_attack_auto_17":"{p0} rate son coup !",
"combat_attack_auto_18":"{p0} s'est endormi !",
"combat_attack_auto_19":"{p0} rate son coup !",
"combat_attack_auto_20":"Ça n'affecte pas {p0}...",
"combat_attack_auto_21":"{p0} est gelé !",
"combat_attack_auto_22":"{p0} rate son coup !",
"combat_attack_auto_23":"La vitesse de {p0} ne peut plus baisser !",
"combat_attack_auto_24":"La vitesse de {p0} baisse !",
"combat_attack_auto_25":"[Coloforce] Attaque physique augmentée de +60% !",
"combat_attack_auto_26":"[Cran] Attaque augmentée de +50% grâce au statut !",
"combat_attack_auto_27":"[Engrais] Puissance Plante augmentée !",
"combat_attack_auto_28":"[Brasier] Puissance Feu augmentée !",
"combat_attack_auto_29":"[Torrent] Puissance Eau augmentée !",
"combat_attack_auto_30":"[Isograisse] Dégâts Feu/Glace réduits de 50% !",
"combat_attack_auto_31":"[Multiécaille] Dégâts subis réduits grâce aux PV max !",
"combat_attack_auto_32":"La Roche Royale de {p0} fait hésiter {p1} !",
"combat_attack_auto_33":"[Fermeté] {p0} encaisse le coup mortel !",
"combat_attack_auto_34":"[Peau Dure] {p0} subit {p1} PV de dégâts au contact !",
"combat_attack_auto_35":"[Statik] {p0} paralyse l'assaillant au contact !",
"combat_attack_auto_36":"[Point Poison] {p0} empoisonne l'assaillant au contact !",
"combat_attack_auto_37":"{p0} est blessé par le contrecoup ! (-{p1} PV)",
"combat_attack_auto_38":"{p0} est blessé par l'Orbe Vie ! (-{p1} PV)",
"combat_attack_auto_39":"{p0} hésite !",
"combat_attack_auto_40":"{p0} est brûlé !",
"combat_attack_auto_41":"{p0} est paralysé !",
"combat_attack_auto_42":"{p0} est empoisonné !",
"combat_attack_auto_43":"{p0} est gelé !",
"combat_attack_auto_44":"{p0} s'est endormi !",
"combat_damage_lost":"{name} perd {damage} PV !{effect}",
"critical_hit":"Coup critique !",
"status_burn_faded":"La brûlure de {name} s'est estompée !",
"status_poison_faded":"{name} n'est plus empoisonné !",
"status_para_faded":"{name} n'est plus paralysé !",
"status_freeze_faded":"{name} a dégelé !",
"status_sleep_faded":"{name} s'est réveillé !",
"burn_damage":"{name} souffre de la brûlure (-{damage} PV)",
"poison_damage":"{name} souffre du poison (-{damage} PV)",
"bad_poison_damage":"{name} souffre du poison virulent (-{damage} PV)",
"leftovers_heal":"{name} récupère {heal} PV grâce aux Restes !",
"pokemon_fainted":"{name} est mis KO !",
"training_round_ev":"Round vaincu ! EV {stat} augmente à {value}/6 !",
"new_talent_unlocked":"Nouveau talent débloqué : {talent} ({rarity}) !",
"talent_reconfirmed":"Talent {talent} ({rarity}) re-confirmé !",
"no_new_talent":"Pas de nouveau talent cette fois...",
"training_room_round":" SALLE D'ENTRAÎNEMENT - Round {round}/6 : {pokemon} !",
"champion_sends":"{champion} envoie {pokemon} !",
"league_stage_victory":" Victoire contre {trainer} ! Votre équipe a été entièrement soignée (100% PV) !",
"league_stage_success":" Étape {stage}/5 réussie ! Équipe soignée ! Combat suivant : {trainer}...",
"league_next_battle":" LIGUE KANTO - Combat {stage}/5 : {trainer} envoie {pokemon} !",
"team_gains_xp":"Votre équipe gagne {xp} XP chacun !",
"empty_enemy_team_error":" Erreur : équipe adverse vide.",
"enemy_not_found_error":" Erreur : Pokémon adverse introuvable.",
"wild_shiny_appears":" Un {name} sauvage apparaît... il brille étrangement !",
"pokemon_appears":"Un {name} apparaît !",
"trainer_sends":"{trainer} envoie {pokemon} !",
"give_up":"Abandonner",
"leave_battle_button":"Quitter",
"need_badges_challenge":" Il vous faut {need} badge(s) pour défier {champion}.",
"league_battle_challenge":" LIGUE KANTO - Combat 1/5 : {trainer} vous défie !",
"league_intro_quote":"{trainer} : « Préparez-vous à affronter la puissance du Conseil 4 ! »",
"champion_team_error":" Erreur d'équipe pour le champion {champion}.",
"champion_battle_start":"Combat contre {champion} !",
"champion_intro_quote":"{champion} : « Je suis le champion de cette arène ! »",
"wild_pokemon_shiny_appears":" Un {name} sauvage apparaît... il brille étrangement !",
"wild_pokemon_appears":"Un {name} sauvage apparaît !",
"player_pokemon_ko":"{name} est KO !",
"training_failed_ko_log":" Votre Pokémon à l'entraînement est KO ! Entraînement échoué...",
"training_failed_ko_notify":"Entraînement échoué ! Votre Pokémon a été mis KO.",
"all_pokemon_ko_lost":"Tous vos Pokémon sont KO ! Vous avez perdu...",
"money_lost":"Vous perdez {money}₽ !",
"battle_lost_recover":" Vous avez perdu ! Relancez un combat quand vous voulez : votre équipe est soignée à chaque début de combat.",
"go_pokemon":"Allez, {name} !",
"switch_pending":"{name} entrera en jeu dès que possible...",
"solo_training_no_switch":"Switch impossible : votre Pokémon s'entraîne en solo au Dojo !",
"shiny_captured":" POKÉMON SHINY CAPTURÉ ! ",
"hidden_talent_unlocked_reward":" (Talent Caché débloqué !)",
"league_master_victory_log":" Vous avez vaincu le Maître Kanto et triomphé des 5 combats de la Ligue !",
"league_master_title_reward":" Félicitations ! Vous obtenez le Titre de Maître Pokémon ! (+{money}₽)",
"rematch_won_reward":" Revanche remportée contre {champion} ! (+{money}₽)",
"league_victory_message":" Félicitations ! Vous avez triomphé des 5 combats de la Ligue Kanto et obtenez le Titre de Maître Pokémon !",
"add_pokemon":"Ajouter un Pokémon",
"team_count":"{count}/6 dans l'équipe",
"item_removed_team":"{item} retiré de l'équipe.",
"evolution_duplicate_bonus":" {name} aurait évolué en {target}, déjà possédé ! (+{money}₽)",
"evolution_duplicate_bonus_html":" {name} aurait évolué en <b>{target}</b>, déjà possédé ! (+{money}₽)",
"evolution_triggered_box":" {name} déclenche une évolution : {target} apparaît dans la boîte PC !",
"evolution_created_box":" Une évolution de {name} est née : <b>{target}</b> (Nv.1, → boîte) !",
"captured_pokemon_title":"Pokémon capturés :",
"found_items_title":"Objets trouvés :",
"woke_up_log":"{name} se réveille !",
"sleeping_turns_log":"{name} est endormi... ({turns} tour{plural})",
"thawed_log":"{name} se décongèle !",
"frozen_skip_log":"{name} est gelé...",
"paralyzed_skip_log":"{name} est paralysé et ne peut pas attaquer !",
"uses_move_log":"{name} utilise <b>{move}</b> !",
"forfeit_champion":"Vous abandonnez le combat contre {champion}. Vous pourrez le redéfier à tout moment.",
"leave_battle_notify":"Vous quittez le combat.",
"leaving_button":"Départ...",
"map_legend_title":"Légende de la carte",
"current_location":"Lieu actuel",
"reachable_location":"Lieu accessible",
"locked_location":"Lieu verrouillé",
"eff_immune":"Immunité !",
"eff_very_weak":"Très peu efficace...",
"battle_in_progress":"Combat en cours",
};

