// ===== FR — ECONOMY strings =====
// Auto-extracted & grouped by domain. Edit text here, never hardcode in logic.

window.L_fr_economy = {
"already_eq":"Déjà équipé",
"already_held":"Déjà tenu par",
"already_owned_sp":"Espèce poss.",
"back_bag":"Retour au sac",
"box_empty":"Votre boîte est vide.<br><br>Les Pokémon capturés quand votre équipe est pleine (6/6) et les évolutions y apparaissent.",
"evolves_into":"Évolue en :",
"in_stock":"En stock",
"inv_empty":"Votre sac est vide.<br><br>Achetez des baies au shop ou creusez dans le souterrain pour trouver des pierres et trésors.",
"market_cat_leg":"Légendaires",
"market_cat_other":"Autres Pokémon",
"market_cat_rare":"Pokémon rares",
"market_cat_starter":"Starters",
"market_empty":"Tous les Pokémon sont déjà obtenables en jeu !",
"market_owned":"Déjà possédé",
"mine_chisel":"Burin (1x1 profond, -5 Énergie)",
"mine_energy":"Énergie de Forage",
"mine_energy_hint":"+2 / sec · +15 par victoire sauvage",
"mine_hammer":"Marteau (3x3 large, -15 Énergie)",
"mine_new_layer":"Sondage (Nouvelle Couche)",
"mine_treasures":"Trésors déterrés :",
"no_evo_stone":"Aucune pierre d'évolution disponible.",
"remove_q":"Retirer",
"sell_all":"Vendre tout",
"sell_one":"Vendre x1",
"shop_empty":"Pas de boutique ici.",
"stone_inv_lbl":"Pierre d'Évolution",
"stone_lbl":"Pierre d'évolution : Cliquez pour faire évoluer un Pokémon",
"treasure_inv_lbl":"Trésor (Revente)",
"treasure_lbl":"Trésor Souterrain : Cliquez pour revendre",
"use_stone":"Utiliser",
"will_replace":"(remplacera l'objet actuel)",
};
