// ===== FR — Location names (all regions) =====

export const L_location_names_fr = {
  "abandoned_ship": "Épave",
  "ancient_tomb": "Tombeau Antique (Registeel)",
  "aqua_hideout": "Planque Aqua",
  "azalea": "Écorcia",
  "battle_frontier": "Zone de Combat",
  "blackthorn": "Ébénelle",
  "burnedtower": "Tour Cendrée",
  "billshouse": "Chalet de Léo",
  "cave_of_origin": "Grotte Origine",
  "celadon": "Céladopole",
  "cerulean": "Azuria",
  "ceruleancave": "Caverne Azurée",
  "cherrygrove": "Ville Griotte",
  "cianwood": "Irisia",
  "cinnabar": "Cramois'île",
  "darkcave": "Antre Noir",
  "desert_ruins": "Ruines Désert (Regirock)",
  "dewford": "Myokara",
  "diglettscave": "Cave Taupiqueur",
  "diglettscave_2": "Cave Taupiqueur",
  "ecruteak": "Rosalia",
  "evergrande": "Éternara",
  "fallarbor": "Autopia",
  "fiery_path": "Chemin Ardente",
  "fortree": "Cimmery",
  "fuchsia": "Parmanie",
  "goldenrod": "Doublonville",
  "granite_cave": "Grotte Granite",
  "hoenn_league": "Ligue Pokémon de Hoenn",
  "icepath": "Route de Glace",
  "ilexforest": "Bois aux Chênes",
  "indigo": "Plateau Indigo",
  "indigo_jo": "Plateau Indigo",
  "island_cave": "Grotte Isolée (Regice)",
  "jroute26": "Route 26",
  "jroute27": "Route 27",
  "jroute28": "Route 28",
  "jroute29": "Route 29",
  "jroute30": "Route 30",
  "jroute31": "Route 31",
  "jroute32": "Route 32",
  "jroute32_mid": "Route 32",
  "jroute32_south": "Route 32",
  "jroute33": "Route 33",
  "jroute34": "Route 34",
  "jroute35": "Route 35",
  "jroute36": "Route 36",
  "jroute37": "Route 37",
  "jroute38": "Route 38",
  "jroute39": "Route 39",
  "jroute40": "Route 40",
  "jroute41": "Route 41",
  "jroute42": "Route 42",
  "jroute43": "Route 43",
  "jroute44": "Route 44",
  "jroute45": "Route 45",
  "jroute46": "Route 46",
  "jroute47": "Route 47",
  "jroute48": "Route 48",
  "lakerage": "Lac Colère",
  "lavaridge": "Vermilava",
  "lavender": "Lavanville",
  "lilycove": "Nénucrique",
  "littleroot": "Bourg-en-Vol",
  "mahogany": "Acajou",
  "mauville": "Lavandia",
  "meteor_falls": "Grotte Tréfonds",
  "mirage_island": "Île Mirage",
  "mossdeep": "Algatia",
  "mossdeep_space_center": "Centre Spatial d'Algatia",
  "mt_chimney": "Mont Chimnée",
  "mt_pyre": "Mont Mémoria",
  "mtmoon": "Mont Sélénite",
  "mtmortar": "Mont Creuset",
  "mtsilver": "Mont Argenté",
  "nationalpark": "Parc Naturel",
  "newbark": "Bourg Geon",
  "oldale": "Rosyères",
  "olivine": "Oliville",
  "pacifidlog": "Pacifiville",
  "pallet": "Bourg Palette",
  "petalburg": "Clémenti-Ville",
  "petalburg_woods": "Bois Clémenti",
  "pewter": "Argenta",
  "pokemonmansion": "Manoir Pokémon",
  "pokemontower": "Tour Pokémon",
  "powerplant": "Centrale Électrique",
  "rocktunnel": "Grotte Rocheuse",
  "route1": "Route 1",
  "route10": "Route 10",
  "route101": "Route 101",
  "route102": "Route 102",
  "route103": "Route 103",
  "route104": "Route 104",
  "route105": "Chenal 105",
  "route106": "Chenal 106",
  "route107": "Chenal 107",
  "route108": "Chenal 108",
  "route109": "Chenal 109",
  "route11": "Route 11",
  "route110": "Route 110",
  "route111": "Route 111",
  "route112": "Route 112",
  "route113": "Route 113",
  "route114": "Route 114",
  "route115": "Route 115",
  "route116": "Route 116",
  "route117": "Route 117",
  "route118": "Route 118",
  "route119": "Route 119",
  "route12": "Route 12",
  "route120": "Route 120",
  "route121": "Route 121",
  "route122": "Chenal 122",
  "route123": "Route 123",
  "route124": "Chenal 124",
  "route125": "Chenal 125",
  "route126": "Chenal 126",
  "route127": "Chenal 127",
  "route128": "Chenal 128",
  "route129": "Chenal 129",
  "route13": "Route 13",
  "route130": "Chenal 130",
  "route131": "Chenal 131",
  "route132": "Chenal 132",
  "route133": "Chenal 133",
  "route134": "Chenal 134",
  "route14": "Route 14",
  "route15": "Route 15",
  "route16": "Route 16",
  "route17": "Piste Cyclable (17)",
  "route18": "Route 18",
  "route19": "Chenal 19",
  "route2": "Route 2",
  "route20": "Chenal 20",
  "route21": "Chenal 21",
  "route22": "Route 22",
  "route23": "Route 23",
  "route24": "Pont Pépite (24)",
  "route25": "Route 25",
  "route2_south": "Route 2 (Sud)",
  "route3": "Route 3",
  "route4": "Route 4",
  "route5": "Route 5",
  "route6": "Route 6",
  "route7": "Route 7",
  "route8": "Route 8",
  "route9": "Route 9",
  "ruinsofalph": "Ruines d'Alpha",
  "rustboro": "Mérouville",
  "rusturf_tunnel": "Tunnel Mérazon",
  "safari_zone_ho": "Parc Safari Hoenn",
  "safarizone": "Parc Safari",
  "saffron": "Safrania",
  "seafloor_cavern": "Caverne Fond-de-Mer",
  "seafoamislands": "Îles Écume",
  "sealed_chamber": "Sanctuaire",
  "shoal_cave": "Grotte Tréfonds Mer",
  "sky_pillar": "Pilier Céleste",
  "slateport": "Poivressel",
  "slowpokewell": "Puits Ramoloss",
  "sootopolis": "Atalanopolis",
  "southern_island": "Île du Sud",
  "sprouttower": "Tour Chétiflor",
  "tintower": "Tour Carillon",
  "tohjofalls": "Chutes Tohjo",
  "unioncave": "Caves Jumelles",
  "verdanturf": "Vergazon",
  "vermilion": "Carmin sur Mer",
  "victoryroad": "Route Victoire",
  "victoryroad_ho": "Route Victoire Hoenn",
  "victoryroad_jo": "Route Victoire (Johto)",
  "violet": "Mauville",
  "viridian": "Jadielle",
  "viridianforest": "Forêt de Jade",
  "weather_institute": "Centre Météo",
  "whirlislands": "Tourb'Îles"
};

// T2 (vague 38) : module ESM — export natif ; la surface classique est
// gardée sur l'objet global pour les registres (data.js) et les harnais VM.
if (typeof globalThis !== 'undefined') globalThis.L_location_names_fr = L_location_names_fr;
