// ===== FR — Location names (Kanto + Johto) =====

window.L_location_names_fr = {
"azalea":"Écorcia",
"blackthorn":"Ébénelle",
"celadon":"Céladopole",
"cerulean":"Azuria",
"ceruleancave":"Caverne Azurée",
"cherrygrove":"Ville Griotte",
"cianwood":"Irisia",
"cinnabar":"Cramois'île",
"diglettscave":"Cave Taupiqueur",
"ecruteak":"Rosalia",
"fuchsia":"Parmanie",
"goldenrod":"Doublonville",
"ilexforest":"Bois aux Chênes",
"indigo":"Plateau Indigo",
"jroute29":"Route 29",
"jroute30":"Route 30",
"jroute31":"Route 31",
"jroute32":"Route 32",
"jroute32_mid":"Route 32",
"jroute32_south":"Route 32",
"jroute33":"Route 33",
"jroute34":"Route 34",
"jroute35":"Route 35",
"jroute36":"Route 36",
"jroute38":"Route 38/39",
"jroute40":"Chenal 40/41",
"jroute42":"Route 42",
"jroute44":"Route de Glace",
"jroute45":"Route 45/46",
"lakerage":"Lac Colère",
"lavender":"Lavanville",
"mahogany":"Acajou",
"mtmoon":"Mont Sélénite",
"newbark":"Bourg Geon",
"olivine":"Oliville (Port )",
"pallet":"Bourg Palette",
"pewter":"Argenta",
"pokemonmansion":"Manoir Pokémon",
"pokemontower":"Tour Pokémon",
"powerplant":"Centrale Électrique",
"rocktunnel":"Grotte Rocheuse",
"route1":"Route 1",
"route10":"Route 10",
"route11":"Route 11",
"route12":"Route 12",
"route13":"Route 13",
"route14":"Route 14",
"route15":"Route 15",
"route16":"Route 16",
"route17":"Piste Cyclable (17)",
"route18":"Route 18",
"route19":"Chenal 19",
"route2":"Route 2",
"route20":"Chenal 20",
"route21":"Chenal 21",
"route22":"Route 22",
"route23":"Route Victoire (23)",
"route24":"Pont Pépite (24)",
"route25":"Route 25",
"route3":"Route 3",
"route4":"Route 4",
"route5":"Route 5",
"route6":"Route 6",
"route7":"Route 7",
"route8":"Route 8",
"route9":"Route 9",
"safarizone":"Parc Safari",
"saffron":"Safrania",
"seafoamislands":"Îles Écume",
"unioncave":"Caves Jumelles",
"vermilion":"Carmin sur Mer",
"victoryroad":"Route Victoire (Grotte)",
"violet":"Mauville",
"viridian":"Jadielle",
"viridianforest":"Forêt Jadielle",
};

