// ===== FR — Descriptions des capacités =====
// Passe 24 : généré par tools/gen_move_descs_fr.mjs (couvre les 400 attaques).
// Clé = id d'attaque ; consommé via t('move_descs.'+id) AVANT le repli mv.desc.
window.L_fr_move_descs = {
  "accelerock": "Attaque 1.2 fois plus vite que la normale.",
  "acid": "10% de chance de baisser la Défense Spéciale ennemie de 50%.",
  "acid_armor": "Augmente la Défense de 100%.",
  "acid_spray": "50% de chance de baisser la Défense Spéciale ennemie de 50%.",
  "acrobatics": "Puissance doublée si le lanceur ne tient aucun objet.",
  "acupressure": "Augmente deux stats aléatoires de 100%.",
  "aeroblast": "Taux de critique augmenté.",
  "agility": "Augmente la Vitesse de 75%.",
  "air_shlash": "30% de chance de baisser la Défense Spéciale ennemie de 50%.",
  "alluring_voice": "Le lanceur attaque avec sa voix angélique. Rend aussi la cible confuse si ses stats ont été augmentées pendant le tour.",
  "amnesia": "Augmente la Défense Spéciale de 100%.",
  "anchor_shot": "Piège la cible.",
  "ancient_power": "10% de chance d'augmenter toutes les stats de 50%.",
  "apple_acid": "Baisse la Défense ennemie de 50%.",
  "aqua_jet": "Attaque 1.2 fois plus vite que la normale.",
  "aqua_step": "Augmente la Vitesse de 50%.",
  "aqua_tail": "Inflige des dégâts sans effet supplémentaire.",
  "arm_thrust": "Frappe 2 à 5 fois.",
  "armor_cannon": "Le lanceur projette son armure en projectiles ardents. Baisse aussi sa Défense et sa Défense Spéciale.",
  "aromatic_mist": "Augmente la Défense Spéciale de toute l'équipe de 50%.",
  "attack_order": "Puissance de base x1.15 à chaque utilisation (max 10). Les cumuls s'annulent au changement de Pokémon.",
  "aura_sphere": "Ne rate jamais.",
  "aura_wheel": "Augmente la Vitesse de 50%.",
  "aurora_beam": "50% de chance de baisser l'Attaque ennemie de 50%.",
  "aurora_punch": "Le lanceur frappe la cible avec un pouvoir d'aurore scintillant.",
  "avalanche": "Baisse la Vitesse ennemie de 50%.",
  "babydoll_eyes": "Baisse l'Attaque ennemie de 50%.",
  "barb_barrage": "Frappe 2 à 5 fois.",
  "barrage": "Frappe 2 à 5 fois.",
  "barrier": "Augmente la Défense de 100%.",
  "baton_pass": "Le lanceur transfère tous ses changements de stats et son statut à toute l'équipe.",
  "beak_blast": "Attaque 1.5 fois plus lentement que la normale.",
  "belly_drum": "Augmente l'Attaque de 150% mais baisse la Défense et la Défense Spéciale de 50%.",
  "bite": "Peut faire trembler la cible.",
  "bitter_blade": "Le lanceur concentre son amertume en une attaque tranchante. Restaure jusqu'à la moitié des dégâts infligés en PV.",
  "blaze_kick": "10% de chance de brûler.",
  "blizzard": "Peut geler la cible.",
  "blue_flare": "30% de chance de brûler.",
  "body_press": "Puissance x1.2 à x1.5 si la Défense/Défense Spéciale est augmentée.",
  "bodyslam": "Peut paralyser la cible.",
  "bolt_strike": "30% de chance de paralyser.",
  "bone_rush": "Frappe 2 à 5 fois.",
  "boomburst": "Inflige des dégâts.",
  "bounce": "Puissance x1.2 à x1.5 si la Défense/Défense Spéciale est augmentée.",
  "brave_bird": "Attaque 1.2 fois plus lentement que la normale.",
  "brick_break": "30% de chance de baisser la Défense ennemie de 50%.",
  "brutal_claw": "Le lanceur lacère la cible avec des griffes brutales pouvant brûler.",
  "bubble_beam": "30% de chance de baisser la Vitesse ennemie de 50%.",
  "bug_bite": "Si la cible tient une Baie, dégâts doublés et la Baie est utilisée.",
  "bug_buzz": "10% de chance de baisser la Défense Spéciale ennemie de 50%.",
  "bulk_up": "Augmente l'Attaque et la Défense de 50%.",
  "bulldoze": "Baisse la Vitesse ennemie de 50%.",
  "bullet_punch": "Attaque 1.2 fois plus vite que la normale.",
  "bullet_seed": "Frappe 2 à 5 fois.",
  "burn_up": "Brûle.",
  "calm_mind": "Augmente la Défense Spéciale et l'Attaque Spéciale de 50%.",
  "camouflage": "Le type du lanceur change selon la météo.",
  "charge": "Augmente l'Attaque Spéciale de 100% et la Défense Spéciale de 50%.",
  "charge_beam": "50% de chance d'augmenter l'Attaque Spéciale de 50%.",
  "charm": "Baisse l'Attaque ennemie de 100%.",
  "chatter": "20% de chance de rendre confus.",
  "chilling_water": "Baisse l'Attaque ennemie de 50%.",
  "chilly_reception": "Invoque la grêle et remplace par le membre suivant de l'équipe.",
  "chloroblast": "Le lanceur projette sa chlorophylle amassée. Le blesse aussi et baisse sa vitesse d'action.",
  "clamp": "Frappe 2 à 5 fois.",
  "clanging_scales": "Baisse la Défense ennemie de 50%.",
  "close_combat": "Baisse la Défense et la Défense Spéciale de 50%.",
  "coil": "Augmente l'Attaque et la Défense de 50%.",
  "comet_punch": "Frappe 2 à 5 fois.",
  "confuse_ray": "Rend confus.",
  "confusion": "Attaque 1.2 fois plus vite que la normale.",
  "conversion": "Le type du lanceur devient celui de sa première capacité.",
  "cotton_guard": "Augmente la Défense de 100% et la Défense Spéciale de 50%.",
  "cotton_spore": "Baisse la Vitesse ennemie de 75%.",
  "crabhammer": "Attaque 1.2 fois plus lentement que la normale.",
  "cross_chop": "Taux de critique augmenté.",
  "cross_poison": "10% de chance d'empoisonner.",
  "cross_room": "Invoque la Salle Croisée.",
  "crunch": "Peut baisser la Défense de la cible d'un cran.",
  "cut": "Inflige des dégâts sans effet supplémentaire.",
  "dark_pulse": "Peut faire trembler la cible.",
  "darkest_lariat": "Ignore les changements de stats de la cible.",
  "dazzling_gleam": "Inflige des dégâts sans effet supplémentaire.",
  "dig": "Puissance x1.2 à x1.5 si la Défense/Défense Spéciale est augmentée.",
  "disarming_voice": "Attaque 1.2 fois plus vite que la normale.",
  "discharge": "30% de chance de paralyser.",
  "dizzy_punch": "10% de chance de rendre confus.",
  "doom_desire": "Attaque 1.5 fois plus lentement que la normale.",
  "double_hit": "Frappe 2 fois.",
  "double_slap": "Frappe 2 à 5 fois.",
  "doubleedge": "Blesse aussi légèrement le lanceur (recul).",
  "draco_meteor": "Baisse l'Attaque Spéciale de 50%.",
  "dragon_breath": "10% de chance de paralyser.",
  "dragon_claw": "Inflige des dégâts sans effet supplémentaire.",
  "dragon_dance": "Augmente l'Attaque et la Vitesse de 50%. Attaque 1.4 fois plus lentement que la normale.",
  "dragon_darts": "Frappe 2 fois.",
  "dragon_energy": "Attaque 1.5 fois plus lentement que la normale.",
  "dragon_pulse": "Inflige des dégâts sans effet supplémentaire.",
  "dragon_rush": "Attaque 1.2 fois plus lentement que la normale. Puissance x1.2 à x1.5 si la Défense/Défense Spéciale est augmentée.",
  "dragon_tail": "30% de chance d'augmenter l'Attaque de 50%.",
  "draining_kiss": "50% de chance de baisser la Défense ennemie de 50%.",
  "drill_peck": "Inflige des dégâts sans effet supplémentaire.",
  "drum_beating": "Baisse la Vitesse ennemie de 50%.",
  "dual_chop": "Frappe 2 fois.",
  "dual_wingbeat": "Frappe 2 fois.",
  "dynamic_punch": "Rend confus.",
  "earth_power": "10% de chance de baisser la Défense Spéciale ennemie de 50%.",
  "earthquake": "Inflige des dégâts et peut toucher les Pokémon sous terre (Tunnel).",
  "echoed_voice": "Puissance de base x1.2 à chaque utilisation (max 5). Les cumuls s'annulent au changement de Pokémon.",
  "egg_bomb": "Inflige des dégâts sans effet supplémentaire.",
  "electric_terrain": "Active un Champ Électrifié.",
  "electrify": "Ajoute temporairement le type Électrik à l'ennemi. Le bonus super efficace des types temporaires est réduit de moitié, et un second type temporaire remplace le premier.",
  "electro_ball": "Attaque 2 fois plus vite que la normale.",
  "electro_web": "Baisse la Vitesse ennemie de 50%.",
  "ember": "10% de chance de brûler.",
  "energy_ball": "10% de chance de baisser la Défense Spéciale ennemie de 50%.",
  "extrasensory": "Peut faire trembler la cible.",
  "extreme_speed": "Attaque 1.2 fois plus vite que la normale.",
  "facade": "Puissance doublée si le lanceur est paralysé, brûlé ou empoisonné.",
  "fairy_lock": "Ajoute temporairement le type Fée à l'ennemi. Le bonus super efficace des types temporaires est réduit de moitié, et un second type temporaire remplace le premier.",
  "fairy_wind": "30% de chance de baisser la Vitesse ennemie de 50%.",
  "fake_tears": "Baisse la Défense Spéciale ennemie de 100%.",
  "false_surrender": "Ne rate jamais.",
  "feather_dance": "Baisse l'Attaque ennemie de 100%.",
  "feint_attack": "Attaque 1.2 fois plus vite que la normale.",
  "fiery_dance": "30% de chance d'augmenter l'Attaque Spéciale de 50%.",
  "fiery_wrath": "Baisse la Défense Spéciale ennemie de 50%.",
  "fire_blast": "Attaque 1.2 fois plus lentement que la normale.",
  "fire_fang": "10% de chance de brûler.",
  "fire_lash": "Baisse la Défense ennemie de 50%.",
  "fire_punch": "10% de chance de brûler.",
  "fire_spin": "Frappe 2 à 5 fois.",
  "first_impression": "Attaque 1.2 fois plus lentement que la normale.",
  "fishious_rend": "Le lanceur déchire la cible avec ses ouïes dures. Puissance doublée s'il attaque avant la cible.",
  "flame_burst": "Brûle toute l'équipe.",
  "flame_charge": "50% de chance d'augmenter la Vitesse de 50%.",
  "flamethrower": "10% de chance de brûler.",
  "flare_blitz": "Attaque 1.2 fois plus lentement que la normale.",
  "flash_cannon": "10% de chance de baisser la Défense Spéciale ennemie de 50%.",
  "floral_healing": "Soigne toutes les altérations de statut de l'équipe.",
  "fly": "Le lanceur s'envole en esquivant toutes les attaques, et frappe au tour suivant.",
  "flying_press": "Attaque 1.2 fois plus lentement que la normale.",
  "foam_shot": "Frappe 2 à 5 fois.",
  "focus_blast": "Attaque 1.2 fois plus lentement que la normale.",
  "fog": "Invoque le brouillard.",
  "force_palm": "Peut paralyser la cible.",
  "forest_curse": "Ajoute temporairement le type Plante à l'ennemi. Le bonus super efficace des types temporaires est réduit de moitié, et un second type temporaire remplace le premier.",
  "freeze_dry": "Super efficace contre les types Eau.",
  "freezing_glare": "Baisse la Vitesse ennemie de 50%.",
  "frenzy_plant": "Attaque 1.5 fois plus lentement que la normale.",
  "frost_breath": "30% de chance de baisser l'Attaque Spéciale ennemie de 50%.",
  "fury_cutter": "Puissance de base x1.2 à chaque utilisation (max 5). Les cumuls s'annulent au changement de Pokémon.",
  "future_sight": "Attaque 2 fois plus lentement que la normale.",
  "gear_up": "Augmente l'Attaque et la Vitesse de toute l'équipe de 50%.",
  "gemstone_crush": "Frappe 2 à 5 fois.",
  "giga_impact": "Attaque 1.5 fois plus lentement que la normale.",
  "gigaton_hammer": "Attaque 1.5 fois plus lentement que la normale.",
  "glaciate": "20% de chance de geler.",
  "grassy_terrain": "Active un Champ Herbu.",
  "growl": "Baisse l'Attaque ennemie de 50%.",
  "gust": "Inflige des dégâts et peut toucher les Pokémon en l'air.",
  "hail": "Invoque la grêle.",
  "hammer_arm": "Baisse la Vitesse de 50%.",
  "head_charge": "Le lanceur subit 1/4 des dégâts infligés en recul.",
  "headlong_rush": "Baisse la Défense de 50%.",
  "heat_crash": "20% de chance de brûler.",
  "heat_wave": "50% de chance de brûler.",
  "hex": "Puissance doublée si la cible a une altération de statut.",
  "hi_jump_kick": "Si le lanceur rate, il subit en recul la moitié des dégâts qu'il aurait infligés.",
  "high_horsepower": "Inflige des dégâts sans effet supplémentaire.",
  "hone_claws": "Augmente l'Attaque et la Vitesse de 50%. Attaque 1.4 fois plus lentement que la normale.",
  "howl": "Augmente l'Attaque de toute l'équipe de 50%.",
  "hurricane": "10% de chance de rendre confus.",
  "hydro_cannon": "Attaque 1.5 fois plus lentement que la normale.",
  "hydro_pump": "Attaque 1.2 fois plus lentement que la normale.",
  "hyper_beam": "Attaque 1.5 fois plus lentement que la normale.",
  "hyper_drill": "Le lanceur vrille la partie pointue de son corps pour transpercer la cible. Peut toucher une cible sous Abri ou Détection.",
  "hyper_voice": "Inflige des dégâts sans effet supplémentaire.",
  "ice_ball": "Puissance de base x1.2 à chaque utilisation (max 5). Les cumuls s'annulent au changement de Pokémon.",
  "ice_beam": "10% de chance de geler.",
  "ice_fang": "10% de chance de geler.",
  "ice_hammer": "Baisse la Vitesse de 50%.",
  "ice_punch": "10% de chance de geler.",
  "ice_shard": "Attaque 1.2 fois plus vite que la normale.",
  "icicle_crash": "Peut faire trembler la cible.",
  "icicle_spear": "Frappe 2 à 5 fois.",
  "icy_wind": "Baisse la Vitesse ennemie de 50%.",
  "incinerate": "Détruit la Baie tenue par la cible.",
  "inferno": "Baisse la Défense et la Défense Spéciale de 100%.",
  "infestation": "Frappe 2 à 5 fois.",
  "ionise": "Augmente l'Attaque Spéciale de 50% et la Défense Spéciale de 100%.",
  "iron_defense": "Augmente la Défense de 100%.",
  "iron_head": "Peut faire trembler la cible.",
  "iron_slug": "Frappe 2 à 5 fois.",
  "iron_tail": "Attaque 1.2 fois plus lentement que la normale. Puissance x1.2 à x1.5 si la Défense/Défense Spéciale est augmentée.",
  "jet_punch": "Attaque 1.5 fois plus vite que la normale.",
  "judgment": "Si le lanceur tient la Plaque ou le Module approprié, les dégâts prennent ce type.",
  "kinesis": "Augmente l'Attaque Spéciale de 100% et la Défense Spéciale de 50%.",
  "kings_shield": "Augmente la Défense Spéciale de 100% et la Défense de 50%.",
  "knock_off": "30% de chance de baisser la Défense ennemie de 50%.",
  "leaf_blade": "Taux de critique augmenté.",
  "leaf_storm": "Baisse l'Attaque Spéciale de 50%.",
  "leafage": "Inflige des dégâts sans effet supplémentaire.",
  "leer": "Baisse la Défense ennemie de 50%.",
  "lick": "10% de chance de paralyser.",
  "light_screen": "Invoque le Mur Lumière.",
  "liquidation": "30% de chance d'augmenter la Défense de 50%.",
  "lovely_kiss": "10% de chance de rendre confus.",
  "low_sweep": "Baisse la Vitesse ennemie de 50%.",
  "lumina_crash": "Puissance x1.2 à x1.5 si la Vitesse est augmentée.",
  "luster_purge": "50% de chance de baisser la Défense Spéciale ennemie de 50%.",
  "mach_punk": "Attaque 1.2 fois plus vite que la normale.",
  "magic_powder": "Ajoute temporairement le type Psy à l'ennemi. Le bonus super efficace des types temporaires est réduit de moitié, et un second type temporaire remplace le premier.",
  "magical_leaf": "50% de chance de baisser l'Attaque Spéciale ennemie de 50%.",
  "magma_storm": "Invoque le soleil.",
  "magnet_bomb": "Ne rate jamais.",
  "magnetic_flux": "Augmente la Défense Spéciale de 50%.",
  "magnitude": "Puissance aléatoire de x1 à x8.",
  "me_first": "Exécute la première capacité de l'adversaire. Attaque 2 fois plus vite que la normale.",
  "megahorn": "Inflige des dégâts sans effet supplémentaire.",
  "memento": "Met le lanceur K.O. et baisse l'Attaque et l'Attaque Spéciale ennemies de 100%.",
  "metal_claw": "30% de chance d'augmenter l'Attaque de 50%.",
  "metal_sound": "Baisse la Défense Spéciale ennemie de 100%.",
  "meteor_assault": "Attaque 1.2 fois plus lentement que la normale.",
  "meteor_beam": "Attaque 1.2 fois plus lentement que la normale.",
  "metronome": "Le lanceur exécute une capacité au hasard.",
  "mimic": "Exécute la première capacité de l'adversaire avec des dégâts de base doublés.",
  "mind_blown": "Inflige des dégâts ; le lanceur perd la moitié de ses PV max (arrondi supérieur).",
  "mirror_shot": "Peut baisser la précision de la cible d'un cran.",
  "mirror_shrapnel": "Frappe 2 à 5 fois.",
  "mist_ball": "50% de chance de baisser l'Attaque Spéciale ennemie de 50%.",
  "misty_terrain": "Active un Champ Brumeux.",
  "moonblast": "10% de chance de baisser l'Attaque Spéciale ennemie de 50%.",
  "morning_sun": "Invoque le soleil et augmente l'Attaque Spéciale de 50%.",
  "mountain_gale": "Baisse la Vitesse de 50%.",
  "mud_shot": "Baisse la Vitesse ennemie de 50%.",
  "mud_slap": "Peut baisser la précision de la cible d'un cran.",
  "mud_sport": "Ajoute temporairement le type Sol à l'ennemi. Le bonus super efficace des types temporaires est réduit de moitié, et un second type temporaire remplace le premier.",
  "muddy_water": "30% de chance de baisser la Vitesse ennemie de 50%.",
  "mystical_power": "50% de chance d'augmenter l'Attaque Spéciale de 50%.",
  "nasty_plot": "Augmente l'Attaque Spéciale de 100%.",
  "needle_arm": "Peut faire trembler la cible.",
  "night_daze": "10% de chance de baisser la Vitesse ennemie de 50%.",
  "night_slash": "Taux de critique augmenté.",
  "no_retreat": "Augmente toutes les stats de 50%.",
  "noble_roar": "Baisse l'Attaque ennemie de 100% et l'Attaque Spéciale de 50%.",
  "nuzzle": "30% de chance de paralyser.",
  "ominous_wind": "10% de chance d'augmenter toutes les stats de 50%.",
  "outrage": "Rend le lanceur confus.",
  "overheat": "Baisse l'Attaque Spéciale de 50%.",
  "pay_day": "Une fois utilisée, augmente de 1% le poids des butins rares pour ce combat. Ne se cumule pas. Fonctionne toujours, pour tous.",
  "peck": "Inflige des dégâts sans effet supplémentaire.",
  "phantom_force": "Attaque 1.2 fois plus lentement que la normale.",
  "pin_missile": "Frappe 2 à 5 fois.",
  "play_nice": "Baisse l'Attaque ennemie de 50%.",
  "play_rough": "Peut baisser l'Attaque de la cible d'un cran.",
  "poison_claw": "10% de chance d'empoisonner.",
  "poison_fang": "10% de chance d'empoisonner.",
  "poison_jab": "10% de chance d'empoisonner.",
  "poison_powder": "Empoisonne.",
  "poison_sting": "30% de chance d'empoisonner.",
  "poison_tail": "20% de chance d'empoisonner.",
  "population_bomb": "Puissance de base x1.15 à chaque utilisation (max 10). Les cumuls s'annulent au changement de Pokémon.",
  "pounce": "Baisse la Vitesse ennemie de 50%.",
  "powder_snow": "10% de chance de geler.",
  "power_gem": "Inflige des dégâts sans effet supplémentaire.",
  "powerup_punch": "50% de chance d'augmenter l'Attaque de 50%.",
  "prismatic_laser": "Attaque 1.2 fois plus lentement que la normale.",
  "psybeam": "30% de chance de rendre confus.",
  "psychic": "10% de chance de baisser la Défense Spéciale ennemie de 50%.",
  "psychic_fangs": "Détruit Protection et Mur Lumière.",
  "psycho_cut": "Taux de critique augmenté.",
  "psyshield_bash": "Augmente la Défense de 50%.",
  "pursuit": "Puissance doublée contre les Pokémon qui battent en retraite, et peut les toucher.",
  "pyro_ball": "Attaque 2 fois plus vite que la normale.",
  "quick_attack": "Attaque 1.2 fois plus vite que la normale.",
  "quiver_dance": "Augmente la Défense Spéciale et l'Attaque Spéciale de 50%, et la Vitesse de 100%.",
  "rage_fist": "Puissance de base x1.2 à chaque utilisation (max 5). Les cumuls s'annulent au changement de Pokémon.",
  "rage_powder": "Rend confus, mais augmente l'Attaque Spéciale ennemie de 100%.",
  "rain_dance": "Invoque la pluie.",
  "razor_leaf": "30% de chance de baisser la Défense ennemie de 50%.",
  "razor_shell": "50% de chance de baisser la Défense ennemie de 50%.",
  "razor_talons": "Frappe 2 fois.",
  "reflect": "Invoque la Protection.",
  "relic_song": "20% de chance d'endormir.",
  "revelation_dance": "Le type change selon le premier type du lanceur.",
  "roar_of_time": "Attaque 1.2 fois plus lentement que la normale.",
  "rock_blast": "Frappe 2 à 5 fois.",
  "rock_polish": "Augmente la Vitesse de 75%.",
  "rock_slide": "Puissance x1.2 à x1.5 si la Défense/Défense Spéciale est augmentée.",
  "rock_smash": "Peut baisser la Défense de la cible d'un cran.",
  "rock_throw": "Inflige des dégâts sans effet supplémentaire.",
  "rock_tomb": "Baisse la Vitesse ennemie de 50%.",
  "rock_wrecker": "Le lanceur passe son prochain tour pour se recharger.",
  "rollout": "Puissance de base x1.2 à chaque utilisation (max 5). Les cumuls s'annulent au changement de Pokémon.",
  "rototiller": "Augmente l'Attaque et l'Attaque Spéciale de 100%.",
  "ruination": "L'attaque devient physique ou spéciale selon la meilleure stat du lanceur.",
  "sacred_fire": "Peut brûler la cible. Permet aux Pokémon gelés de dégeler.",
  "safeguard": "Invoque la Rune Protectrice.",
  "sandsear_storm": "10% de chance de brûler.",
  "sandstorm": "Invoque une tempête de sable.",
  "scald": "30% de chance de brûler.",
  "scale_shot": "Frappe 2 à 5 fois.",
  "scorching_sands": "30% de chance de brûler.",
  "screech": "Baisse la Défense ennemie de 100%.",
  "seed_bomb": "10% de chance de baisser l'Attaque ennemie de 50%.",
  "shadow_ball": "10% de chance de baisser la Défense Spéciale ennemie de 50%.",
  "shadow_claw": "Taux de critique augmenté.",
  "shadow_force": "Peut toucher quels que soient les types.",
  "shadow_punch": "Ne rate jamais.",
  "shadow_sneak": "Attaque 1.2 fois plus vite que la normale.",
  "shark_jaws": "10% de chance de baisser la Défense ennemie de 50%.",
  "shift_gear": "Augmente l'Attaque de 100% et la Vitesse de 50%.",
  "signal_beam": "30% de chance de rendre confus.",
  "silver_wind": "50% de chance de baisser la Défense Spéciale ennemie de 50%.",
  "sketch": "Exécute la première capacité. Attaque 1.5 fois plus lentement que la normale.",
  "sky_drop": "Baisse la Vitesse ennemie de 50%.",
  "sky_uppercut": "Puissance doublée si la cible est de type Vol.",
  "slash": "Taux de critique augmenté.",
  "sludge": "30% de chance d'empoisonner.",
  "sludge_bomb": "30% de chance d'empoisonner.",
  "sludge_wave": "10% de chance d'empoisonner.",
  "smack_down": "Puissance doublée si la cible est de type Vol.",
  "smart_strike": "Ne rate jamais.",
  "smelling_salts": "Puissance doublée si la cible est paralysée.",
  "smog": "30% de chance d'empoisonner.",
  "snarl": "Baisse l'Attaque Spéciale ennemie de 50%.",
  "snipe_shot": "Ignore les effets des capacités et talents adverses qui détournent les attaques : cette capacité touche sa cible.",
  "snowscape": "Invoque la grêle et augmente l'Attaque Spéciale de 50%.",
  "soak": "Ajoute temporairement le type Eau à l'ennemi. Le bonus super efficace des types temporaires est réduit de moitié, et un second type temporaire remplace le premier.",
  "solar_beam": "Attaque 1.2 fois plus lentement que la normale.",
  "solar_blade": "Attaque 1.2 fois plus lentement que la normale.",
  "spacial_rend": "Taux de critique augmenté.",
  "sparkling_aria": "Soigne les brûlures de toute l'équipe.",
  "spectral_thief": "Vole les changements de stats de l'ennemi.",
  "spirit_break": "50% de chance de baisser l'Attaque ennemie de 50%.",
  "splash": "…",
  "spore": "50% de chance d'endormir.",
  "steel_wing": "50% de chance d'augmenter la Défense de 50%.",
  "sticky_web": "Baisse la Vitesse ennemie de 50%.",
  "stomp": "Peut faire trembler la cible.",
  "stone_edge": "Taux de critique augmenté.",
  "stored_power": "Puissance de base +30 par augmentation de stat distincte du lanceur.",
  "storm_throw": "Puissance x1.2 à x1.5 si la Défense/Défense Spéciale est augmentée.",
  "strength": "Inflige des dégâts sans effet supplémentaire.",
  "string_shot": "Baisse la Vitesse ennemie de 75%.",
  "struggle_bug": "Baisse l'Attaque Spéciale ennemie de 50%. Puissance x1.2 à x1.5 si la Défense/Défense Spéciale est augmentée.",
  "stun_spore": "Paralyse.",
  "sunny_day": "Invoque le soleil.",
  "superpower": "Baisse la Défense et l'Attaque de 50%.",
  "surf": "Inflige des dégâts et peut toucher les Pokémon en Plongée.",
  "swagger": "Rend confus, mais augmente l'Attaque ennemie de 100%.",
  "sweet_kiss": "Rend confus.",
  "swift": "Attaque 1.2 fois plus vite que la normale.",
  "swords_dance": "Augmente l'Attaque de 100%.",
  "tackle": "Inflige des dégâts sans effet supplémentaire.",
  "tail_glow": "Augmente l'Attaque Spéciale de 150%. Attaque 1.5 fois plus lentement que la normale.",
  "tailwind": "Augmente la Vitesse de toute l'équipe de 50%. Attaque 1.5 fois plus lentement que la normale.",
  "teatime": "Une fois utilisée, augmente de 1% le poids des Pokémon rares pour ce combat. Ne se cumule pas. Fonctionne toujours, pour tous.",
  "thunder": "Attaque 1.2 fois plus lentement que la normale.",
  "thunder_cage": "Attaque 2 fois plus vite que la normale.",
  "thunder_fang": "10% de chance de paralyser.",
  "thunder_punch": "10% de chance de paralyser.",
  "thunder_shock": "10% de chance de paralyser.",
  "thunder_wave": "Paralyse.",
  "thunderbolt": "10% de chance de paralyser.",
  "thunderous_kick": "Baisse la Défense ennemie de 50%.",
  "torch_song": "Augmente l'Attaque Spéciale de 50%.",
  "toxic": "Empoisonne.",
  "toxic_thread": "Empoisonne et baisse la Vitesse ennemie de 50%.",
  "trailblaze": "Augmente la Vitesse de 50%.",
  "tri_attack": "10% de chance d'infliger brûlure, paralysie ou gel.",
  "trick_or_treat": "Ajoute temporairement le type Spectre à l'ennemi. Le bonus super efficace des types temporaires est réduit de moitié, et un second type temporaire remplace le premier.",
  "trick_room": "Invoque la Distorsion.",
  "triple_axel": "Puissance de base x1.3 à chaque utilisation (max 3). Les cumuls s'annulent au changement de Pokémon.",
  "triple_dive": "Frappe 3 fois.",
  "trop_kick": "Baisse l'Attaque ennemie de 50%.",
  "twin_beam": "Frappe 2 fois.",
  "twineedle": "Frappe 2 fois.",
  "twister": "Peut faire trembler la cible.",
  "u_turn": "Remplace par le membre suivant de l'équipe.",
  "v_create": "Baisse la Défense, la Défense Spéciale et la Vitesse de 50%.",
  "vacuum_wave": "Attaque 1.2 fois plus vite que la normale.",
  "venoshock": "Puissance doublée si la cible est empoisonnée.",
  "vine_whip": "Inflige des dégâts sans effet supplémentaire.",
  "volt_switch": "Remplace par le membre suivant de l'équipe.",
  "volt_tackle": "10% de chance de paralyser.",
  "water_gun": "Inflige des dégâts sans effet supplémentaire.",
  "water_pulse": "30% de chance de rendre confus.",
  "water_shuriken": "Frappe 2 à 5 fois.",
  "waterfall": "Peut faire trembler la cible.",
  "weather_ball": "Puissance doublée sous une météo, et le type change selon celle-ci (soleil = Feu, pluie = Eau, tempête de sable = Sol, grêle = Glace, brouillard = Spectre, Champ Électrifié = Électrik, Champ Herbu = Plante, Champ Brumeux = Psy).",
  "weird_room": "Invoque la Salle Étrange.",
  "whirlpool": "Frappe 2 à 5 fois.",
  "wild_charge": "Attaque 1.2 fois plus lentement que la normale.",
  "will_owisp": "Brûle.",
  "x_scissor": "Inflige des dégâts sans effet supplémentaire.",
  "zap_cannon": "Paralyse.",
  "zen_headbut": "Peut faire trembler la cible.",
  "zing_zap": "Peut faire trembler la cible."
};
