// ===== FR — UI strings =====
// Auto-extracted & grouped by domain. Edit text here, never hardcode in logic.

window.L_fr_ui = {
"debug_toggle_btn":"Debug",
"debug_x10_toggle":"Vitesse x10 :",
"debug_fill_mine":"Recharger l'énergie de mine (100)",
"debug_unlock_badges":"Débloquer 8 badges Kanto",
"debug_give_candies":"+10 Super Bonbons",
"debug_give_money":"+50 000₽",
"debug_menu_title":"Menu debug / triche",
"guide_pokedex_title":"Pokédex",
"guide_dictionary_text":"Cherche les objets, attaques et talents. Tu peux voir qui connaît une attaque, qui possède un talent et où trouver un objet.",
"guide_dictionary_title":"Dictionnaire",
"guide_training_text":"Entraîne un Pokémon pour gagner niveaux, EV, talents ou débloquer des attaques avancées.",
"guide_training_title":"Entraînement",
"guide_hatchery_text":"Dépose des Pokémon ou des fossiles. Les améliorations et automatisations se trouvent dans le menu dédié.",
"guide_hatchery_title":"Pension",
"guide_mine_text":"Creuse les cases pour révéler trésors et fossiles. La mine se régénère quand tous les objets sont récupérés.",
"guide_mine_title":"Mine",
"guide_bag_text":"Les objets sont classés par catégorie. Certains se tiennent, d’autres évoluent, se vendent ou servent aux quêtes.",
"guide_bag_title":"Sac",
"guide_pokemon_text":"La fiche Pokémon montre Base Stats, IV, EV, talents, objet tenu, attaques connues et attaques apprenables.",
"guide_pokemon_title":"Pokémon",
"guide_combat_text":"Les combats sont automatiques. Surveille les PV, les attaques qui se chargent, le butin et change de Pokémon si besoin.",
"guide_combat_title":"Combat",
"guide_map_text":"Clique sur une zone débloquée pour t’y déplacer. Les routes demandent parfois des combats, les villes importantes demandent des badges ou des quêtes.",
"guide_map_title":"Carte & progression",
"tutorial_step_badge_desc":"Progresse jusqu’à Argenta et bats Pierre.",
"tutorial_step_badge_title":"Premier badge",
"tutorial_step_dex_desc":"Ouvre le Pokédex et clique sur un Pokémon vu.",
"tutorial_step_dex_title":"Le Pokédex",
"tutorial_step_bag_desc":"Ouvre le Sac depuis les raccourcis pour voir tes objets.",
"tutorial_step_bag_title":"Le sac",
"tutorial_step_sheet_desc":"Ouvre une fiche Pokémon pour voir stats, IV, EV, talents et attaques.",
"tutorial_step_sheet_title":"Fiche Pokémon",
"tutorial_step_route1_desc":"Va sur la Route 1 et gagne 3 combats sauvages pour apprendre le rythme du jeu.",
"tutorial_step_route1_title":"Premiers combats",
"guide_intro":"Guide rapide pour comprendre PokéWorld sans interrompre le jeu.",
"tutorial_progress":"tutoriel",
"tutorial_complete_desc":"Tu connais les bases. Le guide reste disponible dans les raccourcis.",
"tutorial_complete_title":"Tutoriel terminé",
"tutorial_enable":"Activer les tutos",
"tutorial_disable_all":"Désactiver",
"tutorial_enabled":"Tutoriels activés",
"tutorial_disabled":"Tutoriels désactivés",
"guide_title":"Guide",
"route_events_placeholder_title":"Événements de route",
"route_events_placeholder_desc":"Le système d’événements de route est prêt. Les événements dynamiques seront ajoutés dans une phase ultérieure.",
"dict_abilities":"Talents",
"dict_moves":"Attaques",
"dict_items":"Objets",
"dict_search_placeholder":"Rechercher...",
"dict_no_results":"Aucun résultat.",
"dict_owned_qty":"Possédé ×{count}",
"dict_not_owned":"Non possédé",
"dict_main_quest":"Quête principale",
"dict_side_quest":"Quête secondaire",
"dict_repeatable_quest":"Quête répétable",
"dict_unknown_source":"Obtention non renseignée",
"dict_rarity":"Rareté",
"dict_affected_pokemon":"Pokémon concernés",
"dict_no_pokemon_listed":"Aucun Pokémon listé.",
"dict_move_users":"{count} Pokémon connaissent cette attaque",
"dict_move_users_none":"Aucun Pokémon ne connaît cette attaque",
"dict_ability_unlocked":"Débloqué",
"dict_ability_locked":"Non débloqué",
"dict_ability_carriers":"{count} porteur(s)",
"dict_where_find":"Où le trouver",
"dict_base_stats":"Stats de base",
"dict_description_unavailable":"Description indisponible pour le moment.",
"dict_no_moves_listed":"Aucune attaque renseignée.",
"dict_no_abilities_listed":"Aucun talent renseigné.",
"evolutions_title":"Évolutions",
"dictionary_title":"Dictionnaire",
"add_to_team_btn":"Ajouter à l'équipe",
"box_header":"Pokémon en boîte",
"box_pc_note":"Ce Pokémon est dans votre boîte PC. Placez-le dans votre équipe pour l'entraîner ou lui équiper des objets !",
"box_swap_header":"Échange : choisissez un Pokémon de la boîte pour remplacer",
"buy_btn":"Acheter",
"quest_challenge_btn":"Défier !",
"challenge_btn":"Défier",
"arena_challenge_label":"Arène — Défier {champion}",
"arena_rematch_label":"Arène — Revanche {champion}",
"arena_locked_label":"Arène — {champion} ({badges} badges requis)",
"league_challenge_label":"Ligue — Défier {champion}",
"league_rematch_label":"Ligue — Revanche {champion}",
"league_locked_label":"Ligue — {champion} ({badges} badges requis)",
"choose_starter":"Choisir votre Starter",
"cols3":"3 Colonnes",
"defeated_lbl":"vaincu",
"drop_items_lbl":"Objets trouvables :",
"eq_sub":"Gestion d'équipement",
"equip_btn":"Équiper",
"equipped_lbl":"Équipé sur :",
"evo_title":"Méthode d'évolution :",
"evolve_btn":"Évoluer !",
"explore_btn":"Explorer",
"explore_routes":"Explorer les routes",
"fiche_btn":"Fiche",
"finish_btn":"Terminer",
"forget_btn":"Oublier",
"forget_first":"(oubliez-en une d'abord)",
"full_btn":"Plein",
"idle_desc":"Déplacez-vous sur une route de la carte à gauche et cliquez sur <b> Explorer</b> ou <b> Défier</b> pour lancer un combat en temps réel au centre de l'écran !",
"idle_title":"Exploration au repos",
"inv_desc_sub":"Sélectionnez un objet pour l'utiliser ou l'équiper.",
"inv_sub":"Cliquez sur un objet pour l'utiliser, le revendre ou l'équiper sur un Pokémon.",
"lang_title":"Langue / Language",
"learn_btn":"Apprendre",
"learnable_moves":"Capacités apprenables",
"loot_btn":"Résumé",
"loot_continue_btn":"Continuer sur la route",
"loot_restart_btn":"Relancer le combat immédiatement",
"loot_summary_title":"Butin de la session",
"battle_session_summary_title":"Butin & résumé de session", 
"battle_team_damage_title":"Dégâts de l’équipe", 
"loot_title":"Butin de la session",
"lvl_lbl":"Nv.",
"market_sub":"Achetez des Pokémon introuvables dans la nature !",
"market_title":"PokéMarket",
"mine_sub":"Creusez les couches rocheuses pour déterrer des <b>Pierres d'Évolution</b>, Pépites et Fossiles !",
"mine_title":"Grand Souterrain (Mines de Kanto)",
"modify_btn":"Modifier",
"moves_lbl":"Capacités :",
"no_item":"Aucun objet",
"no_more_moves":"Aucune autre capacité disponible.",
"owned_btn":"Possédé",
"rarity_com":"● Commun (~75%)",
"rarity_rare":"Rare (~4%)",
"rarity_uncom":"Peu commun (~20%)",
"rematch_btn":"Revanche",
"req_lbl":"requis",
"shop_sub":"Sac plafonné à 25 exemplaires par objet.",
"skin_shiny_lbl":"Skin Shiny",
"skin_shiny_sub":"Bascule d'apparence uniquement",
"starter_choose_sub":"Ce Pokémon vous accompagnera tout au long de votre aventure.",
"starter_choose_title":"Choisissez votre Starter !",
"stone_evo_title":"Évolution par pierre",
"stone_sub":"Sélectionnez un Pokémon pour utiliser cette pierre.",
"swap_btn":"Échanger",
"swap_with_btn":"Échanger avec",
"tab_box":"Boîte",
"tab_dex":"Pokédex",
"tab_fossil":"Fossiles",
"tab_info":"Lieu",
"tab_inv":"Sac",
"tab_market":"Marché",
"tab_mine":"Mine",
"tab_shop":"Boutique",
"team_btn":"Équipe",
"team_empty":"Aucun Pokémon dans l'équipe !",
"to_box_btn":"Retirer (→ boîte)",
"typ_dungeon":"Grotte / Donjon",
"typ_route":"Route",
"typ_sea":"Chenal maritime",
"typ_town":"Ville",
"wild_poke":"Pokémon sauvages",
"win_battle":"Combat en direct (PokéChill)",
"win_map":"Carte Kanto",
"win_tabs":"Lieu",
"win_team":"Équipe Active",
"xp_lbl":"XP:",
"lang_switched_fr":"Langue changée en Français !",
"lang_switched_en":"Langue changée en Anglais !",
"save_incompatible_deleted":"Sauvegarde incompatible supprimée automatiquement.",
"level_abbrev":"Nv.",
"stat_hp_short":"PV",
"click_replace_context_info":"Clic pour sélectionner (remplacement) | Clic droit ou appui long pour info",
"replacement_badge":"⬇ Remplacement",
"power_abbrev":"Puiss :",
"learnable_moves_title":"Capacités Apprenables",
"click_to_replace_selected":"← Clic pour remplacer",
"select_move_first":"(4/4 — sélectionnez une attaque ci-dessus)",
"context_info_touch":"Clic droit ou appui long pour info",
"no_other_moves":"Aucune autre capacité disponible.",
"level_word":"Niveau",
"pc_box":"Boîte PC",
"shiny_skin":"Skin Shiny",
"cosmetic_switch_only":"Bascule d'apparence",
"moves_title":"Capacités",
"cancel":"Annuler",
"stone_evolution":"Évolution par pierre",
"team_full_title":"Équipe pleine (6/6)",
"add_to_team":"Ajouter à l'équipe",
"remove_from_team":"Retirer de l'équipe",
"swap_with":"Échanger avec {name}",
"the_team":"l'équipe",
"evolution_stone_notify":" {from} évolue en {to} grâce à {item} !",
"welcome_johto":"Bienvenue dans la région de Johto — Bourg Geon !",
"arrived_kanto_harbor":"Arrivée au port de Carmin sur Mer dans la région de Kanto !",
"map_title_prefix":"Carte : ",
"roaming_legendary_appeared":" UN LÉGENDAIRE ERRANT APPARAÎT : {name} !",
"no_pokemon_in_team":" Vous n'avez pas de Pokémon !",
"no_wild_pokemon_here":"Aucun Pokémon sauvage ici.",
"team_healed_center":"Équipe soignée au Centre Pokémon !",
"all_pokemon_healed":" Tous vos Pokémon ont été soignés !",
"pokemon_already_healthy":"Vos Pokémon sont déjà en pleine forme !",
"fullscreen_pc_box":"Agrandir la Boîte",
"action_blocked_in_battle":"Action impossible en combat : quittez le combat d'abord !",
"team_already_full":" Votre équipe est déjà pleine (6/6). Retirez un Pokémon d'abord.",
"species_already_in_team":" Espèce déjà dans l'équipe.",
"species_already_in_team_present":" Espèce déjà présente dans l'équipe.",
"box_conflict":" Conflit boîte.",
"joined_team":"{name} rejoint votre équipe !",
"sent_to_box":"{name} est envoyé dans la boîte.",
"must_keep_one_pokemon":" Vous devez garder au moins un Pokémon dans l'équipe.",
"species_already_in_box":" Cette espèce est déjà dans la boîte.",
"presets_label":"Presets :",
"save_short":"Sauver",
"remove":"Retirer",
"equipped_item_label":"Objet équipé",
"none":"Aucun",
"no_equippable_item":"Aucun objet équipable",
"holding_item":"{name} tient {item} !",
"holding_nothing":"{name} ne tient plus rien.",
"item_removed_from":"{item} retiré de {name}.",
"load_preset_title":"Charger {name}",
"save_current_team_title":"Sauvegarder l'équipe actuelle",
"pokemon_talents":"Talents du Pokémon",
"locked_talent_hint":"Verrouillé : capturer/entraîner pour débloquer",
"item_power":"Puissance :",
"no_item_equipped_bag":"Aucun objet équipé. Choisissez-en un depuis l'onglet Sac.",
"cosmetic_switch_only_team":"Bascule d'apparence uniquement",
"sail_to_johto":"Prendre le bateau vers Johto",
"sail_to_kanto":"Prendre le bateau vers Kanto",
"locked":"Verrouillé",
"next_zone":"la prochaine zone",
"battles":"combats",
"to_unlock":"avant le déblocage de",
"roaming_legendary_rotation":"Légendaire errant (rotation 12h) :",
"can_appear_here":"peut apparaître ici !",
"roaming_short":"Errant (1%)",
"map_title_name":"Carte {region}",
"requires_badges":"nécessite {need} badge(s) (vous en avez {have})",
"win_wild_battles_req":"remporte {need} combats sauvages à {location} (tu en as {have})",
"locked_by_story":"verrouillé par l'histoire — {current}/{required}",
"choose_kanto_starter_first":"Choisissez d'abord votre starter Kanto à Bourg Palette.",
"choose_johto_starter_first":"Choisissez d'abord votre starter Johto à Bourg Geon.",
"need_badges_access":"Il vous faut {need} badge(s) pour accéder à {location} (vous en avez {have}).",
"story_not_reached":"L'histoire n'a pas encore débloqué {location}. (Progression {current}/{required})",
"win_battles_to_unlock":"Remporte {need} combats sauvages à {from} pour débloquer {to} (tu en as {have}).",
"location_not_reachable":"{location} n'est pas encore accessible.",
"teleported_to":" Vous vous téléportez à {location}.",
"panel_inventory_title":"Sac",
"panel_shop_title":"Boutique",
"panel_market_title":"Poké Marché",
"panel_pokedex_title":"Pokédex",
"shortcut_pc_box":"Boîte PC",
"shortcut_bag":"Sac",
"shortcut_market":"Marché",
"starter_johto_chikorita_desc":"Plante - Calme et robuste",
"starter_johto_cyndaquil_desc":"Feu - Rapide et explosif",
"starter_johto_totodile_desc":"Eau - Mâchoires puissantes",
"starter_kanto_bulbasaur_desc":"Plante/Poison - Solide défensivement",
"starter_kanto_charmander_desc":"Feu - Puissance offensive élevée",
"starter_kanto_squirtle_desc":"Eau - Grande endurance",
"starter_welcome_johto":"Bienvenue à Johto ! Le Prof. Orme vous attend à Bourg Geon.",
"starter_welcome_kanto":"Bienvenue à Kanto ! Le Prof. Chen vous attend à Bourg Palette.",
"starter_title_johto":"Choisissez votre Starter Johto !",
"starter_title_kanto":"Choisissez votre Starter !",
"starter_subtitle":"Ce Pokémon vous accompagnera tout au long de votre aventure dans cette région.",
"choose":"Choisir",
"starter_required":"Vous devez choisir un starter pour continuer. Cette fenêtre ne peut pas être fermée.",
"partner_now":"{name} est maintenant votre partenaire !",
"shiny_form_unlocked":" Forme Shiny débloquée/possédée !",
"level_up_moves":"Capacités par niveau",
"close":"Fermer",
"move_cat_physical":"Physique",
"move_cat_special":"Spéciale",
"move_cat_status":"Statut",
"accuracy":"Précision",
"effects":"Effets",
"no_special_effects":"Aucun effet spécial",
"back_to_pokemon":"Retour au Pokémon",
"effect_burn_stat":"Brûle ({pct}%) — 3 tours de dégâts",
"effect_para_stat":"Paralyse ({pct}%) — 2 tours",
"effect_poison_stat":"Empoisonne ({pct}%) — 3 tours de dégâts",
"effect_badpoison_stat":"Empoisonne gravement ({pct}%) — Persistant, dégâts croissants",
"effect_sleep_stat":"Endort ({pct}%) — 1 à 3 tours",
"effect_freeze_stat":"Gèle ({pct}%) — 3 tours max",
"effect_slow_stat":"Baisse la Vitesse ({pct}%)",
"effect_burn_chance":"{pct}% de brûler — 3 tours de dégâts",
"effect_para_chance":"{pct}% de paralyser — 2 tours",
"effect_poison_chance":"{pct}% d'empoisonner — 3 tours de dégâts",
"effect_freeze_chance":"{pct}% de geler — 3 tours max",
"effect_sleep_chance":"{pct}% d'endormir — 1 à 3 tours",
"effect_slow_chance":"{pct}% de baisser la Vitesse",
"effect_confuse_chance":"{pct}% de rendre confus",
"effect_flinch_chance":"{pct}% de faire hésiter",
"effect_crit":"Taux de critique élevé (×1.5 dégâts)",
"effect_recoil":"Dégâts de recul: 25% des dégâts infligés",
"effect_recharge":"Doit recharger au tour suivant",
"effect_trap":"Piège l'adversaire pendant 4-5 tours",
"effect_drain":"Absorbe 50% des dégâts en PV",
"effect_charge":"Charge au 1er tour, attaque au 2nd",
"effect_heal":"Soigne {pct}% PV",
"effect_priority":"Priorité +{prio} (attaque en premier)",
"effect_fixed":"Dégâts fixes: {damage} PV",
"sort_name":"Nom",
"sort_quantity":"Quantité",
"sort_category":"Catégorie",
"filter_label":"Filtre:",
"sort_label":"Tri:",
"mine_locked_badges":"Mine verrouillée (2 Badges requis)",
"pokedex_seen":"Vus",
"pokedex_caught":"Capturés",
"pokedex_shiny":"Shiny",
"pokedex_moves":"Capacités",
"wild_legendary_appeared":"LÉGENDAIRE SAUVAGE : {name} (Nv.65) apparaît ! Vainquez-le pour le capturer !",
"item_found_log":"{icon} Objet trouvé : {item} !",
"money_won_log":"Vous gagnez {money}₽ !",
"capture_title":"Capture !",
"training_complete":" Entraînement réussi !{reward}",
"legendary_boss_defeated":" Vous avez vaincu le Boss Légendaire {pokemon} !",
"boss_captured":" Boss vaincu ! {pokemon}{shiny} capturé !",
"continue":"Continuer",
"held_effect_max":"Effet équipé (à 25/25)",
"item_type_stone":" Pierre d'évolution",
"item_type_treasure":" Trésor",
"item_type_candy":" Bonbon",
"item_type_special":" Spécial",
"item_type_key":"Objet clé",
"item_type_held":" Objet équipé",
"item_type_berry":"Baie",
"description":"Description",
"price":"Prix",
"owned":"Possédé",
"money":"Argent",
"bought":"Acheté",
"stock":"Stock",
"indigo_shop_locked_title":"Boutique du Plateau Indigo Verrouillée",
"indigo_shop_locked_desc":"Cette boutique d'élite est réservée exclusivement aux Maîtres de la Ligue Kanto.",
"bag_full_for":"Sac plein pour {item} (max {max}).",
"item_bought":"{item} acheté !",
"sent_to_box_price":"{name} envoyé dans la boîte ! (-{price}₽)",
"joined_team_price":"{name} rejoint votre équipe ! (-{price}₽)",
"hatchery_locked_title":"Pension & Couveuse verrouillées",
"hatchery_locked_desc":"Battez Ondine à Azuria (2 Badges) pour débloquer la pension de la Route 5 !",
"hatchery_place_slot":"Slot #{slot} : Déposer un Pokémon",
"ready":"Prêt !",
"incubating":"Incubation : {steps} / {required} KO",
"hatch":"Éclore",
"hatchery_upgrade_slot":"Améliorer Pension : +1 Slot ({cost}₽)",
"fossil_lab":"Laboratoire Fossile",
"fossil_lab_desc":"Ranimez les Pokémon préhistoriques trouvés dans la Mine Souterraine, façon PokéClicker !",
"no_fossils_yet":"Aucun fossile",
"fossil_mine_hint":"Creusez dans la Mine Souterraine pour trouver des fossiles Nautile, Dôme et Vieil Ambre !",
"go_to_mine":"Aller à la Mine",
"quantity_abbrev":"Qté",
"revives_into":"Ranime en",
"revive":"Ranimer !",
"fossil_lab_tip":"<b>Style PokéClicker :</b> les fossiles se trouvent en minant. Chaque fossile ranime instantanément son Pokémon préhistorique (Nv.1). Les Shiny sont possibles !",
"hatchery_upgraded":" Pension améliorée ! Vous avez maintenant {slots} slots d'œufs !",
"iv_money_bonus":" (+5 000₽ bonus IV max)",
"no_fossil_left":"Plus de fossile !",
"unknown_fossil":"Fossile inconnu.",
"fossil_revived_party":"{name} ranimé ! Il rejoint votre équipe !",
"fossil_revived_box":"{name} ranimé ! Envoyé au PC.",
"box_label":"Boîte",
"fossils":"Fossiles",
"no_pokemon_found":"Aucun Pokémon trouvé.",
"select_or_details_hint":"Clic: Sélectionner | Clic Droit: Fiche",
"fossil_selector_hint":"Sélectionnez un fossile pour l'envoyer à la Pension.",
"incubate":"Incuber",
"ko_unit":"KO",
"hatchery_full":"Couveuse pleine !",
"fossil_sent_hatchery":"{item} envoyé à la Pension !",
"dig_mine_fossils":"Creusez dans la Mine Souterraine pour trouver des fossiles !",
"preset_adventure":"Équipe Aventure",
"preset_boss":"Équipe Boss",
"preset_training":"Équipe Entraînement",
"preset_saved":" {name} sauvegardée ({count} Pokémon) !",
"cannot_change_team_battle":"Impossible de changer d'équipe de combat pendant un affrontement !",
"preset_empty":"Ce preset d'équipe est vide ! Mettez des Pokémon en équipe et cliquez sur Sauvegarder.",
"preset_pokemon_not_found":"Aucun Pokémon du preset n'a été trouvé !",
"preset_loaded":" {name} chargée avec succès ({count} Pokémon) !",
"no_pokemon_yet":"Vous n'avez pas encore de Pokémon !",
"choose_starter_bang":"Choisir votre Starter !",
"explore_to_catch":"Explorez les routes pour en capturer.",
"live_battle_lock_team":"Combat en direct en cours :",
"team_locked_battle_long":"L'équipe active est verrouillée. Vous ne pouvez ni échanger, ni réordonner, ni modifier le stuff pendant le combat.",
"cannot_swap_team_battle":"Action impossible : impossible d'échanger l'équipe en plein combat.",
"cannot_during_battle":"Impossible pendant un combat !",
"cannot_remove_only_pokemon":"Impossible de retirer votre seul Pokémon !",
"removed_to_pc":"{name} retiré de l'équipe et placé dans la boîte PC.",
"swap_cancelled":"Échange annulé.",
"box_pokemon_not_found":"Pokémon introuvable dans la boîte !",
"team_pokemon_not_found":"Pokémon d'équipe introuvable !",
"pokemon_swapped":"{a} et {b} ont été échangés !",
"team_full_short":"Équipe pleine ! (6/6)",
"pokemon_not_found":"Pokémon introuvable !",
"added_to_team":"{name} ajouté à l'équipe !",
"selected_pokemon":"Sélectionné: {name} (Nv.{level})",
"team_full_select_replace":"Équipe pleine ! (6/6) - Sélectionnez d'abord un Pokémon de l'équipe à remplacer.",
"already_in_team":"Ce Pokémon est déjà dans l'équipe !",
"selected_for_training":"{name} sélectionné pour l'entraînement !",
"cannot_deposit_only_pokemon":"Impossible de déposer votre seul Pokémon !",
"deposited_hatchery":"{name} déposé à la pension !",
"no_active_pokemon":"Aucun Pokémon actif.",
"team_location":" Équipe",
"box_location":" Boîte",
"easy_minus_two":"Facile : -2 Nv.",
"easy_minus_one":"Facile : -1 Nv.",
"medium_plus_two":"Moyen : +2 Nv.",
"medium_plus_three":"Moyen : +3 Nv.",
"talent_system_unavailable":"Système de talents non disponible",
"no_talent_species":"Aucun talent disponible pour cette espèce",
"no_compatible_talent":"Aucun talent compatible trouvé",
"all_talents_unlocked":"Tous les talents sont débloqués ! L'entraînement peut encore re-roller.",
"holo_ditto":"Holo-Métamorph",
"holo_porygon":"Holo-Porygon",
"punching_bag":"Sac de Frappe",
"training_room_battle_start":" SALLE D'ENTRAÎNEMENT ({mode}) - Round 1/6 : {pokemon} Nv.{level} !",
"switch_pending":"{name} entrera en jeu dès que possible...",
"solo_training_no_switch":"Switch impossible : votre Pokémon s'entraîne en solo au Dojo !",
"shiny_captured":" POKÉMON SHINY CAPTURÉ ! ",
"hidden_talent_unlocked_reward":" (Talent Caché débloqué !)",
"league_master_victory_log":" Vous avez vaincu le Maître Kanto et triomphé des 5 combats de la Ligue !",
"league_master_title_reward":" Félicitations ! Vous obtenez le Titre de Maître Pokémon ! (+{money}₽)",
"rematch_won_reward":" Revanche remportée contre {champion} ! (+{money}₽)",
"league_victory_message":" Félicitations ! Vous avez triomphé des 5 combats de la Ligue Kanto et obtenez le Titre de Maître Pokémon !",
"add_pokemon":"Ajouter un Pokémon",
"team_count":"{count}/6 dans l'équipe",
"item_removed_team":"{item} retiré de l'équipe.",
"evolution_duplicate_bonus":" {name} aurait évolué en {target}, déjà possédé ! (+{money}₽)",
"evolution_duplicate_bonus_html":" {name} aurait évolué en <b>{target}</b>, déjà possédé ! (+{money}₽)",
"evolution_triggered_box":" {name} déclenche une évolution : {target} apparaît dans la boîte PC !",
"evolution_created_box":" Une évolution de {name} est née : <b>{target}</b> (Nv.1, → boîte) !",
"captured_pokemon_title":"Pokémon capturés :",
"found_items_title":"Objets trouvés :",
"map_help_title_attr":"Aide — code couleur de la carte",
"map_help_title":"Code couleur de la carte",
"map_help_green":"<b>Vert</b> — Une quête (principale ou secondaire) est à faire ici.",
"map_help_purple":"<b>Violet</b> — Un Pokémon légendaire errant est présent (non capturé).",
"map_help_blue":"<b>Bleu</b> — Des Pokémon sont encore à capturer.",
"map_help_yellow":"<b>Jaune</b> — Un shiny est encore à capturer.",
"map_help_gray":"<b>Gris</b> — Zone verrouillée (badge ou histoire manquant).",
"map_help_transparent":"<b>Transparent</b> — Zone terminée (tout est capturé).",
"no_save_found":"Aucune sauvegarde trouvée",
"game_loaded":"Partie chargée !",
"no_save_to_export":"Aucune sauvegarde à exporter",
"save_exported":"Sauvegarde exportée !",
"save_imported_reload":"Sauvegarde importée ! Rechargement...",
"save_deleted":"Sauvegarde supprimée",
"debug_x10_on":"Vitesse x10 activée",
"debug_x10_off":"Vitesse x10 désactivée",
"mine_found":"Trouvé : {item} !",
"mine_battle_log":"Souterrain : vous avez déterré {icon} <b>{item}</b> !",
"legacy_message_n_10_super_bonbons_ajout_s":"+10 Super Bonbons ajoutés !",
"legacy_message_n_50_000_ajout_s":"+50 000₽ ajoutés !",
"legacy_message_n_8_badges_d_bloqu_s":"8 Badges débloqués !",
"legacy_message_n_aucun_pok_mon_entra_ner":"Aucun Pokémon à entraîner !",
"legacy_message_n_capacit_s_pleines_4_oubliezen_une_dabord":"Capacités pleines (4). Oubliez-en une d'abord.",
"legacy_message_n_ce_pok_mon_conna_t_ou_a_d_j_d_bloqu_to":"Ce Pokémon connaît ou a déjà débloqué toutes les capacités disponibles pour son espèce !",
"legacy_message_n_ce_pok_mon_est_d_j_au_niveau_100_maximu":"Ce Pokémon est déjà au Niveau 100 maximum !",
"legacy_message_n_ce_pok_mon_poss_de_d_j_6_toiles_ev_sur":"Ce Pokémon possède déjà 6 étoiles EV sur toutes ses statistiques (36/66) !",
"legacy_message_n_erreur_lors_de_la_cr_ation_du_pok_mon":"Erreur lors de la création du Pokémon.",
"legacy_message_n_objectif_pas_encore_termin":"Objectif pas encore terminé !",
"legacy_message_n_partie_sauvegard_e":"Partie sauvegardée !",
"legacy_message_n_qu_te_d_j_active":"Quête déjà active.",
"legacy_message_n_qu_te_d_j_termin_e":"Quête déjà terminée.",
"legacy_message_n_qu_te_r_p_table_d_j_active":"Quête répétable déjà active.",
"legacy_message_n_sauvegarde_import_e":"Sauvegarde importée !",
"legacy_message_n_un_pok_mon_doit_conserver_au_moins_une_c":"Un Pokémon doit conserver au moins une capacité.",
"legacy_message_n_vous_poss_dez_d_j_cette_esp_ce":"Vous possédez déjà cette espèce !",
"legacy_message_n_nergie_de_mine_restaur_e_100":"Énergie de mine restaurée à 100 !",
"legacy_message_n_nergie_insuffisante_combattez_des_pok_m":"Énergie insuffisante ! Combattez des Pokémon sauvages pour recharger.",
"legacy_message_n2_cet_objet_na_aucun_effet_sur_ce_pok_mon":"Cet objet n'a aucun effet sur ce Pokémon.",
"woke_up_log":"{name} se réveille !",
"sleeping_turns_log":"{name} est endormi... ({turns} tour{plural})",
"thawed_log":"{name} se décongèle !",
"frozen_skip_log":"{name} est gelé...",
"paralyzed_skip_log":"{name} est paralysé et ne peut pas attaquer !",
"uses_move_log":"{name} utilise <b>{move}</b> !",
"forfeit_champion":"Vous abandonnez le combat contre {champion}. Vous pourrez le redéfier à tout moment.",
"leave_battle_notify":"Vous quittez le combat.",
"leaving_button":"Départ...",
"map_legend_title":"Légende de la carte",
"current_location":"Lieu actuel",
"reachable_location":"Lieu accessible",
"locked_location":"Lieu verrouillé",
"selector_title_hatchery":"Pension & Couveuse",
"selector_title_hatchery_queue":"Ajouter à la liste Pension",
"selector_title_training_queue":"Ajouter à la liste Entraînement — slot {slot}",
"selector_title_training":"Salle d'Entraînement",
"selector_title_team":"Sélection Équipe",
"selector_title_box":"Boîte PC",
"selector_title_item_use":"Utiliser un objet",
"equip_click_title":"Clic: équiper",
"sprite_click_context_title":"Clic gauche: équipe | Clic droit: infos",
"team_location_clean":"Équipe",
"box_pc_location":"Boîte PC",
"change_or_info_title":"Clic: changer | Clic droit: infos",
"sprite_team_info_title":"Clic gauche: équipe | Clic droit: infos",
"rarity_common_label":"Commun",
"rarity_uncommon_label":"Peu commun",
"rarity_rare_label":"Rare",
"rarity_unknown_label":"Inconnu",
"shop_default_name":"Boutique",
"battle_in_progress":"Combat en cours",
"battle_in_progress_no_training":"Combat en cours : impossible de lancer un entraînement.",
"training_in_progress_no_battle":"Entraînement en cours : impossible de lancer un autre combat.",
"management_trainers":"Entraîneurs",
"hatchery_trainers_soon":"Les trainers de pension arrivent bientôt dans une prochaine mise à jour de la pension.",
"training_trainers_soon":"Les trainers d’entraînement arrivent bientôt dans une prochaine mise à jour de l’entraînement.",
"select_or_details_hint":"Clic: Sélectionner | Clic Droit: Fiche",
"context_info_touch":"Clic droit ou appui long pour info",
"save_menu_title":"PokéWorld",
"save_menu_subtitle":"Choisis une sauvegarde ou crée une nouvelle aventure.",
"save_menu_empty_title":"Aucune sauvegarde trouvée",
"save_menu_empty_desc":"Crée une nouvelle sauvegarde ou importe un fichier pour l’ajouter à la liste.",
"save_menu_new":"Nouvelle partie",
"save_menu_import":"Importer",
"save_menu_click_hint":"Cliquer pour lancer",
"save_menu_badges":"Badges",
"save_menu_pokedex":"Pokédex",
"save_menu_playtime":"Temps",
"save_menu_id":"ID",
"save_default_name":"Sauvegarde {num}",
"save_imported_name":"Sauvegarde importée",
"save_created":"Nouvelle sauvegarde créée !",
"save_imported_library":"Sauvegarde ajoutée à la liste !",
"save_profile_title":"Profil de la sauvegarde",
"save_profile_name":"Nom de la sauvegarde",
"save_profile_color":"Couleur de la carte",
"save_profile_background":"Fond de la carte",
"save_profile_apply":"Appliquer au menu des saves",
"save_profile_updated":"Profil de sauvegarde mis à jour !",
"save_profile_name_placeholder":"Nom de la save",
"save_color_blue":"Bleu",
"save_color_red":"Rouge",
"save_color_green":"Vert",
"save_color_purple":"Violet",
"save_color_gold":"Or",
"save_color_silver":"Argent",
"save_bg_classic":"Kanto — Rouge / Bleu",
"save_bg_goldsilver":"Johto — Or / Argent",
"save_bg_emerald":"Hoenn — Émeraude",
"save_bg_diamondpearl":"Sinnoh — Diamant / Perle",
"save_bg_blackwhite":"Unys — Noir / Blanc",
"save_bg_xy":"Kalos — X / Y",
"save_bg_forest":"Forêt animée",
"save_error_too_large":"Erreur : sauvegarde trop volumineuse",
"save_error_message":"Erreur lors de la sauvegarde : {message}",
"load_error_message":"Erreur lors du chargement : {message}",
"save_export_error":"Erreur lors de l’export",
"save_import_error":"Erreur lors de l’import : {message}",
"save_delete_error":"Erreur lors de la suppression",
"save_profile_icon":"Icône de la save (Pokémon en boîte PC)",
"save_icon_keep_current":"Garder l’icône actuelle",
"save_icon_no_box":"Aucun Pokémon en boîte PC disponible",
"save_need_starter":"Choisissez un starter avant de sauvegarder.",
"save_choose_starter_first":"Choisissez votre starter : la save sera créée juste après.",
"save_profile_choose_icon":"Choisir dans la boîte PC",
"save_profile_current_icon":"Icône actuelle",
"save_context_download":"Télécharger",
"save_context_import_overwrite":"Importer (écraser)",
"save_context_delete":"Supprimer",
"save_delete_confirm":"Supprimer définitivement cette sauvegarde ?",
"save_overwritten":"Sauvegarde écrasée !",
"afk_progress_summary":"AFK {time} : {wins} combats gagnés, {fainted} Pokémon K.O., +{money}₽.",
"afk_battle_log_summary":"⏱ AFK {time} : {wins} Pokémon sauvages vaincus, {fainted} Pokémon K.O. (+{money}₽).",
"afk_energy_summary":"AFK {time} : énergie de mine récupérée.",
"debug_timeskip_10m":"⏱ Timeskip AFK +10 min",
"debug_timeskip_unavailable":"Timeskip AFK indisponible.",
"afk_progress_lost_summary":"AFK {time} : perdu, toute l’équipe est K.O. ({wins} combats gagnés, +{money}₽).",
"afk_battle_log_lost_summary":"⏱ AFK {time} : perdu, toute l’équipe est K.O. après {wins} combats gagnés (+{money}₽).",
"afk_no_progress_summary":"AFK {time} : aucune zone sauvage active à simuler.",
"afk_party_ko_log":"⏱ AFK : votre équipe est K.O., la simulation s’arrête.",
"afk_error_resume":"Erreur pendant la simulation AFK : combat relancé.",
"afk_panel_title_return":"Retour AFK",
"afk_panel_title_debug":"Timeskip debug",
"afk_panel_status_ok":"Progression simulée avec succès.",
"afk_panel_status_lost":"Perdu : toute l’équipe est K.O.",
"afk_panel_status_empty":"Aucune ressource gagnée pendant cette période.",
"afk_panel_status_error":"Erreur pendant la simulation AFK.",
"afk_panel_duration":"Durée",
"afk_panel_battles":"Combats",
"afk_panel_money":"Argent",
"afk_panel_captures":"Captures",
"afk_panel_energy":"Énergie mine",
"afk_panel_items":"Objets gagnés",
"afk_none":"Aucun",
"afk_panel_team_ko":"Pokémon K.O.",
"team_slot_name":"Slot équipe {slot}",
"afk_captures_normal":"Normaux",
"afk_captures_shiny":"Shiny",
"duplicate_short":"doublon(s)",
"region_kanto":"Kanto",
"region_johto":"Johto",
"region_hoenn":"Hoenn",
"region_sinnoh":"Sinnoh",
"region_locked_league":"Accès à {target} verrouillé : bats d’abord la Ligue de {region}.",
"region_locked_dex":"Accès à {target} verrouillé : complète d’abord le Pokédex de {region} ({caught}/{total}).",
"region_locked_generic":"Accès à {target} verrouillé.",
"region_team_restricted":"À {region}, avant de battre la Ligue locale, seuls les Pokémon de {region} peuvent combattre. À retirer : {pokemon}.",
"league_battle_challenge_region":"LIGUE {region} - Combat 1/5 : {trainer} vous défie !",
"league_master_victory_log_region":"Vous avez vaincu le Maître de {region} et triomphé des 5 combats de la Ligue !",
"league_master_title_reward_region":"Félicitations ! Vous obtenez le Titre de Maître {region} ! (+{money}₽)",
"league_victory_message_region":"Félicitations ! Vous avez triomphé des 5 combats de la Ligue {region} !",
"league_next_battle_region":"LIGUE {region} - Combat {stage}/5 : {trainer} envoie {pokemon} !",
"pokedex_regions":"Régions visibles",
"box_filter_region":"Région",
"box_filter_type":"Type",
"box_filter_shiny":"Shiny",
"box_filter_evolution":"Évolution",
"box_filter_all_regions":"Toutes",
"box_filter_all_types":"Tous",
"box_filter_all_shiny":"Tous",
"box_filter_shiny_only":"Shiny",
"box_filter_non_shiny_only":"Non shiny",
"box_filter_all_evo":"Toutes",
"box_filter_evo_missing":"Évolution possible non obtenue",
"box_filter_reset":"Réinitialiser",
"box_filter_favorite":"Favori",
"box_filter_all_favorites":"Tous",
"box_filter_favorite_only":"Favoris",
"box_filter_not_favorite":"Non favoris",
"box_filter_locked":"Verrouillage",
"box_filter_all_locked":"Tous",
"box_filter_locked_only":"Verrouillés",
"box_filter_unlocked_only":"Non verrouillés",
"box_filter_iv":"IV",
"box_filter_ev":"EV",
"box_filter_rank":"Rang",
"box_filter_all_ranks":"Tous",
"box_filter_all_ev":"Tous",
"box_filter_ev_complete":"EV complets",
"box_filter_ev_incomplete":"EV incomplets",
"auto_sort_ev_asc":"EV les plus bas",
"auto_sort_ev_desc":"EV les plus hauts",
"auto_sort_talent_missing":"Talents manquants",
"auto_sort_move_missing":"Attaques manquantes",
"auto_sort_level_missing":"Niveau manquant",
"box_filter_all_iv":"Tous",
"box_filter_iv_complete":"IV complets",
"box_filter_iv_incomplete":"IV incomplets",
"filters_title":"Filtres",
"quest_battle_btn":"Combattre",
"quest_battle_started":"Combat de quête : {quest}",
"quest_battle_none":"Aucune quête de combat active ici.",
"quest_battle_title":"Quête locale",
"quest_reward_battle_active":"Un combat est déjà en cours : terminez-le avant de défier ce Pokémon.",
"quest_battle_stop_current":"Combat actuel arrêté : lancement du défi...",
"quest_reward_battle_started":"Défi lancé : {pokemon} vous attend en combat !",
"shiny_skin_on":"Sprite shiny activé",
"shiny_skin_off":"Sprite normal activé",
"duplicate_item_money_log":"Objet déjà possédé : {item} converti en +{money}₽.",
"capture_duplicate_no_money":"{name} était déjà possédé : aucun Pokédollar gagné.",
"rematch_no_money":"Victoire de revanche : aucun Pokédollar gagné.",
"fossil_not_sellable":"Les fossiles ne sont pas vendables.",
"repeatable_slots":"Slots de quêtes répétables",
"repeatable_upgrades":"Améliorations répétables",
"repeatable_reroll_timer":"Reroll gratuit : {time}",
"repeatable_reroll_wait":"Reroll disponible dans {time}",
"repeatable_slots_full":"Slots pleins",
"repeatable_slots_current":"Slots actuels : {count}/{max}",
"repeatable_slot_upgrade_buy":"Débloquer le slot {next} ({price}₽)",
"repeatable_slots_max":"Tous les slots répétables sont débloqués.",
"repeatable_reroll_free_desc":"Le reroll est gratuit toutes les 10 minutes. Aucun reroll payant.",
"repeatable_slot_upgraded":"Slots de quêtes répétables : {count}.",
"hatchery_management_title":"Gestion Pension",
"hatchery_management_button":"Gestion Pension",
"hatchery_slots_title":"Améliorations de slots",
"hatchery_slots_current":"Slots actuels : {count}/{max}",
"hatchery_automation_title":"Automatisations Pension",
"hatchery_automation_desc":"Achète d’abord un module, puis active ou désactive son comportement.",
"automation_autoHatch_desc":"Éclos automatiquement les œufs prêts.",
"automation_autoSeedHatchery_desc":"Remplit automatiquement les slots libres depuis la boîte PC.",
"automation_buy_button":"Acheter ({price}₽)",
"automation_owned":"Acheté",
"automation_locked_upgrade":"À débloquer dans Améliorations",
"staff_xp_bar":"XP {xp}/{need}",
"staff_level_short":"Niv. {level}",
"automation_enabled":"Activé",
"automation_disabled":"Désactivé",
"automation_already_bought":"Automatisation déjà achetée.",
"hatchery_slots_max":"Tous les slots de pension sont débloqués.",
"automation_autoHatch":"Éclosion automatique",
"automation_autoSeedHatchery":"Remplissage automatique",
"automation_upgrade_need_money":"Amélioration trop chère : {price}₽ requis.",
"automation_upgrade_bought":"Amélioration achetée : {name} ({price}₽).",
"training_slots":"Slots entraînement",
"training_slots_current":"Slots actuels : {count}/{max}",
"training_multi_slot_buy":"Débloquer le 2e slot ({price}₽)",
"training_multi_slot_bought":"Deuxième slot d’entraînement débloqué.",
"training_multi_slot_max":"Le deuxième slot d’entraînement est déjà débloqué.",
"training_multi_slot_note":"Le deuxième slot débloque un vrai combat d’entraînement parallèle : tu peux assigner un autre Pokémon et lancer deux entraînements en même temps.",
"training_upgrades":"Améliorations",
"training_center_title":"Centre d'entraînement",
"training_parallel_hint":"Chaque slot lance son propre combat d’entraînement en parallèle.",
"training_slot_title":"Slot {slot}",
"training_slot_empty":"Aucun Pokémon assigné à ce slot.",
"training_slot_choose":"Ajouter un Pokémon",
"training_slot_change":"Changer le Pokémon",
"training_slot_active":"Combat en cours",
"training_slot_time_left":"{time} restant",
"training_slot_busy":"Ce slot est déjà en combat d’entraînement.",
"training_slot_no_pokemon":"Aucun Pokémon dans ce slot.",
"training_slot_started":"Entraînement lancé pour {name} ({mode}).",
"training_slot_failed":"Entraînement échoué pour {name}. Le coach était trop fort.",
"training_slot_cancel":"Abandonner",
"training_slot_cancelled":"Entraînement annulé.",
"training_slot_missing":"Pokémon d’entraînement introuvable.",
"training_slot_locked":"2e slot verrouillé",
"training_slot_last_success":"Dernier résultat : {mode} réussi{reward}",
"training_slot_last_failed":"Dernier résultat : {mode} échoué",
"selector_title_training_slot":"Salle d'Entraînement — slot {slot}",
"selected_for_training_slot":"{name} sélectionné pour le slot {slot} !",
"training_mode_move_title":"Discipline Capacités",
"training_mode_move_desc":"Débloque une attaque verrouillée par entraînement.",
"training_mode_move_done":"Toutes les attaques d’entraînement sont déjà débloquées.",
"training_mode_talent_title":"Atelier Talents",
"training_mode_talent_desc":"Tente d’obtenir un talent de la liste du Pokémon.",
"training_mode_talent_done":"Tous les talents disponibles sont déjà débloqués.",
"training_mode_ev_title":"Stage EV ciblé",
"training_mode_ev_desc":"Gagne exactement 1 EV aléatoire.",
"training_mode_ev_done":"EV au maximum.",
"training_mode_level_title":"Stage Niveau",
"training_mode_level_desc":"Gagne entre 2 et 5 niveaux.",
"training_mode_level_done":"Niveau 100 atteint.",
"management_upgrades":"Améliorations",
"management_automation":"Automatisation",
"training_management_title":"Gestion entraînement",
"training_management_button":"Gestion entraînement",
"training_automation_title":"Automatisations d’entraînement",
"training_automation_desc":"Vue des slots d’entraînement prête pour les futures automatisations.",
"training_live_title":"Combats d’entraînement en direct",
"training_live_running":"Entraînements en cours",
"training_live_waiting":"Le combat commence...",
"training_live_visible_hint":"Combat visible dans le panneau Combat en direct.",
"training_live_started":"{name} commence un entraînement {mode} contre {enemy}.",
"training_live_hit":"{name} utilise {move} sur {target} : {damage} dégâts.",
"training_live_miss":"{name} rate {move}.",
"training_live_no_effect":"Ça n’a aucun effet sur {name}.",
"training_live_status_move":"{move} prépare le rythme du combat.",
"training_live_next_round":"Round {round}/{total} : {enemy} entre en scène. Votre Pokémon est soigné.",
"training_live_enemy_down":"{enemy} est K.O. !",
"training_round_label":"Round {round}/{total}",
"pokemon_favorite_on":"Favori",
"pokemon_favorite_off":"Marquer favori",
"pokemon_locked_on":"Verrouillé",
"pokemon_locked_off":"Verrouiller",
"automation_rules":"Règles automatiques",
"auto_filter_shiny":"Shiny",
"auto_sort_iv_desc":"Meilleurs IV d’abord",
"auto_sort_iv_asc":"Plus faibles IV d’abord",
"auto_sort_level_desc":"Plus haut niveau d’abord",
"auto_sort_level_asc":"Plus bas niveau d’abord",
"auto_sort_dex":"Ordre Pokédex",
"queue_build":"Générer la liste d’attente",
"queue_waiting_list":"Liste d’attente",
"queue_empty":"Liste d’attente vide.",
"queue_manual_hint":"Ajoutez les Pokémon manuellement depuis la boîte PC. La liste existe même avant d’acheter l’automatisation.",
"queue_add_from_box":"Listes d’attente",
"queue_add_hatchery":"Ajouter à la pension",
"queue_add_training_slot1":"Ajouter entraînement slot 1",
"queue_add_training_slot2":"Ajouter entraînement slot 2",
"queue_already_added_short":"Déjà en liste",
"queue_clear":"Vider la liste",
"queue_capacity":"Capacité : {count}/{max}",
"queue_upgrade_buy":"Améliorer la liste à {count} places ({price}₽)",
"queue_size_maxed":"Taille de liste au maximum.",
"queue_size_upgraded":"Taille de liste améliorée : {count} places.",
"queue_size_title":"Taille de liste d’attente",
"queue_full":"Liste d’attente pleine ({count}).",
"queue_locked_rejected":"Pokémon verrouillé : impossible de l’ajouter à une liste auto.",
"queue_team_rejected":"Pokémon dans une équipe : impossible de l’ajouter à une liste auto.",
"queue_already_busy":"Ce Pokémon est déjà occupé.",
"queue_already_other":"Ce Pokémon est déjà dans une autre liste d’attente.",
"queue_already_added":"Ce Pokémon est déjà dans cette liste.",
"queue_added_hatchery":"{name} ajouté à la liste d’attente pension.",
"queue_added_training":"{name} ajouté à la liste d’attente entraînement slot {slot}.",
"queue_refreshed":"Liste d’attente rafraîchie.",
"hatchery_queue_built":"Liste d’attente pension : {count} Pokémon.",
"training_queue_built":"Slot {slot} : {count} Pokémon en liste d’attente.",
"training_auto_mode":"Mode auto",
"training_auto_mode_all":"Tout faire",
"training_no_available":"Ce Pokémon n’a plus aucun entraînement disponible.",
"training_no_available_for_mode":"Ce Pokémon n’a plus d’entraînement disponible pour ce mode.",
"management_miners":"Mineurs",
"hatchery_managers_title":"Gérants",
"training_trainers_title":"Entraîneurs",
"staff_active":"Actifs",
"staff_bonus":"Bonus",
"staff_bonus_hatchery_speed":"réduction des K.O. d’éclosion",
"staff_bonus_hatchery_queue":"optimisation de pension",
"staff_bonus_training_ease":"avantage en combat d’entraînement",
"staff_bonus_training_mastery":"maîtrise d’entraînement",
"staff_bonus_mine_efficiency":"réduction du coût d’énergie",
"staff_bonus_mine_energy":"endurance minière",
"staff_name_manager_saffron":"Gérant Sacha",
"staff_desc_manager_saffron":"Spécialiste de l’éclosion régulière et des cycles longs.",
"staff_name_manager_cinnabar":"Chercheuse Ambre",
"staff_desc_manager_cinnabar":"Chercheuse de laboratoire, utile pour les longues files de pension.",
"staff_name_manager_goldenrod":"Gérante Flora",
"staff_desc_manager_goldenrod":"Gérante Johto expérimentée, pensée pour la pension avancée.",
"staff_name_trainer_fuchsia":"Coach Nina",
"staff_desc_trainer_fuchsia":"Entraîneuse d’endurance pour sécuriser les combats longs.",
"staff_name_trainer_indigo":"Coach Indigo",
"staff_desc_trainer_indigo":"Coach d’élite pour l’entraînement haut niveau.",
"staff_name_trainer_blackthorn":"Maître Draco",
"staff_desc_trainer_blackthorn":"Entraîneur exigeant, spécialisé dans les gros Pokémon.",
"staff_name_miner_cerulean":"Spéléologue Azur",
"staff_desc_miner_cerulean":"Mineur précis qui réduit les pertes d’énergie.",
"staff_name_miner_mahogany":"Mineur Givre",
"staff_desc_miner_mahogany":"Mineur de Johto habitué aux couches profondes.",
"staff_name_miner_blackthorn":"Foreuse Sandra",
"staff_desc_miner_blackthorn":"Experte minière d’Ébénelle pour les longues sessions.",
"staff_already_owned":"Employé déjà recruté.",
"staff_location_locked":"Employé indisponible : débloquez {loc}.",
"staff_hired":"{name} recruté !",
"staff_active_limit":"Limite d’employés actifs atteinte ({count}).",
"staff_level_up":"{name} passe niveau {level} !",
"staff_level":"Niveau {level} · XP {xp}/{need}",
"staff_active_on":"Actif",
"staff_active_off":"Inactif",
"staff_hire_price":"Recruter ({price}₽)",
"staff_unlock_at":"Débloquer {loc}",
"staff_name_manager_daisy":"Gérante Daisy",
"staff_desc_manager_daisy":"Réduit progressivement le nombre de K.O. nécessaires à l’éclosion.",
"staff_name_manager_celadon":"Gérante Mila",
"staff_desc_manager_celadon":"Optimise la pension et prépare les futures règles avancées de file d’attente.",
"staff_name_trainer_vermilion":"Coach Armand",
"staff_desc_trainer_vermilion":"Rend les combats d’entraînement légèrement plus favorables.",
"staff_name_trainer_saffron":"Maître Soren",
"staff_desc_trainer_saffron":"Spécialiste des entraînements avancés, prêt pour les futures automatisations.",
"staff_name_miner_pewter":"Mineur Roch",
"staff_desc_miner_pewter":"Réduit progressivement le coût d’énergie des outils.",
"staff_name_miner_cinnabar":"Foreur Vulcain",
"staff_desc_miner_cinnabar":"Spécialiste de l’endurance minière, prêt pour les futurs outils.",
"mine_management_title":"Gestion Mine",
"mine_management_button":"Gestion Mine",
"mine_auto_title":"Mine automatique",
"mine_energy_upgrade_title":"Énergie de mine",
"mine_energy_current":"Énergie max actuelle : {energy}",
"mine_energy_upgrade_buy":"Augmenter l’énergie max (+25) ({price}₽)",
"mine_energy_upgraded":"Énergie max de la mine : {energy}.",
"mine_energy_maxed":"Énergie de mine au maximum.",
"mine_tools_title":"Outils",
"mine_tool_chisel":"Burin",
"mine_tool_hammer":"Marteau",
"mine_tool_pickaxe":"Pioche renforcée",
"mine_tool_drill":"Foreuse",
"mine_tool_dynamite":"Dynamite",
"mine_tool_owned":"Outil déjà débloqué.",
"mine_tool_locked":"Outil non débloqué.",
"mine_tool_bought":"Outil débloqué : {tool}.",
"mine_tools_soon":"De nouveaux outils plus puissants arriveront dans une prochaine passe de la mine.",
"mine_miners_soon":"Les mineurs arrivent bientôt dans une prochaine mise à jour de la mine.",
"trainer_battle":"Combat de dresseur",
"trainer_role_rival":"Rival",
"trainer_role_rocket":"Team Rocket",
"trainer_role_boss":"Boss",
"trainer_role_gym":"Arène",
"trainer_role_league":"Ligue",
"trainer_role_atoll":"Atoll",
"trainer_role_trainer":"Dresseur",
"trainer_role_sage":"Sage",
"trainer_style_balanced":"Équilibré",
"trainer_style_speed":"Vitesse",
"trainer_style_special":"Spécial",
"trainer_style_poison":"Poison",
"trainer_style_ground":"Sol",
"trainer_style_boss":"Boss",
"trainer_style_rocket":"Rocket",
"trainer_style_status":"Statut",
"trainer_style_tank":"Tank",
"trainer_style_defense":"Défense",
"trainer_style_water":"Eau",
"trainer_style_electric":"Électrik",
"trainer_style_grass":"Plante",
"trainer_style_fire":"Feu",
"trainer_style_psychic":"Psy",
"trainer_style_fighting":"Combat",
"trainer_style_ghost":"Spectre",
"trainer_style_dragon":"Dragon",
"trainer_style_offense":"Offense",
"trainer_style_bulk":"Résistance",
"trainer_style_coverage":"Couverture",
"trainer_style_fast":"Rapide",
"trainer_style_early":"Début",
"trainer_style_science":"Science",
"trainer_style_starter":"Starter",
"trainer_style_aggressive":"Agressif",
"trainer_style_tower":"Tour",
"trainer_style_atoll":"Atoll",
"trainer_style_tower_c":"Tour C",
"trainer_style_tower_b":"Tour B",
"trainer_style_tower_a":"Tour A",
"trainer_style_tower_free":"Libre",
"trainer_style_factory_c":"Usine C",
"trainer_style_factory_a":"Usine A",
"trainer_style_arena_three":"3 Pokémon",
"trainer_style_arena_no_item":"Sans confort",
"trainer_style_arena_type":"Types",
"trainer_style_dome_quarter":"Dôme",
"trainer_style_dome_final":"Finale",
"trainer_style_rage":"Colère",
"trainer_style_champion_prep":"Pré-Ligue",
"trainer_battle_target":"Adversaire : {trainer}",
"trainer_battle_hint":"Combat de quête : le combat actuel sera arrêté si besoin, puis la quête se valide après victoire.",
"trainer_battle_name_kanto_rival_route22":"Blue",
"trainer_battle_name_kanto_rocket_mtmoon":"Sbire Rocket",
"trainer_battle_name_kanto_super_nerd_fossil":"Intello Miguel",
"trainer_battle_name_kanto_rival_cerulean":"Blue",
"trainer_battle_name_kanto_rival_ssanne":"Blue",
"trainer_battle_name_kanto_rocket_hideout":"Admin Rocket",
"trainer_battle_name_kanto_giovanni_hideout":"Giovanni",
"trainer_battle_name_kanto_rival_silph":"Blue",
"trainer_battle_name_kanto_giovanni_silph":"Giovanni",
"trainer_battle_name_kanto_rival_victory":"Blue",
"trainer_battle_name_johto_rival_cherrygrove":"Silver",
"trainer_battle_name_johto_sprout_elder":"Sage Li",
"trainer_battle_name_johto_rocket_slowpoke":"Sbire Rocket",
"trainer_battle_name_johto_rival_ilex":"Silver",
"trainer_battle_name_johto_rival_burned":"Silver",
"trainer_battle_name_johto_rocket_lake":"Exécutif Rocket",
"trainer_battle_name_johto_rocket_radio":"Exécutif Rocket",
"trainer_battle_name_johto_rival_victory":"Silver",
"trainer_battle_done":"Combat remporté",
"trainer_battle_won":"{trainer} vaincu !",
"battle_atoll_title":"Atoll de Combat",
"battle_atoll_desc":"Un endgame alpha inspiré de la Zone de Combat : séries de combats par rang, équipes variées et Jetons Atoll.",
"atoll_tokens":"Jetons Atoll",
"atoll_tower":"Tour Combat",
"atoll_locked":"Atoll verrouillé : bats d’abord la Ligue Kanto.",
"atoll_locked_desc":"L’Atoll de Combat se débloque après la Ligue Kanto. Il servira de premier endgame alpha avec plusieurs formats et une boutique dédiée.",
"atoll_modes":"Modes de combat",
"atoll_home":"Accueil",
"atoll_factory":"Usine Combat",
"atoll_arena":"Arène Combat",
"atoll_dome":"Dôme Combat",
"atoll_rental":"Prêt",
"atoll_tower_desc":"Série classique avec catégories de puissance et récompenses progressives.",
"atoll_factory_desc":"Utilise des Pokémon prêtés pour tester des équipes sans farm préalable.",
"atoll_arena_desc":"Formats courts avec restrictions pour tester la préparation d’équipe.",
"atoll_dome_desc":"Formats longs de type tournoi, avec récompenses plus importantes.",
"atoll_tower_c":"Tour Combat — Rang C max",
"atoll_tower_c_desc":"Série accessible avec Pokémon moyens.",
"atoll_tower_b":"Tour Combat — Rang B max",
"atoll_tower_b_desc":"Difficulté intermédiaire avec équipes plus solides.",
"atoll_tower_a":"Tour Combat — Rang A max",
"atoll_tower_a_desc":"Format avancé pour équipes bien préparées.",
"atoll_tower_free":"Tour Combat — Libre",
"atoll_tower_free_desc":"Format libre, adversaires puissants.",
"atoll_factory_c":"Usine Combat — Standard",
"atoll_factory_c_desc":"Pokémon prêtés, difficulté moyenne.",
"atoll_factory_a":"Usine Combat — Expert",
"atoll_factory_a_desc":"Pokémon prêtés plus puissants, meilleurs jetons.",
"atoll_arena_three":"Arène Combat — 3 Pokémon",
"atoll_arena_three_desc":"Ton équipe est limitée à ses 3 premiers Pokémon.",
"atoll_arena_no_item":"Arène Combat — Sans confort",
"atoll_arena_no_item_desc":"Format court plus rude, pensé pour les rôles clairs.",
"atoll_arena_type":"Arène Combat — Pression type",
"atoll_arena_type_desc":"Combat court avec couverture de types plus punissante.",
"atoll_dome_quarter":"Dôme Combat — Demi-tournoi",
"atoll_dome_quarter_desc":"Adversaire solide, récompense élevée.",
"atoll_dome_final":"Dôme Combat — Finale",
"atoll_dome_final_desc":"Équipe complète et très forte, grosse récompense.",
"atoll_mode_rule":"Nv.{level} · {size} Pokémon · +{reward} jetons",
"atoll_mode_tower":"Tour Combat",
"atoll_mode_tower_desc":"Format classique : équipe polyvalente et difficulté stable.",
"atoll_mode_arena":"Arène Sprint",
"atoll_mode_arena_desc":"Combat court en petit format, plus direct et plus rapide.",
"atoll_mode_dome":"Dôme Combat",
"atoll_mode_dome_desc":"Combat long contre une équipe complète, récompense plus élevée.",
"atoll_mode_factory":"Usine Combat",
"atoll_mode_factory_desc":"Équipes variées et moins prévisibles, inspirées de l’Usine Combat.",
"atoll_shop":"Boutique Atoll",
"atoll_start":"Combattre",
"atoll_rank_rule":"Rang max {rank} · Nv.{level} · +{reward} jetons",
"atoll_max_rank":"Rang max {rank}",
"atoll_rank_free":"Libre",
"atoll_rank_blocked":"Rang max {rank} requis. À retirer : {pokemon}.",
"atoll_tower_e":"Tour Combat — Rang E max",
"atoll_tower_e_desc":"Format faible rang niveau 100 : petits Pokémon, vrais choix stratégiques.",
"atoll_tower_d":"Tour Combat — Rang D max",
"atoll_tower_d_desc":"Pokémon modestes niveau 100, récompense faible mais format très varié.",
"atoll_tower_s":"Tour Combat — Rang S max",
"atoll_tower_s_desc":"Format endgame complet avec Pokémon puissants niveau 100.",
"atoll_streak":"Série {streak} · Record {best}",
"atoll_win_reward":"Victoire Atoll : +{tokens} jetons · série {streak}",
"atoll_not_enough_tokens":"Pas assez de Jetons Atoll.",
"atoll_item_bought":"Objet Atoll acheté : {item}.",
"atoll_streak_lost":"Série Atoll interrompue.",
"pokemon_rank":"Rang",
"note":"Note",
};

