// ===== FR — UI strings =====
// Auto-extracted & grouped by domain. Edit text here, never hardcode in logic.

window.L_fr_ui = {
  "add_to_team_btn": "➕ Ajouter à l'équipe",
  "box_header": "📦 Pokémon en boîte",
  "box_pc_note": "📦 Ce Pokémon est dans votre boîte PC. Placez-le dans votre équipe pour l'entraîner ou lui équiper des objets !",
  "box_swap_header": "🔁 Échange : choisissez un Pokémon de la boîte pour remplacer",
  "buy_btn": "Acheter",
  "challenge_btn": "⚔️ Défier",
  "choose_starter": "Choisir votre Starter",
  "cols3": "3 Colonnes",
  "defeated_lbl": "vaincu",
  "drop_items_lbl": "🎁 Objets trouvables :",
  "eq_sub": "Gestion d'équipement",
  "equip_btn": "Équiper",
  "equipped_lbl": "Équipé sur :",
  "evo_title": "🌱 Méthode d'évolution :",
  "evolve_btn": "Évoluer !",
  "explore_btn": "🌾 Explorer",
  "explore_routes": "🌾 Explorer les routes",
  "fiche_btn": "📋 Fiche",
  "finish_btn": "✓ Terminer",
  "forget_btn": "Oublier",
  "forget_first": "(oubliez-en une d'abord)",
  "full_btn": "Plein",
  "idle_desc": "Déplacez-vous sur une route de la carte à gauche et cliquez sur <b>🌾 Explorer</b> ou <b>⚔️ Défier</b> pour lancer un combat en temps réel au centre de l'écran !",
  "idle_title": "Exploration au repos",
  "inv_desc_sub": "Sélectionnez un objet pour l'utiliser ou l'équiper.",
  "inv_sub": "Cliquez sur un objet pour l'utiliser, le revendre ou l'équiper sur un Pokémon.",
  "lang_title": "🌐 Langue / Language",
  "learn_btn": "Apprendre",
  "learnable_moves": "Capacités apprenables",
  "loot_btn": "📋 Butin",
  "loot_continue_btn": "Continuer sur la route",
  "loot_restart_btn": "🔄 Relancer le combat immédiatement",
  "loot_summary_title": "📋 Butin de la session",
  "loot_title": "📋 Butin de la session",
  "lvl_lbl": "Nv.",
  "market_sub": "Achetez des Pokémon introuvables dans la nature !",
  "market_title": "🏪 PokéMarket",
  "mine_sub": "Creusez les couches rocheuses pour déterrer des <b>Pierres d'Évolution</b>, Pépites et Fossiles !",
  "mine_title": "⛏️ Grand Souterrain (Mines de Kanto)",
  "modify_btn": "✏️ Modifier",
  "moves_lbl": "Capacités :",
  "no_item": "Aucun objet",
  "no_more_moves": "Aucune autre capacité disponible.",
  "owned_btn": "Possédé",
  "rarity_com": "● Commun (~75%)",
  "rarity_rare": "⭐ Rare (~4%)",
  "rarity_uncom": "🔹 Peu commun (~20%)",
  "rematch_btn": "🔄 Revanche",
  "req_lbl": "requis",
  "shop_sub": "Sac plafonné à 25 exemplaires par objet.",
  "skin_shiny_lbl": "✨ Skin Shiny",
  "skin_shiny_sub": "Bascule d'apparence uniquement",
  "starter_choose_sub": "Ce Pokémon vous accompagnera tout au long de votre aventure.",
  "starter_choose_title": "Choisissez votre Starter !",
  "stone_evo_title": "🪨 Évolution par pierre",
  "stone_sub": "Sélectionnez un Pokémon pour utiliser cette pierre.",
  "swap_btn": "🔁 Échanger",
  "swap_with_btn": "🔁 Échanger avec",
  "tab_box": "📦 Boîte",
  "tab_dex": "📖 Pokédex",
  "tab_fossil": "🦴 Fossiles",
  "tab_info": "📍 Lieu",
  "tab_inv": "🎒 Sac",
  "tab_market": "🏪 Marché",
  "tab_mine": "⛏️ Mine",
  "tab_shop": "🛒 Shop",
  "team_btn": "➕ Équipe",
  "team_empty": "Aucun Pokémon dans l'équipe !",
  "to_box_btn": "📦 Retirer (→ boîte)",
  "typ_dungeon": "⛰ Grotte / Donjon",
  "typ_route": "🌿 Route",
  "typ_sea": "🌊 Chenal maritime",
  "typ_town": "🏙 Ville",
  "wild_poke": "🌿 Pokémon sauvages",
  "win_battle": "⚔️ Combat en direct (PokéChill)",
  "win_map": "🗺️ Carte Kanto",
  "win_tabs": "📑 Menus & Gestion",
  "win_team": "⚡ Équipe Active",
  "xp_lbl": "XP:",
  "lang_switched_fr": "🇫🇷 Langue changée en Français !",
  "lang_switched_en": "🇬🇧 Langue changée en Anglais !",
};
