// ===== FR — UI strings =====
// Auto-extracted & grouped by domain. Edit text here, never hardcode in logic.

// T2 (vague 37) : module ESM — export natif + exposition gardée sur l'objet
// global (registre de langues wave-32 + harnais VM) — gabarit fr/quests.js.
export const L_fr_ui = {
"debug_toggle_btn":"Debug",
"debug_x10_toggle":"Vitesse x10 :",
"debug_fill_mine":"Recharger l'énergie de mine (100)",
"debug_unlock_badges":"Débloquer 8 badges Kanto",
"debug_give_candies":"+10 Super Bonbons",
"debug_give_money":"+50 000₽",
"debug_menu_title":"Menu debug / triche",
"guide_pokedex_title":"Pokédex",
"guide_dictionary_text":"Cherche les objets, attaques et talents. Tu peux voir qui connaît une attaque, qui possède un talent et où trouver un objet.",
"guide_dictionary_title":"Dictionnaire",
"guide_training_text":"Entraîne un Pokémon pour gagner niveaux, EV, talents ou débloquer des attaques avancées.",
"guide_training_title":"Entraînement",
"guide_hatchery_text":"Dépose des Pokémon ou des fossiles. Les améliorations et automatisations se trouvent dans le menu dédié.",
"guide_hatchery_title":"Pension",
"guide_mine_text":"Creuse les cases pour révéler trésors et fossiles. La mine se régénère quand tous les objets sont récupérés.",
"guide_mine_title":"Mine",
"guide_bag_text":"Les objets sont classés par catégorie. Certains se tiennent, d’autres évoluent, se vendent ou servent aux quêtes.",
"guide_bag_title":"Sac",
"app_update_banner_text":"🚀 Une nouvelle version de PokéWorld est disponible sur GitHub !",
"app_update_banner_btn":"🔄 Mettre à jour",
"app_update_banner_close":"Fermer la notification",

"guide_pokemon_text":"La fiche Pokémon montre Base Stats, IV, EV, talents, objet tenu, attaques connues et attaques apprenables.",
"guide_pokemon_title":"Pokémon",
"guide_combat_text":"Les combats sont automatiques. Surveille les PV, les attaques qui se chargent, le butin et change de Pokémon si besoin.",
"guide_combat_title":"Combat",
"guide_map_text":"Clique sur une zone débloquée pour t’y déplacer. Les routes demandent parfois des combats, les villes importantes demandent des badges ou des quêtes.",
"guide_map_title":"Carte & progression",
"tutorial_step_badge_desc":"Progresse jusqu’à Argenta et bats Pierre.",
"tutorial_step_badge_title":"Premier badge",
"tutorial_step_dex_desc":"Ouvre le Pokédex et clique sur un Pokémon vu.",
"tutorial_step_dex_title":"Le Pokédex",
"tutorial_step_bag_desc":"Ouvre le Sac depuis les raccourcis pour voir tes objets.",
"tutorial_step_bag_title":"Le sac",
"tutorial_step_sheet_desc":"Ouvre une fiche Pokémon pour voir stats, IV, EV, talents et attaques.",
"tutorial_step_sheet_title":"Fiche Pokémon",
"tutorial_step_route1_desc":"Va sur la Route 1 et gagne 3 combats sauvages pour apprendre le rythme du jeu.",
"tutorial_step_route1_title":"Premiers combats",
"guide_intro":"Guide rapide pour comprendre PokéWorld sans interrompre le jeu.",
"tutorial_progress":"tutoriel",
"tutorial_complete_desc":"Tu connais les bases. Le guide reste disponible dans les raccourcis.",
"tutorial_complete_title":"Tutoriel terminé",
"tutorial_enable":"Activer les tutos",
"tutorial_disable_all":"Désactiver",
"tutorial_enabled":"Tutoriels activés",
"tutorial_disabled":"Tutoriels désactivés",
"guide_title":"Guide",
"route_events_placeholder_title":"Événements de route",
"route_events_placeholder_desc":"Le système d’événements de route est prêt. Les événements dynamiques seront ajoutés dans une phase ultérieure.",
"dict_abilities":"Talents",
"dict_moves":"Attaques",
"dict_items":"Objets",
"dict_search_placeholder":"Rechercher...",
"dict_no_results":"Aucun résultat.",
"dict_owned_qty":"Possédé ×{count}",
"dict_not_owned":"Non possédé",
"dict_main_quest":"Quête principale",
"dict_side_quest":"Quête secondaire",
"dict_repeatable_quest":"Quête répétable",
"dict_unknown_source":"Obtention non renseignée",
"dict_rarity":"Rareté",
"dict_affected_pokemon":"Pokémon concernés",
"dict_no_pokemon_listed":"Aucun Pokémon listé.",
"dict_move_users":"{count} Pokémon connaissent cette attaque",
"dict_move_users_none":"Aucun Pokémon ne connaît cette attaque",
"dict_ability_unlocked":"Débloqué",
"dict_ability_locked":"Non débloqué",
"dict_ability_carriers":"{count} porteur(s)",
"dict_where_find":"Où le trouver",
"dict_base_stats":"Stats de base",
"dict_description_unavailable":"Description indisponible pour le moment.",
"dict_no_moves_listed":"Aucune attaque renseignée.",
"dict_no_abilities_listed":"Aucun talent renseigné.",
"evolutions_title":"Évolutions",
"dictionary_title":"Dictionnaire",
"add_to_team_btn":"Ajouter à l'équipe",
"box_header":"Pokémon en boîte",
"box_pc_note":"Ce Pokémon est dans votre boîte PC. Placez-le dans votre équipe pour l'entraîner ou lui équiper des objets !",
"box_swap_header":"Échange : choisissez un Pokémon de la boîte pour remplacer",
"buy_btn":"Acheter",
"quest_challenge_btn":"Défier !",
"challenge_btn":"Défier",
"arena_challenge_label":"Arène — Défier {champion}",
"arena_rematch_label":"Arène — Revanche {champion}",
"arena_locked_label":"Arène — {champion} ({badges} badges requis)",
"league_challenge_label":"Ligue — Défier {champion}",
"league_rematch_label":"Ligue — Revanche {champion}",
"league_locked_label":"Ligue — {champion} ({badges} badges requis)",
"choose_starter":"Choisir votre Starter",
"cols3":"3 Colonnes",
"defeated_lbl":"vaincu",
"drop_items_lbl":"Objets trouvables :",
"eq_sub":"Gestion d'équipement",
"equip_btn":"Équiper",
"equipped_lbl":"Équipé sur :",
"evo_title":"Méthode d'évolution :",
"evolve_btn":"Évoluer !",
"explore_btn":"Explorer",
"explore_routes":"Explorer les routes",
"fiche_btn":"Fiche",
"finish_btn":"Terminer",
"forget_btn":"Oublier",
"forget_first":"(oubliez-en une d'abord)",
"full_btn":"Plein",
"idle_desc":"Déplacez-vous sur une route de la carte à gauche et cliquez sur <b> Explorer</b> ou <b> Défier</b> pour lancer un combat en temps réel au centre de l'écran !",
"idle_title":"Exploration au repos",
"inv_desc_sub":"Sélectionnez un objet pour l'utiliser ou l'équiper.",
"inv_sub":"Cliquez sur un objet pour l'utiliser, le revendre ou l'équiper sur un Pokémon.",
"lang_title":"Langue / Language",
"learn_btn":"Apprendre",
"learnable_moves":"Capacités apprenables",
"loot_btn":"Résumé",
"loot_continue_btn":"Continuer sur la route",
"loot_restart_btn":"Relancer le combat immédiatement",
"loot_summary_title":"Butin de la session",
"battle_session_summary_title":"Butin & résumé de session", 
"battle_team_damage_title":"Dégâts de l’équipe", 
"loot_title":"Butin de la session",
"lvl_lbl":"Nv.",
"market_sub":"Achetez des Pokémon introuvables dans la nature !",
"market_title":"PokéMarket",
"mine_sub":"Creusez les couches rocheuses pour déterrer des <b>Pierres d'Évolution</b>, Pépites et Fossiles !",
"mine_title":"Grand Souterrain",
"modify_btn":"Modifier",
"moves_lbl":"Capacités :",
"no_item":"Aucun objet",
"no_more_moves":"Aucune autre capacité disponible.",
"owned_btn":"Possédé",
"rarity_com":"● Commun (~75%)",
"rarity_rare":"Rare (~4%)",
"rarity_uncom":"Peu commun (~20%)",
"rematch_btn":"Revanche",
"req_lbl":"requis",
"shop_sub":"Sac plafonné à 25 exemplaires par objet.",
"skin_shiny_lbl":"Skin Shiny",
"skin_shiny_sub":"Bascule d'apparence uniquement",
"starter_choose_sub":"Ce Pokémon vous accompagnera tout au long de votre aventure.",
"starter_choose_title":"Choisissez votre Starter !",
"stone_evo_title":"Évolution par pierre",
"stone_sub":"Sélectionnez un Pokémon pour utiliser cette pierre.",
"swap_btn":"Échanger",
"swap_with_btn":"Échanger avec",
"tab_box":"Boîte",
"tab_dex":"Pokédex",
"tab_fossil":"Fossiles",
"tab_info":"Lieu",
"tab_inv":"Sac",
"tab_market":"Marché",
"tab_mine":"Mine",
"tab_shop":"Boutique",
"team_btn":"Équipe",
"team_empty":"Aucun Pokémon dans l'équipe !",
"to_box_btn":"Retirer (→ boîte)",
"typ_dungeon":"Grotte / Donjon",
"typ_route":"Route",
"typ_sea":"Chenal maritime",
"typ_town":"Ville",
"wild_poke":"Pokémon sauvages",
"win_battle":"Combat en direct (PokéChill)",
"win_map":"Carte Kanto",
"win_tabs":"Lieu",
"win_team":"Équipe Active",
"xp_lbl":"XP:",
"lang_switched_fr":"Langue changée en Français !",
"lang_switched_en":"Langue changée en Anglais !",
"save_incompatible_deleted":"Sauvegarde incompatible supprimée automatiquement.",
"level_abbrev":"Nv.",
"stat_hp_short":"PV",
"click_replace_context_info":"Clic pour sélectionner (remplacement) | Clic droit ou appui long pour info",
"replacement_badge":"⬇ Remplacement",
"power_abbrev":"Puiss :",
"learnable_moves_title":"Capacités Apprenables",
"click_to_replace_selected":"← Clic pour remplacer",
"select_move_first":"(4/4 — sélectionnez une attaque ci-dessus)",
"context_info_touch":"Clic droit ou appui long pour info",
"no_other_moves":"Aucune autre capacité disponible.",
"level_word":"Niveau",
"pc_box":"Boîte PC",
"shiny_skin":"Skin Shiny",
"cosmetic_switch_only":"Bascule d'apparence",
"moves_title":"Capacités",
"cancel":"Annuler",
"stone_evolution":"Évolution par pierre",
"team_full_title":"Équipe pleine (6/6)",
"add_to_team":"Ajouter à l'équipe",
"remove_from_team":"Retirer de l'équipe",
"swap_with":"Échanger avec {name}",
"the_team":"l'équipe",
"evolution_stone_notify":" {from} évolue en {to} grâce à {item} !",
"welcome_johto":"Bienvenue dans la région de Johto — Bourg Geon !",
"arrived_kanto_harbor":"Arrivée au port de Carmin sur Mer dans la région de Kanto !",
"map_title_prefix":"Carte : ",
"roaming_legendary_appeared":" UN LÉGENDAIRE ERRANT APPARAÎT : {name} !",
"no_pokemon_in_team":" Vous n'avez pas de Pokémon !",
"no_wild_pokemon_here":"Aucun Pokémon sauvage ici.",
"team_healed_center":"Équipe soignée au Centre Pokémon !",
"all_pokemon_healed":" Tous vos Pokémon ont été soignés !",
"pokemon_already_healthy":"Vos Pokémon sont déjà en pleine forme !",
"fullscreen_pc_box":"Agrandir la Boîte",
"action_blocked_in_battle":"Action impossible en combat : quittez le combat d'abord !",
"moves_swapped":"🔀 {a} ↔ {b} : positions échangées",
"team_already_full":" Votre équipe est déjà pleine (6/6). Retirez un Pokémon d'abord.",
"species_already_in_team":" Espèce déjà dans l'équipe.",
"species_already_in_team_present":" Espèce déjà présente dans l'équipe.",
"box_conflict":" Conflit boîte.",
"joined_team":"{name} rejoint votre équipe !",
"sent_to_box":"{name} est envoyé dans la boîte.",
"must_keep_one_pokemon":" Vous devez garder au moins un Pokémon dans l'équipe.",
"species_already_in_box":" Cette espèce est déjà dans la boîte.",
"presets_label":"Presets :",
"save_short":"Sauver",
"remove":"Retirer",
"equipped_item_label":"Objet équipé",
"none":"Aucun",
"no_equippable_item":"Aucun objet équipable",
"holding_item":"{name} tient {item} !",
"holding_nothing":"{name} ne tient plus rien.",
"item_removed_from":"{item} retiré de {name}.",
"load_preset_title":"Charger {name}",
"save_current_team_title":"Sauvegarder l'équipe actuelle",
"pokemon_talents":"Talents du Pokémon",
"locked_talent_hint":"Verrouillé : capturer/entraîner pour débloquer",
"item_power":"Puissance :",
"no_item_equipped_bag":"Aucun objet équipé. Choisissez-en un depuis l'onglet Sac.",
"cosmetic_switch_only_team":"Bascule d'apparence uniquement",
"sail_to_johto":"Prendre le bateau vers Johto",
"sail_to_kanto":"Prendre le bateau vers Kanto",
"locked":"Verrouillé",
"next_zone":"la prochaine zone",
"battles":"combats",
"to_unlock":"avant le déblocage de",
"roaming_legendary_rotation":"Légendaire errant (rotation 12h) :",
"can_appear_here":"peut apparaître ici !",
"roaming_short":"Errant (1%)",
"map_title_name":"Carte : {region}",
"requires_badges":"nécessite {need} badge(s) (vous en avez {have})",
"win_wild_battles_req":"remporte {need} combats sauvages à {location} (tu en as {have})",
"locked_by_story":"verrouillé par l'histoire — {current}/{required}",
"choose_kanto_starter_first":"Choisissez d'abord votre starter Kanto à Bourg Palette.",
"choose_johto_starter_first":"Choisissez d'abord votre starter Johto à Bourg Geon.",
"need_badges_access":"Il vous faut {need} badge(s) pour accéder à {location} (vous en avez {have}).",
"story_not_reached":"L'histoire n'a pas encore débloqué {location}. (Progression {current}/{required})",
"win_battles_to_unlock":"Remporte {need} combats sauvages à {from} pour débloquer {to} (tu en as {have}).",
"location_not_reachable":"{location} n'est pas encore accessible.",
"teleported_to":" Vous vous téléportez à {location}.",
"panel_inventory_title":"Sac",
"panel_shop_title":"Boutique",
"panel_market_title":"Poké Marché",
"panel_pokedex_title":"Pokédex",
"shortcut_pc_box":"Boîte PC",
"shortcut_bag":"Sac",
"shortcut_market":"Marché",
"starter_johto_chikorita_desc":"Plante - Calme et robuste",
"starter_johto_cyndaquil_desc":"Feu - Rapide et explosif",
"starter_johto_totodile_desc":"Eau - Mâchoires puissantes",
"starter_kanto_bulbasaur_desc":"Plante/Poison - Solide défensivement",
"starter_kanto_charmander_desc":"Feu - Puissance offensive élevée",
"starter_kanto_squirtle_desc":"Eau - Grande endurance",
"starter_welcome_johto":"Bienvenue à Johto ! Le Prof. Orme vous attend à Bourg Geon.",
"starter_welcome_kanto":"Bienvenue à Kanto ! Le Prof. Chen vous attend à Bourg Palette.",
"starter_title_johto":"Choisissez votre Starter Johto !",
"starter_title_kanto":"Choisissez votre Starter !",
"starter_subtitle":"Ce Pokémon vous accompagnera tout au long de votre aventure dans cette région.",
"choose":"Choisir",
"starter_required":"Vous devez choisir un starter pour continuer. Cette fenêtre ne peut pas être fermée.",
"partner_now":"{name} est maintenant votre partenaire !",
"shiny_form_unlocked":" Forme Shiny débloquée/possédée !",
"level_up_moves":"Capacités par niveau",
"close":"Fermer",
"move_cat_physical":"Physique",
"move_cat_special":"Spéciale",
"move_cat_status":"Statut",
"accuracy":"Précision",
"effects":"Effets",
"no_special_effects":"Aucun effet spécial",
"back_to_team": "← Retour à l'Équipe",
  "back_to_dictionary": "← Retour au Dictionnaire",
  "back_to_box": "← Retour à la Box",
  "hidden_ability_label": "Talent Caché",
  "back_to_pokemon":"← Retour au Pokémon",
  "back_to_equip_selector":"← Retour au choix d'objet",
  "back_to_atoll_prep":"← Retour à la préparation",
  "learners_title":"Pokémon pouvant l'apprendre",
  "learners_level":"Par niveau",
  "learners_ctcs":"Par CT / CS",
  "learners_training":"Par dressage",
  "hidden_carriers":"Talent caché de…",
  "dict_and_n_more":"… et {count} autres",
  "bag_search_placeholder":"Rechercher un objet…",
  "box_filter_search_placeholder":"Rechercher un Pokémon…",
  "delete_save_warning":"⚠️ Cette action est irréversible : toute ta progression sera effacée.",
  "preset_missing_hint":"Pokémon introuvable (déplacé ou relâché)",
  "drag_win_hint":"Déplacer la fenêtre",
  "preset_default_name":"Équipe {n}",
  "panel_presets_title":"Mes Équipes",
  "teams_manager_open":"Gérer mes équipes",
  "presets_hint":"Charge une équipe sauvegardée dans l'équipe active, sauve l'équipe actuelle dans un emplacement, ou clique sur « Modifier » pour l'ajuster. 20 emplacements — pense à les renommer (par rang, par région…).",
  "preset_active_tag":"active",
  "preset_load_btn":"Charger",
  "preset_save_btn":"Sauver ici",
  "preset_edit_btn":"Modifier",
  "back_to_presets":"← Retour aux Équipes",
  "back_to_preset_editor":"← Retour à l'éditeur d'équipe",
  "preset_editor_sub":"Éditeur d'équipe",
  "preset_editor_hint":"Clic sur le sprite : changer de Pokémon · clic droit : fiche du Pokémon (modifier) · badge objet : gérer l'objet tenu · glisser-déposer : réordonner.",
  "preset_editor_sprite_hint":"Clic : changer · clic droit : fiche",
  "preset_add_lbl":"+ Ajouter un Pokémon",
  "preset_apply_btn":"Appliquer à l'équipe",
  "preset_save_current_btn":"💾 Sauver l'équipe actuelle ici",
  "preset_remove_member":"Retirer de l'équipe",
  "preset_pick_poke_title":"Choisir un Pokémon",
  "preset_pick_search_ph":"Rechercher (nom ou n°)…",
  "preset_in_team_tag":"Équipe",
  "preset_pick_item_title":"Objet tenu — {name}",
  "preset_items_team_only":"Les objets se gèrent sur les Pokémon de l'équipe active — applique d'abord ce preset.",
  "preset_remove_item":"Retirer l'objet",
  "preset_no_item":"Aucun objet équipable dans le sac",
"effect_burn_stat":"Brûle ({pct}%) — 3 tours de dégâts",
"effect_para_stat":"Paralyse ({pct}%) — 2 tours",
"effect_poison_stat":"Empoisonne ({pct}%) — 3 tours de dégâts",
"effect_badpoison_stat":"Empoisonne gravement ({pct}%) — Persistant, dégâts croissants",
"effect_sleep_stat":"Endort ({pct}%) — 1 à 3 tours",
"effect_freeze_stat":"Gèle ({pct}%) — 3 tours max",
"effect_slow_stat":"Baisse la Vitesse ({pct}%)",
"effect_burn_chance":"{pct}% de brûler — 3 tours de dégâts",
"effect_para_chance":"{pct}% de paralyser — 2 tours",
"effect_poison_chance":"{pct}% d'empoisonner — 3 tours de dégâts",
"effect_freeze_chance":"{pct}% de geler — 3 tours max",
"effect_sleep_chance":"{pct}% d'endormir — 1 à 3 tours",
"effect_slow_chance":"{pct}% de baisser la Vitesse",
"effect_confuse_chance":"{pct}% de rendre confus",
"effect_flinch_chance":"{pct}% de faire hésiter",
"effect_crit":"Taux de critique élevé (×1.5 dégâts)",
"effect_recoil":"Dégâts de recul: 25% des dégâts infligés",
"effect_recharge":"Doit recharger au tour suivant",
"effect_trap":"Piège l'adversaire pendant 4-5 tours",
"effect_drain":"Absorbe 50% des dégâts en PV",
"effect_charge":"Charge au 1er tour, attaque au 2nd",
"effect_heal":"Soigne {pct}% PV",
"effect_priority":"Attaque Rapide (Vitesse +100%)",
"effect_fixed":"Dégâts fixes: {damage} PV",
"sort_name":"Nom",
"sort_quantity":"Quantité",
"sort_category":"Catégorie",
"sort_name_asc":"Nom A→Z",
"sort_name_desc":"Nom Z→A",
"sort_quantity_asc":"Quantité 0→9",
"sort_quantity_desc":"Quantité 9→0",
"filter_label":"Filtre:",
"sort_label":"Tri:",
  "dex_sort_number":"Numéro",
  "dex_sort_name":"Nom",
  "dex_sort_rank":"Rang",
  "dex_sort_number_asc":"N° 1→9",
  "dex_sort_number_desc":"N° 9→1",
  "dex_sort_name_asc":"Nom A→Z",
  "dex_sort_name_desc":"Nom Z→A",
  "dex_sort_rank_asc":"Rang E→S",
  "dex_sort_rank_desc":"Rang S→E",
"mine_locked_badges":"Mine verrouillée (2 Badges requis)",
"pokedex_seen":"Vus",
"pokedex_caught":"Capturés",
"pokedex_shiny":"Shiny",
"pokedex_moves":"Capacités",
"wild_legendary_appeared":"LÉGENDAIRE SAUVAGE : {name} (Nv.65) apparaît ! Vainquez-le pour le capturer !",
"item_found_log":"{icon} Objet trouvé : {item} !",
"money_won_log":"Vous gagnez {money}₽ !",
"capture_title":"Capture !",
"training_complete":" Entraînement réussi !{reward}",
"legendary_boss_defeated":" Vous avez vaincu le Boss Légendaire {pokemon} !",
"boss_captured":" Boss vaincu ! {pokemon}{shiny} capturé !",
"continue":"Continuer",
"held_effect_max":"Effet équipé (à 25/25)",
"item_type_stone":" Pierre d'évolution",
"item_type_treasure":" Trésor",
"item_type_candy":" Bonbon",
"item_type_special":" Spécial",
"item_type_key":"Objet clé",
"item_type_held":" Objet équipé",
"item_type_fossil":" Fossile",
  "item_type_evolution":" Objet d'évol.",
  "item_type_tm":" CT / CS",
  "item_type_berry":"Baie",
"description":"Description",
"price":"Prix",
"owned":"Possédé",
"money":"Argent",
"bought":"Acheté",
"stock":"Stock",
"indigo_shop_locked_title":"Boutique du Plateau Indigo Verrouillée",
"indigo_shop_locked_desc":"Cette boutique d'élite est réservée exclusivement aux Maîtres de la Ligue Kanto.",
"bag_full_for":"Sac plein pour {item} (max {max}).",
"item_bought":"{item} acheté !",
"sent_to_box_price":"{name} envoyé dans la boîte ! (-{price}₽)",
"joined_team_price":"{name} rejoint votre équipe ! (-{price}₽)",
"hatchery_locked_title":"Pension & Couveuse verrouillées",
"hatchery_locked_desc":"Battez Ondine à Azuria (2 Badges) pour débloquer la pension de la Route 5 !",
"hatchery_place_slot":"Slot #{slot} : Déposer un Pokémon",
"ready":"Prêt !",
"incubating":"Incubation : {steps} / {required} KO",
"hatch":"Éclore",
"hatchery_upgrade_slot":"Améliorer Pension : +1 Slot ({cost}₽)",
"fossil_lab":"Laboratoire Fossile",
"fossil_lab_desc":"Ranimez les Pokémon préhistoriques trouvés dans la Mine Souterraine, façon PokéClicker !",
"no_fossils_yet":"Aucun fossile",
"fossil_mine_hint":"Creusez dans la Mine Souterraine pour trouver des fossiles Nautile, Dôme et Vieil Ambre !",
"go_to_mine":"Aller à la Mine",
"quantity_abbrev":"Qté",
"revives_into":"Ranime en",
"revive":"Ranimer !",
"fossil_lab_tip":"<b>Style PokéClicker :</b> les fossiles se trouvent en minant. Chaque fossile ranime instantanément son Pokémon préhistorique (Nv.1). Les Shiny sont possibles !",
"hatchery_upgraded":" Pension améliorée ! Vous avez maintenant {slots} slots d'œufs !",
"iv_money_bonus":" (+5 000₽ bonus IV max)",
"no_fossil_left":"Plus de fossile !",
"unknown_fossil":"Fossile inconnu.",
"fossil_revived_party":"{name} ranimé ! Il rejoint votre équipe !",
"fossil_revived_box":"{name} ranimé ! Envoyé au PC.",
"box_label":"Boîte",
"fossils":"Fossiles",
"no_pokemon_found":"Aucun Pokémon trouvé.",
"select_or_details_hint":"Clic: Sélectionner | Clic Droit: Fiche",
"fossil_selector_hint":"Sélectionnez un fossile pour l'envoyer à la Pension.",
"incubate":"Incuber",
"ko_unit":"KO",
"hatchery_full":"Couveuse pleine !",
"fossil_sent_hatchery":"{item} envoyé à la Pension !",
"dig_mine_fossils":"Creusez dans la Mine Souterraine pour trouver des fossiles !",
"preset_adventure":"Équipe Aventure",
"preset_boss":"Équipe Boss",
"preset_training":"Équipe Entraînement",
"preset_saved":" {name} sauvegardée ({count} Pokémon) !",
"cannot_change_team_battle":"Impossible de changer d'équipe de combat pendant un affrontement !",
"preset_empty":"Ce preset d'équipe est vide ! Mettez des Pokémon en équipe et cliquez sur Sauvegarder.",
"preset_pokemon_not_found":"Aucun Pokémon du preset n'a été trouvé !",
"preset_loaded":" {name} chargée avec succès ({count} Pokémon) !",
"no_pokemon_yet":"Vous n'avez pas encore de Pokémon !",
"choose_starter_bang":"Choisir votre Starter !",
"explore_to_catch":"Explorez les routes pour en capturer.",
"live_battle_lock_team":"Combat en direct en cours :",
"team_locked_battle_long":"L'équipe active est verrouillée. Vous ne pouvez ni échanger, ni réordonner, ni modifier le stuff pendant le combat.",
"cannot_swap_team_battle":"Action impossible : impossible d'échanger l'équipe en plein combat.",
"cannot_during_battle":"Impossible pendant un combat !",
"cannot_remove_only_pokemon":"Impossible de retirer votre seul Pokémon !",
"removed_to_pc":"{name} retiré de l'équipe et placé dans la boîte PC.",
"swap_cancelled":"Échange annulé.",
"box_pokemon_not_found":"Pokémon introuvable dans la boîte !",
"team_pokemon_not_found":"Pokémon d'équipe introuvable !",
"pokemon_swapped":"{a} et {b} ont été échangés !",
"team_full_short":"Équipe pleine ! (6/6)",
"pokemon_not_found":"Pokémon introuvable !",
"added_to_team":"{name} ajouté à l'équipe !",
"selected_pokemon":"Sélectionné: {name} (Nv.{level})",
"team_full_select_replace":"Équipe pleine ! (6/6) - Sélectionnez d'abord un Pokémon de l'équipe à remplacer.",
"already_in_team":"Ce Pokémon est déjà dans l'équipe !",
"selected_for_training":"{name} sélectionné pour l'entraînement !",
"cannot_deposit_only_pokemon":"Impossible de déposer votre seul Pokémon !",
"deposited_hatchery":"{name} déposé à la pension !",
"no_active_pokemon":"Aucun Pokémon actif.",
"team_location":" Équipe",
"box_location":" Boîte",
"easy_minus_two":"Facile : -2 Nv.",
"easy_minus_one":"Facile : -1 Nv.",
"medium_plus_two":"Moyen : +2 Nv.",
"medium_plus_three":"Moyen : +3 Nv.",
"talent_system_unavailable":"Système de talents non disponible",
"no_talent_species":"Aucun talent disponible pour cette espèce",
"no_compatible_talent":"Aucun talent compatible trouvé",
"all_talents_unlocked":"Tous les talents sont débloqués ! L'entraînement peut encore re-roller.",
"holo_ditto":"Holo-Métamorph",
"holo_porygon":"Holo-Porygon",
"punching_bag":"Sac de Frappe",
"training_room_battle_start":" SALLE D'ENTRAÎNEMENT ({mode}) - Round 1/6 : {pokemon} Nv.{level} !",
"switch_pending":"{name} entrera en jeu dès que possible...",
"solo_training_no_switch":"Switch impossible : votre Pokémon s'entraîne en solo au Dojo !",
"shiny_captured":" POKÉMON SHINY CAPTURÉ ! ",
"hidden_talent_unlocked_reward":" (Talent Caché débloqué !)",
"league_master_victory_log":" Vous avez vaincu le Maître Kanto et triomphé des 5 combats de la Ligue !",
"league_master_title_reward":" Félicitations ! Vous obtenez le Titre de Maître Pokémon ! (+{money}₽)",
"rematch_won_reward":" Revanche remportée contre {champion} ! (+{money}₽)",
"league_victory_message":" Félicitations ! Vous avez triomphé des 5 combats de la Ligue Kanto et obtenez le Titre de Maître Pokémon !",
"add_pokemon":"Ajouter un Pokémon",
"team_count":"{count}/6 dans l'équipe",
"item_removed_team":"{item} retiré de l'équipe.",
"evolution_duplicate_bonus":" {name} aurait évolué en {target}, déjà possédé ! (+{money}₽)",
"evolution_duplicate_bonus_html":" {name} aurait évolué en <b>{target}</b>, déjà possédé ! (+{money}₽)",
"evolution_triggered_box":" {name} déclenche une évolution : {target} apparaît dans la boîte PC !",
"evolution_created_box":" Une évolution de {name} est née : <b>{target}</b> (Nv.1, → boîte) !",
"captured_pokemon_title":"Pokémon capturés :",
"found_items_title":"Objets trouvés :",
"map_help_title_attr":"Aide — code couleur de la carte",
"map_help_title":"Code couleur de la carte",
"map_help_green":"<b>Vert</b> — Une quête (principale ou secondaire) est à faire ici.",
"map_help_purple":"<b>Violet</b> — Un Pokémon légendaire errant est présent (non capturé).",
"map_help_blue":"<b>Bleu</b> — Des Pokémon sont encore à capturer.",
"map_help_yellow":"<b>Jaune</b> — Un shiny est encore à capturer.",
"map_help_gray":"<b>Gris</b> — Zone verrouillée (badge ou histoire manquant).",
"map_help_transparent":"<b>Transparent</b> — Zone terminée (tout est capturé).",
"no_save_found":"Aucune sauvegarde trouvée",
"game_loaded":"Partie chargée !",
"no_save_to_export":"Aucune sauvegarde à exporter",
"save_exported":"Sauvegarde exportée !",
"save_imported_reload":"Sauvegarde importée ! Rechargement...",
"save_deleted":"Sauvegarde supprimée",
"debug_x10_on":"Vitesse x10 activée",
"debug_x10_off":"Vitesse x10 désactivée",
"mine_found":"Trouvé : {item} !",
"mine_battle_log":"Souterrain : vous avez déterré {icon} <b>{item}</b> !",
"legacy_message_n_10_super_bonbons_ajout_s":"+10 Super Bonbons ajoutés !",
"legacy_message_n_50_000_ajout_s":"+50 000₽ ajoutés !",
"legacy_message_n_8_badges_d_bloqu_s":"8 Badges débloqués !",
"legacy_message_n_aucun_pok_mon_entra_ner":"Aucun Pokémon à entraîner !",
"legacy_message_n_capacit_s_pleines_4_oubliezen_une_dabord":"Capacités pleines (4). Oubliez-en une d'abord.",
"legacy_message_n_ce_pok_mon_conna_t_ou_a_d_j_d_bloqu_to":"Ce Pokémon connaît ou a déjà débloqué toutes les capacités disponibles pour son espèce !",
"legacy_message_n_ce_pok_mon_est_d_j_au_niveau_100_maximu":"Ce Pokémon est déjà au Niveau 100 maximum !",
"legacy_message_n_ce_pok_mon_poss_de_d_j_6_toiles_ev_sur":"Ce Pokémon possède déjà 6 étoiles EV sur toutes ses statistiques (36/66) !",
"legacy_message_n_erreur_lors_de_la_cr_ation_du_pok_mon":"Erreur lors de la création du Pokémon.",
"legacy_message_n_objectif_pas_encore_termin":"Objectif pas encore terminé !",
"legacy_message_n_partie_sauvegard_e":"Partie sauvegardée !",
"legacy_message_n_qu_te_d_j_active":"Quête déjà active.",
"legacy_message_n_qu_te_d_j_termin_e":"Quête déjà terminée.",
"legacy_message_n_qu_te_r_p_table_d_j_active":"Quête répétable déjà active.",
"legacy_message_n_sauvegarde_import_e":"Sauvegarde importée !",
"legacy_message_n_un_pok_mon_doit_conserver_au_moins_une_c":"Un Pokémon doit conserver au moins une capacité.",
"legacy_message_n_vous_poss_dez_d_j_cette_esp_ce":"Vous possédez déjà cette espèce !",
"legacy_message_n_nergie_de_mine_restaur_e_100":"Énergie de mine restaurée à 100 !",
"legacy_message_n_nergie_insuffisante_combattez_des_pok_m":"Énergie insuffisante ! Combattez des Pokémon sauvages pour recharger.",
"legacy_message_n2_cet_objet_na_aucun_effet_sur_ce_pok_mon":"Cet objet n'a aucun effet sur ce Pokémon.",
"woke_up_log":"{name} se réveille !",
"sleeping_turns_log":"{name} est endormi... ({turns} tour{plural})",
"thawed_log":"{name} se décongèle !",
"frozen_skip_log":"{name} est gelé...",
"paralyzed_skip_log":"{name} est paralysé et ne peut pas attaquer !",
"uses_move_log":"{name} utilise <b>{move}</b> !",
"forfeit_champion":"Vous abandonnez le combat contre {champion}. Vous pourrez le redéfier à tout moment.",
"leave_battle_notify":"Vous quittez le combat.",
"leaving_button":"Départ...",
"map_legend_title":"Légende de la carte",
"current_location":"Lieu actuel",
"reachable_location":"Lieu accessible",
"locked_location":"Lieu verrouillé",
"selector_title_hatchery":"Pension & Couveuse",
"selector_title_hatchery_queue":"Ajouter à la liste Pension",
"selector_title_training_queue":"Ajouter à la liste Entraînement — slot {slot}",
"selector_title_training":"Salle d'Entraînement",
"selector_title_team":"Sélection Équipe",
"selector_title_box":"Boîte PC",
"selector_title_item_use":"Utiliser un objet",
"equip_click_title":"Clic: équiper",
"sprite_click_context_title":"Clic gauche: équipe | Clic droit: infos",
"team_location_clean":"Équipe",
"box_pc_location":"Boîte PC",
"change_or_info_title":"Clic: changer | Clic droit: infos",
"sprite_team_info_title":"Clic gauche: équipe | Clic droit: infos",
"rarity_common_label":"Commun",
"rarity_uncommon_label":"Peu commun",
"rarity_rare_label":"Rare",
"rarity_unknown_label":"Inconnu",
"shop_default_name":"Boutique",
"battle_in_progress":"Combat en cours",
"battle_in_progress_no_training":"Combat en cours : impossible de lancer un entraînement.",
"training_in_progress_no_battle":"Entraînement en cours : impossible de lancer un autre combat.",
"management_trainers":"Entraîneurs",
"hatchery_trainers_soon":"Les trainers de pension arrivent bientôt dans une prochaine mise à jour de la pension.",
"training_trainers_soon":"Les trainers d’entraînement arrivent bientôt dans une prochaine mise à jour de l’entraînement.",
"save_menu_title":"PokéWorld",
"save_menu_subtitle":"Choisis une sauvegarde ou crée une nouvelle aventure.",
"save_menu_empty_title":"Aucune sauvegarde trouvée",
"save_menu_empty_desc":"Crée une nouvelle sauvegarde ou importe un fichier pour l’ajouter à la liste.",
"save_menu_new":"Nouvelle partie",
"save_menu_import":"Importer",
"save_menu_click_hint":"Cliquer pour lancer",
"save_menu_badges":"Badges",
"save_menu_pokedex":"Pokédex",
"save_menu_playtime":"Temps",
"save_menu_id":"ID",
"save_default_name":"Sauvegarde {num}",
"save_imported_name":"Sauvegarde importée",
"save_created":"Nouvelle sauvegarde créée !",
"save_imported_library":"Sauvegarde ajoutée à la liste !",
"save_profile_title":"Profil de la sauvegarde",
"save_profile_name":"Nom de la sauvegarde",
"save_profile_color":"Couleur de la carte",
"save_profile_background":"Fond de la carte",
"save_profile_apply":"Appliquer au menu des saves",
"save_profile_updated":"Profil de sauvegarde mis à jour !",
"save_profile_name_placeholder":"Nom de la save",
"save_color_blue":"Bleu",
"save_color_red":"Rouge",
"save_color_green":"Vert",
"save_color_purple":"Violet",
"save_color_gold":"Or",
"save_color_silver":"Argent",
"save_bg_classic":"Kanto — Rouge / Bleu",
"save_bg_goldsilver":"Johto — Or / Argent",
"save_bg_emerald":"Hoenn — Émeraude",
"save_bg_diamondpearl":"Sinnoh — Diamant / Perle",
"save_bg_blackwhite":"Unys — Noir / Blanc",
"save_bg_xy":"Kalos — X / Y",
"save_bg_forest":"Forêt animée",
"save_error_too_large":"Erreur : sauvegarde trop volumineuse",
"save_error_message":"Erreur lors de la sauvegarde : {message}",
"load_error_message":"Erreur lors du chargement : {message}",
"save_export_error":"Erreur lors de l’export",
"save_import_error":"Erreur lors de l’import : {message}",
"save_delete_error":"Erreur lors de la suppression",
"save_profile_icon":"Icône de la save (Pokémon en boîte PC)",
"save_icon_keep_current":"Garder l’icône actuelle",
"save_icon_no_box":"Aucun Pokémon en boîte PC disponible",
"save_need_starter":"Choisissez un starter avant de sauvegarder.",
"save_choose_starter_first":"Choisissez votre starter : la save sera créée juste après.",
"save_profile_choose_icon":"Choisir dans la boîte PC",
"save_profile_current_icon":"Icône actuelle",
"save_context_download":"Télécharger",
"save_context_import_overwrite":"Importer (écraser)",
"save_context_delete":"Supprimer",
"save_delete_confirm":"Supprimer définitivement cette sauvegarde ?",
"delete_save_title":"Supprimer cette sauvegarde ?",
"save_overwritten":"Sauvegarde écrasée !",
"afk_progress_summary":"AFK {time} : {wins} combats gagnés, {fainted} Pokémon K.O., +{money}₽.",
"afk_battle_log_summary":"⏱ AFK {time} : {wins} Pokémon sauvages vaincus, {fainted} Pokémon K.O. (+{money}₽).",
"afk_energy_summary":"AFK {time} : énergie de mine récupérée.",
"debug_timeskip_10m":"⏱ Timeskip AFK +10 min",
"debug_timeskip_unavailable":"Timeskip AFK indisponible.",
"afk_progress_lost_summary":"AFK {time} : perdu, toute l’équipe est K.O. ({wins} combats gagnés, +{money}₽).",
"afk_battle_log_lost_summary":"⏱ AFK {time} : perdu, toute l’équipe est K.O. après {wins} combats gagnés (+{money}₽).",
"afk_no_progress_summary":"AFK {time} : rien en cours à simuler.",
"afk_boss_won":"Pendant ton absence : combat majeur terminé — victoire !",
"afk_boss_lost":"Pendant ton absence : combat majeur terminé — défaite…",
"afk_party_ko_log":"⏱ AFK : votre équipe est K.O., la simulation s’arrête.",
"afk_error_resume":"Erreur pendant la simulation AFK : combat relancé.",
"afk_panel_title_return":"Retour AFK",
"afk_panel_title_debug":"Timeskip debug",
"afk_panel_status_ok":"Progression simulée avec succès.",
"afk_panel_status_lost":"Perdu : toute l’équipe est K.O.",
"afk_panel_status_empty":"Aucune ressource gagnée pendant cette période.",
"afk_panel_status_error":"Erreur pendant la simulation AFK.",
"afk_panel_duration":"Durée",
"afk_panel_battles":"Combats",
"afk_panel_money":"Argent",
"afk_panel_captures":"Captures",
"afk_panel_energy":"Énergie mine",
"afk_panel_training":"Entraînement",
"afk_panel_mine_digs":"Minages auto",
"afk_panel_daycare_levels":"Niv. garderie",
"afk_panel_boss_battle":"Combat clé",
"afk_ff_progress":"Calcul des gains hors-ligne… {pct} %",
"offline_ff_title":"⏳ Calcul du temps écoulé…",
"offline_stage_battles":"Combats sauvages…",
"offline_stage_boss":"Combat majeur en cours…",
"offline_stage_battles_wins":"Combats sauvages… · {wins} victoires",
"offline_stage_training":"Entraînement…",
"offline_stage_training_sessions":"Entraînement… · {n} sessions",
"offline_stage_mine":"Mine…",
"offline_stage_generic":"Calcul…",
"afk_panel_items":"Objets gagnés",
"afk_none":"Aucun",
"afk_panel_team_ko":"Pokémon K.O.",
"team_slot_name":"Slot équipe {slot}",
"afk_captures_normal":"Normaux",
"afk_captures_shiny":"Shiny",
"duplicate_short":"doublon(s)",
"region_kanto":"Kanto",
"region_johto":"Johto",
"region_hoenn":"Hoenn",
"panel_puzzles_title":"🧩 Explorations à énigmes",
"puzzle_explore_btn":"Explorations à énigmes",
"shiny_charm_regional_hint":"Bonus shiny actif sur les régions au Pokédex 100 %.",
"region_sinnoh":"Sinnoh",
"region_locked_league":"Accès à {target} verrouillé : bats d’abord la Ligue de {region}.",
"region_locked_dex":"Accès à {target} verrouillé : complète d’abord le Pokédex de {region} ({caught}/{total}).",
"region_locked_generic":"Accès à {target} verrouillé.",
"region_team_restricted":"À {region}, avant de battre la Ligue locale, seuls les Pokémon de {region} peuvent combattre. À retirer : {pokemon}.",
"league_battle_challenge_region":"LIGUE {region} - Combat 1/5 : {trainer} vous défie !",
"league_master_victory_log_region":"Vous avez vaincu le Maître de {region} et triomphé des 5 combats de la Ligue !",
"league_master_title_reward_region":"Félicitations ! Vous obtenez le Titre de Maître {region} ! (+{money}₽)",
"league_victory_message_region":"Félicitations ! Vous avez triomphé des 5 combats de la Ligue {region} !",
"league_next_battle_region":"LIGUE {region} - Combat {stage}/5 : {trainer} envoie {pokemon} !",
"pokedex_regions":"Régions visibles",
"box_filter_region":"Région",
"box_filter_type":"Type",
"box_filter_shiny":"Shiny",
"box_filter_evolution":"Évolution",
"box_filter_all_regions":"Toutes",
"box_filter_all_types":"Tous",
"box_filter_all_shiny":"Tous",
"box_filter_shiny_only":"Shiny",
"box_filter_non_shiny_only":"Non shiny",
"box_filter_all_evo":"Toutes",
"box_filter_evo_missing":"Évolution possible non obtenue",
"box_filter_reset":"Réinitialiser",
"box_filter_favorite":"Favori",
"box_filter_all_favorites":"Tous",
"box_filter_favorite_only":"Favoris",
"box_filter_not_favorite":"Non favoris",
"box_filter_locked":"Verrouillage",
"box_filter_all_locked":"Tous",
"box_filter_locked_only":"Verrouillés",
"box_filter_unlocked_only":"Non verrouillés",
"box_filter_iv":"IV",
"box_filter_ev":"EV",
"box_filter_rank":"Rang",
"box_filter_all_ranks":"Tous",
"box_filter_all_ev":"Tous",
"box_filter_ev_complete":"EV complets",
"box_filter_ev_incomplete":"EV incomplets",
"auto_sort_ev_asc":"EV les plus bas",
"auto_sort_ev_desc":"EV les plus hauts",
"auto_sort_talent_missing":"Talents manquants",
"auto_sort_move_missing":"Attaques manquantes",
"auto_sort_level_missing":"Niveau manquant",
"box_filter_all_iv":"Tous",
"box_filter_iv_complete":"IV complets",
"box_filter_iv_incomplete":"IV incomplets",
"filters_title":"Filtres",
"quest_battle_btn":"Combattre",
"quest_battle_started":"Combat de quête : {quest}",
"quest_battle_none":"Aucune quête de combat active ici.",
"quest_battle_title":"Quête locale",
"quest_reward_battle_active":"Un combat est déjà en cours : terminez-le avant de défier ce Pokémon.",
"quest_battle_stop_current":"Combat actuel arrêté : lancement du défi...",
"quest_reward_battle_started":"Défi lancé : {pokemon} vous attend en combat !",
"shiny_skin_on":"Sprite shiny activé",
"shiny_skin_off":"Sprite normal activé",
"duplicate_item_money_log":"Objet déjà possédé : {item} converti en +{money}₽.",
"capture_duplicate_no_money":"{name} était déjà possédé : aucun Pokédollar gagné.",
"rematch_no_money":"Victoire de revanche : aucun Pokédollar gagné.",
"fossil_not_sellable":"Les fossiles ne sont pas vendables.",
"repeatable_slots":"Slots de quêtes répétables",
"repeatable_upgrades":"Améliorations répétables",
"repeatable_reroll_timer":"Reroll gratuit : {time}",
"repeatable_reroll_wait":"Reroll disponible dans {time}",
"repeatable_slots_full":"Slots pleins",
"repeatable_slots_current":"Slots actuels : {count}/{max}",
"repeatable_slot_upgrade_buy":"Débloquer le slot {next} ({price}₽)",
"repeatable_slots_max":"Tous les slots répétables sont débloqués.",
"repeatable_reroll_free_desc":"Le reroll est gratuit toutes les 10 minutes. Aucun reroll payant.",
"repeatable_slot_upgraded":"Slots de quêtes répétables : {count}.",
"hatchery_management_title":"Gestion Pension",
"hatchery_management_button":"Gestion Pension",
"hatchery_slots_title":"Améliorations de slots",
"hatchery_slots_current":"Slots actuels : {count}/{max}",
"hatchery_automation_title":"Automatisations Pension",
"hatchery_automation_desc":"Achète d’abord un module, puis active ou désactive son comportement.",
"automation_autoHatch_desc":"Éclos automatiquement les œufs prêts.",
"automation_autoSeedHatchery_desc":"Remplit automatiquement les slots libres depuis la boîte PC.",
"automation_buy_button":"Acheter ({price}₽)",
"automation_owned":"Acheté",
"automation_locked_upgrade":"À débloquer dans Améliorations",
"staff_xp_bar":"XP {xp}/{need}",
"staff_level_short":"Niv. {level}",
"automation_enabled":"Activé",
"automation_disabled":"Désactivé",
"training_auto_on":"Auto : activé",
"training_auto_off":"Auto : désactivé",
"automation_already_bought":"Automatisation déjà achetée.",
"hatchery_slots_max":"Tous les slots de pension sont débloqués.",
"automation_autoHatch":"Éclosion automatique",
"automation_autoSeedHatchery":"Remplissage automatique",
"automation_upgrade_need_money":"Amélioration trop chère : {price}₽ requis.",
"automation_upgrade_bought":"Amélioration achetée : {name} ({price}₽).",
"training_slots":"Slots entraînement",
"training_slots_current":"Slots actuels : {count}/{max}",
"training_multi_slot_buy":"Débloquer le 2e slot ({price}₽)",
"training_multi_slot_bought":"Deuxième slot d’entraînement débloqué.",
"training_multi_slot_max":"Le deuxième slot d’entraînement est déjà débloqué.",
"training_multi_slot_note":"Le deuxième slot débloque un vrai combat d’entraînement parallèle : tu peux assigner un autre Pokémon et lancer deux entraînements en même temps.",
"training_upgrades":"Améliorations",
"training_center_title":"Centre d'entraînement",
"training_parallel_hint":"Chaque slot lance son propre combat d’entraînement en parallèle.",
"training_slot_title":"Slot {slot}",
"training_slot_empty":"Aucun Pokémon assigné à ce slot.",
"training_slot_choose":"Ajouter un Pokémon",
"training_slot_change":"Changer le Pokémon",
"training_slot_active":"Combat en cours",
"training_slot_time_left":"{time} restant",
"training_slot_busy":"Ce slot est déjà en combat d’entraînement.",
"training_slot_no_pokemon":"Aucun Pokémon dans ce slot.",
"training_slot_started":"Entraînement lancé pour {name} ({mode}).",
"training_slot_failed":"Entraînement échoué pour {name}. Le coach était trop fort.",
"training_slot_cancel":"Abandonner",
"training_slot_cancelled":"Entraînement annulé.",
"training_slot_missing":"Pokémon d’entraînement introuvable.",
"training_slot_locked":"2e slot verrouillé",
"training_slot_last_success":"Dernier résultat : {mode} réussi{reward}",
"training_slot_last_failed":"Dernier résultat : {mode} échoué",
"selector_title_training_slot":"Salle d'Entraînement — slot {slot}",
"selected_for_training_slot":"{name} sélectionné pour le slot {slot} !",
"training_mode_move_title":"Discipline Capacités",
"training_mode_move_desc":"Débloque une attaque verrouillée par entraînement.",
"training_mode_move_done":"Toutes les attaques d’entraînement sont déjà débloquées.",
"training_mode_talent_title":"Atelier Talents",
"training_mode_talent_desc":"Tente d’obtenir un talent de la liste du Pokémon.",
"training_mode_talent_done":"Tous les talents disponibles sont déjà débloqués.",
"training_mode_ev_title":"Stage EV ciblé",
"training_mode_ev_desc":"Gagne exactement 1 EV aléatoire.",
"training_mode_ev_done":"EV au maximum.",
"training_mode_level_title":"Stage Niveau",
"training_mode_level_desc":"Gagne entre 2 et 5 niveaux.",
"training_mode_level_done":"Niveau 100 atteint.",
"management_upgrades":"Améliorations",
"management_automation":"Automatisation",
"training_management_title":"Gestion entraînement",
"training_management_button":"Gestion entraînement",
"training_automation_title":"Automatisations d’entraînement",
"training_automation_desc":"Vue des slots d’entraînement prête pour les futures automatisations.",
"training_live_title":"Combats d’entraînement en direct",
"training_live_running":"Entraînements en cours",
"training_live_waiting":"Le combat commence...",
"training_live_visible_hint":"Combat visible dans le panneau Combat en direct.",
"training_live_started":"{name} commence un entraînement {mode} contre {enemy}.",
"training_live_hit":"{name} utilise {move} sur {target} : {damage} dégâts.",
"training_live_miss":"{name} rate {move}.",
"training_live_no_effect":"Ça n’a aucun effet sur {name}.",
"training_live_status_move":"{move} prépare le rythme du combat.",
"training_live_next_round":"Round {round}/{total} : {enemy} entre en scène. Votre Pokémon est soigné.",
"training_live_enemy_down":"{enemy} est K.O. !",
"training_round_label":"Round {round}/{total}",
"pokemon_favorite_on":"Favori",
"pokemon_favorite_off":"Marquer favori",
"pokemon_locked_on":"Verrouillé",
"pokemon_locked_off":"Verrouiller",
"automation_rules":"Règles automatiques",
"auto_filter_shiny":"Shiny",
"auto_sort_iv_desc":"Meilleurs IV d’abord",
"auto_sort_iv_asc":"Plus faibles IV d’abord",
"auto_sort_level_desc":"Plus haut niveau d’abord",
"auto_sort_level_asc":"Plus bas niveau d’abord",
"auto_sort_dex":"Ordre Pokédex",
"queue_build":"Générer la liste d’attente",
"queue_waiting_list":"Liste d’attente",
"queue_empty":"Liste d’attente vide.",
"queue_manual_hint":"Ajoutez les Pokémon manuellement depuis la boîte PC. La liste existe même avant d’acheter l’automatisation.",
"queue_add_from_box":"Listes d’attente",
"queue_add_hatchery":"Ajouter à la pension",
"queue_add_training_slot1":"Ajouter entraînement slot 1",
"queue_add_training_slot2":"Ajouter entraînement slot 2",
"queue_already_added_short":"Déjà en liste",
"queue_clear":"Vider la liste",
"queue_capacity":"Capacité : {count}/{max}",
"queue_upgrade_buy":"Améliorer la liste à {count} places ({price}₽)",
"queue_size_maxed":"Taille de liste au maximum.",
"queue_size_upgraded":"Taille de liste améliorée : {count} places.",
"queue_size_title":"Taille de liste d’attente",
"queue_full":"Liste d’attente pleine ({count}).",
"queue_locked_rejected":"Pokémon verrouillé : impossible de l’ajouter à une liste auto.",
"queue_team_rejected":"Pokémon dans une équipe : impossible de l’ajouter à une liste auto.",
"queue_already_busy":"Ce Pokémon est déjà occupé.",
"queue_already_other":"Ce Pokémon est déjà dans une autre liste d’attente.",
"queue_already_added":"Ce Pokémon est déjà dans cette liste.",
"queue_added_hatchery":"{name} ajouté à la liste d’attente pension.",
"queue_added_training":"{name} ajouté à la liste d’attente entraînement slot {slot}.",
"queue_refreshed":"Liste d’attente rafraîchie.",
"hatchery_queue_built":"Liste d’attente pension : {count} Pokémon.",
"training_queue_built":"Slot {slot} : {count} Pokémon en liste d’attente.",
"training_auto_mode":"Mode auto",
"training_auto_mode_all":"Tout faire",
"training_no_available":"Ce Pokémon n’a plus aucun entraînement disponible.",
"training_no_available_for_mode":"Ce Pokémon n’a plus d’entraînement disponible pour ce mode.",
"management_miners":"Mineurs",
"hatchery_managers_title":"Gérants",
"training_trainers_title":"Entraîneurs",
"staff_active":"Actifs",
"staff_bonus":"Bonus",
"staff_bonus_hatchery_speed":"Vitesse d'incubation / Pension",
"staff_bonus_hatchery_cost":"Réduction des Frais de Pension",
"staff_bonus_hatchery_shiny":"Chance d'Œuf Shiny",
"staff_bonus_hatchery_exp":"Boost d'Expérience Pension",
"staff_bonus_hatchery_double_iv_level":"Double IV / Niveau d'Œuf",
"staff_bonus_training_exp":"Gain d'XP Entraînement",
"staff_bonus_training_kill_reduction":"Réduction des K.O. requis",
"staff_bonus_training_cost":"Réduction des Frais d'Entraînement",
"staff_bonus_training_crit":"Chance de Succès Critique",
"staff_bonus_training_drop":"Butin de Fin de Stage",
"staff_bonus_mine_energy_cost":"Réduction Consommation d'Énergie",
"staff_bonus_mine_energy_regen":"Vitesse Recharge Énergie",
"staff_bonus_mine_value":"Valeur de Revente des Trésors",
"staff_bonus_mine_extra_items":"Objets Supplémentaires par Couche",
"staff_bonus_mine_energy_max":"Énergie Maximale",
"staff_name_manager_saffron":"Gérant Sacha",
"staff_desc_manager_saffron":"Spécialiste de l’éclosion régulière et des cycles longs.",
"staff_name_manager_cinnabar":"Chercheuse Ambre",
"staff_desc_manager_cinnabar":"Chercheuse de laboratoire, utile pour les longues files de pension.",
"staff_name_manager_goldenrod":"Gérante Flora",
"staff_desc_manager_goldenrod":"Gérante Johto expérimentée, pensée pour la pension avancée.",
"staff_name_trainer_fuchsia":"Coach Nina",
"staff_desc_trainer_fuchsia":"Entraîneuse d’endurance pour sécuriser les combats longs.",
"staff_name_trainer_indigo":"Coach Indigo",
"staff_desc_trainer_indigo":"Coach d’élite pour l’entraînement haut niveau.",
"staff_name_trainer_blackthorn":"Maître Draco",
"staff_desc_trainer_blackthorn":"Entraîneur exigeant, spécialisé dans les gros Pokémon.",
"staff_name_miner_cerulean":"Spéléologue Azur",
"staff_desc_miner_cerulean":"Mineur précis qui réduit les pertes d’énergie.",
"staff_name_miner_mahogany":"Mineur Givre",
"staff_desc_miner_mahogany":"Mineur de Johto habitué aux couches profondes.",
"staff_name_miner_blackthorn":"Foreuse Sandra",
"staff_desc_miner_blackthorn":"Experte minière d’Ébénelle pour les longues sessions.",
"staff_already_owned":"Employé déjà recruté.",
"staff_location_locked":"Employé indisponible : débloquez {loc}.",
"staff_hired":"{name} recruté !",
"staff_active_limit":"Limite d’employés actifs atteinte ({count}).",
"staff_level_up":"{name} passe niveau {level} !",
"staff_level":"Niveau {level} · XP {xp}/{need}",
"staff_active_on":"Actif",
"staff_active_off":"Inactif",
"staff_hire_price":"Recruter ({price}₽)",
"staff_unlock_at":"Débloquer {loc}",
"staff_name_manager_daisy":"Gérante Daisy",
"staff_desc_manager_daisy":"Réduit progressivement le nombre de K.O. nécessaires à l’éclosion.",
"staff_name_manager_celadon":"Gérante Mila",
"staff_desc_manager_celadon":"Optimise la pension et prépare les futures règles avancées de file d’attente.",
"staff_name_trainer_vermilion":"Coach Armand",
"staff_desc_trainer_vermilion":"Rend les combats d’entraînement légèrement plus favorables.",
"staff_name_trainer_saffron":"Maître Soren",
"staff_desc_trainer_saffron":"Spécialiste des entraînements avancés, prêt pour les futures automatisations.",
"staff_name_miner_pewter":"Mineur Roch",
"staff_desc_miner_pewter":"Réduit progressivement le coût d’énergie des outils.",
"staff_name_miner_cinnabar":"Foreur Vulcain",
"staff_desc_miner_cinnabar":"Spécialiste de l’endurance minière, prêt pour les futurs outils.",
"mine_management_title":"Gestion Mine",
"mine_management_button":"Gestion Mine",
"mine_auto_title":"Mine automatique",
"mine_energy_upgrade_title":"Énergie de mine",
"mine_energy_current":"Énergie max actuelle : {energy}",
"mine_energy_upgrade_buy":"Augmenter l’énergie max (+25) ({price}₽)",
"mine_energy_upgraded":"Énergie max de la mine : {energy}.",
"mine_energy_maxed":"Énergie de mine au maximum.",
"mine_tools_title":"Outils",
"mine_tool_chisel":"Burin",
"mine_tool_hammer":"Marteau",
"mine_tool_pickaxe":"Pioche renforcée",
"mine_tool_drill":"Foreuse",
"mine_tool_dynamite":"Dynamite",
"mine_tool_owned":"Outil déjà débloqué.",
"mine_tool_locked":"Outil non débloqué.",
"mine_tool_bought":"Outil débloqué : {tool}.",
"mine_tools_soon":"De nouveaux outils plus puissants arriveront dans une prochaine passe de la mine.",
"mine_miners_soon":"Les mineurs arrivent bientôt dans une prochaine mise à jour de la mine.",
"trainer_battle":"Combat de dresseur",
"trainer_role_rival":"Rival",
"trainer_role_rocket":"Team Rocket",
"trainer_role_boss":"Boss",
"trainer_role_gym":"Arène",
"trainer_role_league":"Ligue",
"trainer_role_atoll":"Atoll",
"trainer_role_trainer":"Dresseur",
"trainer_role_sage":"Sage",
"trainer_style_balanced":"Équilibré",
"trainer_style_speed":"Vitesse",
"trainer_style_special":"Spécial",
"trainer_style_poison":"Poison",
"trainer_style_ground":"Sol",
"trainer_style_boss":"Boss",
"trainer_style_rocket":"Rocket",
"trainer_style_status":"Statut",
"trainer_style_tank":"Tank",
"trainer_style_defense":"Défense",
"trainer_style_water":"Eau",
"trainer_style_electric":"Électrik",
"trainer_style_grass":"Plante",
"trainer_style_fire":"Feu",
"trainer_style_psychic":"Psy",
"trainer_style_fighting":"Combat",
"trainer_style_ghost":"Spectre",
"trainer_style_dragon":"Dragon",
"trainer_style_offense":"Offense",
"trainer_style_bulk":"Résistance",
"trainer_style_coverage":"Couverture",
"trainer_style_fast":"Rapide",
"trainer_style_early":"Début",
"trainer_style_science":"Science",
"trainer_style_starter":"Starter",
"trainer_style_aggressive":"Agressif",
"trainer_style_tower":"Tour",
"trainer_style_atoll":"Atoll",
"trainer_style_tower_c":"Tour C",
"trainer_style_tower_b":"Tour B",
"trainer_style_tower_a":"Tour A",
"trainer_style_tower_free":"Libre",
"trainer_style_factory_c":"Usine C",
"trainer_style_factory_a":"Usine A",
"trainer_style_arena_three":"3 Pokémon",
"trainer_style_arena_no_item":"Sans confort",
"trainer_style_arena_type":"Types",
"trainer_style_dome_quarter":"Dôme",
"trainer_style_dome_final":"Finale",
"trainer_style_rage":"Colère",
"trainer_style_champion_prep":"Pré-Ligue",
"trainer_battle_target":"Adversaire : {trainer}",
"trainer_battle_hint":"Combat de quête : le combat actuel sera arrêté si besoin, puis la quête se valide après victoire.",
"trainer_battle_name_kanto_rocket_tower":"Sbire Rocket",
"trainer_battle_intro_kanto_rival_route22":"Te voilà enfin ! J'ai choisi le starter parfait pour écraser le tien. En garde !",
"trainer_battle_intro_hoenn_poochyena_route101":"Grrr... Wouf ! (Le Medhyèna sauvage vous attaque !)",
"trainer_battle_intro_kanto_rocket_mtmoon":"Des fossiles par ici ? Ils sont à nous ! La Team Rocket prend tout !",
"trainer_battle_intro_kanto_super_nerd_fossil":"Mes recherches prouvent que mes Pokémon Électrik sont supérieurs. Démonstration !",
"trainer_battle_intro_kanto_dojo_master":"Le Dojo de Safrania n'abdique jamais ! Affronte mes deux champions des arts martiaux… si tu en es digne. HYAH !",
"trainer_battle_intro_kanto_rival_cerulean":"Encore toi ? J'ai capturé plein de Pokémon balaises depuis la dernière fois. Tiens-toi prêt !",
"trainer_battle_intro_kanto_rival_ssanne":"Le gratin de Kanto est à bord, et toi tu n'es pas invité ! Je vais te jeter par-dessus bord !",
"trainer_battle_intro_kanto_rocket_tower":"Cette tour est la nôtre ! Les Pokémon morts ne se plaignent pas… et toi non plus, bientôt !",
"trainer_battle_intro_kanto_rocket_hideout":"Halte ! Personne ne passe jusqu'à l'antre du boss. Même pas en rêve !",
"trainer_battle_intro_kanto_giovanni_hideout":"Tu veux défaire ce que j'ai mis des années à bâtir ? Quelle audace. Permets-moi de t'écraser proprement.",
"trainer_battle_intro_kanto_rival_silph":"T'as vu tout ce grabuge ? Parfait pour s'entraîner ! D'abord toi, ensuite la Team Rocket !",
"trainer_battle_intro_kanto_giovanni_silph":"La Sylphe me fabriquera la Master Ball, et toi, tu n'es qu'un obstacle de plus à balayer.",
"trainer_battle_intro_kanto_rival_victory":"Une dernière fois avant la Ligue ! Si tu perds ici, tu ne mérites pas d'y aller. Vas-y, à fond !",
"trainer_battle_intro_johto_rival_cherrygrove":"Ce starter ? Je l'ai pris, il est à moi. Et maintenant, je vais te montrer à quel point tu es faible !",
"trainer_battle_intro_johto_sprout_elder":"Jeune dresseur, la tour juge ton cœur autant que ta force. Montre-moi ta sérénité.",
"trainer_battle_intro_johto_rocket_slowpoke":"Les queues de Ramoloss rapportent un max ! Personne ne nous arrêtera, et encore moins un gamin !",
"trainer_battle_intro_johto_rival_ilex":"Encore toi ? Je vais te prouver que la gentillesse ne mène nulle part. Combat !",
"trainer_battle_intro_johto_rival_burned":"Ces ruines cachent de vrais monstres de puissance… et toi tu continues de suivre tes rêves de gamin ?",
"trainer_battle_intro_johto_rocket_lake":"Le signal force l'évolution des Magicarpe ! Génial, non ? La Team Rocket renaît par la rage !",
"trainer_battle_intro_johto_rocket_radio":"Giovanni nous a abandonnés, mais nous bâtirons un empire à sa place ! La Tour Radio est le premier pas !",
"trainer_battle_intro_johto_rival_victory":"Un dernier combat. Si tu gagnes, je saurai enfin ce qui te rend si fort. Viens !",
"trainer_battle_win_kanto_rival_route22":"Hein ? J'ai perdu ?! Tu as juste eu de la chance cette fois !",
"trainer_battle_win_hoenn_poochyena_route101":"Kaii !! (Le Medhyèna s'enfuit dans les hautes herbes !)",
"trainer_battle_win_kanto_rocket_mtmoon":"Nom d'un Rattata… Le boss entendra parler de toi !",
"trainer_battle_win_kanto_super_nerd_fossil":"Fascinant… Tes données de combat dépassent toutes mes projections !",
"trainer_battle_win_kanto_dojo_master":"HAÏ… Ta force intérieure dépasse mes coups ! Prends ce Tyrogue : élève-le dans la voie du pied ou du poing !",
"trainer_battle_win_kanto_rival_cerulean":"Pfff… Tu progresses vite, je l'admets. Mais ce n'est pas fini entre nous !",
"trainer_battle_win_kanto_rival_ssanne":"OK, OK ! Tu es plus fort que je ne le pensais. Amuse-toi bien à Carmin, je file !",
"trainer_battle_win_kanto_rocket_tower":"Reculez, reculez ! La Team Rocket ne perd JAMAIS… enfin, presque jamais !",
"trainer_battle_win_kanto_rocket_hideout":"Impossible… Le boss va me renvoyer au trou à Rattata !",
"trainer_battle_win_kanto_giovanni_hideout":"Incroyable… La Team Rocket est finie… du moins ici. Souviens-toi de moi.",
"trainer_battle_win_kanto_rival_silph":"T'es devenu vraiment bon… Bon, maintenant file ! La Sylphe a besoin de toi.",
"trainer_battle_win_kanto_giovanni_silph":"Vu ta valeur, je te laisse la Sylphe… pour cette fois. La Team Rocket s'en souviendra.",
"trainer_battle_win_kanto_rival_victory":"…Tu m'as battu. Vraiment. Va là-bas et deviens le meilleur, d'accord ? C'est un ordre !",
"trainer_battle_win_johto_rival_cherrygrove":"Tch… Tu crois que ça change quelque chose ? Seule la puissance compte !",
"trainer_battle_win_johto_sprout_elder":"Ta flamme brille avec douceur. La tour te reconnaît digne.",
"trainer_battle_win_johto_rocket_slowpoke":"Aaargh ! Retraite ! Le trafic reprendra sans toi !",
"trainer_battle_win_johto_rival_ilex":"Pourquoi… Pourquoi je perds contre quelqu'un qui aime ses Pokémon ?!",
"trainer_battle_win_johto_rival_burned":"Tes Pokémon se battent POUR toi… C'est peut-être ça, la vraie force. …Laisse-moi.",
"trainer_battle_win_johto_rocket_lake":"Le repaire est perdu… mais le Lac Colère gardera sa rage…",
"trainer_battle_win_johto_rocket_radio":"L'appel à Giovanni ne partira jamais… La Team Rocket… c'est fini pour de bon…",
"trainer_battle_win_johto_rival_victory":"…Merci. Maintenant je sais. Ce n'est pas la force brute… c'est le lien. Va gagner la Ligue.",
"trainer_battle_name_johto_film3_entei":"Prof. Hale (illusion)",
"trainer_battle_intro_johto_film3_entei":"Les glyphes s'embrasent… L'Entei cristallin rugit depuis le monde de cristal !",
"trainer_battle_win_johto_film3_entei":"L'illusion se fissure… les Ruines respirent à nouveau.",
"item_not_holdable":"{item} ne peut pas être tenu par un Pokémon.",
"already_equipped_by_name":"{item} est déjà équipé par {name}.",
"quest_item_obtained":"{item} obtenu !",
"quest_item_obtain":"Objectif : obtenir {item}.",
"trainer_battle_name_kanto_rival_route22":"Blue",
"trainer_battle_name_hoenn_poochyena_route101":"Medhyèna sauvage",
"trainer_battle_name_kanto_rocket_mtmoon":"Sbire Rocket",
"trainer_battle_name_kanto_super_nerd_fossil":"Intello Miguel",
"trainer_battle_name_kanto_dojo_master":"Karatéka Karuo",
"trainer_battle_name_kanto_rival_cerulean":"Blue",
"trainer_battle_name_kanto_rival_ssanne":"Blue",
"trainer_battle_name_kanto_rocket_hideout":"Admin Rocket",
"trainer_battle_name_kanto_giovanni_hideout":"Giovanni",
"trainer_battle_name_kanto_rival_silph":"Blue",
"trainer_battle_name_kanto_giovanni_silph":"Giovanni",
"trainer_battle_name_kanto_rival_victory":"Blue",
"trainer_battle_name_johto_rival_cherrygrove":"Silver",
"trainer_battle_name_johto_sprout_elder":"Sage Li",
"trainer_battle_name_johto_rocket_slowpoke":"Sbire Rocket",
"trainer_battle_name_johto_rival_ilex":"Silver",
"trainer_battle_name_johto_rival_burned":"Silver",
"trainer_battle_name_johto_rocket_lake":"Exécutif Rocket",
"trainer_battle_name_johto_rocket_radio":"Exécutif Rocket",
"trainer_battle_name_johto_rival_victory":"Silver",
"trainer_battle_done":"Combat remporté",
"trainer_battle_won":"{trainer} vaincu !",
"battle_atoll_title":"Atoll de Combat",
"battle_atoll_desc":"L’endgame de PokéWorld : rotation toutes les 12 h avec minuteur visible, 6 équipes tournantes par format en cycle de 3 jours à graine datée, bans de légendaires rotatifs et Usine à équipe prêtée. Le vrai défi.",
"atoll_tokens":"Jetons Atoll",
"atoll_tower":"Tour Combat",
"atoll_locked":"Atoll verrouillé : bats d’abord la Ligue Kanto.",
"atoll_locked_desc":"L’Atoll de Combat se débloque après la Ligue Kanto. Il servira de premier endgame alpha avec plusieurs formats et une boutique dédiée.",
"atoll_modes":"Modes de combat",
"atoll_home":"Accueil",
"atoll_factory":"Usine Combat",
"atoll_arena":"Arène Combat",
"atoll_dome":"Dôme Combat",
"atoll_rental":"Prêt",
"atoll_tower_desc":"Séries classiques par rang (E→S) ou libre. 6 équipes tournantes par rang, renouvelées toutes les 12 h. La Tour S bannit 4 légendaires par rotation — la Tour Libre, jamais : c’est leur refuge.",
"atoll_factory_desc":"Équipe PRÊTÉE imposée, en série : chaque victoire soigne puis RÉORGANISE l’ordre de tes Pokémon ET de leurs attaques. L’adversaire grimpe la table de rotation (+25 % de jetons par palier). La défaite termine la série.",
"atoll_arena_desc":"Formats courts à restriction (3 Pokémon, sans objets, pression des types) contre des équipes tournantes à graine datée.",
"atoll_dome_desc":"Formats longs de type tournoi, grosses récompenses. La Finale bannit 3 légendaires par rotation.",
"atoll_tower_c":"Tour Combat — Rang C max",
"atoll_tower_c_desc":"Série accessible avec Pokémon moyens.",
"atoll_tower_b":"Tour Combat — Rang B max",
"atoll_tower_b_desc":"Difficulté intermédiaire avec équipes plus solides.",
"atoll_tower_a":"Tour Combat — Rang A max",
"atoll_tower_a_desc":"Format avancé pour équipes bien préparées.",
"atoll_tower_free":"Tour Combat — Libre",
"atoll_tower_free_desc":"Format libre, adversaires puissants.",
"atoll_factory_c":"Usine Combat — Standard",
"atoll_factory_c_desc":"Pokémon prêtés, difficulté moyenne.",
"atoll_factory_a":"Usine Combat — Expert",
"atoll_factory_a_desc":"Pokémon prêtés plus puissants, meilleurs jetons.",
"atoll_arena_three":"Arène Combat — 3 Pokémon",
"atoll_arena_three_desc":"Ton équipe est limitée à ses 3 premiers Pokémon.",
"atoll_arena_no_item":"Arène Combat — Sans confort",
"atoll_arena_no_item_desc":"Format court plus rude, pensé pour les rôles clairs.",
"atoll_arena_type":"Arène Combat — Pression type",
"atoll_arena_type_desc":"Combat court avec couverture de types plus punissante.",
"atoll_dome_quarter":"Dôme Combat — Demi-tournoi",
"atoll_dome_quarter_desc":"Adversaire solide, récompense élevée.",
"atoll_dome_final":"Dôme Combat — Finale",
"atoll_dome_final_desc":"Équipe complète et très forte, grosse récompense.",
"atoll_mode_rule":"Nv.{level} · {size} Pokémon · +{reward} jetons",
"atoll_mode_tower":"Tour Combat",
"atoll_mode_tower_desc":"Format classique : équipe polyvalente et difficulté stable.",
"atoll_mode_arena":"Arène Sprint",
"atoll_mode_arena_desc":"Combat court en petit format, plus direct et plus rapide.",
"atoll_mode_dome":"Dôme Combat",
"atoll_mode_dome_desc":"Combat long contre une équipe complète, récompense plus élevée.",
"atoll_mode_factory":"Usine Combat",
"atoll_mode_factory_desc":"Équipes variées et moins prévisibles, inspirées de l’Usine Combat.",
"atoll_shop":"Boutique Atoll",
"atoll_start":"Combattre",
"atoll_rank_rule":"Rang max {rank} · Nv.{level} · +{reward} jetons",
"atoll_max_rank":"Rang max {rank}",
"atoll_rank_free":"Libre",
"atoll_rank_blocked":"Rang max {rank} requis. À retirer : {pokemon}.",
"atoll_tower_e":"Tour Combat — Rang E max",
"atoll_tower_e_desc":"Format faible rang niveau 100 : petits Pokémon, vrais choix stratégiques.",
"atoll_tower_d":"Tour Combat — Rang D max",
"atoll_tower_d_desc":"Pokémon modestes niveau 100, récompense faible mais format très varié.",
"atoll_tower_s":"Tour Combat — Rang S max",
"atoll_tower_s_desc":"Format endgame complet avec Pokémon puissants niveau 100.",
"atoll_streak":"Série {streak} · Record {best}",
"atoll_win_reward":"Victoire Atoll : +{tokens} jetons · série {streak}",
"atoll_not_enough_tokens":"Pas assez de Jetons Atoll.",
"atoll_item_bought":"Objet Atoll acheté : {item}.",
"atoll_streak_lost":"Série Atoll interrompue.",

"atoll_rotation_timer":"Rotation dans {time}",
"atoll_cycle_info":"Équipe {n}/{total} · Jour {day}/{days} du cycle",
"atoll_banned_row":"Légendaires bannis cette rotation :",
"atoll_banned_blocked":"Légendaire banni cette rotation. À retirer : {pokemon}.",
"atoll_ban_free_note":"Aucun ban ici : le refuge des légendaires.",
"atoll_enemy_preview":"Équipe adverse de la rotation :",
"atoll_rental_preview":"Équipe prêtée de la rotation :",
"atoll_mode_rule_factory":"Nv.{level} · {size} prêtés · +{reward} jetons de base",
"atoll_factory_continue":"Combattre",
"atoll_factory_prep_open":"⚙ Organiser l'équipe prêtée",
"atoll_factory_run_title":"Série Usine en cours",
"atoll_factory_run_streak":"Palier {streak} · {mode}",
"atoll_factory_reorg_hint":"Après chaque victoire, l’équipe prêtée est soignée puis réorganisée (ordre des Pokémon ET des attaques), et l’adversaire passe à l’équipe de rotation suivante (+25 % de jetons par palier).",
"atoll_factory_abandon":"Abandonner la série",
"atoll_factory_reorg_notice":"Équipe prêtée soignée et réorganisée !",
"atoll_factory_wrong_mode":"Série Usine en cours dans : {mode}. Termine-la ou abandonne-la d’abord.",
"atoll_factory_broken":"Équipe prêtée indisponible pour cette rotation.",
"atoll_factory_run_ended":"Série Usine terminée.",
"atoll_factory_prep_hint":"Avant le combat, glisse-dépose les Pokémon et leurs attaques pour choisir l’ordre (le premier Pokémon est envoyé en premier). Objets, talents et attaques ne peuvent pas être modifiés : seule leur position compte.",
"atoll_factory_order_poke":"Ordre du Pokémon",
"atoll_factory_order_move":"Ordre de l’attaque",
"training_slot_next_from_queue":"{name} (file d’attente) prend le slot {slot}.",
"roaming_rotation_timer":"Rotation dans {time}",
"mirage_rotation_timer":"L'île change dans {time}",
"mirage_island_present":"L'Île Mirage est visible !",
"mirage_island_absent":"L'Île Mirage a disparu dans la brume…",
"pokemon_rank":"Rang",
"note":"Note",
"hatchery_egg_quest_required":"🔒 Quête de l\'Œuf requise",
"hatchery_passive_daycare":"En Garderie passive :",
"hatchery_incubation_label":"Incubation :",
"hatchery_filter_shiny":"Filtre Shiny :",
"hatchery_filter_iv":"Filtre IV :",
"hatchery_sort_order":"Trier par ordre :",
"hatchery_queue_title":"📋 File d\'attente (Se vide si le mode change)",
"hatchery_mode_label":"Mode :",
"hatchery_mode_daycare":"Garderie",
"hatchery_mode_incubation":"Incubation",
"hatchery_priority_label":"Priorité :",
"hatchery_priority_pokemon":"Pokémon",
"hatchery_priority_fossil":"Fossile",
"hatchery_mode_pending_short":"fin incubation",
"hatchery_mode_pending_title":"Le changement de mode s'appliquera à la fin de l'incubation en cours",
"hatchery_mode_deferred":"Slot #{slot} : passage en mode Garderie après la fin de l'incubation en cours. La liste d'attente a été vidée.",
"fossil_queued_count":"{count} en file d'attente",
"fossil_all_queued":"Tous les exemplaires sont réservés dans une file de la pension.",
"hatchery_mode_ejected":"{name} a été renvoyé au PC (Incubation réservée aux Niv. 100). La liste d'attente a été vidée.",
"hatchery_mode_pending_cancelled":"Changement de mode en attente annulé.",
"hatchery_filter_all":"Tous",
"hatchery_filter_non_shiny":"Non-Shiny",
"hatchery_sort_iv_desc":"IVs Élevés",
"hatchery_sort_iv_asc":"IVs Faibles",
"hatchery_sort_lvl_desc":"Niveau Élevé",
"hatchery_sort_lvl_asc":"Niveau Faible",
"hatchery_sort_dex":"N° Pokédex",
  "tm":"CT/CS",
  "item_type":"Type",
  "hidden_talent_unlocked":"★ Talent Caché débloqué !",
  "no_hidden_talent_species":"Cette espèce n'a pas de talent caché.",
  "hidden_talent_already_unlocked":"Talent caché déjà débloqué !",
  "training_mode_hidden_talent_title":"Déblocage Talent Caché",
  "training_mode_hidden_talent_desc":"Tente de débloquer le talent caché de ce Pokémon.",
  "training_mode_hidden_talent_done":"Talent caché déjà débloqué.",
  "weather_back_to_normal":"Le climat revient à la normale.",
  "terrain_back_to_normal":"Le terrain redevient neutre.",
  "regenerator_proc":"[Talent] Régé-Force : {name} récupère des PV !",
  "drizzle_proc":"[Talent] Crachin : {name} invoque la pluie !",
  "drought_proc":"[Talent] Sécheresse : {name} invoque le soleil !",
  "sandstream_proc":"[Talent] Sable Volant : {name} invoque une tempête de sable !",
  "snowwarning_proc":"[Talent] Alerte Neige : {name} invoque la grêle !",
  "electricsurge_proc":"[Talent] Créa-Élec : {name} active un Champ Électrique !",
  "grassysurge_proc":"[Talent] Créa-Herbe : {name} active un Champ Herbeux !",
  "mistysurge_proc":"[Talent] Créa-Brum : {name} active un Champ Brumeux !",
  "psychicsurge_proc":"[Talent] Créa-Psy : {name} active un Champ Psychique !",
  "hatchery_no_lvl100_passive":"Impossible de mettre un Pokémon de Niveau 100 en Garderie passive !",
  "hatchery_only_lvl100_breed":"Seuls les Pokémon de Niveau 100 peuvent être mis en Reproduction !",
  "hatchery_no_money_auto":"Pas assez d'argent pour payer les frais d'automation d'éclosion !",
  "hatchery_autofill_no_money":"Remplissage automatique désactivé : pas assez d'argent !",
  "hatchery_cannot_remove_breeding":"Impossible de retirer un Pokémon mis en mode Reproduction !",
  "tutorial_hint_sheet_mobile":"Mobile : appuie longtemps sur un Pokémon de ton équipe, ou touche sa carte si elle est visible.",
  "tutorial_hint_sheet_pc":"PC : clique ou clic droit sur un Pokémon dans la fenêtre Équipe Active.",
  "tutorial_hint_map_mobile":"Mobile : utilise la barre du bas pour revenir à la Carte ou au Lieu.",
  "tutorial_hint_map_pc":"PC : clique directement sur la Carte puis sur les boutons du panneau Lieu.",
  "eff_immune":"×0",
  "eff_4x":"×4",
  "eff_2x":"×2",
  "eff_quarter":"×¼",
  "eff_half":"×½",
  "eff_1x":"×1",
  "stat_up_high":"▲▲▲",
  "stat_up_mid":"▲▲",
  "stat_up_low":"▲",
  "stat_down_high":"▼▼▼",
  "stat_down_mid":"▼▼",
  "stat_down_low":"▼",
  "transform_into":"{attacker} → {defender}",
  "req_gym_level":"Auguste (Cramois'île)",
  "req_gym_ev":"Giovanni (Jadielle)",
  "req_league_kanto":"la Ligue de Kanto",
  "new_talent":"Nouveau talent",
  "talent_confirmed":"Talent confirmé",
  "all_moves_unlocked":"toutes les capacités sont déjà débloquées",
  "move_unlocked":"Capacité débloquée",
  "sector_hatchery":"Pension",
  "sector_training":"Entraînement",
  "sector_mine":"Mine",
  "fee_hatchery":"éclosion automatique",
  "fee_training":"combat automatique",
  "fee_mine":"tuile extraite",
  "quest_required":"Quête requise : ",
  "pokeflute_snorlax":"Poké Flûte / Ronflex",
  "league_champion":"Ligue Pokémon",
  "requires_league_win":"Requiert la victoire à la Ligue Pokémon",
  "icon_town":"🏘",
  "icon_sea":"🌊",
  "icon_dungeon":"⛰",
  "already_equipped_by":"Déjà équipé par {name}",
  "switch_talent_new":"Nouveau talent",
  "switch_talent_confirm":"Talent confirmé",
  "switch_move_unlocked":"Capacité débloquée",
  "switch_all_moves_done":"toutes les capacités sont déjà débloquées",
  "guide_map_read":"Lire la carte",
  "guide_map_read_desc":"Les couleurs montrent l'état des lieux : disponibles, verrouillés, zones avec captures manquantes, quêtes actives ou shiny encore absents. Le bouton d'aide de la carte résume ce code couleur.",
  "guide_movement":"Déplacements",
  "guide_movement_desc":"Clique sur un lieu débloqué pour t'y rendre. Une fois sur place, la fenêtre Lieu affiche les actions disponibles : explorer, défier, boutique, PNJ, bateau, labo fossile ou accès spéciaux.",
  "guide_progress_locks":"Verrous de progression",
  "guide_progress_locks_desc":"La progression peut dépendre d'un nombre de combats sauvages gagnés, d'un badge, d'une quête principale ou d'un objet spécial. Les messages de blocage indiquent toujours la condition manquante.",
  "guide_regions":"Régions",
  "guide_regions_desc":"Kanto puis Johto se débloquent avec la progression. Certaines règles d'accès imposent aussi de terminer une Ligue ou un Pokédex régional avant d'aller plus loin.",
  "guide_npc_quests":"PNJ et quêtes",
  "guide_npc_quests_desc":"Les PNJ servent à faire avancer l'histoire, lancer des quêtes secondaires ou déclencher des combats scénarisés. Pense à revisiter les villes après les gros objectifs.",
  "guide_combat_basics":"Principe général",
  "guide_combat_basics_desc":"Les combats sont automatiques et en temps réel. Tu ne choisis pas l'attaque pendant le combat : la stratégie se prépare avant, via l'équipe, les objets, les talents et l'ordre de tes Pokémon.",
  "guide_combat_bars":"Barres d'attaque",
  "guide_combat_bars_desc":"Chaque Pokémon charge automatiquement son attaque suivante. La vitesse, les statuts et certains talents modifient le rythme des attaques.",
  "guide_combat_eff":"Efficacité",
  "guide_combat_eff_desc":"Les indicateurs ×2, ×4, ×½, ×¼ et ×0 montrent l'efficacité d'un type contre la cible actuelle. Ils sont visibles directement sur les attaques pour lire rapidement un matchup.",
  "guide_combat_switch":"Changement de Pokémon",
  "guide_combat_switch_desc":"Tu peux changer de Pokémon actif pendant un combat normal si un autre membre vivant est disponible. Les combats d'entraînement solo n'autorisent pas ce changement.",
  "guide_combat_status":"Statuts",
  "guide_combat_status_desc":"Brûlure, poison, poison grave, sommeil, gel et paralysie ont des effets récurrents ou des pertes de tour. Ils sont affichés en badges courts sur les cartes.",
  "guide_combat_items":"Talents et objets",
  "guide_combat_items_desc":"Les talents et objets tenus peuvent réduire des dégâts, soigner, booster des stats ou modifier des types d'attaque. Observe les petites capsules visuelles quand ils s'activent.",
  "guide_combat_loot":"Butin et captures",
  "guide_combat_loot_desc":"Après les combats sauvages, le jeu gère automatiquement les captures et le butin. Le résumé de session regroupe captures, objets, victoires, K.O. et dégâts de l'équipe.",
  "guide_combat_special":"Combats spéciaux",
  "guide_combat_special_desc":"Arènes, Ligue, rival, Team Rocket, boss de quête et Atoll demandent surtout de la préparation : bonne équipe, bons talents, EV et objets tenus.",
  "guide_sheet_base":"Base Stats",
  "guide_sheet_base_desc":"Les Base Stats représentent le potentiel naturel de l'espèce. Deux Pokémon d'une même espèce partagent cette base, puis les IV/EV/personnalisation font la différence.",
  "guide_sheet_iv":"IV",
  "guide_sheet_iv_desc":"Les IV sont des bonus durables sur chaque statistique. Plus ils sont hauts, meilleur est le Pokémon sur le long terme.",
  "guide_sheet_ev":"EV",
  "guide_sheet_ev_desc":"Les EV représentent l'entraînement spécialisé. Ils montent surtout via l'entraînement EV et améliorent progressivement une statistique précise.",
    "guide_rewards":"Récompenses",
  "guide_atoll_rotation":"Rotation de 12 h",
  "guide_atoll_rotation_desc":"Les équipes adverses, les légendaires bannis et la boutique tournent toutes les 12 heures (fenêtre UTC partagée). Le minuteur est affiché dans le menu de l’Atoll.",
"guide_sheet_abilities":"Talents",
  "guide_sheet_abilities_desc":"Chaque espèce peut disposer de plusieurs talents. La capture, l'entraînement Talent et certains progrès débloquent ces options au fil du temps.",
  "guide_sheet_moves":"Attaques",
  "guide_sheet_moves_desc":"Clique une attaque connue pour sélectionner un slot à remplacer, puis une attaque apprenable. Les descriptions de capacités indiquent type, puissance, précision et effets.",
  "guide_sheet_item":"Objet tenu",
  "guide_sheet_item_desc":"Un objet tenu peut transformer un Pokémon médiocre en bon support, ou renforcer un sweeper déjà fort. Un même objet ne peut être équipé que sur un seul Pokémon à la fois.",
  "guide_sheet_fav":"Favori / verrouillage",
  "guide_sheet_fav_desc":"Favori sert à repérer un Pokémon important. Verrouillé empêche plusieurs automatismes de le recycler par erreur.",
  "guide_bag_org":"Organisation",
  "guide_bag_org_desc":"Le sac est trié par catégories : consommables, objets tenus, pierres, trésors, fossiles et objets spéciaux. Utilise les filtres et le tri pour gagner du temps.",
  "guide_bag_consumables":"Consommables",
  "guide_bag_consumables_desc":"Les soins, bonbons et objets d'usage immédiat s'emploient depuis le sac ou via certaines interfaces dédiées.",
  "guide_bag_held":"Objets tenus",
  "guide_bag_held_desc":"Les objets tenus sont pensés pour la préparation d'équipe. Le bonus réel dépend parfois du stock possédé dans le sac.",
  "guide_bag_stones":"Pierres d'évolution",
  "guide_bag_stones_desc":"Les pierres affichent les Pokémon compatibles. Le jeu t'indique aussi si l'évolution cible est déjà obtenue.",
  "guide_bag_treasure":"Trésors et fossiles",
  "guide_bag_treasure_desc":"Les trésors servent surtout à l'économie. Les fossiles servent à la pension / résurrection plutôt qu'à la vente.",
  "guide_mine_goal":"Objectif",
  "guide_mine_goal_desc":"La mine cache pierres, trésors et fossiles. Il faut révéler complètement les objets pour les récupérer.",
  "guide_mine_tools":"Outils",
  "guide_mine_tools_desc":"Le burin est précis. Le marteau couvre une petite zone. Les améliorations débloquent des outils plus efficaces comme la pioche renforcée, la foreuse et la dynamite.",
  "guide_mine_energy":"Énergie",
  "guide_mine_energy_desc":"Chaque coup consomme de l'énergie. L'énergie se régénère avec le temps et certains systèmes de progression.",
  "guide_mine_refresh":"Renouvellement",
  "guide_mine_refresh_desc":"Une fois tous les objets d'une couche récupérés, la mine se renouvelle. Les futurs mineurs améliorent l'efficacité et l'endurance des sessions.",
  "guide_hatchery_deposit":"Déposer un Pokémon",
  "guide_hatchery_deposit_desc":"Dépose un Pokémon depuis l'équipe ou depuis la boîte si un slot est libre. Plusieurs slots se débloquent via les améliorations.",
  "guide_hatchery_eggs":"Progression des œufs",
  "guide_hatchery_eggs_desc":"Les œufs et fossiles avancent avec les K.O. de combat. Quand le compteur requis est atteint, ils sont prêts à éclore.",
  "guide_hatchery_fossils":"Fossiles",
  "guide_hatchery_fossils_desc":"Les fossiles trouvés à la mine peuvent être envoyés en pension pour être ranimés sous forme de Pokémon.",
  "guide_hatchery_auto":"Automatisation",
  "guide_hatchery_auto_desc":"La pension possède une file d'attente manuelle, un remplissage automatique, une éclosion automatique, des filtres de tri et du personnel.",
  "guide_hatchery_staff":"Gérants",
  "guide_hatchery_staff_desc":"Les gérants améliorent progressivement l'efficacité de la pension. Ils se recrutent par lieu et gagnent de l'XP en travaillant.",
  "guide_training_modes":"Modes",
  "guide_training_modes_desc":"Les modes principaux sont Niveau, EV, Talent et Capacité. Chaque mode vise une amélioration précise.",
  "guide_training_prep":"Préparation",
  "guide_training_prep_desc":"Avant de lancer un entraînement, assure-toi d'avoir un Pokémon disponible. Chaque mode nécessite parfois un badge pour être débloqué.",
  "guide_training_slots":"Slots",
  "guide_training_slots_desc":"Les slots permettent d'entraîner plusieurs Pokémon en parallèle. Le second slot s'achète dans les améliorations.",
  "guide_training_auto":"File d'attente",
  "guide_training_auto_desc":"La file d'attente automatique permet de laisser la progression s'enchaîner sans intervention manuelle. L'automatisation est disponible après la Ligue.",
  "battle_effect_burn":"brûlure",
  "battle_effect_poison":"poison",
  "battle_effect_badpoison":"poison grave",
  "battle_effect_sleep":"sommeil",
  "battle_effect_freeze":"gel",
  "battle_effect_para":"paralysie",
  "battle_effect_confuse":"confusion",
  "battle_effect_flinch":"apeuré",
  "battle_effect_slow":"ralenti",
  "effect_immune":"Aucun effet",
  "effect_4x":"Super efficace x4",
  "effect_2x":"Super efficace x2",
  "effect_half":"Peu efficace x½",
  "effect_quarter":"Peu efficace x¼",
  "effect_normal":"Normal",
  "buff_atk":"ATK",
  "buff_def":"DEF",
  "buff_spe":"VIT",
  "loc_type_town":"🏘",
  "loc_type_sea":"🌊",
  "loc_type_dungeon":"⛰",
  "yes":"Oui",
  "no":"Non",
  "quest_pokeflute":"Poké Flûte / Ronflex",
  "quest_league":"Ligue Pokémon",
  "ditto":"Métamorph",
  "tab_combat":"Combat",
  "tab_hatchery":"Pension",
  "story_quests_title":"Histoire & Quêtes",
  "shortcut_title":"Raccourcis",
  "hide_window":"Masquer",
  "close_window":"Fermer",
  "minimize_window":"Minimiser",
  "shortcut_menu":"Menu des raccourcis",
  "quick_manage_menu":"Menu de gestion rapide",
  "item_info_panel":"Informations sur l'objet",
  "move_info_panel":"Informations sur la capacité",
  "ability_info_panel":"Informations sur le talent",
  "pokemon_info_panel":"Informations sur le Pokémon",
  "map_legend_visited":"Lieu visité",
  "map_legend_current":"Lieu actuel",
  "map_legend_locked":"Lieu verrouillé",
  "map_legend_quest":"Quête disponible",
  "map_legend_roaming":"Légendaire errant",
  "map_legend_catch":"Capture manquante",
  "map_legend_shiny":"Shiny manquant",
  "map_legend_complete":"Zone terminée",
  "settings_language":"Langue",
  "settings_save":"Sauvegarde",
  "settings_export":"Exporter",
  "settings_import":"Importer",
  "settings_delete":"Supprimer",
  "settings_theme":"Thème",
  "guide_quick_start":"Guide de démarrage rapide",
  "guide_controls":"Contrôles",
  "guide_gameplay":"Gameplay",
  "panel_bag":"Sac",
  "panel_shop":"Boutique",
  "panel_market":"Marché",
  "panel_pokedex":"Pokédex",
  "panel_team":"Équipe",
  "panel_box":"Boîte PC",
  "panel_training":"Entraînement",
  "panel_hatchery":"Pension",
  "panel_mine":"Mine",
  "panel_map":"Carte",
  "panel_battle":"Combat",
  "abilities_all_unlocked":" (toutes les capacités sont déjà débloquées)",
  "auto_fill_no_money":"Remplissage automatique désactivé : pas assez d'argent !",
  "only_lv100_breeding":"Seuls les Pokémon de Niveau 100 peuvent être mis en Reproduction !",
  "poke_flute_snorlax":"Poké Flûte / Ronflex",
  "pokemon_league":"Ligue Pokémon",
  "guide_detail":"Guide détaillé",
  "guide_ability":"Capacité",
  "guide_quests_title":"Quêtes",
  "guide_main_quests":"Quêtes principales",
  "guide_economy":"Économie & marché",
  "guide_attack_bars":"Barres d'attaque",
  "guide_attack_bars_desc":"Chaque Pokémon charge automatiquement son attaque suivante. La vitesse, les statuts et certains talents modifient le rythme des attaques.",
  "guide_evo_stones":"Pierres d’évolution",
  "guide_evo_stones_desc":"Les pierres affichent les Pokémon compatibles. Le jeu t’indique aussi si l’évolution cible est déjà obtenue.",
  "guide_ev_training":"EV",
  "guide_ev_training_desc":"Le stage EV donne exactement +1 EV aléatoire tant que le Pokémon n’est pas déjà au maximum.",
  "guide_talent_training":"Talent",
  "guide_talent_training_desc":"Le stage Talent tente de débloquer ou reconfirmer un talent possible de l’espèce. Les talents rares prennent naturellement plus de temps.",
  "guide_slots_auto":"Slots et automatisation",
  "guide_slots_auto_desc":"Chaque slot peut avoir sa propre file d’attente et son propre mode auto. Le personnel d’entraînement améliore aussi la régularité du système.",
  "guide_side_quests":"Quêtes secondaires",
  "guide_side_quests_desc":"Elles donnent surtout de l’argent, des objets ou des combats spéciaux. Elles apparaissent souvent via les PNJ de ville.",
  "guide_repeatable_quests":"Quêtes répétables",
  "guide_repeatable_quests_desc":"Les répétables servent d’économie long terme. Elles demandent de vaincre, capturer ou vendre selon l’objectif proposé.",
  "guide_quest_battles":"Combats de quête",
  "guide_quest_battles_desc":"Certaines quêtes lancent un combat unique. Le défi est souvent plus important que les combats sauvages classiques.",
  "guide_shops":"Boutiques",
  "guide_shops_desc":"Les boutiques vendent soins, objets spéciaux, pierres, objets tenus et autres ressources.",
  "guide_pokemarket":"PokéMarket",
  "guide_pokemarket_desc":"Le marché sert à acheter certaines espèces introuvables facilement dans la nature. Il complète la collection plus qu’il ne remplace l’exploration.",
  "guide_treasures":"Trésors et ventes",
  "guide_treasures_desc":"La mine alimente une grande partie de l’économie via les trésors. Les doublons d’objets spéciaux peuvent aussi être convertis en argent.",
  "guide_queues":"Files d’attente",
  "guide_queues_desc":"La pension et l’entraînement possèdent leurs propres files, avec capacité maximale et priorités configurables.",
  "guide_staff":"Personnel",
  "guide_staff_desc":"Le personnel se recrute selon la progression. Chaque employé donne un bonus spécialisé à la pension ou à l’entraînement.",
  "guide_protections":"Protections",
  "guide_protections_desc":"Les Pokémon verrouillés et certaines situations évitent que l’automatisation touche à des éléments sensibles.",
  "guide_multi_saves":"Multi-saves",
  "guide_multi_saves_desc":"Le jeu gère plusieurs sauvegardes avec nom, fond et icône personnalisables.",
  "guide_import_export":"Import / export",
  "guide_import_export_desc":"Exporte régulièrement tes saves pour éviter toute perte pendant les phases alpha.",
  "guide_afk":"AFK",
  "guide_afk_desc":"Une partie de la progression peut être simulée hors ligne. Le résumé AFK indique combats gagnés, captures, items et dégâts subis.",
  "guide_formats":"Formats",
  "guide_formats_desc":"Tour, Usine, Arène et Dôme appliquent chacun des contraintes différentes : rang maximum, types imposés ou équipe aléatoire.",
  "guide_dict_items":"Objets",
  "guide_dict_items_desc":"Cherche un objet pour savoir si tu le possèdes, où le trouver et à quoi il sert.",
  "guide_dict_moves":"Attaques",
  "guide_dict_moves_desc":"Cherche une attaque pour voir son type, sa puissance, ses effets et quels Pokémon la connaissent.",
  "guide_dict_abilities":"Talents",
  "guide_dict_abilities_desc":"Cherche un talent pour voir son effet, sa rareté et les Pokémon concernés.",
  "guide_dict_usage":"Usage",
  "guide_dict_usage_desc":"Le dictionnaire devient très utile quand le nombre d’objets, de talents et d’attaques commence à grandir.",
  "cat_evolution":"Évolution",
  "cat_key_special":"Objets-clés & spéciaux",
  "evolution_owned":"Évolution déjà possédée",
  "evolution_not_owned":"Évolution non possédée",
  "main_quest_label":"Quête principale",
  "not_specified":"Non renseigné",
  "mine_depleted_new":"Couche épuisée : nouvelle mine générée automatiquement !",
  "poke_flute_obtained":"Poké Flûte obtenue !",
  "obtain_poke_flute":"Obtenez la Poké Flûte.",
  "where_to_find":"📍 Où trouver : ",
  "where_to_find2":"📍 Où trouver : ",
  "evo_stone":"Pierre Évolutive",
  "cat_treasure":"Trésor",
  "cat_evolution2":"Évolution",
  "cat_key_item":"Objet Clé",
  "boosted_type":"Type Boosté",
  "resistance":"Résistance",
  "revives":"Réanime",
  "evolves_some_pokemon":"Fait évoluer certains Pokémon",
  "cat_special":"Spéciale",
  "status_burn":"Brûlure",
  "status_scared":"Apeuré",
  "power_label":"Puissance",
  "cat_fossil":"Fossile",
  "cat_evolution_item":"Objet d'Évolution",
  "cat_held_item":"Objet Tenu",
  "cat_tm":"CT",
  "cat_hm":"CS",
  "cat_candy":"Bonbon",
  "cat_item":"Objet",
  "status_para":"Paralysie",
  "status_poison":"Poison",
  "status_sleep":"Sommeil",
  "status_freeze":"Gel",
  "status_confuse":"Confusion",
  "status_slow":"Ralentissement",
  "needs_recharge":"Doit recharger",
  "_lang_code":"fr",
  "learnable_moves_panel_title":"Capacités apprenables",
  "known_short":"connues",
  "possessed_short":"possédées",
  "move_pill_equipped":"Équipée",
  "move_pill_available":"Disponible",
  "all_learnable_moves":"Toutes les capacités apprenables",
  "view_all_learnable_moves":"Voir toutes les capacités",
  "training_only":"Entraînement",
  "learnable_moves_count":"{known}/{total} connues",
  "debug_ct_added":"Debug : +1 de chaque CT/CS ajouté au Sac !",
  "already_owned_sp":"Déjà possédé",
  "teaching_move":"Enseigner",
  "non_possede":"Non possédé",
  "category_level_up":"★ Niveau",
  "category_ct_cs":"◇ CT/CS",
  "category_training":"▽ Entraînement",
  "no_level_up_moves":"Aucune capacité de niveau",
  "no_ct_moves":"Aucune CT/CS",
  "no_training_moves":"Aucune capacité d'entraînement",
  "hatchery_mode_set":"Slot #{mode} configuré en mode {mode}",
  "hatchery_mode_exp":"Garderie passive (EXP)",
  "hatchery_mode_breeding":"Reproduction (Œuf / IV)",
  "repeatable_unlock_hint":"🔒 Parlez à la Nageuse Ondée à Azuria pour débloquer les Quêtes Répétables.",
  "repeatable_quests_unlocked":"Quêtes répétables débloquées !",
  "hatchery_daycare_label":"Garderie",
  "hatchery_breeding_label":"Reproduction",
  "hatchery_daycare_short":"Garderie",
  "hatchery_breeding_short":"Reprod.",
  "hatchery_exp_desc":"Garderie passive : 10 K.O. = 1 niveau (Niv. < 100 uniquement)",
  "hatchery_breeding_desc":"Œuf / +1 IV (Niv. 100 uniquement)",
  "hatchery_filter_max_iv":"Max (36)",
  "hatchery_filter_max_short":"Max",
  "hatchery_add_queue":"+ Ajouter un Pokémon de la Boîte",
  "hatchery_clear_queue":"Vider la file",
  "hatchery_withdraw":"Retirer",
  "training_auto_no_money":"Auto-entraînement désactivé : pas assez d'argent !",
  "mine_auto_no_money":"Auto-minage désactivé : pas assez d'argent !",
  "status_poisoned":"Empoisonné",
  "weather_sandstorm":"Tempête de Sable",
  "terrain_electric":"Champ Électrifié",
  "held_boost_type":"Objet tenu : augmente les dégâts des capacités ",
  "held_resist_prefix":"Objet tenu : réduit de ",
  "held_resist_suffix":"% les dégâts super efficaces des capacités ",
  "held_boost_prefix":"Objet tenu : booste les dégâts ",
  "held_terrain_def":"Objet tenu : augmente la Défense dans un Champ ",
  "held_weather_duration":"Objet tenu : augmente la durée du climat ",
  "held_damage_boost":"Objet tenu : augmente les Dégâts du porteur de ",
  "to_compatible_pokemon":" à un Pokémon compatible.",
  "status_burn_label":"Brûlure",
  "status_freeze_label":"Gel",
  "status_para_label":"Paralysie",
  "status_sleep_label":"Sommeil",
  "status_confuse_label":"Confusion",
  "weather_rainy":"Pluie",
  "weather_hail":"Grêle",
  "terrain_grassy":"Champ Herbu",
  "terrain_misty":"Champ Brumeux",
  "weather_sunny":"Soleil",
  "held_choice_item":"Objet tenu : augmente ",
  "held_choice_lock":", mais l'empêche de changer",
  "held_inflicts":", mais inflige ",
  "held_power_sentence":"Augmente la puissance de ",
  "teaches_move":"Enseigne ",
  "effect_applied_in_battle":"Effet appliqué en combat.",
  "keystone_label":"Clé de Voûte",
  "unlocked_after":"Débloqué après ",
  "status_toxic":"Toxique",
  "talents_label":"Talents",
  "moves_label":"Capacités",
  "training_fee_log_label":"[Entraînement]",
  "training_fee_paid":"payés d'avance pour le dresseur automatique.",
  "sector_fee_label":"<b>Frais du secteur",
  "sector_fee_per":"par",
  "sector_fee_desc":"Montez tous vos gérants au niveau 100 (Max) pour réduire ces frais à 0₽!",
  "sector_fee_levels":"Niveaux cumulés du secteur",
  "training_mode_hidden_title":"Déblocage Talent Caché",
  "training_mode_hidden_desc":"Tente de débloquer le talent caché de ce Pokémon.",
  "training_mode_hidden_done":"Talent caché déjà débloqué.",
  "battle_summary_team_damage":"Dégâts de l'équipe",
  "battle_summary_no_damage":"Aucun dégât enregistré pour cette session.",
  "battle_summary_no_captures":"Aucune capture pendant cette session.",
  "battle_summary_no_items":"Aucun objet trouvé pendant cette session.",
  "leave_battle_button":"Quitter le combat",
  "loot_open_btn":"Résumé",
  "modal_close_btn":"Fermer",
  "turns_abbrev":"t.",
  "active_zone_effects":"Effets de zone actifs",
  "settings_title":"Réglages",
  "theme_title":"Thème",
  "theme_dark":"Sombre",
  "theme_light":"Clair",
  "theme_gameboy":"Game Boy",
  "theme_fire":"Feu",
  "save_title":"Sauvegarde",
  "save_btn":"Sauvegarder",
  "load_btn":"Charger",
  "export_btn":"Exporter",
  "import_btn":"Importer",
  "delete_save_btn":"Supprimer la sauvegarde",
  "confirm_delete_btn":"Confirmer la suppression",
  "cancel_btn":"Annuler",
  "confirm_btn":"Confirmer",
  "adventure_tab":"Aventure",
  "mine_window_title":"Mine souterraine",
  "map_region_kanto":"Région Kanto",
  "map_region_johto":"Région Johto",
  "region_coming_soon":"Région {region} (Bientôt)",
  "search_by_name":"Rechercher par nom...",
  "debug_menu_title_short":"Menu debug",
  "debug_close_menu":"Fermer le menu debug",
  "debug_money":"Monnaie +50 000₽",
  "debug_candies":"Super Bonbons +10",
  "debug_badges":"Débloquer 8 badges Kanto",
  "debug_base_grant":"Base : toutes les décos +1",
  "debug_base_npc":"Base : +1 copain (équipe actuelle)",
  "debug_base_npcs":"Base : vivier de copains (8)",
  "debug_mine":"Énergie mine +100",
  "debug_ctcs":"Obtenir CT/CS +1",
  "debug_afk":"AFK +30 min",
  "debug_speed_x10":"Vitesse x10 :",
  "debug_off":"OFF",
  "victory_title":"CHAMPION !",
  "victory_message":"Vous avez vaincu tous les Dresseurs!",
  "continue_btn":"Continuer",
  "battle_summary_title":"Butin & résumé de session",
  "quests_tab":"Quêtes",
  "manage_tab":"Gestion",
  "training_tab":"Entraînement",
  "shortcuts_tab":"Raccourcis",
  "base_tab":"Base",
  "welcome_msg":"Bienvenue dans PokéWorld ! Cliquez sur un lieu adjacent pour vous déplacer.",
  "usm_selection":"Sélection",
  "sort_dex_number":"Pokédex #",
  "sort_level":"Niveau",
  "sort_iv":"IVs",
  "sort_ev":"EVs",
  "sort_rank":"Rang",
  "language_title":"Langue / Language",
  "badges_lbl":"Badges",
  "leave_battle_btn":"Quitter le combat",
  "map_region_hoenn":"Région Hoenn",
  "map_region_sinnoh":"Région Sinnoh (Bientôt)",
  "found_in_lbl":"Où trouver :",
  "power_prefix":"Puissance : ",
  "back_to_inventory":"← Retour au Sac",
  "back_to_shop":"← Retour à la Boutique",
  "back_to_market":"← Retour au Marché",
  "back_to_pokedex":"← Retour au Pokédex",
  "back_to_guide":"← Retour au Guide",
  "back_to_atoll":"← Retour à l'Atoll",
  "affected_pokemon_lbl":"Pokémon concernés",
  "base_stats_tab":"Stats de base",
  "johto_required":"🔒 Johto requis",
  "item_required":"Objet requis : {item}",
  "no_talent_available":"aucun talent disponible",
  "hatchery_cannot_remove_fossil":"Impossible de retirer un fossile en cours d'incubation !",
  "max_lbl":"MAX",
  "mine_auto_fee_log":" [Mine] -{fee}₽ payés pour l'extraction automatique d'une tuile.",
  "evo_item_lbl":"Objet d'Évolution",
  "cat_held_items":"Objets tenus",
  "cat_fossils":"Fossiles",
  "cat_misc":"Divers",
  "guide_pages_info":"{count} pages d'informations",
  "tutorial_howto":"Comment faire :",
  "tutorial_step_lbl":"Tutoriel guidé — Étape {idx}/{total}",
  "tutorial_do_btn":"Faire",
  "tutorial_step_route1_how":"Où aller : fenêtre Carte → Route 1. Ensuite, dans la fenêtre Lieu, clique sur Explorer.",
  "tutorial_step_route1_action":"Aller à Route 1",
  "tutorial_step_route1_reward":"+300₽ + 1 Baie Occa",
  "tutorial_step_sheet_how":"La fiche contient les onglets Base Stats / IV / EV et la liste des attaques.",
  "tutorial_step_sheet_action":"Voir mon équipe",
  "tutorial_step_sheet_reward":"+200₽",
  "tutorial_step_bag_how":"Dans la fenêtre Raccourcis, clique sur Sac. Tu y trouveras baies, objets tenus, pierres, trésors et objets spéciaux.",
  "tutorial_step_bag_action":"Ouvrir le Sac",
  "tutorial_step_bag_reward":"+2 Potions",
  "tutorial_step_dex_how":"Dans Raccourcis, ouvre le Pokédex. Clique sur un Pokémon non grisé pour voir où le trouver, ses talents et sa description.",
  "tutorial_step_dex_action":"Ouvrir le Pokédex",
  "tutorial_step_dex_reward":"+500₽",
  "tutorial_step_badge_how":"Nettoie les routes jusqu’à Argenta. Une fois à Argenta, dans la fenêtre Lieu, clique sur Défier Pierre. Les badges débloquent de nouvelles zones.",
  "tutorial_step_badge_action":"Voir la Carte",
  "tutorial_step_badge_reward":"+1 Super Bonbon",
  "guide_pokemon_sheet":"Fiche Pokémon",
  "guide_pokemon_sheet_desc":"La fiche montre types, niveau, rang, Base Stats, IV, EV, talents, objet tenu, évolutions, attaques connues et attaques apprenables.",
  "guide_training_level":"Niveau",
  "guide_training_level_desc":"Le stage Niveau donne plusieurs niveaux d’un coup, dans la limite du niveau 100.",
  "guide_ability_desc":"Le stage Capacité débloque des attaques avancées réservées à l’entraînement. Elles deviennent ensuite apprenables dans la fiche du Pokémon.",
  "guide_main_quests_desc":"Elles débloquent l’histoire, des villes, des objets-clés et les passages majeurs comme la Poké Flûte ou l’accès à d’autres régions.",
  "guide_economy_rewards_desc":"Argent et objets viennent des quêtes, combats, mine, captures, répétables et modes spéciaux comme l’Atoll.",
  "guide_automation_title":"Automatisation & personnel",
  "guide_automation":"Fonctionnement de l'automatisation",
  "guide_automation_desc":"L’automatisation n’agit pas seule au début : il faut acheter les modules, configurer les règles et parfois remplir la file d’attente manuellement.",
  "guide_save_title":"Sauvegardes & AFK",
  "guide_base_title":"Bases Secrètes",
  "guide_battle_atoll":"Atoll de Combat",
  "guide_alpha_safety":"Sécurité des sauvegardes (Alpha)",
  "guide_alpha_safety_desc":"Comme le projet est encore en alpha, garde toujours une exportation récente avant de tester un nouveau zip.",
  "guide_battle_atoll_desc":"L’Atoll de Combat est le contenu de fin d’alpha. Il sert à tester des équipes optimisées dans plusieurs formats.",
  "guide_atoll_rewards_desc":"Les victoires donnent des jetons Atoll utilisables dans la boutique dédiée. Les séries augmentent l’intérêt du farm."
};

// Consommateurs classiques : exposition gardée sur l'objet global à l'éval.
if (typeof globalThis !== 'undefined') globalThis.L_fr_ui = L_fr_ui;
