// ============================================================================
// Passe 24 — Génère src/localization/fr/move-descs.js : descriptions FRANÇAISES
// of the 400 moves (until now: mv.desc English shown almost systematically,
// since no fr/move-descs.js file existed even though the nested
// 'move_descs' domain is supported by the i18n loader).
// The info panel (openMoveInfo) now reads the locale BEFORE mv.desc.
// Idempotent: re-running regenerates the same file.
// ============================================================================
import { readFileSync, writeFileSync } from 'fs';
import vm from 'vm';

// ——— Translation of the 196 distinct descriptions ———
const TR = new Map(Object.entries({
  'Hits 2-5 times':'Frappe 2 à 5 fois.',
  'Inflicts regular damage with no additional effect.':'Inflige des dégâts sans effet supplémentaire.',
  'Attacks x1.2 slower than usual':'Attaque 1.2 fois plus lentement que la normale.',
  'Attacks x1.2 faster than usual':'Attaque 1.2 fois plus vite que la normale.',
  'Decreases enemy Speed by 50%':'Baisse la Vitesse ennemie de 50%.',
  'Has a chance to make the target flinch.':'Peut faire trembler la cible.',
  'Has an increased chance for a critical hit.':'Taux de critique augmenté.',
  'Attacks x1.5 slower than usual':'Attaque 1.5 fois plus lentement que la normale.',
  '10% chance to decrease enemy Special Defense by 50%':'10% de chance de baisser la Défense Spéciale ennemie de 50%.',
  'Hits 2 times':'Frappe 2 fois.',
  '10% chance to inflict Paralysis':'10% de chance de paralyser.',
  '10% chance to inflict Burn':'10% de chance de brûler.',
  'Decreases enemy Defense by 50%':'Baisse la Défense ennemie de 50%.',
  'Never misses.':'Ne rate jamais.',
  'Decreases enemy Attack by 50%':'Baisse l\'Attaque ennemie de 50%.',
  'Power increases by x1.2-1.5 if Defense/Special Defense is risen':'Puissance x1.2 à x1.5 si la Défense/Défense Spéciale est augmentée.',
  '10% chance to inflict Poisoned':'10% de chance d\'empoisonner.',
  'Multiplies base power by 1.2x everytime its used, up to 5 times. Depletes all stacks upon switching Pokemon':'Puissance de base x1.2 à chaque utilisation (max 5). Les cumuls s\'annulent au changement de Pokémon.',
  '10% chance to inflict Freeze':'10% de chance de geler.',
  '30% chance to inflict Poisoned':'30% de chance d\'empoisonner.',
  'Increases Defense by 100%':'Augmente la Défense de 100%.',
  '50% chance to decrease enemy Special Defense by 50%':'50% de chance de baisser la Défense Spéciale ennemie de 50%.',
  'Increases Speed by 50%':'Augmente la Vitesse de 50%.',
  '30% chance to inflict Burn':'30% de chance de brûler.',
  '30% chance to inflict Paralysis':'30% de chance de paralyser.',
  '30% chance to decrease enemy Defense by 50%':'30% de chance de baisser la Défense ennemie de 50%.',
  '30% chance to decrease enemy Speed by 50%':'30% de chance de baisser la Vitesse ennemie de 50%.',
  'Inflicts Confusion':'Rend confus.',
  '10% chance to inflict Confusion':'10% de chance de rendre confus.',
  'Decreases Special Attack by 50%':'Baisse l\'Attaque Spéciale de 50%.',
  'Attacks x2 faster than usual':'Attaque 2 fois plus vite que la normale.',
  'Decreases Speed by 50%':'Baisse la Vitesse de 50%.',
  '30% chance to inflict Confusion':'30% de chance de rendre confus.',
  'Inflicts Paralysis':'Paralyse.',
  'Increases Speed by 75%':'Augmente la Vitesse de 75%.',
  '10% chance to increase all Stats by 50%':'10% de chance d\'augmenter toutes les stats de 50%.',
  'Multiplies base power by 1.15x everytime its used, up to 10 times. Depletes all stacks upon switching Pokemon':'Puissance de base x1.15 à chaque utilisation (max 10). Les cumuls s\'annulent au changement de Pokémon.',
  '50% chance to decrease enemy Attack by 50%':'50% de chance de baisser l\'Attaque ennemie de 50%.',
  'Increases Attack and Defense by 50%':'Augmente l\'Attaque et la Défense de 50%.',
  'Inflicts Burn':'Brûle.',
  'Increases Special Attack by 100% and Special Defense by 50%':'Augmente l\'Attaque Spéciale de 100% et la Défense Spéciale de 50%.',
  '50% chance to increase Special Attack by 50%':'50% de chance d\'augmenter l\'Attaque Spéciale de 50%.',
  'Decreases enemy Attack by 100%':'Baisse l\'Attaque ennemie de 100%.',
  'Decreases enemy Speed by 75%':'Baisse la Vitesse ennemie de 75%.',
  'Has a chance to lower the target’s Defense by one stage.':'Peut baisser la Défense de la cible d\'un cran.',
  'Increases Attack and Speed by 50%. Attacks x1.4 slower than usual':'Augmente l\'Attaque et la Vitesse de 50%. Attaque 1.4 fois plus lentement que la normale.',
  'Attacks x1.2 slower than usual. Power increases by x1.2-1.5 if Defense/Special Defense is risen':'Attaque 1.2 fois plus lentement que la normale. Puissance x1.2 à x1.5 si la Défense/Défense Spéciale est augmentée.',
  '30% chance to increase Attack by 50%':'30% de chance d\'augmenter l\'Attaque de 50%.',
  '50% chance to decrease enemy Defense by 50%':'50% de chance de baisser la Défense ennemie de 50%.',
  'Decreases enemy Special Defense by 100%':'Baisse la Défense Spéciale ennemie de 100%.',
  '50% chance to decrease enemy Special Attack by 50%':'50% de chance de baisser l\'Attaque Spéciale ennemie de 50%.',
  'Changes the weather to Sunny':'Invoque le soleil.',
  'Has a chance to lower the target’s accuracy by one stage.':'Peut baisser la précision de la cible d\'un cran.',
  'Inflicts Poisoned':'Empoisonne.',
  'Power doubles if the target is Flying-Type':'Puissance doublée si la cible est de type Vol.',
  'Switches to the next party member':'Remplace par le membre suivant de l\'équipe.',
  'Power doubles if the user is not holding any item':'Puissance doublée si le lanceur ne tient aucun objet.',
  'Raises by 100% two random stats':'Augmente deux stats aléatoires de 100%.',
  '30% chance to decrease enemy Special Defense by 50%':'30% de chance de baisser la Défense Spéciale ennemie de 50%.',
  'The user attacks the target using its angelic voice. This also confuses the target if its stats have been boosted during the turn.':'Le lanceur attaque avec sa voix angélique. Rend aussi la cible confuse si ses stats ont été augmentées pendant le tour.',
  'Increases Special Defense by 100%':'Augmente la Défense Spéciale de 100%.',
  'Traps the target.':'Piège la cible.',
  'The user shoots its own armor out as blazing projectiles. This also lowers the user’s Defense and Sp. Def stats.':'Le lanceur projette son armure en projectiles ardents. Baisse aussi sa Défense et sa Défense Spéciale.',
  'Increases Special Defense by 50% to the entire team':'Augmente la Défense Spéciale de toute l\'équipe de 50%.',
  'The user punches the target with shimmering aurora power.':'Le lanceur frappe la cible avec un pouvoir d\'aurore scintillant.',
  'User transfers all of its stat changes and status to a the entire team':'Le lanceur transfère tous ses changements de stats et son statut à toute l\'équipe.',
  'Increases Attack by 150% but decreases Defense and Special Defense by 50%':'Augmente l\'Attaque de 150% mais baisse la Défense et la Défense Spéciale de 50%.',
  'The user focuses its bitter feelings toward the world of the living into a slashing attack. The user\'s HP is restored by up to half the damage taken by the target.':'Le lanceur concentre son amertume en une attaque tranchante. Restaure jusqu\'à la moitié des dégâts infligés en PV.',
  'Has a chance to freeze the target.':'Peut geler la cible.',
  'May paralyze the target.':'Peut paralyser la cible.',
  'Also damages the user a little (recoil).':'Blesse aussi légèrement le lanceur (recul).',
  'Inflicts regular damage.':'Inflige des dégâts.',
  'The user slashes the target with brutal claws that may burn.':'Le lanceur lacère la cible avec des griffes brutales pouvant brûler.',
  'If target has a berry, inflicts double damage and uses the berry.':'Si la cible tient une Baie, dégâts doublés et la Baie est utilisée.',
  'Increases Special Defense and Special Attack by 50%':'Augmente la Défense Spéciale et l\'Attaque Spéciale de 50%.',
  'Changes the type of the user corresponding to the weather':'Le type du lanceur change selon la météo.',
  '20% chance to inflict Confusion':'20% de chance de rendre confus.',
  'Changes the weather to Hail and switches to the next party member':'Invoque la grêle et remplace par le membre suivant de l\'équipe.',
  'The user launches its amassed chlorophyll to inflict damage on the target. This also damages the user and lowers the user\'s action speed.':'Le lanceur projette sa chlorophylle amassée. Le blesse aussi et baisse sa vitesse d\'action.',
  'Decreases Defense and Special Defense by 50%':'Baisse la Défense et la Défense Spéciale de 50%.',
  'Changes the type of the user to the type of the first move slot':'Le type du lanceur devient celui de sa première capacité.',
  'Increases Defense by 100% and Special Defense by 50%':'Augmente la Défense de 100% et la Défense Spéciale de 50%.',
  'Changes the weather to Cross Room':'Invoque la Salle Croisée.',
  'Ignores the target’s stat modifiers.':'Ignore les changements de stats de la cible.',
  'Inflicts regular damage and can hit Dig users.':'Inflige des dégâts et peut toucher les Pokémon sous terre (Tunnel).',
  'Changes the weather to Electric Terrain':'Active un Champ Électrifié.',
  'Temporarily adds Electric to the type of the enemy. Super-effective damage bonus dealt from temporal types is halved, and applying a second temporary type replaces the first one':'Ajoute temporairement le type Électrik à l\'ennemi. Le bonus super efficace des types temporaires est réduit de moitié, et un second type temporaire remplace le premier.',
  'Power doubles if the user is Paralyzed, Burned or Poisoned':'Puissance doublée si le lanceur est paralysé, brûlé ou empoisonné.',
  'Temporarily adds Fairy to the type of the enemy. Super-effective damage bonus dealt from temporal types is halved, and applying a second temporary type replaces the first one':'Ajoute temporairement le type Fée à l\'ennemi. Le bonus super efficace des types temporaires est réduit de moitié, et un second type temporaire remplace le premier.',
  '30% chance to increase Special Attack by 50%':'30% de chance d\'augmenter l\'Attaque Spéciale de 50%.',
  'Decreases enemy Special Defense by 50%':'Baisse la Défense Spéciale ennemie de 50%.',
  'The user rends the target with its hard gills. If the user attacks before the target, the power of this move is doubled.':'Le lanceur déchire la cible avec ses ouïes dures. Puissance doublée s\'il attaque avant la cible.',
  'Inflicts Burn to the entire team':'Brûle toute l\'équipe.',
  '50% chance to increase Speed by 50%':'50% de chance d\'augmenter la Vitesse de 50%.',
  'Removes all status effect for the entire party':'Soigne toutes les altérations de statut de l\'équipe.',
  'User flies high into the air, dodging all attacks, and hits next turn.':'Le lanceur s\'envole en esquivant toutes les attaques, et frappe au tour suivant.',
  'Changes the weather to Foggy':'Invoque le brouillard.',
  'Has a chance to paralyze the target.':'Peut paralyser la cible.',
  'Temporarily adds Grass to the type of the enemy. Super-effective damage bonus dealt from temporal types is halved, and applying a second temporary type replaces the first one':'Ajoute temporairement le type Plante à l\'ennemi. Le bonus super efficace des types temporaires est réduit de moitié, et un second type temporaire remplace le premier.',
  'Super-effective against Water-types':'Super efficace contre les types Eau.',
  '30% chance to decrease enemy Special Attack by 50%':'30% de chance de baisser l\'Attaque Spéciale ennemie de 50%.',
  'Attacks x2 slower than usual':'Attaque 2 fois plus lentement que la normale.',
  'Increases Attack and Speed by 50% to the entire team':'Augmente l\'Attaque et la Vitesse de toute l\'équipe de 50%.',
  '20% chance to inflict Freeze':'20% de chance de geler.',
  'Changes the weather to Grassy Terrain':'Active un Champ Herbu.',
  'Inflicts regular damage and can hit Pokémon in the air.':'Inflige des dégâts et peut toucher les Pokémon en l\'air.',
  'Changes the weather to Hail':'Invoque la grêle.',
  'User receives 1/4 the damage it inflicts in recoil.':'Le lanceur subit 1/4 des dégâts infligés en recul.',
  'Decreases Defense by 50%':'Baisse la Défense de 50%.',
  '20% chance to inflict Burn':'20% de chance de brûler.',
  '50% chance to inflict Burn':'50% de chance de brûler.',
  'Power doubles if the target has a status condition':'Puissance doublée si la cible a une altération de statut.',
  'If the user misses, it takes half the damage it would have inflicted in recoil.':'Si le lanceur rate, il subit en recul la moitié des dégâts qu\'il aurait infligés.',
  'Increases Attack by 50% to the entire team':'Augmente l\'Attaque de toute l\'équipe de 50%.',
  'The user spins the pointed part of its body at high speed to pierce the target. This attack can hit a target using a move such as Protect or Detect.':'Le lanceur vrille la partie pointue de son corps pour transpercer la cible. Peut toucher une cible sous Abri ou Détection.',
  'Destroys the target’s held berry.':'Détruit la Baie tenue par la cible.',
  'Decreases Defense and Special Defense by 100%':'Baisse la Défense et la Défense Spéciale de 100%.',
  'Increases Special Attack by 50% and Special Defense by 100%':'Augmente l\'Attaque Spéciale de 50% et la Défense Spéciale de 100%.',
  'Attacks x1.5 faster than usual':'Attaque 1.5 fois plus vite que la normale.',
  'If the user is holding a appropriate plate or drive, the damage inflicted will match it.':'Si le lanceur tient la Plaque ou le Module approprié, les dégâts prennent ce type.',
  'Increases Special Defense by 100% and Defense by 50%':'Augmente la Défense Spéciale de 100% et la Défense de 50%.',
  'Changes the weather to Light Screen':'Invoque le Mur Lumière.',
  '30% chance to increase Defense by 50%':'30% de chance d\'augmenter la Défense de 50%.',
  'Power increases by x1.2-1.5 if Speed is risen':'Puissance x1.2 à x1.5 si la Vitesse est augmentée.',
  'Temporarily adds Psychic to the type of the enemy. Super-effective damage bonus dealt from temporal types is halved, and applying a second temporary type replaces the first one':'Ajoute temporairement le type Psy à l\'ennemi. Le bonus super efficace des types temporaires est réduit de moitié, et un second type temporaire remplace le premier.',
  'Increases Special Defense by 50%':'Augmente la Défense Spéciale de 50%.',
  'Power randomly varies from x1 to x8':'Puissance aléatoire de x1 à x8.',
  'Perform the first move of the oponent. Attacks x2 faster than usual':'Exécute la première capacité de l\'adversaire. Attaque 2 fois plus vite que la normale.',
  'Faints the user and decreases enemy Attack and Special Attack by 100%':'Met le lanceur K.O. et baisse l\'Attaque et l\'Attaque Spéciale ennemies de 100%.',
  'User performs any move at random':'Le lanceur exécute une capacité au hasard.',
  'Perform the first move of the oponent, at double the base damage':'Exécute la première capacité de l\'adversaire avec des dégâts de base doublés.',
  'Inflicts damage, and the user takes damage equal to half of its max HP, rounded up.':'Inflige des dégâts ; le lanceur perd la moitié de ses PV max (arrondi supérieur).',
  'Changes the weather to Misty Terrain':'Active un Champ Brumeux.',
  '10% chance to decrease enemy Special Attack by 50%':'10% de chance de baisser l\'Attaque Spéciale ennemie de 50%.',
  'Changes the weather to Sunny and increases Special Attack by 50%':'Invoque le soleil et augmente l\'Attaque Spéciale de 50%.',
  'Temporarily adds Ground to the type of the enemy. Super-effective damage bonus dealt from temporal types is halved, and applying a second temporary type replaces the first one':'Ajoute temporairement le type Sol à l\'ennemi. Le bonus super efficace des types temporaires est réduit de moitié, et un second type temporaire remplace le premier.',
  'Increases Special Attack by 100%':'Augmente l\'Attaque Spéciale de 100%.',
  '10% chance to decrease enemy Speed by 50%':'10% de chance de baisser la Vitesse ennemie de 50%.',
  'Increase all Stats by 50%':'Augmente toutes les stats de 50%.',
  'Decreases enemy Attack by 100% and Special Attack by 50%':'Baisse l\'Attaque ennemie de 100% et l\'Attaque Spéciale de 50%.',
  'Inflicts Confusion on the user':'Rend le lanceur confus.',
  'Once used,increases the weight of rare item drops by 1% for the current battle. Multiple uses wont stack. Works always for everyone regardless of the user':'Une fois utilisée, augmente de 1% le poids des butins rares pour ce combat. Ne se cumule pas. Fonctionne toujours, pour tous.',
  'Has a chance to lower the target’s Attack by one stage.':'Peut baisser l\'Attaque de la cible d\'un cran.',
  '20% chance to inflict Poisoned':'20% de chance d\'empoisonner.',
  '50% chance to increase Attack by 50%':'50% de chance d\'augmenter l\'Attaque de 50%.',
  'Destroys Reflect and Light Screen.':'Détruit Protection et Mur Lumière.',
  'Increases Defense by 50%':'Augmente la Défense de 50%.',
  'Has double power against, and can hit, Pokémon attempting to switch out.':'Puissance doublée contre les Pokémon qui battent en retraite, et peut les toucher.',
  'Increases Special Defense and Special Attack by 50%, and Speed by 100%':'Augmente la Défense Spéciale et l\'Attaque Spéciale de 50%, et la Vitesse de 100%.',
  'Inflicts Confusion, but increases enemy Special Attack by 100%':'Rend confus, mais augmente l\'Attaque Spéciale ennemie de 100%.',
  'Changes the weather to Rainy':'Invoque la pluie.',
  'Changes the weather to tagReflect':'Invoque la Protection.',
  '20% chance to inflict Sleep':'20% de chance d\'endormir.',
  'Type changes based on the first type of the user':'Le type change selon le premier type du lanceur.',
  'User foregoes its next turn to recharge.':'Le lanceur passe son prochain tour pour se recharger.',
  'Increases Attack and Special Attack by 100%':'Augmente l\'Attaque et l\'Attaque Spéciale de 100%.',
  'Attack becomes physical or special to match the highest stat of the user':'L\'attaque devient physique ou spéciale selon la meilleure stat du lanceur.',
  'Has a chance to burn the target.  Lets frozen Pokémon thaw themselves.':'Peut brûler la cible. Permet aux Pokémon gelés de dégeler.',
  'Changes the weather to Safeguard':'Invoque la Rune Protectrice.',
  'Changes the weather to Sandstorm':'Invoque une tempête de sable.',
  'Decreases enemy Defense by 100%':'Baisse la Défense ennemie de 100%.',
  '10% chance to decrease enemy Attack by 50%':'10% de chance de baisser l\'Attaque ennemie de 50%.',
  'Can hit regardless of the typing':'Peut toucher quels que soient les types.',
  '10% chance to decrease enemy Defense by 50%':'10% de chance de baisser la Défense ennemie de 50%.',
  'Increases Attack by 100% and Speed by 50%':'Augmente l\'Attaque de 100% et la Vitesse de 50%.',
  'Executes the first move slot. Attacks x1.5 slower than usual':'Exécute la première capacité. Attaque 1.5 fois plus lentement que la normale.',
  'Power doubles if the target is Paralyzed':'Puissance doublée si la cible est paralysée.',
  'Decreases enemy Special Attack by 50%':'Baisse l\'Attaque Spéciale ennemie de 50%.',
  'The user ignores the effects of opposing Pokémon\'s moves and Abilities that draw in moves, allowing this move to hit the chosen target.':'Ignore les effets des capacités et talents adverses qui détournent les attaques : cette capacité touche sa cible.',
  'Changes the weather to Hail and increases Special Attack by 50%':'Invoque la grêle et augmente l\'Attaque Spéciale de 50%.',
  'Temporarily adds Water to the type of the enemy. Super-effective damage bonus dealt from temporal types is halved, and applying a second temporary type replaces the first one':'Ajoute temporairement le type Eau à l\'ennemi. Le bonus super efficace des types temporaires est réduit de moitié, et un second type temporaire remplace le premier.',
  'Removes Burn for the entire party':'Soigne les brûlures de toute l\'équipe.',
  'Steals the stat changes of the enemy':'Vole les changements de stats de l\'ennemi.',
  '...':'…',
  '50% chance to inflict Sleep':'50% de chance d\'endormir.',
  '50% chance to increase Defense by 50%':'50% de chance d\'augmenter la Défense de 50%.',
  'Increases base power by 30 for every unique stat up of the user':'Puissance de base +30 par augmentation de stat distincte du lanceur.',
  'Decreases enemy Special Attack by 50%. Power increases by x1.2-1.5 if Defense/Special Defense is risen':'Baisse l\'Attaque Spéciale ennemie de 50%. Puissance x1.2 à x1.5 si la Défense/Défense Spéciale est augmentée.',
  'Decreases Defense and Attack by 50%':'Baisse la Défense et l\'Attaque de 50%.',
  'Inflicts regular damage and can hit Dive users.':'Inflige des dégâts et peut toucher les Pokémon en Plongée.',
  'Inflicts Confusion, but increases enemy Attack by 100%':'Rend confus, mais augmente l\'Attaque ennemie de 100%.',
  'Increases Attack by 100%':'Augmente l\'Attaque de 100%.',
  'Increases Special Attack by 150%. Attacks x1.5 slower than usual':'Augmente l\'Attaque Spéciale de 150%. Attaque 1.5 fois plus lentement que la normale.',
  'Increases Speed by 50% to the entire team. Attacks x1.5 slower than usual':'Augmente la Vitesse de toute l\'équipe de 50%. Attaque 1.5 fois plus lentement que la normale.',
  'Once used,increases the weight of rare Pokemon by 1% for the current battle. Multiple uses wont stack. Works always for everyone regardless of the user':'Une fois utilisée, augmente de 1% le poids des Pokémon rares pour ce combat. Ne se cumule pas. Fonctionne toujours, pour tous.',
  'Increases Special Attack by 50%':'Augmente l\'Attaque Spéciale de 50%.',
  'Inflicts Poisoned and decreases enemy Speed by 50%':'Empoisonne et baisse la Vitesse ennemie de 50%.',
  '10% chance to inflict Burn,Paralysis or Freeze':'10% de chance d\'infliger brûlure, paralysie ou gel.',
  'Temporarily adds Ghost to the type of the enemy. Super-effective damage bonus dealt from temporal types is halved, and applying a second temporary type replaces the first one':'Ajoute temporairement le type Spectre à l\'ennemi. Le bonus super efficace des types temporaires est réduit de moitié, et un second type temporaire remplace le premier.',
  'Changes the weather to Trick Room':'Invoque la Distorsion.',
  'Multiplies base power by 1.3x everytime its used, up to 3 times. Depletes all stacks upon switching Pokemon':'Puissance de base x1.3 à chaque utilisation (max 3). Les cumuls s\'annulent au changement de Pokémon.',
  'Hits 3 times':'Frappe 3 fois.',
  'Decreases Defense, Special Defense and Speed by 50%':'Baisse la Défense, la Défense Spéciale et la Vitesse de 50%.',
  'Power doubles if the target is Poisoned':'Puissance doublée si la cible est empoisonnée.',
  'Power doubles under a weather condition, and type changes depending on it (Sunny is Fire, Rainy is Water, Sandstorm is Ground, Hail is Ice, Foggy is Ghost, Electric Terrain is Electric, Grassy Terrain is Grass, Misty Terrain is Psychic )':'Puissance doublée sous une météo, et le type change selon celle-ci (soleil = Feu, pluie = Eau, tempête de sable = Sol, grêle = Glace, brouillard = Spectre, Champ Électrifié = Électrik, Champ Herbu = Plante, Champ Brumeux = Psy).',
  'Changes the weather to Weird Room':'Invoque la Salle Étrange.',
}));

// ——— Load MOVES in a vm context (the file is not strict JSON) ———
const src = readFileSync(new URL('../src/data/moves.js', import.meta.url), 'utf8');
const sandbox = { window: {} };
vm.createContext(sandbox);
vm.runInContext(src + ';this.MOVES=MOVES;', sandbox);
const MOVES = sandbox.MOVES;

const missing = new Set();
const out = {};
for (const [id, mv] of Object.entries(MOVES)) {
  const d = mv.desc || '';
  const fr = TR.get(d);
  if (fr === undefined) { missing.add(d); continue; }
  out[id] = fr;
}
if (missing.size) {
  console.error('Descriptions WITHOUT translation (' + missing.size + '):');
  for (const d of missing) console.error('  • ' + JSON.stringify(d));
  process.exit(1);
}

const body = Object.keys(out).sort().map((id) => `  "${id}": "${out[id].replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`).join(',\n');
writeFileSync(new URL('../src/localization/fr/move-descs.js', import.meta.url),
`// ===== FR — Move descriptions =====
// Phase 24: generated by tools/gen_move_descs_fr.mjs (covers the 400 moves).
// Key = move id; consumed via t('move_descs.'+id) BEFORE the mv.desc fallback.
window.L_fr_move_descs = {
${body}
};
`);
console.log(`fr/move-descs.js : ${Object.keys(out).length} descriptions écrites`);


